/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern jint amaya_APIJavaAmaya_IsDocumentLoaded ( struct Hamaya_APIJavaAmaya* none,
                                                  struct Hjava_lang_String* jdocumentURL );
extern void amaya_APIJavaAmaya_ExtractParameters ( struct Hamaya_APIJavaAmaya* none,
                                                   struct Hjava_lang_String* jaName,
                                                   struct Hjava_lang_String* jparameters );
extern void amaya_APIJavaAmaya_ExtractSuffix ( struct Hamaya_APIJavaAmaya* none,
                                               struct Hjava_lang_String* jaName,
                                               struct Hjava_lang_String* jaSuffix );
extern void amaya_APIJavaAmaya_ResetStop ( struct Hamaya_APIJavaAmaya* none,
                                           jint document );
extern void amaya_APIJavaAmaya_ActiveTransfer ( struct Hamaya_APIJavaAmaya* none,
                                                jint document );
extern void amaya_APIJavaAmaya_StopTransfer ( struct Hamaya_APIJavaAmaya* none,
                                              jint document,
                                              jint view );
extern void amaya_APIJavaAmaya_SetCharEmphasis ( struct Hamaya_APIJavaAmaya* none,
                                                 jint document,
                                                 jint view );
extern void amaya_APIJavaAmaya_SetCharStrong ( struct Hamaya_APIJavaAmaya* none,
                                               jint document,
                                               jint view );
extern void amaya_APIJavaAmaya_SetCharCode ( struct Hamaya_APIJavaAmaya* none,
                                             jint document,
                                             jint view );
extern void amaya_APIJavaAmaya_InitFormAnswer ( struct Hamaya_APIJavaAmaya* none,
                                                jint document,
                                                jint view );
extern void amaya_APIJavaAmaya_InitConfirm ( struct Hamaya_APIJavaAmaya* none,
                                             jint document,
                                             jint view,
                                             struct Hjava_lang_String* jlabel );
extern void amaya_APIJavaAmaya_OpenDocInNewWindow ( struct Hamaya_APIJavaAmaya* none,
                                                    jint document,
                                                    jint view );
extern void amaya_APIJavaAmaya_OpenDoc ( struct Hamaya_APIJavaAmaya* none,
                                         jint document,
                                         jint view );
extern void amaya_APIJavaAmaya_Reload ( struct Hamaya_APIJavaAmaya* none,
                                        jint document,
                                        jint view );
extern void amaya_APIJavaAmaya_ShowStructure ( struct Hamaya_APIJavaAmaya* none,
                                               jint document,
                                               jint view );
extern void amaya_APIJavaAmaya_ShowAlternate ( struct Hamaya_APIJavaAmaya* none,
                                               jint document,
                                               jint view );
extern void amaya_APIJavaAmaya_ShowLinks ( struct Hamaya_APIJavaAmaya* none,
                                           jint document,
                                           jint view );
extern void amaya_APIJavaAmaya_ShowToC ( struct Hamaya_APIJavaAmaya* none,
                                         jint document,
                                         jint view );
extern void amaya_APIJavaAmaya_ShowMapAreas ( struct Hamaya_APIJavaAmaya* none,
                                              jint document,
                                              jint view );
extern jint amaya_APIJavaAmaya_NormalizeFile ( struct Hamaya_APIJavaAmaya* none,
                                               struct Hjava_lang_String* jsrc,
                                               struct Hjava_lang_String* jtarget );
extern void amaya_APIJavaAmaya_SectionNumbering ( struct Hamaya_APIJavaAmaya* none,
                                                  jint document,
                                                  jint view );
extern void amaya_APIJavaAmaya_MakeBook ( struct Hamaya_APIJavaAmaya* none,
                                          jint document,
                                          jint view );
extern void amaya_APIJavaAmaya_RealTimeHTML ( struct Hamaya_APIJavaAmaya* none,
                                              jint document,
                                              jint view );
extern void amaya_APIJavaAmaya_HelpAmaya ( struct Hamaya_APIJavaAmaya* none,
                                           jint document,
                                           jint view );
extern void amaya_APIJavaAmaya_AmayaClose ( struct Hamaya_APIJavaAmaya* none,
                                            jint document,
                                            jint view );
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetUserAgentName ( struct Hamaya_APIJavaAmaya* none );
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetDocumentURL ( struct Hamaya_APIJavaAmaya* none,
                                                                     jint doc );
extern struct Hjava_lang_String* amaya_APIJavaAmaya_AmayaGetMessage ( struct Hamaya_APIJavaAmaya* none,
                                                                      jint msg );
extern jint amaya_APIJavaAmaya_PopUpAuthDialog ( struct Hamaya_APIJavaAmaya* none,
                                                 jint doc );
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetUserString ( struct Hamaya_APIJavaAmaya* none );
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetPasswdString ( struct Hamaya_APIJavaAmaya* none );
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetAnswerString ( struct Hamaya_APIJavaAmaya* none );
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetTempDirectory ( struct Hamaya_APIJavaAmaya* none );
extern void register_amaya_APIJavaAmaya_stubs ( void );

#else /* __STDC__ */

extern jint amaya_APIJavaAmaya_IsDocumentLoaded (/* struct Hamaya_APIJavaAmaya* none,
                                                    struct Hjava_lang_String* jdocumentURL */);
extern void amaya_APIJavaAmaya_ExtractParameters (/* struct Hamaya_APIJavaAmaya* none,
                                                     struct Hjava_lang_String* jaName,
                                                     struct Hjava_lang_String* jparameters */);
extern void amaya_APIJavaAmaya_ExtractSuffix (/* struct Hamaya_APIJavaAmaya* none,
                                                 struct Hjava_lang_String* jaName,
                                                 struct Hjava_lang_String* jaSuffix */);
extern void amaya_APIJavaAmaya_ResetStop (/* struct Hamaya_APIJavaAmaya* none,
                                             jint document */);
extern void amaya_APIJavaAmaya_ActiveTransfer (/* struct Hamaya_APIJavaAmaya* none,
                                                  jint document */);
extern void amaya_APIJavaAmaya_StopTransfer (/* struct Hamaya_APIJavaAmaya* none,
                                                jint document,
                                                jint view */);
extern void amaya_APIJavaAmaya_SetCharEmphasis (/* struct Hamaya_APIJavaAmaya* none,
                                                   jint document,
                                                   jint view */);
extern void amaya_APIJavaAmaya_SetCharStrong (/* struct Hamaya_APIJavaAmaya* none,
                                                 jint document,
                                                 jint view */);
extern void amaya_APIJavaAmaya_SetCharCode (/* struct Hamaya_APIJavaAmaya* none,
                                               jint document,
                                               jint view */);
extern void amaya_APIJavaAmaya_InitFormAnswer (/* struct Hamaya_APIJavaAmaya* none,
                                                  jint document,
                                                  jint view */);
extern void amaya_APIJavaAmaya_InitConfirm (/* struct Hamaya_APIJavaAmaya* none,
                                               jint document,
                                               jint view,
                                               struct Hjava_lang_String* jlabel */);
extern void amaya_APIJavaAmaya_OpenDocInNewWindow (/* struct Hamaya_APIJavaAmaya* none,
                                                      jint document,
                                                      jint view */);
extern void amaya_APIJavaAmaya_OpenDoc (/* struct Hamaya_APIJavaAmaya* none,
                                           jint document,
                                           jint view */);
extern void amaya_APIJavaAmaya_Reload (/* struct Hamaya_APIJavaAmaya* none,
                                          jint document,
                                          jint view */);
extern void amaya_APIJavaAmaya_ShowStructure (/* struct Hamaya_APIJavaAmaya* none,
                                                 jint document,
                                                 jint view */);
extern void amaya_APIJavaAmaya_ShowAlternate (/* struct Hamaya_APIJavaAmaya* none,
                                                 jint document,
                                                 jint view */);
extern void amaya_APIJavaAmaya_ShowLinks (/* struct Hamaya_APIJavaAmaya* none,
                                             jint document,
                                             jint view */);
extern void amaya_APIJavaAmaya_ShowToC (/* struct Hamaya_APIJavaAmaya* none,
                                           jint document,
                                           jint view */);
extern void amaya_APIJavaAmaya_ShowMapAreas (/* struct Hamaya_APIJavaAmaya* none,
                                                jint document,
                                                jint view */);
extern jint amaya_APIJavaAmaya_NormalizeFile (/* struct Hamaya_APIJavaAmaya* none,
                                                 struct Hjava_lang_String* jsrc,
                                                 struct Hjava_lang_String* jtarget */);
extern void amaya_APIJavaAmaya_SectionNumbering (/* struct Hamaya_APIJavaAmaya* none,
                                                    jint document,
                                                    jint view */);
extern void amaya_APIJavaAmaya_MakeBook (/* struct Hamaya_APIJavaAmaya* none,
                                            jint document,
                                            jint view */);
extern void amaya_APIJavaAmaya_RealTimeHTML (/* struct Hamaya_APIJavaAmaya* none,
                                                jint document,
                                                jint view */);
extern void amaya_APIJavaAmaya_HelpAmaya (/* struct Hamaya_APIJavaAmaya* none,
                                             jint document,
                                             jint view */);
extern void amaya_APIJavaAmaya_AmayaClose (/* struct Hamaya_APIJavaAmaya* none,
                                              jint document,
                                              jint view */);
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetUserAgentName (/* struct Hamaya_APIJavaAmaya* none */);
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetDocumentURL (/* struct Hamaya_APIJavaAmaya* none,
                                                                       jint doc */);
extern struct Hjava_lang_String* amaya_APIJavaAmaya_AmayaGetMessage (/* struct Hamaya_APIJavaAmaya* none,
                                                                        jint msg */);
extern jint amaya_APIJavaAmaya_PopUpAuthDialog (/* struct Hamaya_APIJavaAmaya* none,
                                                   jint doc */);
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetUserString (/* struct Hamaya_APIJavaAmaya* none */);
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetPasswdString (/* struct Hamaya_APIJavaAmaya* none */);
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetAnswerString (/* struct Hamaya_APIJavaAmaya* none */);
extern struct Hjava_lang_String* amaya_APIJavaAmaya_GetTempDirectory (/* struct Hamaya_APIJavaAmaya* none */);
extern void register_amaya_APIJavaAmaya_stubs (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
