/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int GetObjectWWWCallback ( void *arg );
extern int GetObjectWWW ( int doc,
                          char *url,
                          char *postString,
                          char *outputfile,
                          int mode,
                          void *incremental,
                          void *context,
                          void *terminate,
                          void *tcontext,
                          boolean error_html );
extern int PutObjectWWW ( int doc,
                          char *fileName,
                          char *url,
                          int mode,
                          PicType contentType,
                          void * terminate_cbf,
                          void *context_tcbf );
extern void StopRequest ( int doc );

#else /* __STDC__ */

extern int GetObjectWWWCallback (/* void *arg */);
extern int GetObjectWWW (/* int doc,
                            char *url,
                            char *postString,
                            char *outputfile,
                            int mode,
                            void *incremental,
                            void *context,
                            void *terminate,
                            void *tcontext,
                            boolean error_html */);
extern int PutObjectWWW (/* int doc,
                            char *fileName,
                            char *url,
                            int mode,
                            PicType contentType,
                            void * terminate_cbf,
                            void *context_tcbf */);
extern void StopRequest (/* int doc */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
