/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void thotlib_Extra_TtaRemoveSchemaExtension ( struct Hthotlib_Extra* none,
                                                     jint jdocument,
                                                     jint jextension );
extern void thotlib_Extra_Java2CCallback ( struct Hthotlib_Extra* none,
                                           jlong callback,
                                           struct _object * arg );
extern void thotlib_Extra_JavaPollLoop ( struct Hthotlib_Extra* none );
extern void thotlib_Extra_JavaStopPoll ( struct Hthotlib_Extra* none );
extern void thotlib_Extra_JavaXFlush ( struct Hthotlib_Extra* none );
extern void register_thotlib_Extra_stubs ( void );

#else /* __STDC__ */

extern void thotlib_Extra_TtaRemoveSchemaExtension (/* struct Hthotlib_Extra* none,
                                                       jint jdocument,
                                                       jint jextension */);
extern void thotlib_Extra_Java2CCallback (/* struct Hthotlib_Extra* none,
                                             jlong callback,
                                             struct _object * arg */);
extern void thotlib_Extra_JavaPollLoop (/* struct Hthotlib_Extra* none */);
extern void thotlib_Extra_JavaStopPoll (/* struct Hthotlib_Extra* none */);
extern void thotlib_Extra_JavaXFlush (/* struct Hthotlib_Extra* none */);
extern void register_thotlib_Extra_stubs (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
