#!/bin/sh

PATH=$PATH:${HOME}/bin;				export PATH

if [ -z "${LANG}" ]
then
        LANG=fr
else
        LANGUE_ORIG=`echo ${LANG} | cut -c-2 | tr '[A-Z]' '[a-z]'`
        LANG=${LANGUE_ORIG}
 
fi
if [ "${LANG}" = "c" ];then
        LANG=fr;
fi
export LANG
 
# --------------------------------
 
HERE=`pwd`
 
FIRST_CHAR=`echo $0 | cut -c 1`
 
if test "$FIRST_CHAR" = "/"
then
  FULL_PATHNAME="$0"
else
  FULL_PATHNAME="$HERE/$0"
fi
 
FULL_PATHDIR=`dirname $FULL_PATHNAME`
cd $FULL_PATHDIR
FULL_PATHDIR=`pwd`
cd $HERE
EXEC_FILENAME=`basename $FULL_PATHNAME`
FULL_PATHNAME="$FULL_PATHDIR/$EXEC_FILENAME"
 
THOTDIR=`dirname $FULL_PATHDIR`;                export THOTDIR
 
# --------------------------------

BIN=${THOTDIR}/batch
CONFIG=${THOTDIR}/config
Machine=`${BIN}/MachineType`
THOTBIN=${THOTDIR}/${Machine}/bin

. ${CONFIG}/${LANG}-table
PWD=`pwd`
NOSOURCE=FALSE

if [ "${#}" -eq "0" ]
then
	echo "${0}: "${MSG62}>&2
	echo "Usage: ${0} file [file]">&2
	exit 1
fi

PWD=`pwd`
if [ "$THOTSCH" = "" ]
   then THOTSCH=${PWD}:${THOTDIR}/schemas
else
        tmp=$THOTSCH
        THOTSCH=${PWD}:${tmp}
fi
export THOTSCH

FILELIST=${@}
for FILE in ${FILELIST}
do
# wipe out extension
FILEDIR=`dirname ${FILE}`
NAME=`basename ${FILE} .A`
. ${CONFIG}/${LANG}-table

if [ -f "${FILEDIR}/${NAME}.A" ]
then
	if [ -f "${FILEDIR}/${NAME}APP.c" ]
	then
		echo ${MSG63}
		/bin/mv ${FILEDIR}/${NAME}APP.c ${FILEDIR}/${NAME}APP.c.BAK
	fi
else
	NOSOURCE=TRUE
	if [ -f "${FILEDIR}/${NAME}APP.c" ]
	then
		echo ${MSG63}
	fi
fi

if [ -f "${FILEDIR}/${NAME}.A" ]
then
	echo ${MSG64}
	cpp -C ${FILEDIR}/${NAME}.A > ${FILEDIR}/${NAME}.SCH
	echo ${MSG30}
	(cd ${FILEDIR};${THOTBIN}/app ${NAME});
	(cd ${FILEDIR};
	if [ "${NAME}" != "EDITOR" ]
	then
	      (${THOTBIN}/printstr -h ${NAME} > ${NAME}.h) || (echo ${MSG16}; exit 1;)
	fi
	)
	echo ${MSG29}
	rm ${FILEDIR}/${NAME}.SCH
fi


if [ "${NOSOURCE}" = "TRUE" ]
then
	echo ${MSG65}
fi

done
