#!/bin/sh

PATH=$PATH:${HOME}/bin;				export PATH
#( set -x

if [ -z "${LANG}" ]
then
        LANG=fr
else
        LANG=`echo ${LANG} | cut -c-2 | tr '[A-Z]' '[a-z]'`
        LANG=${LANG}
 
fi
if [ "${LANG}" = "c" ];then
        LANG=fr;
fi
export LANG
 
# --------------------------------
 
HERE=`pwd`
 
FIRST_CHAR=`echo $0 | cut -c 1`
 
if test "$FIRST_CHAR" = "/"
then
  FULL_PATHNAME="$0"
else
  FULL_PATHNAME="$HERE/$0"
fi
 
FULL_PATHDIR=`dirname $FULL_PATHNAME`
cd $FULL_PATHDIR
FULL_PATHDIR=`pwd`
cd $HERE
EXEC_FILENAME=`basename $FULL_PATHNAME`
FULL_PATHNAME="$FULL_PATHDIR/$EXEC_FILENAME"
 
THOTDIR=`dirname $FULL_PATHDIR`;                export THOTDIR
 
# --------------------------------

BIN=${THOTDIR}/batch/
CONFIG=${THOTDIR}/config/
Machine=`${BIN}/MachineType`
THOTBIN=${THOTDIR}/${Machine}/bin

. ${CONFIG}/${LANG}-table

if [ "${#}" -eq "0" ]
then
	echo "${0}: "${MSG51}>&2
	echo "Usage: ${0} [-Doption] -Doption=val] Input_FILE[.P] output_FILE[.PRS]">&2
	exit 1
fi

PWD=`pwd`
if [ "$THOTSCH" = "" ]
   then THOTSCH=${PWD}:${THOTDIR}/schemas:${THOTDIR}/schemasOPERA
else
	tmp=$THOTSCH
	THOTSCH=${PWD}:${tmp}
fi
export THOTSCH

# construct cpp command line
CPP="cpp -C"
NB=1
OPTION="-"
while  [ "${OPTION}" = "-" ]
do
   PARAM=$1
   OPTION=`echo ${PARAM}|cut -d"D" -f1`
   if [ "${OPTION}" = "-" ]
   then
	if [ "${#}" -gt "1" ]
	then
	   shift
	   NB=`expr ${NB} + 1`
	fi
	CPP="${CPP} ${PARAM}"
   fi 
done

# wipe out extension
NAME=`echo ${PARAM}|cut -d"." -f1`
LONG=`echo ${NAME}|wc -c`
. ${CONFIG}/${LANG}-table
if [ -f "${NAME}.P" ]
   then
	if [ "${#}" -gt "1" ]
	then
	   shift
	   PARAM=$1
	   OFILE=`echo ${PARAM}|cut -d"." -f1`
	else
           OFILE=${NAME}
	fi
	echo ${MSG35}
	${CPP} ${NAME}.P > ${OFILE}.SCH
	NAME=${OFILE}
. ${CONFIG}/${LANG}-table
	echo ${MSG30}
	${THOTBIN}/prs ${OFILE} || { echo ${MSG28};rm ${OFILE}.SCH; exit 1; }
	echo ${MSG29}
	rm ${OFILE}.SCH
else
	if [ -f "${NAME}.PRS" ]
	then
		echo ${MSG34}
	fi
	echo ${MSG36}
fi
#)
