#!/bin/sh
if [ -z "${LANG}" ]
then
        LANG=fr
else
        LANGUE_ORIG=`echo ${LANG} | cut -c-2 | tr '[A-Z]' '[a-z]'`
        LANG=${LANGUE_ORIG}

fi
if [ "${LANG}" = "c" ];then
        LANG=fr;
fi
export LANG

# --------------------------------
 
HERE=`pwd`
 
FIRST_CHAR=`echo $0 | cut -c 1`
 
if test "$FIRST_CHAR" = "/"
then
  FULL_PATHNAME="$0"
else
  FULL_PATHNAME="$HERE/$0"
fi
 
FULL_PATHDIR=`dirname $FULL_PATHNAME`
cd $FULL_PATHDIR
FULL_PATHDIR=`pwd`
cd $HERE
EXEC_FILENAME=`basename $FULL_PATHNAME`
FULL_PATHNAME="$FULL_PATHDIR/$EXEC_FILENAME"
 
THOTDIR=`dirname $FULL_PATHDIR`;                export THOTDIR
 
# --------------------------------

BIN=${THOTDIR}/batch
CONFIG=${THOTDIR}/config
Machine=`${BIN}/MachineType`
THOTBIN=${THOTDIR}/${Machine}/bin

PWD=`pwd`

if [ "$THOTSCH" = "" ]
   then THOTSCH=${PWD}:${THOTDIR}/schemas
else
        tmp=$THOTSCH
        THOTSCH=${PWD}:${tmp}
fi
export THOTSCH

. ${CONFIG}/${LANG}-table
if [ "${#}" -eq "0" ]
then
	echo "${0}: "${MSG24}>&2
	echo "Usage: ${0} FILE [FILE]">&2
	exit 1
fi

FILELIST=${@}
for FILE in ${FILELIST}
do
# wipe out extension
NAME=`echo ${FILE}|cut -d"." -f1`
LONG=`echo ${NAME}|wc -c`
. ${CONFIG}/${LANG}-table

if [ "${LONG}" -gt "11" ]
then
	echo ${MSG53}
	echo "Abort."
else
	
  if [ -f "${NAME}.LAN" ]
  then
	echo ${MSG26}
	${THOTBIN}/grm ${NAME};
	echo ${MSG29}
  else
	echo ${MSG27}
  fi
	

fi
done

