#!/bin/sh

#
# concatps [ nom_de_fichier ...]
# (c) Laurent Boivin - Juin 1994
#
# Script permettant de concatener (sur la sortie standard) des fichiers
# PostScript produits par Thot pour obtenir un seul fichier PostScript.
# Les en-tetes PostScript ne sont pas repetees.
# Chaque fichier commence sur une page impaire.
#
# ATTENTION : ce fichier utilise concatps_sup 
#
thotlibdir=/perles/roisin/opera/batch

if [ "$#" -eq "0" ]
then
  echo "Usage: $0 file1 file2 ..."
  echo "     Concat PostScript files produced by Thot in a unique file."
  echo "     The result is build in the standard output."
  exit 1
fi


awk -f $thotlibdir/concatps_sup $*

echo ""
echo "EndThot"
