#!/bin/sh
if [ "$1" = "" -o "$2" = "" ]
then
    echo echange : $0 old_string new_string
    exit 1
fi

old_string=$1
new_string=$2

echo searching for files containing $old_string
LISTE=`lid -S space $old_string`
if [ "$LISTE" = "" ]
then
    echo $old_string not found
    exit 0
fi

substitute $old_string $new_string $LISTE

