#!/bin/sh
cd ../..
AMAYAVERSION=1.3
THOTDIR=/tahiti/diffusion/opera
PLATFORMS="solaris2 SGI RS6000"
cd $THOTDIR
rm solaris2 LINUX-ELF
ln -s solaris-www solaris2
ln -s LINUX-ELF-www LINUX-ELF
cd ..

DIR=/afs/.inria.fr/common/usr/local/amaya/$AMAYAVERSION
echo "Intallation version " $DIR
mkdir $DIR
 mkdir $DIR/config
   cp -p Thot/config/XKeysymDB $DIR/config/
   cp -p Thot/config/thot.ini $DIR/config/
   cp -p Thot/config/amaya.keyboard $DIR/config/
   cp -p Thot/config/en-amayadialogue $DIR/config/
   cp -p Thot/config/en-amayamsg $DIR/config/
   cp -p Thot/config/en-libdialogue $DIR/config/
   cp -p Thot/config/en-transdialogue $DIR/config/
   cp -p Thot/config/en-corrdialogue $DIR/config/
   cp -p Thot/config/fr-amayadialogue $DIR/config/
   cp -p Thot/config/fr-amayamsg $DIR/config/
   cp -p Thot/config/fr-libdialogue $DIR/config/
   cp -p Thot/config/fr-transdialogue $DIR/config/
   cp -p Thot/config/fr-corrdialogue $DIR/config/
 ln -s ../../thot/Current/dicopar $DIR/dicopar
 ln -s ../../thot/Current/fonts $DIR/fonts
 mkdir $DIR/amaya
   cp -p Thot/amaya/COPYRIGHT $DIR/amaya/
   cp -p Thot/amaya/AmayaPage.html $DIR/amaya/
   cp -p Thot/amaya/HTML.STR $DIR/amaya/
   cp -p Thot/amaya/HTML.conf $DIR/amaya/
   cp -p Thot/amaya/HTML.trans $DIR/amaya/
   cp -p Thot/amaya/HTML.en $DIR/amaya/
   cp -p Thot/amaya/HTML.fr $DIR/amaya/
   cp -p Thot/amaya/HTML*.PRS $DIR/amaya/
   cp -p Thot/amaya/HTML*.TRA $DIR/amaya/
   cp -p Thot/amaya/MathML.STR $DIR/amaya/
   cp -p Thot/amaya/MathMLP.PRS $DIR/amaya/
   cp -p Thot/amaya/MathMLT.TRA $DIR/amaya/
   cp -p Thot/amaya/MathML.trans $DIR/amaya/
   cp -p Thot/amaya/*.gif $DIR/amaya/
 mkdir $DIR/doc
 mkdir $DIR/doc/amaya
   cp -p Thot/doc/amaya/Creating.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/MakeBook.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/StyleSheets.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Manual.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Tables.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Math.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Transform.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Attributes.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Views.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/ImageMaps.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Numbering.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Searching.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Selecting.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Browsing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/CSS.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Plugins.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Keyboard.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Printing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Changing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Publishing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Configure.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Links.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Put.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/SpellChecking.html $DIR/doc/amaya/
 mkdir $DIR/doc/Icons
   cp -p Thot/doc/Icons/*.gif $DIR/doc/Icons/
 mkdir $DIR/Icons
 mkdir $DIR/Icons/WWW
   cp -p Thot/Icons/WWW/activity_48x48 $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/guide48x $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/new_red $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/relnotes48x $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/w3c_home $DIR/Icons/WWW/

for MACH in $PLATFORMS
do
 mkdir $DIR/$MACH
 mkdir $DIR/$MACH/bin
   cp -p Thot/$MACH/bin/amaya $DIR/$MACH/bin/
   cp -p Thot/$MACH/bin/print $DIR/$MACH/bin/
done

DIR=/mnt/amaya/$AMAYAVERSION
PLATFORMS="solaris2 SGI RS6000 LINUX-ELF"
echo "Intallation version " $DIR
mkdir $DIR
 mkdir $DIR/config
   cp -p Thot/config/XKeysymDB $DIR/config/
   cp -p Thot/config/thot.ini $DIR/config/
   cp -p Thot/config/amaya.keyboard $DIR/config/
   cp -p Thot/config/en-amayadialogue $DIR/config/
   cp -p Thot/config/en-amayamsg $DIR/config/
   cp -p Thot/config/en-libdialogue $DIR/config/
   cp -p Thot/config/en-transdialogue $DIR/config/
   cp -p Thot/config/en-corrdialogue $DIR/config/
   cp -p Thot/config/en-javamsg $DIR/config/
   cp -p Thot/config/fr-amayadialogue $DIR/config/
   cp -p Thot/config/fr-amayamsg $DIR/config/
   cp -p Thot/config/fr-libdialogue $DIR/config/
   cp -p Thot/config/fr-transdialogue $DIR/config/
   cp -p Thot/config/fr-corrdialogue $DIR/config/
   cp -p Thot/config/fr-javamsg $DIR/config/
   cp -p Thot/config/java.properties $DIR/config/
 mkdir $DIR/amaya
   cp -p Thot/amaya/COPYRIGHT $DIR/amaya/
   cp -p Thot/amaya/AmayaPage.html $DIR/amaya/
   cp -p Thot/amaya/HTML.STR $DIR/amaya/
   cp -p Thot/amaya/HTML.conf $DIR/amaya/
   cp -p Thot/amaya/HTML.trans $DIR/amaya/
   cp -p Thot/amaya/HTML.en $DIR/amaya/
   cp -p Thot/amaya/HTML.fr $DIR/amaya/
   cp -p Thot/amaya/HTML*.PRS $DIR/amaya/
   cp -p Thot/amaya/HTML*.TRA $DIR/amaya/
   cp -p Thot/amaya/MathML.STR $DIR/amaya/
   cp -p Thot/amaya/MathMLP.PRS $DIR/amaya/
   cp -p Thot/amaya/MathMLT.TRA $DIR/amaya/
   cp -p Thot/amaya/MathML.trans $DIR/amaya/
   cp -p Thot/amaya/*.gif $DIR/amaya/
 ln -s ../../thot/Current/dicopar $DIR/dicopar
 ln -s ../../thot/Current/fonts $DIR/fonts
 mkdir $DIR/doc
 mkdir $DIR/doc/amaya
   cp -p Thot/doc/amaya/Creating.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/MakeBook.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/StyleSheets.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Manual.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Tables.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Math.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Transform.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Attributes.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Views.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/ImageMaps.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Numbering.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Searching.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Selecting.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Browsing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/CSS.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Plugins.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Keyboard.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Printing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Changing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Publishing.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Configure.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Links.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/Put.html $DIR/doc/amaya/
   cp -p Thot/doc/amaya/SpellChecking.html $DIR/doc/amaya/
 mkdir $DIR/doc/Icons
   cp -p Thot/doc/Icons/*.gif $DIR/doc/Icons/
 mkdir $DIR/Icons
 mkdir $DIR/Icons/WWW
   cp -p Thot/Icons/WWW/activity_48x48 $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/guide48x $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/new_red $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/relnotes48x $DIR/Icons/WWW/
   cp -p Thot/Icons/WWW/w3c_home $DIR/Icons/WWW/

for MACH in $PLATFORMS
do
 mkdir $DIR/$MACH
 mkdir $DIR/$MACH/bin
   cp -p Thot/$MACH/bin/amaya $DIR/$MACH/bin/
   cp -p Thot/$MACH/bin/print $DIR/$MACH/bin/
done
echo "Fin installation"
