#!/bin/sh
#
# This script builds all the binary tar files for Amaya
# 

find Amaya/README.amaya \
   Amaya/config/XKeysymDB \
   Amaya/config/amaya.kb \
   Amaya/config/amaya.keyboard \
   Amaya/config/amaya.emacs \
   Amaya/config/amaya.profiles \
   Amaya/config/*thot.rc \
   Amaya/config/*-amayadialogue \
   Amaya/config/*-amayamsg \
   Amaya/config/*-libdialogue \
   Amaya/config/*-corrdialogue \
   Amaya/config/annot*rdf \
   Amaya/config/annot.schemas \
   Amaya/dicopar/*.ptn \
   Amaya/dicopar/alphabet \
   Amaya/dicopar/clavier \
   Amaya/doc/html/*.html* \
   Amaya/doc/html/*/*.html* \
   Amaya/doc/html/*.css \
   Amaya/doc/images/*.gif \
   Amaya/doc/images/*.png \
   Amaya/doc/images/*.jpg \
   Amaya/doc/images/w3c_home \
   Amaya/solaris8/bin/amaya \
   Amaya/solaris8/bin/print \
   Amaya/batch/MachineType \
   Amaya/annotlib/Annot.STR \
   Amaya/annotlib/AnnotP.PRS \
   Amaya/annotlib/AnnotT.TRA \
   Amaya/annotlib/*.gif \
   Amaya/amaya/COPYRIGHT* \
   Amaya/amaya/AmayaPage.html* \
   Amaya/amaya/*.png \
   Amaya/amaya/*.gif \
   Amaya/amaya/*.conf \
   Amaya/amaya/*.STR \
   Amaya/amaya/*.trans \
   Amaya/amaya/*.PRS \
   Amaya/amaya/*.TRA \
   Amaya/amaya/*.en \
   Amaya/fonts/Families.list \
   Amaya/fonts/fonts.dir \
   Amaya/fonts/icones* \
-print | pkgproto > prototype

echo "i pkginfo=Amaya/amaya.pkg" >> prototype

mkdir TEMPO
pkgmk -r . -d TEMPO

REP=`pwd`
pkgtrans -s TEMPO $REP/Amaya/amaya-6.3-sol8-sparc-local
rm -rf TEMPO
