#!/bin/sh
#
# This script builds all the binary tar files for Amaya
# running the Kaffe interpreter.
#
#       amaya-java-$MACH-$AMAYAVERSION.tar.gz
# 
AMAYAVERSION=1.1a
THOTDIR=/tahiti/diffusion/opera
DEST=/tahiti/thottape
PLATFORMS="solaris2 LINUX-ELF"

TAR="tar cvbfh 200"
COMPRESS="gzip -9"

cd $THOTDIR
rm solaris2 LINUX-ELF
ln -s solaris-java solaris2
ln -s LINUX-ELF-java LINUX-ELF

cd ..

for MACH in $PLATFORMS
do
   $TAR - \
   Thot/README \
   Thot/NEWS.Amaya.1.1\
   Thot/COPYRIGHT \
   Thot/config/XKeysymDB \
   Thot/config/thot.ini \
   Thot/config/java.properties \
   Thot/config/amaya.css \
   Thot/config/amaya.keyboard \
   Thot/config/en-amayadialogue \
   Thot/config/en-printdialogue \
   Thot/config/en-amayamsg \
   Thot/config/en-javamsg \
   Thot/config/en-libdialogue \
   Thot/config/en-transdialogue \
   Thot/config/en-corrdialogue \
   Thot/config/fr-amayadialogue \
   Thot/config/fr-printdialogue \
   Thot/config/fr-amayamsg \
   Thot/config/fr-javamsg \
   Thot/config/fr-libdialogue \
   Thot/config/fr-transdialogue \
   Thot/config/fr-corrdialogue \
   Thot/dicopar/*.ptn \
   Thot/dicopar/alphabet \
   Thot/dicopar/clavier \
   Thot/$MACH/bin/amaya \
   Thot/$MACH/bin/print \
   Thot/$MACH/bin/dns_daemon \
   Thot/$MACH/bin/kaffe \
   Thot/$MACH/bin/kaffeh \
   Thot/$MACH/bin/javac \
   Thot/classes/amaya.zip \
   Thot/classes/biss.zip \
   Thot/classes/classes.zip \
   Thot/classes/jigsaw.zip \
   Thot/classes/sources.zip \
   Thot/classes/thotlib.zip \
   Thot/classes/lib \
   Thot/batch/MachineType \
   Thot/amaya/COPYRIGHT \
   Thot/amaya/COPYRIGHT.html \
   Thot/amaya/*.gif \
   Thot/amaya/HTML.STR \
   Thot/amaya/HTML.conf \
   Thot/amaya/HTML.trans \
   Thot/amaya/HTML.en \
   Thot/amaya/HTML.fr \
   Thot/amaya/HTML*.PRS \
   Thot/amaya/HTML*.TRA \
   Thot/amaya/MathML.STR \
   Thot/amaya/MathML*.PRS \
   Thot/amaya/MathML*.TRA \
   Thot/fonts/Families.list \
   Thot/fonts/fonts.dir \
   Thot/fonts/icones* \
   | $COMPRESS  > $DEST/amaya-java-$MACH-$AMAYAVERSION.tar.gz
done

