#!/bin/sh
#
# This script builds all the binary tar files for AmayaJava
#
#       amaya-java-$MACH-$AMAYAVERSION.tar.gz
# 
AMAYAVERSION=1.1c
THOTDIR=/nfs/u/veillard/src/Thot
DEST=/u/veillard/
PLATFORMS="LINUX LINUX-SPARC"

TAR="tar cvbfh 200"
COMPRESS="gzip -9"

cd $THOTDIR
cd ..

for MACH in $PLATFORMS
do
   $TAR - \
   Thot/README \
   Thot/NEWS.Amaya.1.1\
   Thot/COPYRIGHT \
   Thot/README.amaya \
   Thot/config/XKeysymDB \
   Thot/config/thot.ini \
   Thot/config/amaya.css \
   Thot/config/amaya.keyboard \
   Thot/config/en-amayadialogue \
   Thot/config/en-printdialogue \
   Thot/config/en-amayamsg \
   Thot/config/en-libdialogue \
   Thot/config/en-transdialogue \
   Thot/config/en-corrdialogue \
   Thot/config/fr-amayadialogue \
   Thot/config/fr-printdialogue \
   Thot/config/fr-amayamsg \
   Thot/config/fr-libdialogue \
   Thot/config/fr-transdialogue \
   Thot/config/fr-corrdialogue \
   Thot/config/java.properties \
   Thot/config/en-javamsg \
   Thot/config/fr-javamsg \
   Thot/dicopar/*.ptn \
   Thot/dicopar/alphabet \
   Thot/dicopar/clavier \
   Thot/doc/amaya/Creating.html \
   Thot/doc/amaya/MakeBook.html \
   Thot/doc/amaya/StyleSheets.html \
   Thot/doc/amaya/Manual.html \
   Thot/doc/amaya/Tables.html \
   Thot/doc/amaya/AmayaArchi.html \
   Thot/doc/amaya/Math.html \
   Thot/doc/amaya/Registry.html \
   Thot/doc/amaya/Transform.html \
   Thot/doc/amaya/Attributes.html \
   Thot/doc/amaya/New.html \
   Thot/doc/amaya/Views.html \
   Thot/doc/amaya/Autoconf.html \
   Thot/doc/amaya/Saving.html \
   Thot/doc/amaya/ImageMaps.html \
   Thot/doc/amaya/Numbering.html \
   Thot/doc/amaya/Searching.html \
   Thot/doc/amaya/BinDist.html \
   Thot/doc/amaya/Selecting.html \
   Thot/doc/amaya/Browsing.html \
   Thot/doc/amaya/CSS.html \
   Thot/doc/amaya/Plugins.html \
   Thot/doc/amaya/Keyboard.html \
   Thot/doc/amaya/Printing.html \
   Thot/doc/amaya/Changing.html \
   Thot/doc/amaya/Publishing.html \
   Thot/doc/amaya/Configure.html \
   Thot/doc/amaya/Links.html \
   Thot/doc/amaya/Put.html \
   Thot/doc/amaya/SpellChecking.html \
   Thot/doc/amaya/api \
   Thot/doc/Icons/*.gif \
   Thot/Icons/WWW/activity_48x48 \
   Thot/Icons/WWW/guide48x \
   Thot/Icons/WWW/new_red \
   Thot/Icons/WWW/relnotes48x \
   Thot/Icons/WWW/w3c_home \
   Thot/$MACH/bin/amaya \
   Thot/$MACH/bin/print \
   Thot/$MACH/bin/dns_daemon \
   Thot/$MACH/bin/kaffe \
   Thot/$MACH/bin/kaffeh \
   Thot/$MACH/bin/javac \
   Thot/classes/amaya.zip \
   Thot/classes/biss.zip \
   Thot/classes/classes.zip \
   Thot/classes/jigsaw.zip \
   Thot/classes/sources.zip \
   Thot/classes/thotlib.zip \
   Thot/classes/lib \
   Thot/batch/MachineType \
   Thot/amaya/COPYRIGHT \
   Thot/amaya/AmayaPage.html \
   Thot/amaya/HTML.STR \
   Thot/amaya/HTML.conf \
   Thot/amaya/HTML.trans \
   Thot/amaya/HTML.en \
   Thot/amaya/HTML.fr \
   Thot/amaya/HTML*.PRS \
   Thot/amaya/HTML*.TRA \
   Thot/amaya/*.gif \
   Thot/amaya/MathML.STR \
   Thot/amaya/MathML*.PRS \
   Thot/amaya/MathML*.TRA \
   Thot/amaya/MathML.trans \
   Thot/fonts/Families.list \
   Thot/fonts/fonts.dir \
   Thot/fonts/icones* \
   | $COMPRESS  > $DEST/amaya-java-$MACH-$AMAYAVERSION.tar.gz
done

