#!/bin/sh
#
# This script builds all the binary tar files for Amaya
#
#       amaya-$MACH-$AMAYAVERSION.tgz
# 
AMAYAVERSION=v.r
THOTDIR=$PWD/../..
DEST=$HOME
PLATFORMS="solaris8 LINUX-ELF GTK GL"

TAR="tar cvzfh "
COMPRESS="gzip -9"

cd $THOTDIR
echo "Generating binary tar files from " $THOTDIR

for MACH in $PLATFORMS
do
echo "Platform ------->" $MACH
 $TAR $DEST/amaya-$MACH-$AMAYAVERSION.tgz \
   Amaya/README.amaya \
   Amaya/README.gl \
   Amaya/config/XKeysymDB \
   Amaya/config/amaya.kb \
   Amaya/config/amaya.keyboard \
   Amaya/config/amaya.emacs \
   Amaya/config/amaya.profiles \
   Amaya/config/*thot.rc \
   Amaya/config/*-amayadialogue \
   Amaya/config/*-amayamsg \
   Amaya/config/*-libdialogue \
   Amaya/config/*-corrdialogue \
   Amaya/config/*rdf \
   Amaya/config/annot.schemas \
   Amaya/config/thread.rdf \
   Amaya/config/replytypes.rdf \
   Amaya/dicopar/*.dic \
   Amaya/dicopar/*.ptn \
   Amaya/dicopar/alphabet \
   Amaya/dicopar/clavier \
   Amaya/doc/html/*.html* \
   Amaya/doc/html/*/*.html* \
   Amaya/doc/html/*.css \
   Amaya/doc/images/*.gif \
   Amaya/doc/images/*.png \
   Amaya/doc/images/*.jpg \
   Amaya/doc/images/w3c_home \
   Amaya/$MACH/bin/amaya \
   Amaya/$MACH/bin/print \
   Amaya/batch/MachineType \
   Amaya/annotlib/Annot.STR \
   Amaya/annotlib/AnnotP.PRS \
   Amaya/annotlib/AnnotT.TRA \
   Amaya/annotlib/selected.gif \
   Amaya/amaya/COPYRIGHT* \
   Amaya/amaya/AmayaPage.html* \
   Amaya/amaya/*.conf \
   Amaya/amaya/HTML.STR \
   Amaya/amaya/HTML.trans \
   Amaya/amaya/HTML*.PRS \
   Amaya/amaya/HTML*.TRA \
   Amaya/amaya/*.en \
   Amaya/amaya/*.gif \
   Amaya/amaya/*.png \
   Amaya/amaya/XLink.STR \
   Amaya/amaya/XLink*.PRS \
   Amaya/amaya/XLink*.TRA \
   Amaya/amaya/MathML.STR \
   Amaya/amaya/MathML*.PRS \
   Amaya/amaya/MathML*.TRA \
   Amaya/amaya/MathML.trans \
   Amaya/amaya/SVG.STR \
   Amaya/amaya/SVG*.PRS \
   Amaya/amaya/SVG*.TRA \
   Amaya/amaya/XML.STR \
   Amaya/amaya/XML*.PRS \
   Amaya/amaya/XML*.TRA \
   Amaya/amaya/TextFile.STR \
   Amaya/amaya/TextFile*.PRS \
   Amaya/amaya/TextFile*.TRA \
   Amaya/fonts/Families.list \
   Amaya/fonts/fonts.dir \
   Amaya/fonts/icones*
done

