#!/bin/sh
#
# This script builds doc tar file for Amaya
#
#       amaya-user-doc.tar.gz
#
THOTDIR=/tahiti/diffusion/opera
DEST=/tahiti/thottape
TAR="tar cvbfh 200"
COMPRESS="gzip -9"

cd $THOTDIR

$TAR - \
Thot/doc/amaya/Creating.html \
Thot/doc/amaya/MakeBook.html \
Thot/doc/amaya/StyleSheets.html \
Thot/doc/amaya/Manual.html \
Thot/doc/amaya/Tables.html \
Thot/doc/amaya/AmayaArchi.html \
Thot/doc/amaya/Math.html \
Thot/doc/amaya/Registry.html \
Thot/doc/amaya/Transform.html \
Thot/doc/amaya/Attributes.html \
Thot/doc/amaya/New.html \
Thot/doc/amaya/Views.html \
Thot/doc/amaya/Autoconf.html \
Thot/doc/amaya/Saving.html \
Thot/doc/amaya/ImageMaps.html \
Thot/doc/amaya/Numbering.html \
Thot/doc/amaya/Searching.html \
Thot/doc/amaya/BinDist.html \
Thot/doc/amaya/Selecting.html \
Thot/doc/amaya/Browsing.html \
Thot/doc/amaya/CSS.html \
Thot/doc/amaya/Plugins.html \
Thot/doc/amaya/Keyboard.html \
Thot/doc/amaya/Printing.html \
Thot/doc/amaya/Changing.html \
Thot/doc/amaya/Publishing.html \
Thot/doc/amaya/Configure.html \
Thot/doc/amaya/Links.html \
Thot/doc/amaya/Put.html \
Thot/doc/amaya/SpellChecking.html \
Thot/doc/Icons/*.gif \
Thot/Icons/WWW/activity_48x48 \
Thot/Icons/WWW/guide48x \
Thot/Icons/WWW/new_red \
Thot/Icons/WWW/relnotes48x \
Thot/Icons/WWW/w3c_home \
 | $COMPRESS  > $DEST/amaya-user-doc.tar.gz
