#!/bin/sh
#
# This script builds doc tar file for Amaya
#
#       amaya-user-doc.tar.gz
#
THOTDIR=/tahiti/diffusion/opera
DEST=/tahiti/thottape
TAR="tar cvbfh 200"
COMPRESS="gzip -9"

cd $THOTDIR

$TAR - \
doc/amaya/*.html \
doc/amaya/*.gif \
doc/amaya/amaya.css \
doc/amaya/daniel.css \
Icons/WWW/ \
 | $COMPRESS  > $DEST/amaya-user-doc.tar.gz
