#!/bin/sh
#
# This script builds doc tar file for Amaya
#
#       amaya-user-doc.tar.gz
#
THOTDIR=/tahiti/diffusion/opera
DEST=/tahiti/thottape
TAR="tar cvbfh 200"
COMPRESS="gzip -9"

cd $THOTDIR

$TAR - \
doc/amaya/Autoconf.html \
doc/amaya/Back.gif \
doc/amaya/COPYRIGHT.html \
doc/amaya/CSS.html \
doc/amaya/Compiling.html \
doc/amaya/Configure.html \
doc/amaya/Forward.gif \
doc/amaya/Overview.html \
doc/amaya/Image.gif \
doc/amaya/Install.html \
doc/amaya/Keyboard.html \
doc/amaya/Limitations.html \
doc/amaya/Manual.html \
doc/amaya/Map.html \
doc/amaya/New.html \
doc/amaya/NumList.gif \
doc/amaya/Overview.html \
doc/amaya/Platforms.html \
doc/amaya/Porting.html \
doc/amaya/Proxy.html \
doc/amaya/Publishing.html \
doc/amaya/Put.html \
doc/amaya/PutCern.html \
doc/amaya/PutOver.html \
doc/amaya/Registry.html \
doc/amaya/SaveAs.gif \
doc/amaya/Sources.gif \
doc/amaya/Sources.html \
doc/amaya/amaya.css \
doc/amaya/amaya.gif \
doc/amaya/css.gif \
doc/amaya/daniel.css \
doc/amaya/destroy.gif \
doc/amaya/drapeau-F.gif \
doc/amaya/floppy.gif \
doc/amaya/lcopy.gif \
doc/amaya/lmerge.gif \
doc/amaya/opera.gif \
doc/amaya/put.conf \
doc/amaya/put.gif \
doc/amaya/rcopy.gif \
doc/amaya/rmerge.gif \
doc/amaya/warning.gif \
Icons/32x32/warning.gif \
Icons/WWW/activity_48x48 \
Icons/WWW/guide48x \
Icons/WWW/new_red \
Icons/WWW/relnotes48x \
Icons/WWW/w3c_48x48 \
Icons/WWW/w3c_home \
 | $COMPRESS  > $DEST/amaya-user-doc.tar.gz
