#!/bin/sh
#
# This script builds the Source tarfile for amaya
#
#       amaya-src-$AMAYAVERSION.tgz
#
# And the associated Librairies for supported versions.
#
# Usage:    ./tarSourcesAmaya amayaversion [dest_path]
# Default : ./tarSourcesAmaya
# (AMAYAVERSION variable is used by default)
#

# default parameters
AMAYAVERSION="8.2"
DEST=$HOME

# Check argument number on the command line
ARGS=2
E_MAUVAISARGS=65
if [ $# -le 0 ]
then
  echo "Usage: `basename $0` amayaversion [dest_path]"
  echo "Default: `basename $0` $AMAYAVERSION"
else
  # amayaversion is the first parameter
  AMAYAVERSION=$1
  # destination directory is the second parameter
  if [ -z $2 ]
  then
    DEST=$HOME
  else
    DEST=$2
  fi
fi

# search directories to tar (Amaya and libwww)
AMAYADIR=$PWD/..
TARDIR=$PWD/../..
cd $AMAYADIR
AMAYADIR=$PWD
cd $TARDIR
TARDIR=$PWD/
AMAYADIR=${AMAYADIR#$TARDIR}
LIBWWWDIR=libwww
REDLANDDIR=redland

TAR="tar cvbfh 200"
COMPRESS="gzip -9"

echo "Generating the source tar file from $AMAYADIR and $LIBWWWDIR"

$TAR - \
${AMAYADIR}/README.amaya \
${AMAYADIR}/README \
${AMAYADIR}/README.gl \
${AMAYADIR}/config.guess \
${AMAYADIR}/config.h.in \
${AMAYADIR}/config.sub \
${AMAYADIR}/configure \
${AMAYADIR}/configure.in \
${AMAYADIR}/Makefile.in \
${AMAYADIR}/install-sh \
${AMAYADIR}/stamp-h.in \
${AMAYADIR}/Options.in \
${AMAYADIR}/batch/Makefile.in \
${AMAYADIR}/batch/tarAmaya \
${AMAYADIR}/amaya/COPYRIGHT* \
${AMAYADIR}/amaya/Makefile.* \
${AMAYADIR}/amaya/AmayaPage.html* \
${AMAYADIR}/amaya/Amaya.svg \
${AMAYADIR}/amaya/Text_SGML.inc \
${AMAYADIR}/amaya/*.A \
${AMAYADIR}/amaya/*.P \
${AMAYADIR}/amaya/*.S \
${AMAYADIR}/amaya/*.T \
${AMAYADIR}/amaya*.spec \
${AMAYADIR}/amaya/*.c \
${AMAYADIR}/amaya/*.cpp \
${AMAYADIR}/amaya/*.conf \
${AMAYADIR}/amaya/*.en \
${AMAYADIR}/amaya/*.h \
${AMAYADIR}/amaya/*.trans* \
${AMAYADIR}/amaya/greek.sgml \
${AMAYADIR}/amaya/*.bmp \
${AMAYADIR}/amaya/*.gif \
${AMAYADIR}/amaya/*.png \
${AMAYADIR}/amaya/*.rc \
${AMAYADIR}/amaya/*.ico \
${AMAYADIR}/amaya/*.cur \
${AMAYADIR}/amaya/f/*.h \
${AMAYADIR}/amaya/xpm/*.xpm \
${AMAYADIR}/annotlib/Makefile.* \
${AMAYADIR}/annotlib/*.A \
${AMAYADIR}/annotlib/*.S \
${AMAYADIR}/annotlib/*.P \
${AMAYADIR}/annotlib/*.T \
${AMAYADIR}/annotlib/*.en \
${AMAYADIR}/annotlib/*.c \
${AMAYADIR}/annotlib/*.cpp \
${AMAYADIR}/annotlib/*.h \
${AMAYADIR}/annotlib/f/*.h \
${AMAYADIR}/annotlib/selected.gif \
${AMAYADIR}/annotlib/closed.png \
${AMAYADIR}/annotlib/open.png \
${AMAYADIR}/batch/COPYRIGHT* \
${AMAYADIR}/batch/*.LAN \
${AMAYADIR}/batch/*.GRM \
${AMAYADIR}/batch/MachineType \
${AMAYADIR}/batch/*.rc \
${AMAYADIR}/batch/resource.h \
${AMAYADIR}/batch/comp_ico.ico \
${AMAYADIR}/batch/comp_toolbar.bmp \
${AMAYADIR}/batch/*.c \
${AMAYADIR}/batch/*.cpp \
${AMAYADIR}/batch/f/*.h \
${AMAYADIR}/config/amaya.kb \
${AMAYADIR}/config/amaya.keyboard \
${AMAYADIR}/config/amaya.emacs \
${AMAYADIR}/config/amaya.profiles \
${AMAYADIR}/config/*-amayadialogue \
${AMAYADIR}/config/*-amayamsg \
${AMAYADIR}/config/*-libdialogue \
${AMAYADIR}/config/*-corrdialogue \
${AMAYADIR}/config/en-appdialogue \
${AMAYADIR}/config/en-compildialogue \
${AMAYADIR}/config/en-grmdialogue \
${AMAYADIR}/config/en-prsdialogue \
${AMAYADIR}/config/en-strdialogue \
${AMAYADIR}/config/en-tradialogue \
${AMAYADIR}/config/XKeysymDB \
${AMAYADIR}/config/*thot.rc \
${AMAYADIR}/config/thot.color \
${AMAYADIR}/config/*rdf \
${AMAYADIR}/config/annot.schemas \
${AMAYADIR}/config/fonts.* \
${AMAYADIR}/config/lib_files.dat \
${AMAYADIR}/config/libconfig/*.css \
${AMAYADIR}/config/libconfig/*.png \
${AMAYADIR}/config/libconfig/*.lhtml \
${AMAYADIR}/config/libconfig/*.svg \
${AMAYADIR}/cpp/winnt/*.bat \
${AMAYADIR}/cpp/*.c \
${AMAYADIR}/cpp/*.cpp \
${AMAYADIR}/cpp/*.h \
${AMAYADIR}/cpp/winnt/*.sed \
${AMAYADIR}/cpp/winnt/*.c \
${AMAYADIR}/cpp/winnt/*.cpp \
${AMAYADIR}/cpp/winnt/*.h \
${AMAYADIR}/cpp/winnt/*.mak \
${AMAYADIR}/cpp/i386/*.c \
${AMAYADIR}/cpp/i386/*.cpp \
${AMAYADIR}/cpp/i386/*.h \
${AMAYADIR}/cpp/i386/*.sed \
${AMAYADIR}/cpp/i386/*.md \
${AMAYADIR}/cpp/i386/*.asm \
${AMAYADIR}/cpp/i386/*.ifile \
${AMAYADIR}/cpp/i386/t-* \
${AMAYADIR}/cpp/i386/x-* \
${AMAYADIR}/davlib/Makefile.in \
${AMAYADIR}/davlib/*.c \
${AMAYADIR}/davlib/*.cpp \
${AMAYADIR}/davlib/f/*.h \
${AMAYADIR}/davlib/h/*.h \
${AMAYADIR}/davlib/tree/*.c \
${AMAYADIR}/davlib/tree/*.cpp \
${AMAYADIR}/davlib/tree/h/*.h \
${AMAYADIR}/dicopar/*.dic \
${AMAYADIR}/dicopar/*.ptn \
${AMAYADIR}/dicopar/alphabet \
${AMAYADIR}/dicopar/clavier \
${AMAYADIR}/doc/html/*.html* \
${AMAYADIR}/doc/html/*/*.html* \
${AMAYADIR}/doc/html/*.css \
${AMAYADIR}/doc/images/*.gif \
${AMAYADIR}/doc/images/*.png \
${AMAYADIR}/doc/images/*.jpg \
${AMAYADIR}/doc/images/w3c_home \
${AMAYADIR}/fonts/Families.list \
${AMAYADIR}/fonts/fonts.dir \
${AMAYADIR}/fonts/icones* \
${AMAYADIR}/libjpeg/Makefile.in \
${AMAYADIR}/libjpeg/Makefile \
${AMAYADIR}/libjpeg/README \
${AMAYADIR}/libjpeg/*.1 \
${AMAYADIR}/libjpeg/*.c \
${AMAYADIR}/libjpeg/*.cpp \
${AMAYADIR}/libjpeg/*.h \
${AMAYADIR}/libjpeg/*.log \
${AMAYADIR}/libjpeg/*.doc \
${AMAYADIR}/libjpeg/configure \
${AMAYADIR}/libjpeg/jconfig.bcc \
${AMAYADIR}/libjpeg/jconfig.cfg \
${AMAYADIR}/libjpeg/jconfig.dj \
${AMAYADIR}/libjpeg/jconfig.manx \
${AMAYADIR}/libjpeg/jconfig.mc6 \
${AMAYADIR}/libjpeg/jconfig.sas \
${AMAYADIR}/libjpeg/jconfig.st \
${AMAYADIR}/libjpeg/jconfig.vms \
${AMAYADIR}/libjpeg/jconfig.wat \
${AMAYADIR}/libjpeg/jmemdosa.asm \
${AMAYADIR}/libjpeg/makcjpeg.st \
${AMAYADIR}/libjpeg/makdjpeg.st \
${AMAYADIR}/libjpeg/makefile.ansi \
${AMAYADIR}/libjpeg/makefile.bcc \
${AMAYADIR}/libjpeg/makefile.cfg \
${AMAYADIR}/libjpeg/makefile.dj \
${AMAYADIR}/libjpeg/makefile.manx \
${AMAYADIR}/libjpeg/makefile.mc6 \
${AMAYADIR}/libjpeg/makefile.mms \
${AMAYADIR}/libjpeg/makefile.sas \
${AMAYADIR}/libjpeg/makefile.unix \
${AMAYADIR}/libjpeg/makefile.vms \
${AMAYADIR}/libjpeg/makefile.wat \
${AMAYADIR}/libjpeg/makljpeg.st \
${AMAYADIR}/libjpeg/maktjpeg.st \
${AMAYADIR}/libjpeg/makvms.opt \
${AMAYADIR}/libjpeg/testimg.gif \
${AMAYADIR}/libjpeg/testimg.jpg \
${AMAYADIR}/libjpeg/testimg.ppm \
${AMAYADIR}/libjpeg/testimgp.jpg \
${AMAYADIR}/libjpeg/testorig.jpg \
${AMAYADIR}/libjpeg/testprog.jpg \
${AMAYADIR}/libpng/Makefile.in \
${AMAYADIR}/libpng/*.c \
${AMAYADIR}/libpng/*.cpp \
${AMAYADIR}/libpng/*.h \
${AMAYADIR}/libpng/zlib/ChangeLog \
${AMAYADIR}/libpng/zlib/Make_vms.com \
${AMAYADIR}/libpng/zlib/Makefile \
${AMAYADIR}/libpng/zlib/Makefile.in \
${AMAYADIR}/libpng/zlib/Makefile.bor \
${AMAYADIR}/libpng/zlib/Makefile.msc \
${AMAYADIR}/libpng/zlib/Makefile.qnx \
${AMAYADIR}/libpng/zlib/Makefile.tc \
${AMAYADIR}/libpng/zlib/README \
${AMAYADIR}/libpng/zlib/*.c \
${AMAYADIR}/libpng/zlib/*.cpp \
${AMAYADIR}/libpng/zlib/*.h \
${AMAYADIR}/libpng/zlib/descrip.mms \
${AMAYADIR}/libraptor/Makefile.in \
${AMAYADIR}/libraptor/README \
${AMAYADIR}/libraptor/stamp-h.in \
${AMAYADIR}/libraptor/AUTHORS \
${AMAYADIR}/libraptor/COPYING \
${AMAYADIR}/libraptor/COPYING.LIB \
${AMAYADIR}/libraptor/ChangeLog \
${AMAYADIR}/libraptor/INSTALL \
${AMAYADIR}/libraptor/Makefile.am \
${AMAYADIR}/libraptor/NEWS \
${AMAYADIR}/libraptor/acconfig.h \
${AMAYADIR}/libraptor/aclocal.m4 \
${AMAYADIR}/libraptor/config.guess \
${AMAYADIR}/libraptor/config.h.in \
${AMAYADIR}/libraptor/config.sub \
${AMAYADIR}/libraptor/configure \
${AMAYADIR}/libraptor/configure.in \
${AMAYADIR}/libraptor/install-sh \
${AMAYADIR}/libraptor/ltmain.sh \
${AMAYADIR}/libraptor/missing \
${AMAYADIR}/libraptor/mkinstalldirs \
${AMAYADIR}/libraptor/raptor.spec.in \
${AMAYADIR}/libraptor/raptor_parse.c \
${AMAYADIR}/libraptor/ntriples_parse.c \
${AMAYADIR}/libraptor/raptor_uri.c \
${AMAYADIR}/libraptor/raptor.h \
${AMAYADIR}/libraptor/ntriples.h \
${AMAYADIR}/libraptor/LICENSE.txt \
${AMAYADIR}/libraptor/README.html \
${AMAYADIR}/libraptor/NEWS.html \
${AMAYADIR}/libraptor/LICENSE.html \
${AMAYADIR}/libraptor/INSTALL.html \
${AMAYADIR}/libraptor/MPL.html \
${AMAYADIR}/libraptor/autogen.sh \
${AMAYADIR}/libraptor/dc.rdf \
${AMAYADIR}/libraptor/raptor_cc.gperf \
${AMAYADIR}/libraptor/raptor_cc.c \
${AMAYADIR}/pluginlib/Makefile.in \
${AMAYADIR}/pluginlib/COPYRIGHT* \
${AMAYADIR}/pluginlib/Makefile.plugin \
${AMAYADIR}/pluginlib/*.h \
${AMAYADIR}/pluginlib/*.c \
${AMAYADIR}/pluginlib/*.cpp \
${AMAYADIR}/pluginlib/f/*.h \
${AMAYADIR}/tablelib/Makefile.in \
${AMAYADIR}/tablelib/COPYRIGHT* \
${AMAYADIR}/tablelib/*.c \
${AMAYADIR}/tablelib/*.cpp \
${AMAYADIR}/tablelib/f/*.h \
${AMAYADIR}/thotlib/Makefile.in \
${AMAYADIR}/thotlib/include/Makefile.in \
${AMAYADIR}/thotlib/base/*.c \
${AMAYADIR}/thotlib/base/*.cpp \
${AMAYADIR}/thotlib/content/*.c \
${AMAYADIR}/thotlib/content/*.cpp \
${AMAYADIR}/thotlib/dialogue/*.c \
${AMAYADIR}/thotlib/dialogue/*.cpp \
${AMAYADIR}/thotlib/document/*.c \
${AMAYADIR}/thotlib/document/*.cpp \
${AMAYADIR}/thotlib/editing/*.c \
${AMAYADIR}/thotlib/editing/*.cpp \
${AMAYADIR}/thotlib/image/*.c \
${AMAYADIR}/thotlib/image/*.cpp \
${AMAYADIR}/thotlib/include/*.h \
${AMAYADIR}/thotlib/internals/f/*.h \
${AMAYADIR}/thotlib/internals/h/*.h \
${AMAYADIR}/thotlib/internals/h/*.xpm \
${AMAYADIR}/thotlib/internals/h/*.xbm \
${AMAYADIR}/thotlib/internals/var/*.h \
${AMAYADIR}/thotlib/presentation/*.c \
${AMAYADIR}/thotlib/presentation/*.cpp \
${AMAYADIR}/thotlib/tree/*.c \
${AMAYADIR}/thotlib/tree/*.cpp \
${AMAYADIR}/thotlib/unicode/*.c \
${AMAYADIR}/thotlib/unicode/*.cpp \
${AMAYADIR}/thotlib/view/*.c \
${AMAYADIR}/thotlib/view/*.cpp \
${AMAYADIR}/tools/Makefile.in \
${AMAYADIR}/tools/mkdep/Makefile.in \
${AMAYADIR}/tools/mkdep/Makefile \
${AMAYADIR}/tools/mkdep/mkdep.c \
${AMAYADIR}/tools/cextract-1.7/Makefile.in \
${AMAYADIR}/tools/cextract-1.7/HPUX.Install \
${AMAYADIR}/tools/cextract-1.7/INSTALL \
${AMAYADIR}/tools/cextract-1.7/INSTALL.VMS \
${AMAYADIR}/tools/cextract-1.7/Imakefile \
${AMAYADIR}/tools/cextract-1.7/MANIFEST \
${AMAYADIR}/tools/cextract-1.7/Makefile \
${AMAYADIR}/tools/cextract-1.7/Makefile.clm \
${AMAYADIR}/tools/cextract-1.7/Makefile.cln \
${AMAYADIR}/tools/cextract-1.7/README \
${AMAYADIR}/tools/cextract-1.7/README.LUCS \
${AMAYADIR}/tools/cextract-1.7/TODO \
${AMAYADIR}/tools/cextract-1.7/build.com \
${AMAYADIR}/tools/cextract-1.7/cextdoc.1 \
${AMAYADIR}/tools/cextract-1.7/cextract.doc \
${AMAYADIR}/tools/cextract-1.7/cextract.hlp \
${AMAYADIR}/tools/cextract-1.7/cextract.man \
${AMAYADIR}/tools/cextract-1.7/cextrc.5 \
${AMAYADIR}/tools/cextract-1.7/cextrc.doc \
${AMAYADIR}/tools/cextract-1.7/io.c \
${AMAYADIR}/tools/cextract-1.7/main.c \
${AMAYADIR}/tools/cextract-1.7/main.c.cln \
${AMAYADIR}/tools/cextract-1.7/newbuild.com \
${AMAYADIR}/tools/cextract-1.7/parse.c \
${AMAYADIR}/tools/cextract-1.7/patchlevel.h \
${AMAYADIR}/tools/cextract-1.7/proto.h \
${AMAYADIR}/tools/cextract-1.7/xtract.h \
${AMAYADIR}/Windows/*.mak \
${AMAYADIR}/Windows/*.dsp \
${AMAYADIR}/Windows/*.dsw \
${AMAYADIR}/Windows/amaya/*.mkf \
${AMAYADIR}/Windows/annotlib/*.dsp \
${AMAYADIR}/Windows/Compilers/*.mak \
${AMAYADIR}/Windows/Compilers/*.dsp \
${AMAYADIR}/Windows/Compilers/*.dsw \
${AMAYADIR}/Windows/LibThotEditor/*.dsp \
${AMAYADIR}/Windows/LibThotKernel/*.dsp \
${AMAYADIR}/Windows/app/*.dsp \
${AMAYADIR}/Windows/cpp/*.dsp \
${AMAYADIR}/Windows/davlib/*.dsp \
${AMAYADIR}/Windows/libThotTable/*.dsp \
${AMAYADIR}/Windows/libjpeg/*.dsp \
${AMAYADIR}/Windows/libpng/*.dsp \
${AMAYADIR}/Windows/libwww/*.dsp \
${AMAYADIR}/Windows/libwww/*.dev \
${AMAYADIR}/Windows/printlib/*.dsp \
${AMAYADIR}/Windows/libraptor/*.dsp \
${AMAYADIR}/Windows/prs/*.dsp \
${AMAYADIR}/Windows/str/*.dsp \
${AMAYADIR}/Windows/thotprinter/*.dsp \
${AMAYADIR}/Windows/tra/*.dsp \
${AMAYADIR}/Windows/zlib/*.dsp \
${AMAYADIR}/Windows/zlib/*.dev \
${AMAYADIR}/WindowsGL/*.mak \
${AMAYADIR}/WindowsGL/*.dsp \
${AMAYADIR}/WindowsGL/*.dsw \
${AMAYADIR}/WindowsGL/amaya/*.mkf \
${AMAYADIR}/WindowsGL/annotlib/*.dsp \
${AMAYADIR}/WindowsGL/Compilers/*.mak \
${AMAYADIR}/WindowsGL/Compilers/*.dsp \
${AMAYADIR}/WindowsGL/Compilers/*.dsw \
${AMAYADIR}/WindowsGL/LibThotEditor/*.dsp \
${AMAYADIR}/WindowsGL/LibThotKernel/*.dsp \
${AMAYADIR}/WindowsGL/app/*.dsp \
${AMAYADIR}/WindowsGL/cpp/*.dsp \
${AMAYADIR}/WindowsGL/libThotTable/*.dsp \
${AMAYADIR}/WindowsGL/libjpeg/*.dsp \
${AMAYADIR}/WindowsGL/libpng/*.dsp \
${AMAYADIR}/WindowsGL/libwww/*.dsp \
${AMAYADIR}/WindowsGL/printlib/*.dsp \
${AMAYADIR}/WindowsGL/libraptor/*.dsp \
${AMAYADIR}/WindowsGL/prs/*.dsp \
${AMAYADIR}/WindowsGL/str/*.dsp \
${AMAYADIR}/WindowsGL/thotprinter/*.dsp \
${AMAYADIR}/WindowsGL/tra/*.dsp \
${AMAYADIR}/WindowsGL/zlib/*.dsp \
${LIBWWWDIR}/COPYRIGH \
${LIBWWWDIR}/README.html \
${LIBWWWDIR}/LICENSE.html \
${LIBWWWDIR}/Makefile.am \
${LIBWWWDIR}/Makefile.in \
${LIBWWWDIR}/aclocal.m4 \
${LIBWWWDIR}/libwww-config.in \
${LIBWWWDIR}/wwwconf.h.in \
${LIBWWWDIR}/w3c-libwww.spec.in \
${LIBWWWDIR}/configure \
${LIBWWWDIR}/configure.ac \
${LIBWWWDIR}/stamp-h.in \
${LIBWWWDIR}/wwwconf.h.in \
${LIBWWWDIR}/Library/Makefile.am \
${LIBWWWDIR}/Library/Makefile.in \
${LIBWWWDIR}/Library/src/Makefile.in \
${LIBWWWDIR}/Library/src/Makefile.am \
${LIBWWWDIR}/Library/src/vms/COPYING.LIB \
${LIBWWWDIR}/Library/src/vms/Makefile.am \
${LIBWWWDIR}/Library/src/vms/Makefile.in \
${LIBWWWDIR}/Library/src/vms/build_multinet.com \
${LIBWWWDIR}/Library/src/vms/descrip.mms \
${LIBWWWDIR}/Library/src/*.c \
${LIBWWWDIR}/Library/src/*.cpp \
${LIBWWWDIR}/Library/src/*.h \
${LIBWWWDIR}/Library/src/windows/Makefile.am \
${LIBWWWDIR}/Library/src/windows/Makefile.in \
${LIBWWWDIR}/Library/src/windows/*.c \
${LIBWWWDIR}/Library/src/windows/*.cpp \
${LIBWWWDIR}/Library/src/windows/*.h \
${LIBWWWDIR}/Library/src/windows/*.def \
${LIBWWWDIR}/Library/src/windows/*.files \
${LIBWWWDIR}/modules/Makefile.am \
${LIBWWWDIR}/modules/Makefile.in \
${LIBWWWDIR}/modules/md5/Makefile.am \
${LIBWWWDIR}/modules/md5/Makefile.in \
${LIBWWWDIR}/modules/md5/*.c \
${LIBWWWDIR}/modules/md5/*.cpp \
${LIBWWWDIR}/modules/md5/*.h \
${LIBWWWDIR}/modules/expat/COPYING \
${LIBWWWDIR}/modules/expat/MANIFEST \
${LIBWWWDIR}/modules/expat/README \
${LIBWWWDIR}/modules/expat/conftools/* \
${LIBWWWDIR}/modules/expat/vms/* \
${LIBWWWDIR}/modules/expat/Makefile.am \
${LIBWWWDIR}/modules/expat/configure \
${LIBWWWDIR}/modules/expat/expat_config.h.in \
${LIBWWWDIR}/modules/expat/win32/* \
${LIBWWWDIR}/modules/expat/Changes \
${LIBWWWDIR}/modules/expat/Makefile.in \
${LIBWWWDIR}/modules/expat/configure.in \
${LIBWWWDIR}/modules/expat/lib/*.h \
${LIBWWWDIR}/modules/expat/lib/*.c \
${LIBWWWDIR}/modules/expat/lib/*.cpp \
${LIBWWWDIR}/config/Makefile.am \
${LIBWWWDIR}/config/Makefile.in \
${LIBWWWDIR}/config/config.guess \
${LIBWWWDIR}/config/config.sub \
${LIBWWWDIR}/config/install-sh \
${LIBWWWDIR}/config/ltmain.sh \
${LIBWWWDIR}/config/ltconfig \
${LIBWWWDIR}/config/makedefs.pl \
${LIBWWWDIR}/config/makeindx.pl \
${LIBWWWDIR}/config/makexprt.pl \
${LIBWWWDIR}/config/missing \
${LIBWWWDIR}/config/mkinstalldirs \
${LIBWWWDIR}/config/winConfigure.pl \
${LIBWWWDIR}/config/depcomp \
${REDLANDDIR} \
 | $COMPRESS  > $DEST/amaya-src-$AMAYAVERSION.tgz

