#!/bin/sh
#
# This script builds the Source tarfile for amaya
#
#       amaya-src-$AMAYAVERSION.tgz
#
# And the associated Librairies for supported versions.
#
# Usage:    ./tarSourcesAmaya amayaversion [dest_path]
# Default : ./tarSourcesAmaya
# (AMAYAVERSION variable is used by default)
#

# default parameters
AMAYAVERSION="11.4"
DEST=$HOME

# Check argument number on the command line
ARGS=2
E_MAUVAISARGS=65
if [ $# -le 0 ]
then
  echo "Usage: `basename $0` amayaversion [dest_path]"
  echo "Default: `basename $0` $AMAYAVERSION"
else
  # amayaversion is the first parameter
  AMAYAVERSION=$1
  # destination directory is the second parameter
  if [ -z $2 ]
  then
    DEST=$HOME
  else
    DEST=$2
  fi
fi

# search directories to tar (Amaya and libwww)
AMAYADIR=$PWD/..
TARDIR=$PWD/../..
cd $AMAYADIR
AMAYADIR=$PWD
cd $TARDIR
TARDIR=$PWD/
AMAYADIR=${AMAYADIR#$TARDIR}
LIBWWWDIR=libwww
REDLANDDIR=redland
WXWIDGETS=wxWidgets
MESA=Mesa
FREETYPE=freetype
TAR="tar czfh "
UNTAR="tar xvzf"
TMP=$DEST/Amaya$AMAYAVERSION

echo "Generating the temporary tar files"
$TAR $DEST/libs-tmp-$AMAYAVERSION.tgz \
${LIBWWWDIR}/COPYRIGH \
${LIBWWWDIR}/Makefile.am \
${LIBWWWDIR}/Makefile.am.64 \
${LIBWWWDIR}/Makefile.in \
${LIBWWWDIR}/aclocal.m4 \
${LIBWWWDIR}/aclocal.m4.64 \
${LIBWWWDIR}/libwww-config.in \
${LIBWWWDIR}/wwwconf.h.in \
${LIBWWWDIR}/w3c-libwww.spec.in \
${LIBWWWDIR}/configure \
${LIBWWWDIR}/configure.ac \
${LIBWWWDIR}/configure.ac.64 \
${LIBWWWDIR}/wwwconf.h.in \
${LIBWWWDIR}/Library/Makefile.am \
${LIBWWWDIR}/Library/Makefile.in \
${LIBWWWDIR}/Library/src \
${LIBWWWDIR}/modules \
${LIBWWWDIR}/config \
${REDLANDDIR} \
${WXWIDGETS}/art \
${WXWIDGETS}/build \
${WXWIDGETS}/distrib \
${WXWIDGETS}/include \
${WXWIDGETS}/lib \
${WXWIDGETS}/locale \
${WXWIDGETS}/src \
${WXWIDGETS}/*.in \
${WXWIDGETS}/mkinstalldirs \
${WXWIDGETS}/*.spec \
${WXWIDGETS}/*.m4 \
${WXWIDGETS}/install-sh \
${WXWIDGETS}/config* \
${WXWIDGETS}/*.txt \
${WXWIDGETS}/*.sh \
${MESA} \
${FREETYPE}

tar czvfh $DEST/amaya-tmp-$AMAYAVERSION.tgz \
${AMAYADIR}/resources/icons/16x16/*.ico \
${AMAYADIR}/resources/icons/misc/*.ico \
${AMAYADIR}/resources/icons/16x16/*.png \
${AMAYADIR}/resources/icons/22x22/*.png \
${AMAYADIR}/resources/icons/misc/*.png \
${AMAYADIR}/resources/svg/*.png \
${AMAYADIR}/resources/svg/*.svg \
${AMAYADIR}/resources/svg/*/*.png \
${AMAYADIR}/resources/svg/*/*.svg \
${AMAYADIR}/resources/xrc/*.xrc \
${AMAYADIR}/resources/bundle/Info.plist.in \
${AMAYADIR}/resources/bundle/amaya.icns \
${AMAYADIR}/resources/bundle/logo.png \
${AMAYADIR}/WindowsWX/*.dsp \
${AMAYADIR}/WindowsWX/*.dsw \
${AMAYADIR}/WindowsWX/amaya/*.mkf \
${AMAYADIR}/WindowsWX/annotlib/*.dsp \
${AMAYADIR}/WindowsWX/Compilers/*.dsp \
${AMAYADIR}/WindowsWX/Compilers/*.dsw \
${AMAYADIR}/WindowsWX/LibThotEditor/*.dsp \
${AMAYADIR}/WindowsWX/LibThotKernel/*.dsp \
${AMAYADIR}/WindowsWX/app/*.dsp \
${AMAYADIR}/WindowsWX/cpp/*.dsp \
${AMAYADIR}/WindowsWX/davlib/*.dsp \
${AMAYADIR}/WindowsWX/libwww/*.dsp \
${AMAYADIR}/WindowsWX/printlib/*.dsp \
${AMAYADIR}/WindowsWX/libraptor/*.dsp \
${AMAYADIR}/WindowsWX/prs/*.dsp \
${AMAYADIR}/WindowsWX/str/*.dsp \
${AMAYADIR}/WindowsWX/thotprinter/*.dsp \
${AMAYADIR}/WindowsWX/tra/*.dsp \
${AMAYADIR}/WindowsWX/wx-setup/setup.h \
${AMAYADIR}/README \
${AMAYADIR}/README.wx \
${AMAYADIR}/config.guess \
${AMAYADIR}/config.h.in \
${AMAYADIR}/config.sub \
${AMAYADIR}/configure \
${AMAYADIR}/configure.in \
${AMAYADIR}/Makefile.in \
${AMAYADIR}/install-sh \
${AMAYADIR}/stamp-h.in \
${AMAYADIR}/Options.in \
${AMAYADIR}/batch/amaya.in \
${AMAYADIR}/batch/script_*.in \
${AMAYADIR}/batch/Makefile.in \
${AMAYADIR}/amaya/COPYRIGHT* \
${AMAYADIR}/amaya/Makefile.* \
${AMAYADIR}/amaya/AmayaPage.html* \
${AMAYADIR}/amaya/AmayaPage_WX.html* \
${AMAYADIR}/amaya/Amaya.svg \
${AMAYADIR}/amaya/Text_SGML.inc \
${AMAYADIR}/amaya/*.A \
${AMAYADIR}/amaya/*.P \
${AMAYADIR}/amaya/*.S \
${AMAYADIR}/amaya/*.T \
${AMAYADIR}/amaya/amaya.css \
${AMAYADIR}/amaya*.spec \
${AMAYADIR}/amaya/*.c \
${AMAYADIR}/amaya/*.cpp \
${AMAYADIR}/amaya/*.conf \
${AMAYADIR}/amaya/*.en \
${AMAYADIR}/amaya/*.h \
${AMAYADIR}/amaya/*.trans* \
${AMAYADIR}/amaya/greek.sgml \
${AMAYADIR}/amaya/*.gif \
${AMAYADIR}/amaya/*.png \
${AMAYADIR}/amaya/*.rc \
${AMAYADIR}/amaya/*.ico \
${AMAYADIR}/amaya/*.cur \
${AMAYADIR}/amaya/mathedit/*.c \
${AMAYADIR}/amaya/mathedit/*.l \
${AMAYADIR}/amaya/mathedit/*.ypp \
${AMAYADIR}/amaya/mathedit/*.cpp \
${AMAYADIR}/amaya/mathedit/*.sh \
${AMAYADIR}/amaya/wxdialog/*.h \
${AMAYADIR}/amaya/wxdialog/*.cpp \
${AMAYADIR}/amaya/wxdialog/*.rc \
${AMAYADIR}/amaya/wxdialog/*.ico \
${AMAYADIR}/amaya/f/*.h \
${AMAYADIR}/annotlib/Makefile.* \
${AMAYADIR}/annotlib/*.A \
${AMAYADIR}/annotlib/*.S \
${AMAYADIR}/annotlib/*.P \
${AMAYADIR}/annotlib/*.T \
${AMAYADIR}/annotlib/*.en \
${AMAYADIR}/annotlib/*.c \
${AMAYADIR}/annotlib/*.h \
${AMAYADIR}/annotlib/f/*.h \
${AMAYADIR}/annotlib/selected.gif \
${AMAYADIR}/annotlib/closed.png \
${AMAYADIR}/annotlib/open.png \
${AMAYADIR}/batch/COPYRIGHT* \
${AMAYADIR}/batch/*.LAN \
${AMAYADIR}/batch/*.GRM \
${AMAYADIR}/batch/MachineType \
${AMAYADIR}/batch/*.rc \
${AMAYADIR}/batch/resource.h \
${AMAYADIR}/batch/comp_ico.ico \
${AMAYADIR}/batch/comp_toolbar.bmp \
${AMAYADIR}/batch/*.c \
${AMAYADIR}/batch/f/*.h \
${AMAYADIR}/config/amaya.kb \
${AMAYADIR}/config/amaya.kb-mac \
${AMAYADIR}/config/amaya.keyboard \
${AMAYADIR}/config/amaya.emacs \
${AMAYADIR}/config/amaya.profiles \
${AMAYADIR}/config/*-amayadialogue \
${AMAYADIR}/config/*-amayamsg \
${AMAYADIR}/config/*-libdialogue \
${AMAYADIR}/config/en-appdialogue \
${AMAYADIR}/config/en-compildialogue \
${AMAYADIR}/config/en-grmdialogue \
${AMAYADIR}/config/en-prsdialogue \
${AMAYADIR}/config/en-strdialogue \
${AMAYADIR}/config/en-tradialogue \
${AMAYADIR}/config/XKeysymDB \
${AMAYADIR}/config/*thot.rc \
${AMAYADIR}/config/thot.color \
${AMAYADIR}/config/*rdf \
${AMAYADIR}/config/*.dat \
${AMAYADIR}/config/*.css \
${AMAYADIR}/config/annot.schemas \
${AMAYADIR}/config/fonts.* \
${AMAYADIR}/cpp/winnt/*.bat \
${AMAYADIR}/cpp/*.c \
${AMAYADIR}/cpp/*.h \
${AMAYADIR}/cpp/winnt/*.sed \
${AMAYADIR}/cpp/winnt/*.c \
${AMAYADIR}/cpp/winnt/*.h \
${AMAYADIR}/cpp/i386/*.c \
${AMAYADIR}/cpp/i386/*.h \
${AMAYADIR}/cpp/i386/*.sed \
${AMAYADIR}/cpp/i386/*.md \
${AMAYADIR}/cpp/i386/*.asm \
${AMAYADIR}/cpp/i386/*.ifile \
${AMAYADIR}/cpp/i386/t-* \
${AMAYADIR}/cpp/i386/x-* \
${AMAYADIR}/davlib/Makefile.in \
${AMAYADIR}/davlib/Makefile.dav \
${AMAYADIR}/davlib/*.c \
${AMAYADIR}/davlib/f/*.h \
${AMAYADIR}/davlib/h/*.h \
${AMAYADIR}/davlib/tree/*.c \
${AMAYADIR}/davlib/tree/h/*.h \
${AMAYADIR}/dicopar/*.dic \
${AMAYADIR}/dicopar/*.ptn \
${AMAYADIR}/dicopar/alphabet \
${AMAYADIR}/dicopar/clavier \
${AMAYADIR}/doc/WX/*.html* \
${AMAYADIR}/doc/WX/*.css \
${AMAYADIR}/doc/WX/HTML-elements/*.html* \
${AMAYADIR}/doc/images/*.gif \
${AMAYADIR}/doc/images/*.png \
${AMAYADIR}/doc/images/*.jpg \
${AMAYADIR}/doc/images/w3c_home \
${AMAYADIR}/fonts/Families.list \
${AMAYADIR}/fonts/fonts.dir \
${AMAYADIR}/fonts/icones* \
${AMAYADIR}/fonts/*.ttf \
${AMAYADIR}/fonts/*.TTF \
${AMAYADIR}/thotlib/Makefile.in \
${AMAYADIR}/thotlib/include/Makefile.in \
${AMAYADIR}/thotlib/base/*.c \
${AMAYADIR}/thotlib/base/*.cpp \
${AMAYADIR}/thotlib/content/*.c \
${AMAYADIR}/thotlib/dialogue/*.c \
${AMAYADIR}/thotlib/dialogue/*.cpp \
${AMAYADIR}/thotlib/document/*.c \
${AMAYADIR}/thotlib/editing/*.c \
${AMAYADIR}/thotlib/image/*.c \
${AMAYADIR}/thotlib/include/*.h \
${AMAYADIR}/thotlib/internals/f/*.h \
${AMAYADIR}/thotlib/internals/h/*.h \
${AMAYADIR}/thotlib/internals/h/*.xpm \
${AMAYADIR}/thotlib/internals/h/*.xbm \
${AMAYADIR}/thotlib/internals/var/*.h \
${AMAYADIR}/thotlib/presentation/*.c \
${AMAYADIR}/thotlib/tree/*.c \
${AMAYADIR}/thotlib/unicode/*.c \
${AMAYADIR}/thotlib/view/*.c \
${AMAYADIR}/tools/Makefile.in \
${AMAYADIR}/tools/mkdep/Makefile.in \
${AMAYADIR}/tools/mkdep/Makefile \
${AMAYADIR}/tools/mkdep/mkdep.c \
${AMAYADIR}/tools/cextract-1.7/Makefile.in \
${AMAYADIR}/tools/cextract-1.7/HPUX.Install \
${AMAYADIR}/tools/cextract-1.7/INSTALL \
${AMAYADIR}/tools/cextract-1.7/INSTALL.VMS \
${AMAYADIR}/tools/cextract-1.7/Imakefile \
${AMAYADIR}/tools/cextract-1.7/MANIFEST \
${AMAYADIR}/tools/cextract-1.7/Makefile \
${AMAYADIR}/tools/cextract-1.7/Makefile.clm \
${AMAYADIR}/tools/cextract-1.7/Makefile.cln \
${AMAYADIR}/tools/cextract-1.7/README \
${AMAYADIR}/tools/cextract-1.7/README.LUCS \
${AMAYADIR}/tools/cextract-1.7/TODO \
${AMAYADIR}/tools/cextract-1.7/build.com \
${AMAYADIR}/tools/cextract-1.7/cextdoc.1 \
${AMAYADIR}/tools/cextract-1.7/cextract.doc \
${AMAYADIR}/tools/cextract-1.7/cextract.hlp \
${AMAYADIR}/tools/cextract-1.7/cextract.man \
${AMAYADIR}/tools/cextract-1.7/cextrc.5 \
${AMAYADIR}/tools/cextract-1.7/cextrc.doc \
${AMAYADIR}/tools/cextract-1.7/io.c \
${AMAYADIR}/tools/cextract-1.7/main.c \
${AMAYADIR}/tools/cextract-1.7/main.c.cln \
${AMAYADIR}/tools/cextract-1.7/newbuild.com \
${AMAYADIR}/tools/cextract-1.7/parse.c \
${AMAYADIR}/tools/cextract-1.7/patchlevel.h \
${AMAYADIR}/tools/cextract-1.7/proto.h \
${AMAYADIR}/tools/cextract-1.7/xtract.h 

mkdir $TMP
cd $TMP
tar xzf $DEST/amaya-tmp-$AMAYAVERSION.tgz
tar xzf $DEST/libs-tmp-$AMAYAVERSION.tgz

echo "Generating amaya-src tar file from $AMAYADIR"
AMAYADIR=Amaya
$TAR $DEST/amaya-src-$AMAYAVERSION.tgz \
${AMAYADIR} 

echo "Generating only the externals librairies source tar file"
$TAR $DEST/amaya-lib-src-$AMAYAVERSION.tgz \
${LIBWWWDIR} \
${REDLANDDIR} \
${WXWIDGETS} \
${MESA} \
${FREETYPE}

echo "Generating fullsrc tar file"
$TAR $DEST/amaya-fullsrc-$AMAYAVERSION.tgz \
${AMAYADIR} \
${LIBWWWDIR} \
${REDLANDDIR} \
${WXWIDGETS} \
${MESA} \
${FREETYPE} 

echo "Generating sources tar file"
cd ..
AMAYADIR=Amaya$AMAYAVERSION
$TAR $DEST/amaya-sources-$AMAYAVERSION.tgz \
${AMAYADIR} 

cd $TARDIR
\rm -r $TMP
\rm $DEST/amaya-tmp-$AMAYAVERSION.tgz
\rm $DEST/libs-tmp-$AMAYAVERSION.tgz
