#!/bin/sh
AMAYAVERSION=1.1
THOTVERSION=2.1c

CC=gcc
CFLAGS=-O2
THOTTAPE=/tahiti/thottape
THOTDIR=/tahiti/diffusion/opera
TESTDIR=$HOME/tmp

if [ -f $TESTDIR/Thot ]
then
    echo Removing Old $TESTDIR/Thot
    echo mv $TESTDIR/Thot $TESTDIR/Thot.old
    echo rm -rf $TESTDIR/Thot.old
fi

echo
echo Creating the Test directory
echo
mkdir -p $TESTDIR
cd $TESTDIR
echo
echo Extracting Thot library sources $THOTVERSION
tar xvzf $THOTTAPE/thot-src-$THOTVERSION.tar.gz
echo
cd Thot
echo
#echo Extracting Thot Editor sources $THOTVERSION
#tar xvzf $THOTTAPE/thoteditor-src-$THOTVERSION.tar.gz
echo
echo Extracting Amaya sources $AMAYAVERSION
tar xvzf $THOTTAPE/amaya-src-$AMAYAVERSION.tar.gz
echo
echo Going to $TESTDIR specific directory
cd $TESTDIR
mkdir archi
cd archi
echo
echo Setting up Conguration
../configure --disable-java
echo
echo Starting compile with THOTDIR=$TESTDIR/Thot CC=$CC CFLAGS=$CFLAGS
echo
make
make amaya
