/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern PUBLIC void HTConverterInit ( HTList * c );
extern PUBLIC void HTPresenterInit ( HTList * c );
extern PUBLIC void HTFormatInit ( HTList * c );
extern PUBLIC void HTTransferEncoderInit ( HTList * c );
extern PUBLIC void HTContentEncoderInit ( HTList * c );
extern PUBLIC void HTBeforeInit ( void );
extern PUBLIC void HTAfterInit ( void );
extern PUBLIC void HTAAInit ( void );
extern PUBLIC void HTNetInit ( void );
extern PUBLIC void HTAlertInit ( void );
extern PUBLIC void HTTransportInit ( void );
extern PUBLIC void HTProtocolInit ( void );
extern PUBLIC void HTProtocolPreemptiveInit ( void );
extern PUBLIC void HTIconInit ( const char * url_prefix );
extern PUBLIC void HTMIMEInit ( void );

#else /* __STDC__ */

extern PUBLIC void HTConverterInit ( HTList * c );
extern PUBLIC void HTPresenterInit ( HTList * c );
extern PUBLIC void HTFormatInit ( HTList * c );
extern PUBLIC void HTTransferEncoderInit ( HTList * c );
extern PUBLIC void HTContentEncoderInit ( HTList * c );
extern PUBLIC void HTBeforeInit ( void );
extern PUBLIC void HTAfterInit ( void );
extern PUBLIC void HTAAInit ( void );
extern PUBLIC void HTNetInit ( void );
extern PUBLIC void HTAlertInit ( void );
extern PUBLIC void HTTransportInit ( void );
extern PUBLIC void HTProtocolInit ( void );
extern PUBLIC void HTProtocolPreemptiveInit ( void );
extern PUBLIC void HTIconInit ( const char * url_prefix );
extern PUBLIC void HTMIMEInit ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
