/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void ConvertToLowerCase ( STRING string );
extern void EscapeChar ( STRING string,
                         UCHAR_T c );
extern STRING EscapeURL ( const STRING url );
extern void ExplodeURL ( char *url,
                         char **proto,
                         char **host,
                         char **dir,
                         char **file );
extern void ExtractSuffix ( STRING aName,
                            STRING aSuffix );
extern ThotBool IsHTMLName ( const STRING path );
extern ThotBool IsXMLName ( const STRING path );
extern ThotBool IsCSSName ( const STRING path );
extern ThotBool IsImageName ( const STRING path );
extern ThotBool IsImageType ( const STRING type );
extern ThotBool IsTextName ( const STRING path );
extern ThotBool IsHTTPPath ( const STRING path );
extern ThotBool IsWithParameters ( const char *url );
extern ThotBool IsW3Path ( const STRING path );
extern ThotBool IsValidProtocol ( const STRING url );
extern STRING GetBaseURL ( Document doc );
extern STRING GetLocalPath ( Document doc,
                             STRING url );
extern void ExtractTarget ( STRING aName,
                            STRING target );
extern void ConvertFileURL ( STRING url );
extern void NormalizeURL ( STRING orgName,
                           Document doc,
                           STRING newName,
                           STRING docName,
                           STRING otherPath );
extern ThotBool IsSameHost ( const STRING url1,
                             const STRING url2 );
extern ThotBool HasKnownFileSuffix ( const STRING path );
extern void ChopURL ( char *outputURL,
                      const char *inputURL );
extern STRING AmayaParseUrl ( const STRING aName,
                              STRING relatedName,
                              int wanted );
extern void SimplifyUrl ( STRING* url );
extern ThotBool NormalizeFile ( STRING src,
                                STRING target );
extern STRING MakeRelativeURL ( STRING aName,
                                STRING relatedName );

#else /* __STDC__ */

extern void ConvertToLowerCase (/* STRING string */);
extern void EscapeChar (/* STRING string,
                           UCHAR_T c */);
extern STRING EscapeURL (/* const STRING url */);
extern void ExplodeURL (/* char *url,
                           char **proto,
                           char **host,
                           char **dir,
                           char **file */);
extern void ExtractSuffix (/* STRING aName,
                              STRING aSuffix */);
extern ThotBool IsHTMLName (/* const STRING path */);
extern ThotBool IsXMLName (/* const STRING path */);
extern ThotBool IsCSSName (/* const STRING path */);
extern ThotBool IsImageName (/* const STRING path */);
extern ThotBool IsImageType (/* const STRING type */);
extern ThotBool IsTextName (/* const STRING path */);
extern ThotBool IsHTTPPath (/* const STRING path */);
extern ThotBool IsWithParameters (/* const char *url */);
extern ThotBool IsW3Path (/* const STRING path */);
extern ThotBool IsValidProtocol (/* const STRING url */);
extern STRING GetBaseURL (/* Document doc */);
extern STRING GetLocalPath (/* Document doc,
                               STRING url */);
extern void ExtractTarget (/* STRING aName,
                              STRING target */);
extern void ConvertFileURL (/* STRING url */);
extern void NormalizeURL (/* STRING orgName,
                             Document doc,
                             STRING newName,
                             STRING docName,
                             STRING otherPath */);
extern ThotBool IsSameHost (/* const STRING url1,
                               const STRING url2 */);
extern ThotBool HasKnownFileSuffix (/* const STRING path */);
extern void ChopURL (/* char *outputURL,
                        const char *inputURL */);
extern STRING AmayaParseUrl (/* const STRING aName,
                                STRING relatedName,
                                int wanted */);
extern void SimplifyUrl (/* STRING* url */);
extern ThotBool NormalizeFile (/* STRING src,
                                  STRING target */);
extern STRING MakeRelativeURL (/* STRING aName,
                                  STRING relatedName */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
