/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern char *get_char_attribute_from_el ( Element el,
                                          int Attribut_Type );
extern void register_animated_element ( Element animated,
                                        Document doc );

#else /* __STDC__ */

extern char *get_char_attribute_from_el ( Element el,
                                            int Attribut_Type );
extern void register_animated_element ( Element animated,
                                          Document doc );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
