/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void SwitchIconAnimPlay ( Document doc,
                                 View view,
                                 ThotBool state );
extern void AddAnimPlayButton ( Document doc,
                                View view );
extern int get_int_attribute_from_el ( Element el,
                                       int Attribut_Type );
extern int *get_intptr_attribute_from_el ( Element el,
                                           int Attribut_Type );
extern char *get_char_attribute_from_el ( Element el,
                                          int Attribut_Type );
extern void register_animated_element ( Element animated );

#else /* __STDC__ */

extern void SwitchIconAnimPlay (/* Document doc,
                                   View view,
                                   ThotBool state */);
extern void AddAnimPlayButton (/* Document doc,
                                  View view */);
extern int get_int_attribute_from_el (/* Element el,
                                         int Attribut_Type */);
extern int *get_intptr_attribute_from_el (/* Element el,
                                             int Attribut_Type */);
extern char *get_char_attribute_from_el (/* Element el,
                                            int Attribut_Type */);
extern void register_animated_element (/* Element animated */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
