/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void PrintCSS ( CSSInfoPtr css,
                       FILE * output );
extern int DumpCSSToFile ( Document doc,
                           CSSInfoPtr css,
                           char *filename );
extern void PrintListCSS ( FILE * output );
extern void AddCSS ( CSSInfoPtr css );
extern void FreeCSS ( CSSInfoPtr css );
extern void InitDocumentCSS ( Document doc );
extern void CleanDocumentCSS ( Document doc );
extern void CleanListCSS ( void );
extern CSSInfoPtr NewCSS ( void );
extern int CmpCSS ( CSSInfoPtr css,
                    CSSInfoPtr cour );
extern CSSInfoPtr SearchCSS ( Document doc,
                              CSSCategory category,
                              char *url );
extern void ClearCSS ( CSSInfoPtr css );
extern void RebuildCSS ( CSSInfoPtr css );
extern CSSInfoPtr GetDocumentStyle ( Document doc );
extern PSchema GetDocumentGenericPresentation ( Document doc );
extern CSSInfoPtr GetUserGenericPresentation ( void );
extern void RebuildHTMLStyleHeader ( Document doc );
extern void ParseHTMLStyleHeader ( Element elem,
                                   char *attrstr,
                                   Document doc,
                                   boolean rebuild );
extern void LoadHTMLStyleSheet ( char *URL,
                                 Document doc );
extern void LoadHTMLExternalStyleSheet ( char *URL,
                                         Document doc,
                                         int merge );
extern void LoadUserStyleSheet ( Document doc );
extern void CSSSetBackground ( Document doc,
                               PSchema gpres,
                               int color );
extern void CSSSetMagnification ( Document doc,
                                  PSchema gpres,
                                  int zoom );
extern void ApplyFinalStyle ( Document doc );
extern void MergeNewCSS ( char *attrstr,
                          Document doc,
                          PSchema gPres );
extern void RemoveCSS ( char *name,
                        Document doc );
extern PRuleInfoPtr SearchRPISel ( char *selector,
                                   PRuleInfoPtr list );
extern void SelectRPIEntry ( char which,
                             int index,
                             char *value );
extern int BuildCSSList ( Document doc,
                          char *buf,
                          int size,
                          char *first );
extern char *GetlistEntry ( char *list,
                            int entry );
extern void RedrawLCSS ( char *name );
extern void RedrawLRPI ( char *name );
extern void RedrawRCSS ( char *name );
extern void RedrawRRPI ( char *name );
extern void CSSHandleMerge ( char which,
                             boolean copy );
extern void RebuildAllCSS ( void );
extern int SaveCSSThroughNet ( Document doc,
                               View view,
                               CSSInfoPtr css );
extern void InitCSS ( void );
extern void CloseCSS ( void );

#else /* __STDC__ */

extern void PrintCSS (/* CSSInfoPtr css,
                         FILE * output */);
extern int DumpCSSToFile (/* Document doc,
                             CSSInfoPtr css,
                             char *filename */);
extern void PrintListCSS (/* FILE * output */);
extern void AddCSS (/* CSSInfoPtr css */);
extern void FreeCSS (/* CSSInfoPtr css */);
extern void InitDocumentCSS (/* Document doc */);
extern void CleanDocumentCSS (/* Document doc */);
extern void CleanListCSS (/* void */);
extern CSSInfoPtr NewCSS (/* void */);
extern int CmpCSS (/* CSSInfoPtr css,
                      CSSInfoPtr cour */);
extern CSSInfoPtr SearchCSS (/* Document doc,
                                CSSCategory category,
                                char *url */);
extern void ClearCSS (/* CSSInfoPtr css */);
extern void RebuildCSS (/* CSSInfoPtr css */);
extern CSSInfoPtr GetDocumentStyle (/* Document doc */);
extern PSchema GetDocumentGenericPresentation (/* Document doc */);
extern CSSInfoPtr GetUserGenericPresentation (/* void */);
extern void RebuildHTMLStyleHeader (/* Document doc */);
extern void ParseHTMLStyleHeader (/* Element elem,
                                     char *attrstr,
                                     Document doc,
                                     boolean rebuild */);
extern void LoadHTMLStyleSheet (/* char *URL,
                                   Document doc */);
extern void LoadHTMLExternalStyleSheet (/* char *URL,
                                           Document doc,
                                           int merge */);
extern void LoadUserStyleSheet (/* Document doc */);
extern void CSSSetBackground (/* Document doc,
                                 PSchema gpres,
                                 int color */);
extern void CSSSetMagnification (/* Document doc,
                                    PSchema gpres,
                                    int zoom */);
extern void ApplyFinalStyle (/* Document doc */);
extern void MergeNewCSS (/* char *attrstr,
                            Document doc,
                            PSchema gPres */);
extern void RemoveCSS (/* char *name,
                          Document doc */);
extern PRuleInfoPtr SearchRPISel (/* char *selector,
                                     PRuleInfoPtr list */);
extern void SelectRPIEntry (/* char which,
                               int index,
                               char *value */);
extern int BuildCSSList (/* Document doc,
                            char *buf,
                            int size,
                            char *first */);
extern char *GetlistEntry (/* char *list,
                              int entry */);
extern void RedrawLCSS (/* char *name */);
extern void RedrawLRPI (/* char *name */);
extern void RedrawRCSS (/* char *name */);
extern void RedrawRRPI (/* char *name */);
extern void CSSHandleMerge (/* char which,
                               boolean copy */);
extern void RebuildAllCSS (/* void */);
extern int SaveCSSThroughNet (/* Document doc,
                                 View view,
                                 CSSInfoPtr css */);
extern void InitCSS (/* void */);
extern void CloseCSS (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
