/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void RemoveElementStyle ( Element el,
                                 Document doc,
                                 boolean removeSpan );
extern boolean UpdateStyleDelete ( NotifyAttribute * event );
extern boolean ChangeStyle ( NotifyElement * event );
extern boolean DeleteStyle ( NotifyElement * event );
extern void StyleChanged ( NotifyAttribute * event );
extern void UpdateStylePost ( NotifyAttribute * event );
extern void CreateClass ( Document doc,
                          View view );
extern void ApplyClass ( Document doc,
                         View view );
extern void StyleCallbackDialogue ( int ref,
                                    int typedata,
                                    STRING data );

#else /* __STDC__ */

extern void RemoveElementStyle (/* Element el,
                                   Document doc,
                                   boolean removeSpan */);
extern boolean UpdateStyleDelete (/* NotifyAttribute * event */);
extern boolean ChangeStyle (/* NotifyElement * event */);
extern boolean DeleteStyle (/* NotifyElement * event */);
extern void StyleChanged (/* NotifyAttribute * event */);
extern void UpdateStylePost (/* NotifyAttribute * event */);
extern void CreateClass (/* Document doc,
                            View view */);
extern void ApplyClass (/* Document doc,
                           View view */);
extern void StyleCallbackDialogue (/* int ref,
                                      int typedata,
                                      STRING data */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
