/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int MapGI ( char* gi,
                   SSchema *schema,
                   Document doc );
extern void GIType ( char* gi,
                     ElementType *elType,
                     Document doc );
extern AttributeMapping *MapAttr ( char* Attr,
                                   SSchema *schema,
                                   int elemEntry,
                                   Document doc );
extern void MapHTMLAttribute ( char* Attr,
                               AttributeType *attrType,
                               char* elementName,
                               Document doc );

#else /* __STDC__ */

extern int MapGI (/* char* gi,
                     SSchema *schema,
                     Document doc */);
extern void GIType (/* char* gi,
                       ElementType *elType,
                       Document doc */);
extern AttributeMapping *MapAttr (/* char* Attr,
                                     SSchema *schema,
                                     int elemEntry,
                                     Document doc */);
extern void MapHTMLAttribute (/* char* Attr,
                                 AttributeType *attrType,
                                 char* elementName,
                                 Document doc */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
