/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern boolean AddLoadedImage ( char *name,
                                char *pathname,
                                Document doc,
                                LoadedImageDesc ** desc );
extern LoadedImageDesc *SearchLoadedImage ( char *localpath,
                                            Document doc );
extern void DisplayImage ( Document doc,
                           Element el,
                           char *imageName );
extern void HandleImageLoaded ( int doc,
                                int status,
                                char *urlName,
                                char *outputfile,
                                void * context );
extern void libWWWImageLoaded ( void *ctxt,
                                int status );
extern void FetchImage ( Document doc,
                         Element el,
                         char *URL,
                         int flags,
                         LoadedImageCallback callback,
                         void *extra );
extern void FetchAndDisplayImages ( Document doc,
                                    int flags );

#else /* __STDC__ */

extern boolean AddLoadedImage (/* char *name,
                                  char *pathname,
                                  Document doc,
                                  LoadedImageDesc ** desc */);
extern LoadedImageDesc *SearchLoadedImage (/* char *localpath,
                                              Document doc */);
extern void DisplayImage (/* Document doc,
                             Element el,
                             char *imageName */);
extern void HandleImageLoaded (/* int doc,
                                  int status,
                                  char *urlName,
                                  char *outputfile,
                                  void * context */);
extern void libWWWImageLoaded (/* void *ctxt,
                                  int status */);
extern void FetchImage (/* Document doc,
                           Element el,
                           char *URL,
                           int flags,
                           LoadedImageCallback callback,
                           void *extra */);
extern void FetchAndDisplayImages (/* Document doc,
                                      int flags */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
