/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void InsertBefore ( Document doc,
                           View view );
extern void InsertAfter ( Document doc,
                          View view );
extern Element GetNoTemplateSibling ( Element el,
                                      ThotBool before );
extern Element GetNoTemplateChild ( Element el,
                                    ThotBool first );
extern Element GetNoTemplateParent ( Element el );
extern Element GetNextNode ( Element curr );
extern void SetTargetContent ( Document doc,
                               Attribute attrNAME );
extern void LinkToPreviousTarget ( Document doc,
                                   View view );
extern void AddAccessKey ( NotifyAttribute *event );
extern ThotBool RemoveAccessKey ( NotifyAttribute *event );
extern void RemoveLink ( Element el,
                         Document doc );
extern ThotBool DeleteLink ( NotifyElement *event );
extern ThotBool CheckMandatory ( NotifyAttribute *event );
extern void AttributeChange ( int aType,
                              char * data );
extern ThotBool GenerateInlineElement ( int eType,
                                        SSchema eSchema,
                                        int aType,
                                        const char * data,
                                        ThotBool replace );
extern void SetREFattribute ( Element element,
                              Document doc,
                              char *targetURL,
                              char *targetName );
extern void ChangeTitle ( Document doc,
                          View view );
extern void SetNewTitle ( Document doc );
extern void TitleModified ( NotifyOnTarget *event );
extern void SelectDestination ( Document doc,
                                Element el,
                                ThotBool withUndo,
                                ThotBool clickFirst );
extern Attribute GetNameAttr ( Document doc,
                               Element selectedElement );
extern void CreateTargetAnchor ( Document doc,
                                 Element el,
                                 ThotBool forceID,
                                 ThotBool generic,
                                 ThotBool withUndo );
extern void CreateAnchor ( Document doc,
                           View view,
                           ThotBool createLink );
extern ThotBool MakeUniqueName ( Element el,
                                 Document doc,
                                 ThotBool doIt,
                                 ThotBool withUndo );
extern void CreateRemoveIDAttribute ( char *elName,
                                      Document doc,
                                      ThotBool createID,
                                      ThotBool inSelection );
extern void CheckPseudoParagraph ( Element el,
                                   Document doc );
extern void ElementCreated ( NotifyElement *event );
extern void TextPasted ( NotifyElement *event );
extern ThotBool ElementWillBeDeleted ( NotifyElement *event );
extern void ElementDeleted ( NotifyElement *event );
extern void RegisterURLSavedElements ( Document doc );
extern void ChangeURI ( Element el,
                        Attribute attr,
                        Document originDocument,
                        Document doc );
extern ThotBool ElementOKforProfile ( Element el,
                                      Document doc );
extern void RemoveTextAttributes ( Element el,
                                   Document doc );
extern void CheckPastedElement ( Element el,
                                 Document doc,
                                 int info,
                                 int position,
                                 ThotBool by_ref );
extern void ElementPasted ( NotifyElement * event );
extern void CheckMaxLength ( Element elText,
                             Document doc );
extern void CheckNewLines ( NotifyOnTarget *event );
extern void CreateTarget ( Document doc,
                           View view );
extern void UpdateAttrNAME ( NotifyAttribute * event );
extern void UpdateAttrID ( NotifyAttribute * event );
extern void CoordsModified ( NotifyAttribute * event );
extern void GraphicsModified ( NotifyAttribute * event );
extern ThotBool StoreWidth ( NotifyAttribute *event );
extern ThotBool StoreHeight ( NotifyAttribute * event );
extern ThotBool AttrHeightDelete ( NotifyAttribute *event );
extern void AttrHeightModified ( NotifyAttribute *event );
extern ThotBool AttrWidthDelete ( NotifyAttribute *event );
extern void AttrWidthModified ( NotifyAttribute *event );
extern ThotBool AttrAreaSizeDelete ( NotifyAttribute *event );
extern void AttrAreaSizeModified ( NotifyAttribute *event );
extern void AttrFontSizeCreated ( NotifyAttribute *event );
extern ThotBool AttrFontSizeDelete ( NotifyAttribute * event );
extern void AttrColorCreated ( NotifyAttribute * event );
extern ThotBool AttrColorDelete ( NotifyAttribute *event );
extern ThotBool GlobalAttrInMenu ( NotifyAttribute * event );
extern ThotBool AttrRELREVinMenu ( NotifyAttribute * event );
extern ThotBool AttrNAMEinMenu ( NotifyAttribute * event );
extern ThotBool AttrScriptLanguageinMenu ( NotifyAttribute * event );
extern void SetOnOffEmphasis ( Document document,
                               View view );
extern void SetOnOffStrong ( Document document,
                             View view );
extern void SetOnOffCite ( Document document,
                           View view );
extern void SetOnOffDefinition ( Document document,
                                 View view );
extern void SetOnOffCode ( Document document,
                           View view );
extern void SetOnOffVariable ( Document document,
                               View view );
extern void SetOnOffSample ( Document document,
                             View view );
extern void SetOnOffKeyboard ( Document document,
                               View view );
extern void SetOnOffAbbr ( Document document,
                           View view );
extern void SetOnOffAcronym ( Document document,
                              View view );
extern void SetOnOffINS ( Document document,
                          View view );
extern void SetOnOffDEL ( Document document,
                          View view );
extern void SetOnOffItalic ( Document document,
                             View view );
extern void SetOnOffBold ( Document document,
                           View view );
extern void SetOnOffTeletype ( Document document,
                               View view );
extern void SetOnOffBig ( Document document,
                          View view );
extern void SetOnOffSmall ( Document document,
                            View view );
extern void SetOnOffSub ( Document document,
                          View view );
extern void SetOnOffSup ( Document document,
                          View view );
extern void SetOnOffQuotation ( Document document,
                                View view );
extern void SetOnOffBDO ( Document document,
                          View view );
extern void CreateSpan ( Document document,
                         View view );
extern Element SearchAnchor ( Document doc,
                              Element element,
                              Attribute *HrefAttr,
                              ThotBool name );

#else /* __STDC__ */

extern void InsertBefore ( Document doc,
                             View view );
extern void InsertAfter ( Document doc,
                            View view );
extern Element GetNoTemplateSibling ( Element el,
                                        ThotBool before );
extern Element GetNoTemplateChild ( Element el,
                                      ThotBool first );
extern Element GetNoTemplateParent ( Element el );
extern Element GetNextNode ( Element curr );
extern void SetTargetContent ( Document doc,
                                 Attribute attrNAME );
extern void LinkToPreviousTarget ( Document doc,
                                     View view );
extern void AddAccessKey ( NotifyAttribute *event );
extern ThotBool RemoveAccessKey ( NotifyAttribute *event );
extern void RemoveLink ( Element el,
                           Document doc );
extern ThotBool DeleteLink ( NotifyElement *event );
extern ThotBool CheckMandatory ( NotifyAttribute *event );
extern void AttributeChange ( int aType,
                                char * data );
extern ThotBool GenerateInlineElement ( int eType,
                                          SSchema eSchema,
                                          int aType,
                                          const char * data,
                                          ThotBool replace );
extern void SetREFattribute ( Element element,
                                Document doc,
                                char *targetURL,
                                char *targetName );
extern void ChangeTitle ( Document doc,
                            View view );
extern void SetNewTitle ( Document doc );
extern void TitleModified ( NotifyOnTarget *event );
extern void SelectDestination ( Document doc,
                                  Element el,
                                  ThotBool withUndo,
                                  ThotBool clickFirst );
extern Attribute GetNameAttr ( Document doc,
                                 Element selectedElement );
extern void CreateTargetAnchor ( Document doc,
                                   Element el,
                                   ThotBool forceID,
                                   ThotBool generic,
                                   ThotBool withUndo );
extern void CreateAnchor ( Document doc,
                             View view,
                             ThotBool createLink );
extern ThotBool MakeUniqueName ( Element el,
                                   Document doc,
                                   ThotBool doIt,
                                   ThotBool withUndo );
extern void CreateRemoveIDAttribute ( char *elName,
                                        Document doc,
                                        ThotBool createID,
                                        ThotBool inSelection );
extern void CheckPseudoParagraph ( Element el,
                                     Document doc );
extern void ElementCreated ( NotifyElement *event );
extern void TextPasted ( NotifyElement *event );
extern ThotBool ElementWillBeDeleted ( NotifyElement *event );
extern void ElementDeleted ( NotifyElement *event );
extern void RegisterURLSavedElements ( Document doc );
extern void ChangeURI ( Element el,
                          Attribute attr,
                          Document originDocument,
                          Document doc );
extern ThotBool ElementOKforProfile ( Element el,
                                        Document doc );
extern void RemoveTextAttributes ( Element el,
                                     Document doc );
extern void CheckPastedElement ( Element el,
                                   Document doc,
                                   int info,
                                   int position,
                                   ThotBool by_ref );
extern void ElementPasted ( NotifyElement * event );
extern void CheckMaxLength ( Element elText,
                               Document doc );
extern void CheckNewLines ( NotifyOnTarget *event );
extern void CreateTarget ( Document doc,
                             View view );
extern void UpdateAttrNAME ( NotifyAttribute * event );
extern void UpdateAttrID ( NotifyAttribute * event );
extern void CoordsModified ( NotifyAttribute * event );
extern void GraphicsModified ( NotifyAttribute * event );
extern ThotBool StoreWidth ( NotifyAttribute *event );
extern ThotBool StoreHeight ( NotifyAttribute * event );
extern ThotBool AttrHeightDelete ( NotifyAttribute *event );
extern void AttrHeightModified ( NotifyAttribute *event );
extern ThotBool AttrWidthDelete ( NotifyAttribute *event );
extern void AttrWidthModified ( NotifyAttribute *event );
extern ThotBool AttrAreaSizeDelete ( NotifyAttribute *event );
extern void AttrAreaSizeModified ( NotifyAttribute *event );
extern void AttrFontSizeCreated ( NotifyAttribute *event );
extern ThotBool AttrFontSizeDelete ( NotifyAttribute * event );
extern void AttrColorCreated ( NotifyAttribute * event );
extern ThotBool AttrColorDelete ( NotifyAttribute *event );
extern ThotBool GlobalAttrInMenu ( NotifyAttribute * event );
extern ThotBool AttrRELREVinMenu ( NotifyAttribute * event );
extern ThotBool AttrNAMEinMenu ( NotifyAttribute * event );
extern ThotBool AttrScriptLanguageinMenu ( NotifyAttribute * event );
extern void SetOnOffEmphasis ( Document document,
                                 View view );
extern void SetOnOffStrong ( Document document,
                               View view );
extern void SetOnOffCite ( Document document,
                             View view );
extern void SetOnOffDefinition ( Document document,
                                   View view );
extern void SetOnOffCode ( Document document,
                             View view );
extern void SetOnOffVariable ( Document document,
                                 View view );
extern void SetOnOffSample ( Document document,
                               View view );
extern void SetOnOffKeyboard ( Document document,
                                 View view );
extern void SetOnOffAbbr ( Document document,
                             View view );
extern void SetOnOffAcronym ( Document document,
                                View view );
extern void SetOnOffINS ( Document document,
                            View view );
extern void SetOnOffDEL ( Document document,
                            View view );
extern void SetOnOffItalic ( Document document,
                               View view );
extern void SetOnOffBold ( Document document,
                             View view );
extern void SetOnOffTeletype ( Document document,
                                 View view );
extern void SetOnOffBig ( Document document,
                            View view );
extern void SetOnOffSmall ( Document document,
                              View view );
extern void SetOnOffSub ( Document document,
                            View view );
extern void SetOnOffSup ( Document document,
                            View view );
extern void SetOnOffQuotation ( Document document,
                                  View view );
extern void SetOnOffBDO ( Document document,
                            View view );
extern void CreateSpan ( Document document,
                           View view );
extern Element SearchAnchor ( Document doc,
                                Element element,
                                Attribute *HrefAttr,
                                ThotBool name );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
