/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void SetTargetContent ( Document doc,
                               Attribute attrNAME );
extern void LinkToPreviousTarget ( Document doc,
                                   View view );
extern void RemoveLink ( Element el,
                         Document doc );
extern ThotBool DeleteLink ( NotifyElement * event );
extern void SetREFattribute ( Element element,
                              Document doc,
                              STRING targetURL,
                              STRING targetName );
extern void SelectDestination ( Document doc,
                                Element el,
                                ThotBool withUndo );
extern Attribute GetNameAttr ( Document doc,
                               Element selectedElement );
extern void CreateTargetAnchor ( Document doc,
                                 Element el,
                                 ThotBool withUndo );
extern void CreateAnchor ( Document doc,
                           View view,
                           ThotBool createLink );
extern void MakeUniqueName ( Element el,
                             Document doc );
extern void ElementCreated ( NotifyElement * event );
extern void ElementDeleted ( NotifyElement *event );
extern void ElementPasted ( NotifyElement * event );
extern void CreateTarget ( Document doc,
                           View view );
extern void UpdateAttrID ( NotifyAttribute * event );
extern void CoordsModified ( NotifyAttribute * event );
extern void GraphicsModified ( NotifyAttribute * event );
extern ThotBool StoreWidth ( NotifyAttribute * event );
extern ThotBool StoreHeight ( NotifyAttribute * event );
extern ThotBool AttrWidthDelete ( NotifyAttribute * event );
extern void AttrWidthModified ( NotifyAttribute * event );
extern void AttrFontSizeCreated ( NotifyAttribute * event );
extern ThotBool AttrFontSizeDelete ( NotifyAttribute * event );
extern void AttrColorCreated ( NotifyAttribute * event );
extern ThotBool AttrColorDelete ( NotifyAttribute * event );
extern void ListItemCreated ( NotifyElement * event );
extern void ListChangedType ( NotifyElement * event );
extern void UpdateAttrIntItemStyle ( NotifyAttribute * event );
extern void AttrItemStyle ( NotifyAttribute * event );
extern ThotBool GlobalAttrInMenu ( NotifyAttribute * event );
extern ThotBool AttrNAMEinMenu ( NotifyAttribute * event );
extern void SetOnOffEmphasis ( Document document,
                               View view );
extern void SetOnOffStrong ( Document document,
                             View view );
extern void SetOnOffCite ( Document document,
                           View view );
extern void SetOnOffDefinition ( Document document,
                                 View view );
extern void SetOnOffCode ( Document document,
                           View view );
extern void SetOnOffVariable ( Document document,
                               View view );
extern void SetOnOffSample ( Document document,
                             View view );
extern void SetOnOffKeyboard ( Document document,
                               View view );
extern void SetOnOffAbbr ( Document document,
                           View view );
extern void SetOnOffAcronym ( Document document,
                              View view );
extern void SetOnOffINS ( Document document,
                          View view );
extern void SetOnOffDEL ( Document document,
                          View view );
extern void SetOnOffItalic ( Document document,
                             View view );
extern void SetOnOffBold ( Document document,
                           View view );
extern void SetOnOffTeletype ( Document document,
                               View view );
extern void SetOnOffBig ( Document document,
                          View view );
extern void SetOnOffSmall ( Document document,
                            View view );
extern void SetOnOffSub ( Document document,
                          View view );
extern void SetOnOffSup ( Document document,
                          View view );
extern void SetOnOffQuotation ( Document document,
                                View view );
extern void SetOnOffBDO ( Document document,
                          View view );
extern Element SearchAnchor ( Document doc,
                              Element element,
                              ThotBool link );
extern void UpdateAtom ( Document doc,
                         STRING url,
                         STRING title );
extern void TitleModified ( NotifyOnTarget * event );

#else /* __STDC__ */

extern void SetTargetContent (/* Document doc,
                                 Attribute attrNAME */);
extern void LinkToPreviousTarget (/* Document doc,
                                     View view */);
extern void RemoveLink (/* Element el,
                           Document doc */);
extern ThotBool DeleteLink (/* NotifyElement * event */);
extern void SetREFattribute (/* Element element,
                                Document doc,
                                STRING targetURL,
                                STRING targetName */);
extern void SelectDestination (/* Document doc,
                                  Element el,
                                  ThotBool withUndo */);
extern Attribute GetNameAttr (/* Document doc,
                                 Element selectedElement */);
extern void CreateTargetAnchor (/* Document doc,
                                   Element el,
                                   ThotBool withUndo */);
extern void CreateAnchor (/* Document doc,
                             View view,
                             ThotBool createLink */);
extern void MakeUniqueName (/* Element el,
                               Document doc */);
extern void ElementCreated (/* NotifyElement * event */);
extern void ElementDeleted (/* NotifyElement *event */);
extern void ElementPasted (/* NotifyElement * event */);
extern void CreateTarget (/* Document doc,
                             View view */);
extern void UpdateAttrID (/* NotifyAttribute * event */);
extern void CoordsModified (/* NotifyAttribute * event */);
extern void GraphicsModified (/* NotifyAttribute * event */);
extern ThotBool StoreWidth (/* NotifyAttribute * event */);
extern ThotBool StoreHeight (/* NotifyAttribute * event */);
extern ThotBool AttrWidthDelete (/* NotifyAttribute * event */);
extern void AttrWidthModified (/* NotifyAttribute * event */);
extern void AttrFontSizeCreated (/* NotifyAttribute * event */);
extern ThotBool AttrFontSizeDelete (/* NotifyAttribute * event */);
extern void AttrColorCreated (/* NotifyAttribute * event */);
extern ThotBool AttrColorDelete (/* NotifyAttribute * event */);
extern void ListItemCreated (/* NotifyElement * event */);
extern void ListChangedType (/* NotifyElement * event */);
extern void UpdateAttrIntItemStyle (/* NotifyAttribute * event */);
extern void AttrItemStyle (/* NotifyAttribute * event */);
extern ThotBool GlobalAttrInMenu (/* NotifyAttribute * event */);
extern ThotBool AttrNAMEinMenu (/* NotifyAttribute * event */);
extern void SetOnOffEmphasis (/* Document document,
                                 View view */);
extern void SetOnOffStrong (/* Document document,
                               View view */);
extern void SetOnOffCite (/* Document document,
                             View view */);
extern void SetOnOffDefinition (/* Document document,
                                   View view */);
extern void SetOnOffCode (/* Document document,
                             View view */);
extern void SetOnOffVariable (/* Document document,
                                 View view */);
extern void SetOnOffSample (/* Document document,
                               View view */);
extern void SetOnOffKeyboard (/* Document document,
                                 View view */);
extern void SetOnOffAbbr (/* Document document,
                             View view */);
extern void SetOnOffAcronym (/* Document document,
                                View view */);
extern void SetOnOffINS (/* Document document,
                            View view */);
extern void SetOnOffDEL (/* Document document,
                            View view */);
extern void SetOnOffItalic (/* Document document,
                               View view */);
extern void SetOnOffBold (/* Document document,
                             View view */);
extern void SetOnOffTeletype (/* Document document,
                                 View view */);
extern void SetOnOffBig (/* Document document,
                            View view */);
extern void SetOnOffSmall (/* Document document,
                              View view */);
extern void SetOnOffSub (/* Document document,
                            View view */);
extern void SetOnOffSup (/* Document document,
                            View view */);
extern void SetOnOffQuotation (/* Document document,
                                  View view */);
extern void SetOnOffBDO (/* Document document,
                            View view */);
extern Element SearchAnchor (/* Document doc,
                                Element element,
                                ThotBool link */);
extern void UpdateAtom (/* Document doc,
                           STRING url,
                           STRING title */);
extern void TitleModified (/* NotifyOnTarget * event */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
