/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotBool WithinLastPastedCell ( Element el );
extern Element GetSiblingRow ( Element row,
                               ThotBool before,
                               ThotBool inMath );
extern Element GetSiblingCell ( Element cell,
                                ThotBool before,
                                ThotBool inMath );
extern Element GetFirstCellOfRow ( Element row,
                                   ThotBool inMath );
extern int SetRowExt ( Element cell,
                       int span,
                       Document doc,
                       ThotBool inMath );
extern int SetColExt ( Element cell,
                       int span,
                       Document doc,
                       ThotBool inMath,
                       ThotBool deletingLastCol );
extern Element GetCellFromColumnHead ( Element row,
                                       Element colhead,
                                       ThotBool inMath );
extern Element NewColumnHead ( Element lastcolhead,
                               ThotBool before,
                               ThotBool last,
                               Element row,
                               Document doc,
                               ThotBool inMath,
                               ThotBool generateEmptyCells,
                               ThotBool generateCol );
extern Element NextTableRow ( Element row );
extern void TransmitWidthToColhead ( Element col,
                                     Document doc,
                                     char *value,
                                     int oldwidth );
extern void CheckAllRows ( Element table,
                           Document doc,
                           ThotBool placeholder,
                           ThotBool deleteLastEmptyColumns );
extern void CheckTable ( Element table,
                         Document doc );
extern void NewCell ( Element cell,
                      Document doc,
                      ThotBool generateColumn,
                      ThotBool generateEmptyCells,
                      ThotBool check );
extern void CellCreated ( NotifyElement * event );
extern void CellPasted ( NotifyElement * event );
extern ThotBool DeleteRow ( NotifyElement *event );
extern void RowDeleted ( NotifyElement *event );
extern void CheckDeleteParentTable ( Element el );
extern ThotBool DeleteTable ( NotifyElement * event );
extern void TableDeleted ( NotifyElement *event );
extern ThotBool DeleteTBody ( NotifyElement * event );
extern ThotBool ModifySpan ( NotifyAttribute * event );
extern void SpanModified ( NotifyAttribute * event );
extern void SpanCreated ( NotifyAttribute * event );
extern ThotBool DeleteSpan ( NotifyAttribute * event );
extern void ApplyCSSRuleOneCol ( Element col,
                                 PresentationContext ctxt,
                                 char *cssRule,
                                 CSSInfoPtr css );
extern void ColApplyCSSRule ( Element el,
                              PresentationContext ctxt,
                              char *cssRule,
                              CSSInfoPtr css );
extern void CellAlignCreated ( NotifyAttribute * event );
extern void CellAlignModified ( NotifyAttribute * event );
extern void CellAlignDeleted ( NotifyAttribute * event );
extern ThotBool DeleteColElement ( NotifyElement * event );
extern ThotBool CreateColElement ( NotifyElement * event );
extern ThotBool PasteColElement ( NotifyOnValue * event );
extern ThotBool DeleteColumn ( NotifyElement * event );
extern void ColumnDeleted ( NotifyElement *event );
extern void ColumnPasted ( NotifyElement * event );
extern void TableCreated ( NotifyElement * event );
extern void TablePasted ( NotifyElement * event );
extern void CopyRow ( Element copyRow,
                      Element origRow,
                      Document doc );
extern void CopyCell ( Element cell,
                       Document doc,
                       ThotBool inRow );
extern void NextCellInColumn ( Element* cell,
                               Element* row,
                               Element colHead,
                               Document doc,
                               ThotBool* fake );
extern void TablebodyDeleted ( NotifyElement * event );
extern void RowCreated ( NotifyElement *event );
extern void RowPasted ( NotifyElement * event );
extern int GetActualColspan ( Element cell,
                              ThotBool inMath );
extern void ChangeColspan ( Element cell,
                            int oldspan,
                            int* newspan,
                            Document doc );
extern void ColspanCreated ( NotifyAttribute * event );
extern ThotBool RegisterColspan ( NotifyAttribute * event );
extern void ColspanModified ( NotifyAttribute * event );
extern void ColspanDeleted ( NotifyAttribute * event );
extern int GetActualRowspan ( Element cell,
                              ThotBool inMath );
extern void ChangeRowspan ( Element cell,
                            int oldspan,
                            int* newspan,
                            Document doc );
extern void RowspanCreated ( NotifyAttribute * event );
extern ThotBool RegisterRowspan ( NotifyAttribute * event );
extern void RowspanModified ( NotifyAttribute * event );
extern void RowspanDeleted ( NotifyAttribute * event );

#else /* __STDC__ */

extern ThotBool WithinLastPastedCell ( Element el );
extern Element GetSiblingRow ( Element row,
                                 ThotBool before,
                                 ThotBool inMath );
extern Element GetSiblingCell ( Element cell,
                                  ThotBool before,
                                  ThotBool inMath );
extern Element GetFirstCellOfRow ( Element row,
                                     ThotBool inMath );
extern int SetRowExt ( Element cell,
                         int span,
                         Document doc,
                         ThotBool inMath );
extern int SetColExt ( Element cell,
                         int span,
                         Document doc,
                         ThotBool inMath,
                         ThotBool deletingLastCol );
extern Element GetCellFromColumnHead ( Element row,
                                         Element colhead,
                                         ThotBool inMath );
extern Element NewColumnHead ( Element lastcolhead,
                                 ThotBool before,
                                 ThotBool last,
                                 Element row,
                                 Document doc,
                                 ThotBool inMath,
                                 ThotBool generateEmptyCells,
                                 ThotBool generateCol );
extern Element NextTableRow ( Element row );
extern void TransmitWidthToColhead ( Element col,
                                       Document doc,
                                       char *value,
                                       int oldwidth );
extern void CheckAllRows ( Element table,
                             Document doc,
                             ThotBool placeholder,
                             ThotBool deleteLastEmptyColumns );
extern void CheckTable ( Element table,
                           Document doc );
extern void NewCell ( Element cell,
                        Document doc,
                        ThotBool generateColumn,
                        ThotBool generateEmptyCells,
                        ThotBool check );
extern void CellCreated ( NotifyElement * event );
extern void CellPasted ( NotifyElement * event );
extern ThotBool DeleteRow ( NotifyElement *event );
extern void RowDeleted ( NotifyElement *event );
extern void CheckDeleteParentTable ( Element el );
extern ThotBool DeleteTable ( NotifyElement * event );
extern void TableDeleted ( NotifyElement *event );
extern ThotBool DeleteTBody ( NotifyElement * event );
extern ThotBool ModifySpan ( NotifyAttribute * event );
extern void SpanModified ( NotifyAttribute * event );
extern void SpanCreated ( NotifyAttribute * event );
extern ThotBool DeleteSpan ( NotifyAttribute * event );
extern void ApplyCSSRuleOneCol ( Element col,
                                   PresentationContext ctxt,
                                   char *cssRule,
                                   CSSInfoPtr css );
extern void ColApplyCSSRule ( Element el,
                                PresentationContext ctxt,
                                char *cssRule,
                                CSSInfoPtr css );
extern void CellAlignCreated ( NotifyAttribute * event );
extern void CellAlignModified ( NotifyAttribute * event );
extern void CellAlignDeleted ( NotifyAttribute * event );
extern ThotBool DeleteColElement ( NotifyElement * event );
extern ThotBool CreateColElement ( NotifyElement * event );
extern ThotBool PasteColElement ( NotifyOnValue * event );
extern ThotBool DeleteColumn ( NotifyElement * event );
extern void ColumnDeleted ( NotifyElement *event );
extern void ColumnPasted ( NotifyElement * event );
extern void TableCreated ( NotifyElement * event );
extern void TablePasted ( NotifyElement * event );
extern void CopyRow ( Element copyRow,
                        Element origRow,
                        Document doc );
extern void CopyCell ( Element cell,
                         Document doc,
                         ThotBool inRow );
extern void NextCellInColumn ( Element* cell,
                                 Element* row,
                                 Element colHead,
                                 Document doc,
                                 ThotBool* fake );
extern void TablebodyDeleted ( NotifyElement * event );
extern void RowCreated ( NotifyElement *event );
extern void RowPasted ( NotifyElement * event );
extern int GetActualColspan ( Element cell,
                                ThotBool inMath );
extern void ChangeColspan ( Element cell,
                              int oldspan,
                              int* newspan,
                              Document doc );
extern void ColspanCreated ( NotifyAttribute * event );
extern ThotBool RegisterColspan ( NotifyAttribute * event );
extern void ColspanModified ( NotifyAttribute * event );
extern void ColspanDeleted ( NotifyAttribute * event );
extern int GetActualRowspan ( Element cell,
                                ThotBool inMath );
extern void ChangeRowspan ( Element cell,
                              int oldspan,
                              int* newspan,
                              Document doc );
extern void RowspanCreated ( NotifyAttribute * event );
extern ThotBool RegisterRowspan ( NotifyAttribute * event );
extern void RowspanModified ( NotifyAttribute * event );
extern void RowspanDeleted ( NotifyAttribute * event );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
