/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern DocumentMetaDataElement *DocumentMetaDataAlloc ( void );
extern void DocumentMetaClear ( DocumentMetaDataElement *me );
extern char * DocumentTypeString ( Document document );
extern void DocumentInfo ( Document document,
                           View view );
extern Document IsDocumentLoaded ( char *documentURL,
                                   char *form_data );
extern void ExtractParameters ( char *aName,
                                char *parameters );
extern void SetArrowButton ( Document document,
                             ThotBool back,
                             ThotBool on );
extern void ResetStop ( Document document );
extern void ActiveTransfer ( Document document );
extern void SetStopButton ( Document document );
extern void DocStatusUpdate ( Document doc,
                              ThotBool modified );
extern void SetTableMenuOff ( Document doc,
                              View view );
extern void SetTableMenuOn ( Document doc,
                             View view );
extern void UpdateEditorMenus ( Document doc );
extern void ChangeToEditorMode ( Document doc );
extern void ChangeToBrowserMode ( Document doc );
extern void SetBrowserEditor ( Document doc,
                               View view );
extern void ShowLogFile ( Document doc,
                          View view );
extern ThotBool OpenParsingErrors ( Document document );
extern void RemoveParsingErrors ( Document document );
extern void CleanUpParsingErrors ( void );
extern void CheckParsingErrors ( Document doc );
extern void UpdateTransfer ( Document document );
extern void StopTransfer ( Document document,
                           View view );
extern void SetWindowTitle ( Document sourceDoc,
                             Document targetDoc,
                             View view );
extern void InitFormAnswer ( Document document,
                             View view,
                             const char *auth_realm,
                             char *server );
extern void InitInfo ( char *label,
                       char *info );
extern void ConfirmError ( Document document,
                           View view,
                           char *label,
                           char *extrabutton,
                           char *confirmbutton );
extern void InitConfirm3L ( Document document,
                            View view,
                            char *label1,
                            char *label2,
                            char *label3,
                            ThotBool withCancel );
extern void InitConfirm ( Document document,
                          View view,
                          char *label );
extern void InitCharset ( Document document,
                          View view,
                          char *url );
extern void InitMimeType ( Document document,
                           View view,
                           char *url,
                           char *status );
extern void OpenDoc ( Document doc,
                      View view );
extern void OpenDocInNewWindow ( Document document,
                                 View view );
extern void OpenNew ( Document document,
                      View view,
                      int docType,
                      int docProfile );
extern void GoToHome ( Document doc,
                       View view );
extern void UpdateDoctypeMenu ( Document doc );
extern void AddDirAttributeToDocEl ( Document doc );
extern Document InitDocAndView ( Document oldDoc,
                                 ThotBool replaceOldDoc,
                                 ThotBool inNewWindow,
                                 char *docname,
                                 DocumentType docType,
                                 Document sourceOfDoc,
                                 ThotBool readOnly,
                                 int profile,
                                 ClickEvent method );
extern void ReparseAs ( Document doc,
                        View view,
                        ThotBool asHTML,
                        CHARSET charset );
extern void ParseAsHTML ( Document doc,
                          View view );
extern void Reload_callback ( int doc,
                              int status,
                              char *urlName,
                              char *outputfile,
                              AHTHeaders *http_headers,
                              void * context );
extern void Reload ( Document doc,
                     View view );
extern void ShowTargets ( Document document,
                          View view );
extern void ZoomIn ( Document document,
                     View view );
extern void ZoomOut ( Document document,
                      View view );
extern void ShowSource ( Document document,
                         View view );
extern void ShowStructure ( Document doc,
                            View view );
extern void ShowAlternate ( Document doc,
                            View view );
extern void ShowLinks ( Document doc,
                        View view );
extern void ShowToC ( Document doc,
                      View view );
extern ThotBool ViewToClose ( NotifyDialog *event );
extern void GetAmayaDoc_callback ( int newdoc,
                                   int status,
                                   char *urlName,
                                   char *outputfile,
                                   AHTHeaders *http_headers,
                                   void * context );
extern Document GetAmayaDoc ( char *urlname,
                              char *form_data,
                              Document doc,
                              Document baseDoc,
                              ClickEvent method,
                              ThotBool history,
                              TTcbf *cbf,
                              void *ctx_cbf );
extern void CallbackDialogue ( int ref,
                               int typedata,
                               char *data );
extern ThotBool CheckMakeDirectory ( char *name,
                                     ThotBool recursive );
extern void FreeAmayaIcons ( void );
extern void FreeAmayaStructures ( void );
extern void InitAmaya ( NotifyEvent * event );
extern void ChangeAttrOnRoot ( Document doc,
                               int attrNum );
extern void ShowMapAreas ( Document doc,
                           View view );
extern void ShowButtons ( Document doc,
                          View view );
extern void ShowAddress ( Document doc,
                          View view );
extern void SectionNumbering ( Document doc,
                               View view );
extern void MakeIDMenu ( Document doc,
                         View view );
extern void CheckAmayaClosed ( void );
extern void CloseDocument ( Document doc,
                            View view );
extern void AmayaClose ( Document document,
                         View view );
extern void AddURLInCombobox ( char *pathname,
                               char *form_data,
                               ThotBool keep );
extern void InitStringForCombobox ( void );
extern void RemoveDocFromSaveList ( char *name,
                                    char *initial_url,
                                    int doctype );
extern void AddDocInSaveList ( char *name,
                               char *initial_url,
                               int doctype );
extern void InitAutoSave ( void );
extern void SaveGeometryOnExit ( int document,
                                 const char * view_name );

#else /* __STDC__ */

extern DocumentMetaDataElement *DocumentMetaDataAlloc ( void );
extern void DocumentMetaClear ( DocumentMetaDataElement *me );
extern char * DocumentTypeString ( Document document );
extern void DocumentInfo ( Document document,
                             View view );
extern Document IsDocumentLoaded ( char *documentURL,
                                     char *form_data );
extern void ExtractParameters ( char *aName,
                                  char *parameters );
extern void SetArrowButton ( Document document,
                               ThotBool back,
                               ThotBool on );
extern void ResetStop ( Document document );
extern void ActiveTransfer ( Document document );
extern void SetStopButton ( Document document );
extern void DocStatusUpdate ( Document doc,
                                ThotBool modified );
extern void SetTableMenuOff ( Document doc,
                                View view );
extern void SetTableMenuOn ( Document doc,
                               View view );
extern void UpdateEditorMenus ( Document doc );
extern void ChangeToEditorMode ( Document doc );
extern void ChangeToBrowserMode ( Document doc );
extern void SetBrowserEditor ( Document doc,
                                 View view );
extern void ShowLogFile ( Document doc,
                            View view );
extern ThotBool OpenParsingErrors ( Document document );
extern void RemoveParsingErrors ( Document document );
extern void CleanUpParsingErrors ( void );
extern void CheckParsingErrors ( Document doc );
extern void UpdateTransfer ( Document document );
extern void StopTransfer ( Document document,
                             View view );
extern void SetWindowTitle ( Document sourceDoc,
                               Document targetDoc,
                               View view );
extern void InitFormAnswer ( Document document,
                               View view,
                               const char *auth_realm,
                               char *server );
extern void InitInfo ( char *label,
                         char *info );
extern void ConfirmError ( Document document,
                             View view,
                             char *label,
                             char *extrabutton,
                             char *confirmbutton );
extern void InitConfirm3L ( Document document,
                              View view,
                              char *label1,
                              char *label2,
                              char *label3,
                              ThotBool withCancel );
extern void InitConfirm ( Document document,
                            View view,
                            char *label );
extern void InitCharset ( Document document,
                            View view,
                            char *url );
extern void InitMimeType ( Document document,
                             View view,
                             char *url,
                             char *status );
extern void OpenDoc ( Document doc,
                        View view );
extern void OpenDocInNewWindow ( Document document,
                                   View view );
extern void OpenNew ( Document document,
                        View view,
                        int docType,
                        int docProfile );
extern void GoToHome ( Document doc,
                         View view );
extern void UpdateDoctypeMenu ( Document doc );
extern void AddDirAttributeToDocEl ( Document doc );
extern Document InitDocAndView ( Document oldDoc,
                                   ThotBool replaceOldDoc,
                                   ThotBool inNewWindow,
                                   char *docname,
                                   DocumentType docType,
                                   Document sourceOfDoc,
                                   ThotBool readOnly,
                                   int profile,
                                   ClickEvent method );
extern void ReparseAs ( Document doc,
                          View view,
                          ThotBool asHTML,
                          CHARSET charset );
extern void ParseAsHTML ( Document doc,
                            View view );
extern void Reload_callback ( int doc,
                                int status,
                                char *urlName,
                                char *outputfile,
                                AHTHeaders *http_headers,
                                void * context );
extern void Reload ( Document doc,
                       View view );
extern void ShowTargets ( Document document,
                            View view );
extern void ZoomIn ( Document document,
                       View view );
extern void ZoomOut ( Document document,
                        View view );
extern void ShowSource ( Document document,
                           View view );
extern void ShowStructure ( Document doc,
                              View view );
extern void ShowAlternate ( Document doc,
                              View view );
extern void ShowLinks ( Document doc,
                          View view );
extern void ShowToC ( Document doc,
                        View view );
extern ThotBool ViewToClose ( NotifyDialog *event );
extern void GetAmayaDoc_callback ( int newdoc,
                                     int status,
                                     char *urlName,
                                     char *outputfile,
                                     AHTHeaders *http_headers,
                                     void * context );
extern Document GetAmayaDoc ( char *urlname,
                                char *form_data,
                                Document doc,
                                Document baseDoc,
                                ClickEvent method,
                                ThotBool history,
                                TTcbf *cbf,
                                void *ctx_cbf );
extern void CallbackDialogue ( int ref,
                                 int typedata,
                                 char *data );
extern ThotBool CheckMakeDirectory ( char *name,
                                       ThotBool recursive );
extern void FreeAmayaIcons ( void );
extern void FreeAmayaStructures ( void );
extern void InitAmaya ( NotifyEvent * event );
extern void ChangeAttrOnRoot ( Document doc,
                                 int attrNum );
extern void ShowMapAreas ( Document doc,
                             View view );
extern void ShowButtons ( Document doc,
                            View view );
extern void ShowAddress ( Document doc,
                            View view );
extern void SectionNumbering ( Document doc,
                                 View view );
extern void MakeIDMenu ( Document doc,
                           View view );
extern void CheckAmayaClosed ( void );
extern void CloseDocument ( Document doc,
                              View view );
extern void AmayaClose ( Document document,
                           View view );
extern void AddURLInCombobox ( char *pathname,
                                 char *form_data,
                                 ThotBool keep );
extern void InitStringForCombobox ( void );
extern void RemoveDocFromSaveList ( char *name,
                                      char *initial_url,
                                      int doctype );
extern void AddDocInSaveList ( char *name,
                                 char *initial_url,
                                 int doctype );
extern void InitAutoSave ( void );
extern void SaveGeometryOnExit ( int document,
                                   const char * view_name );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
