/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void InsertableElement_Init ( void );
extern void InsertableElement_Final ( void );
extern DLList InsertableElement_GetList ( Document doc );
extern DLList InsertableElement_Update ( Document doc,
                                         Element el,
                                         ThotBool force );

#else /* __STDC__ */

extern void InsertableElement_Init ( void );
extern void InsertableElement_Final ( void );
extern DLList InsertableElement_GetList ( Document doc );
extern DLList InsertableElement_Update ( Document doc,
                                           Element el,
                                           ThotBool force );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
