/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void MapMathMLAttribute ( STRING Attr,
                                 AttributeType *attrType,
                                 STRING elementName,
                                 Document doc );
extern void MapMathMLAttributeValue ( STRING AttrVal,
                                      AttributeType attrType,
                                      int *value );
extern void MapMathMLEntity ( STRING entityName,
                              STRING entityValue,
                              int valueLength,
                              STRING alphabet );
extern void MathMLEntityCreated ( USTRING entityValue,
                                  Language lang,
                                  STRING entityName,
                                  Document doc );
extern ThotBool ElementNeedsPlaceholder ( Element el );
extern void SetSingleIntHorizStretchAttr ( Element el,
                                           Document doc,
                                           Element* selEl );
extern void SetIntVertStretchAttr ( Element el,
                                    Document doc,
                                    int base,
                                    Element* selEl );
extern void CheckMTable ( Element elMTABLE,
                          Document doc );
extern void SetFontstyleAttr ( Element el,
                               Document doc );
extern void SetIntAddSpaceAttr ( Element el,
                                 Document doc );
extern void ChangeTypeOfElement ( Element elem,
                                  Document doc,
                                  int newTypeNum );
extern void CheckFence ( Element el,
                         Document doc );
extern void CreateFencedSeparators ( Element fencedExpression,
                                     Document doc,
                                     ThotBool record );
extern void TransformMFENCED ( Element el,
                               Document doc );
extern void MathMLElementComplete ( Element el,
                                    Document doc );
extern void SetFontfamily ( Document doc,
                            Element el,
                            STRING value );
extern void SetFontsize ( Document doc,
                          Element el,
                          STRING value );
extern void MathMLAttributeComplete ( Attribute attr,
                                      Element el,
                                      Document doc );
extern void MathMLGetDTDName ( STRING DTDname,
                               STRING elementName );

#else /* __STDC__ */

extern void MapMathMLAttribute (/* STRING Attr,
                                   AttributeType *attrType,
                                   STRING elementName,
                                   Document doc */);
extern void MapMathMLAttributeValue (/* STRING AttrVal,
                                        AttributeType attrType,
                                        int *value */);
extern void MapMathMLEntity (/* STRING entityName,
                                STRING entityValue,
                                int valueLength,
                                STRING alphabet */);
extern void MathMLEntityCreated (/* USTRING entityValue,
                                    Language lang,
                                    STRING entityName,
                                    Document doc */);
extern ThotBool ElementNeedsPlaceholder (/* Element el */);
extern void SetSingleIntHorizStretchAttr (/* Element el,
                                             Document doc,
                                             Element* selEl */);
extern void SetIntVertStretchAttr (/* Element el,
                                      Document doc,
                                      int base,
                                      Element* selEl */);
extern void CheckMTable (/* Element elMTABLE,
                            Document doc */);
extern void SetFontstyleAttr (/* Element el,
                                 Document doc */);
extern void SetIntAddSpaceAttr (/* Element el,
                                   Document doc */);
extern void ChangeTypeOfElement (/* Element elem,
                                    Document doc,
                                    int newTypeNum */);
extern void CheckFence (/* Element el,
                           Document doc */);
extern void CreateFencedSeparators (/* Element fencedExpression,
                                       Document doc,
                                       ThotBool record */);
extern void TransformMFENCED (/* Element el,
                                 Document doc */);
extern void MathMLElementComplete (/* Element el,
                                      Document doc */);
extern void SetFontfamily (/* Document doc,
                              Element el,
                              STRING value */);
extern void SetFontsize (/* Document doc,
                            Element el,
                            STRING value */);
extern void MathMLAttributeComplete (/* Attribute attr,
                                        Element el,
                                        Document doc */);
extern void MathMLGetDTDName (/* STRING DTDname,
                                 STRING elementName */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
