/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern DicDictionary CreateDictionary ( void );
extern void CleanDictionary ( DicDictionary dic );
extern Record Find ( DicDictionary dic,
                     const char * key );
extern Record FindPrevious ( DicDictionary dic,
                             const char * key,
                             ThotBool *isFirst );
extern Record FindPreviousElement ( DicDictionary dic,
                                    const DicElement el,
                                    ThotBool *isFirst );
extern DicElement Add ( DicDictionary dic,
                        const char * key,
                        const DicElement el );
extern DicElement Remove ( DicDictionary dic,
                           const char * key );
extern DicElement RemoveElement ( DicDictionary dic,
                                  const DicElement el );
extern DicElement Get ( DicDictionary dic,
                        const char * key );
extern void First ( DicDictionary dic );
extern void Next ( DicDictionary dic );
extern ThotBool IsDone ( const DicDictionary dic );
extern char* CurrentKey ( const DicDictionary dic );
extern void* CurrentElement ( const DicDictionary dic );
extern ThotBool IsEmpty ( const DicDictionary dic );
extern ThotBool isEOSorWhiteSpace ( const char c );
extern DicDictionary CreateDictionaryFromList ( const char *list );

#else /* __STDC__ */

extern DicDictionary CreateDictionary ( void );
extern void CleanDictionary ( DicDictionary dic );
extern Record Find ( DicDictionary dic,
                       const char * key );
extern Record FindPrevious ( DicDictionary dic,
                               const char * key,
                               ThotBool *isFirst );
extern Record FindPreviousElement ( DicDictionary dic,
                                      const DicElement el,
                                      ThotBool *isFirst );
extern DicElement Add ( DicDictionary dic,
                          const char * key,
                          const DicElement el );
extern DicElement Remove ( DicDictionary dic,
                             const char * key );
extern DicElement RemoveElement ( DicDictionary dic,
                                    const DicElement el );
extern DicElement Get ( DicDictionary dic,
                          const char * key );
extern void First ( DicDictionary dic );
extern void Next ( DicDictionary dic );
extern ThotBool IsDone ( const DicDictionary dic );
extern char* CurrentKey ( const DicDictionary dic );
extern void* CurrentElement ( const DicDictionary dic );
extern ThotBool IsEmpty ( const DicDictionary dic );
extern ThotBool isEOSorWhiteSpace ( const char c );
extern DicDictionary CreateDictionaryFromList ( const char *list );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
