/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern AHTDocId_Status *GetDocIdStatus ( int docid,
                                         HTList * documents );
extern boolean AHTReqContext_delete ( AHTReqContext * me );
extern int AHTOpen_file ( HTRequest * request );
extern int AHTLoadTerminate_handler ( HTRequest * request,
                                      HTResponse * response,
                                      void *param,
                                      int status );
extern void libwww_CleanCache ( void );
extern void QueryInit ( void );
extern void QueryClose ( void );
extern void InvokeGetObjectWWW_callback ( int docid,
                                          char *urlName,
                                          char *outputfile,
                                          TTcbf *terminate_cbf,
                                          void *context_tcbf,
                                          int status );
extern int GetObjectWWW ( int docid,
                          char* urlName,
                          char* formdata,
                          char* outputfile,
                          int mode,
                          TIcbf* incremental_cbf,
                          void* context_icbf,
                          TTcbf* terminate_cbf,
                          void* context_tcbf,
                          boolean error_html,
                          char *content_type );
extern int PutObjectWWW ( int docid,
                          char *fileName,
                          char *urlName,
                          int mode,
                          PicType contentType,
                          TTcbf * terminate_cbf,
                          void *context_tcbf );
extern void StopRequest ( int docid );
extern void StopAllRequests ( int docid );
extern boolean AmayaIsAlive ( void );
extern boolean CanDoStop ( void );
extern void CanDoStop_set ( boolean value );
extern void libwww_updateNetworkConf ( int status );
#else /* __STDC__ */

extern AHTDocId_Status *GetDocIdStatus (/* int docid,
                                           HTList * documents */);
extern boolean AHTReqContext_delete (/* AHTReqContext * me */);
extern int AHTOpen_file (/* HTRequest * request */);
extern int AHTLoadTerminate_handler (/* HTRequest * request,
                                        HTResponse * response,
                                        void *param,
                                        int status */);
extern void libwww_CleanCache (/* void */);
extern void QueryInit (/* void */);
extern void QueryClose (/* void */);
extern void InvokeGetObjectWWW_callback (/* int docid,
                                            char *urlName,
                                            char *outputfile,
                                            TTcbf *terminate_cbf,
                                            void *context_tcbf,
                                            int status */);
extern int GetObjectWWW (/* int docid,
                            char* urlName,
                            char* formdata,
                            char* outputfile,
                            int mode,
                            TIcbf* incremental_cbf,
                            void* context_icbf,
                            TTcbf* terminate_cbf,
                            void* context_tcbf,
                            boolean error_html,
                            char *content_type */);
extern int PutObjectWWW (/* int docid,
                            char *fileName,
                            char *urlName,
                            int mode,
                            PicType contentType,
                            TTcbf * terminate_cbf,
                            void *context_tcbf */);
extern void StopRequest (/* int docid */);
extern void StopAllRequests (/* int docid */);
extern boolean AmayaIsAlive (/* void */);
extern boolean CanDoStop (/* void */);
extern void CanDoStop_set (/* boolean value */);
extern void libwww_updateNetworkConf ( int status );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
