/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern STRING SkipBlanksAndComments ( STRING ptr );
extern STRING SkipProperty ( STRING ptr );
extern void ParseCSSBackgroundImageCallback ( Document doc,
                                              Element element,
                                              STRING file,
                                              void *extra );
extern STRING GetCSSBackgroundURL ( STRING styleString );
extern void PToCss ( PresentationSetting settings,
                     STRING buffer,
                     int len );
extern void ParseHTMLSpecificStyle ( Element el,
                                     STRING cssRule,
                                     Document doc,
                                     ThotBool destroy );
extern int IsImplicitClassName ( STRING class,
                                 Document doc );
extern void HTMLSetBackgroundColor ( Document doc,
                                     Element el,
                                     STRING color );
extern void HTMLSetBackgroundImage ( Document doc,
                                     Element el,
                                     int repeat,
                                     STRING image );
extern void HTMLSetForegroundColor ( Document doc,
                                     Element el,
                                     STRING color );
extern void HTMLResetBackgroundColor ( Document doc,
                                       Element el );
extern void HTMLResetBackgroundImage ( Document doc,
                                       Element el );
extern void HTMLResetForegroundColor ( Document doc,
                                       Element el );
extern void HTMLSetAlinkColor ( Document doc,
                                STRING color );
extern void HTMLSetAactiveColor ( Document doc,
                                  STRING color );
extern void HTMLSetAvisitedColor ( Document doc,
                                   STRING color );
extern void HTMLResetAlinkColor ( Document doc );
extern void HTMLResetAactiveColor ( Document doc );
extern void HTMLResetAvisitedColor ( Document doc );
extern void ApplyCSSRules ( Element el,
                            STRING cssRule,
                            Document doc,
                            ThotBool destroy );
extern CHAR_T ReadCSSRules ( Document docRef,
                             CSSInfoPtr css,
                             STRING buffer,
                             ThotBool withUndo );

#else /* __STDC__ */

extern STRING SkipBlanksAndComments (/* STRING ptr */);
extern STRING SkipProperty (/* STRING ptr */);
extern void ParseCSSBackgroundImageCallback (/* Document doc,
                                                Element element,
                                                STRING file,
                                                void *extra */);
extern STRING GetCSSBackgroundURL (/* STRING styleString */);
extern void PToCss (/* PresentationSetting settings,
                       STRING buffer,
                       int len */);
extern void ParseHTMLSpecificStyle (/* Element el,
                                       STRING cssRule,
                                       Document doc,
                                       ThotBool destroy */);
extern int IsImplicitClassName (/* STRING class,
                                   Document doc */);
extern void HTMLSetBackgroundColor (/* Document doc,
                                       Element el,
                                       STRING color */);
extern void HTMLSetBackgroundImage (/* Document doc,
                                       Element el,
                                       int repeat,
                                       STRING image */);
extern void HTMLSetForegroundColor (/* Document doc,
                                       Element el,
                                       STRING color */);
extern void HTMLResetBackgroundColor (/* Document doc,
                                         Element el */);
extern void HTMLResetBackgroundImage (/* Document doc,
                                         Element el */);
extern void HTMLResetForegroundColor (/* Document doc,
                                         Element el */);
extern void HTMLSetAlinkColor (/* Document doc,
                                  STRING color */);
extern void HTMLSetAactiveColor (/* Document doc,
                                    STRING color */);
extern void HTMLSetAvisitedColor (/* Document doc,
                                     STRING color */);
extern void HTMLResetAlinkColor (/* Document doc */);
extern void HTMLResetAactiveColor (/* Document doc */);
extern void HTMLResetAvisitedColor (/* Document doc */);
extern void ApplyCSSRules (/* Element el,
                              STRING cssRule,
                              Document doc,
                              ThotBool destroy */);
extern CHAR_T ReadCSSRules (/* Document docRef,
                               CSSInfoPtr css,
                               STRING buffer,
                               ThotBool withUndo */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
