/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern char *GetSchemaFromDocType ( DocumentType docType );
extern void LoadTemplate (Document doc, char* templatename, char* docname,
						  DocumentType doctype, ThotBool createInstance);
extern void CreateInstanceDocument ( Document doc,
                                     char *templatename,
                                     char *docname,
                                     DocumentType docType );
extern void InstanciateTemplate(char *templatename, Document doc);
extern void InstanciateTemplate (Document doc, char *templatename, char *docname,
								 DocumentType docType);

#else /* __STDC__ */

extern char *GetSchemaFromDocType ( DocumentType docType );
extern void LoadTemplate (Document doc, char* templatename, char* docname,
						  DocumentType doctype, ThotBool createInstance);
extern void CreateInstanceDocument ( Document doc,
                                       char *templatename,
                                       char *docname,
                                       DocumentType docType );
extern void InstanciateTemplate(char *templatename, Document doc);
extern void InstanciateTemplate (Document doc, char *templatename, char *docname,
								 DocumentType docType);


#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
