/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern Element Template_InsertRepeatChildAfter ( Document doc,
                                                 Element el,
                                                 Declaration decl,
                                                 Element elPrev );
extern Element Template_InsertBagChild ( Document doc,
                                         Element sel,
                                         Element bag,
                                         Declaration decl,
                                         ThotBool before );
extern void CreateTemplate ( Document doc,
                             char *templatePath );
extern void CreateInstance ( char *templatePath,
                             char *instancePath,
                             char *docname,
                             DocumentType docType,
                             int basedoc );
extern Element Template_GetNewSimpleTypeInstance ( Document doc,
                                                   Element parent,
                                                   Declaration decl );
extern Element Template_GetNewXmlElementInstance ( Document doc,
                                                   Element parent,
                                                   Declaration decl );
extern Element InsertWithNotify ( Element el,
                                  Element child,
                                  Element parent,
                                  Document doc );
extern Element Template_InsertUseChildren ( Document doc,
                                            Element el,
                                            Declaration dec );
extern void Template_FixAccessRight ( XTigerTemplate t,
                                      Element el,
                                      Document doc );
extern void AddPromptIndicator ( Element el,
                                 Document doc );
extern Element InstantiateUse ( XTigerTemplate t,
                                Element el,
                                Document doc,
                                ThotBool registerUndo );
extern void InstantiateRepeat ( XTigerTemplate t,
                                Element el,
                                Document doc,
                                ThotBool registerUndo );
extern void Template_InsertXTigerPI ( Document doc,
                                      XTigerTemplate t );
extern void Template_PreInstantiateComponents ( XTigerTemplate t );
extern ThotBool Template_SetName ( Document doc,
                                   Element el,
                                   const char *name,
                                   ThotBool withUndo );
extern ThotBool Template_SetLabel ( Document doc,
                                    Element el,
                                    const char *label,
                                    ThotBool withUndo );

#else /* __STDC__ */

extern Element Template_InsertRepeatChildAfter ( Document doc,
                                                   Element el,
                                                   Declaration decl,
                                                   Element elPrev );
extern Element Template_InsertBagChild ( Document doc,
                                           Element sel,
                                           Element bag,
                                           Declaration decl,
                                           ThotBool before );
extern void CreateTemplate ( Document doc,
                               char *templatePath );
extern void CreateInstance ( char *templatePath,
                               char *instancePath,
                               char *docname,
                               DocumentType docType,
                               int basedoc );
extern Element Template_GetNewSimpleTypeInstance ( Document doc,
                                                     Element parent,
                                                     Declaration decl );
extern Element Template_GetNewXmlElementInstance ( Document doc,
                                                     Element parent,
                                                     Declaration decl );
extern Element InsertWithNotify ( Element el,
                                    Element child,
                                    Element parent,
                                    Document doc );
extern Element Template_InsertUseChildren ( Document doc,
                                              Element el,
                                              Declaration dec );
extern void Template_FixAccessRight ( XTigerTemplate t,
                                        Element el,
                                        Document doc );
extern void AddPromptIndicator ( Element el,
                                   Document doc );
extern Element InstantiateUse ( XTigerTemplate t,
                                  Element el,
                                  Document doc,
                                  ThotBool registerUndo );
extern void InstantiateRepeat ( XTigerTemplate t,
                                  Element el,
                                  Document doc,
                                  ThotBool registerUndo );
extern void Template_InsertXTigerPI ( Document doc,
                                        XTigerTemplate t );
extern void Template_PreInstantiateComponents ( XTigerTemplate t );
extern ThotBool Template_SetName ( Document doc,
                                     Element el,
                                     const char *name,
                                     ThotBool withUndo );
extern ThotBool Template_SetLabel ( Document doc,
                                      Element el,
                                      const char *label,
                                      ThotBool withUndo );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
