/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotBool CreateInitConfirmDlgWX ( int ref,
                                         ThotWindow parent,
                                         char *title,
                                         char *extrabutton,
                                         char *confirmbutton,
                                         char *label );
extern ThotBool CreateOpenDocDlgWX ( int ref,
                                     ThotWindow parent,
                                     const char *title,
                                     const char *urlList,
                                     const char *docName,
                                     int doc_select,
                                     int dir_select,
                                     DocumentType doc_type );
extern ThotBool CreateTitleDlgWX ( int ref,
                                   ThotWindow parent,
                                   char *doc_title );
extern ThotBool CreateSearchDlgWX ( int ref,
                                    ThotWindow parent,
                                    char* caption );
extern ThotBool CreatePrintDlgWX ( int ref,
                                   ThotWindow parent,
                                   char* ps_file );
extern ThotBool CreateSaveAsDlgWX ( int ref,
                                    ThotWindow parent,
                                    char* pathname,
                                    Document doc );

#else /* __STDC__ */

extern ThotBool CreateInitConfirmDlgWX ( int ref,
                                           ThotWindow parent,
                                           char *title,
                                           char *extrabutton,
                                           char *confirmbutton,
                                           char *label );
extern ThotBool CreateOpenDocDlgWX ( int ref,
                                       ThotWindow parent,
                                       const char *title,
                                       const char *urlList,
                                       const char *docName,
                                       int doc_select,
                                       int dir_select,
                                       DocumentType doc_type );
extern ThotBool CreateTitleDlgWX ( int ref,
                                     ThotWindow parent,
                                     char *doc_title );
extern ThotBool CreateSearchDlgWX ( int ref,
                                      ThotWindow parent,
                                      char* caption );
extern ThotBool CreatePrintDlgWX ( int ref,
                                     ThotWindow parent,
                                     char* ps_file );
extern ThotBool CreateSaveAsDlgWX ( int ref,
                                      ThotWindow parent,
                                      char* pathname,
                                      Document doc );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
