/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void CreateInitConfirmDlgWX ( ThotWindow parent,
                                     char *title,
                                     char *extrabutton,
                                     char *confirmbutton,
                                     char *label );

#else /* __STDC__ */

extern void CreateInitConfirmDlgWX ( ThotWindow parent,
                                       char *title,
                                       char *extrabutton,
                                       char *confirmbutton,
                                       char *label );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
