/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern Element AGetRootElement ( Document doc );
extern Element SearchAttrId ( Element root,
                              const char *val );
extern Element SearchSiblingIndex ( Element root,
                                    const char *el_name,
                                    int *index );
extern ThotBool SearchTextPosition ( Element *mark,
                                     int *firstCh );
extern char * TextPlainId_build ( Document doc,
                                  View view,
                                  ThotBool useDocRoot );
extern char * XPointer_build ( Document doc,
                               View view,
                               ThotBool useDocRoot );
extern void XPointer_bufferStore ( Document doc,
                                   View view );
extern char * XPointer_buffer ( void );
extern void XPointer_bufferFree ( void );

#else /* __STDC__ */

extern Element AGetRootElement ( Document doc );
extern Element SearchAttrId ( Element root,
                                const char *val );
extern Element SearchSiblingIndex ( Element root,
                                      const char *el_name,
                                      int *index );
extern ThotBool SearchTextPosition ( Element *mark,
                                       int *firstCh );
extern char * TextPlainId_build ( Document doc,
                                    View view,
                                    ThotBool useDocRoot );
extern char * XPointer_build ( Document doc,
                                 View view,
                                 ThotBool useDocRoot );
extern void XPointer_bufferStore ( Document doc,
                                     View view );
extern char * XPointer_buffer ( void );
extern void XPointer_bufferFree ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
