/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern const char * DAVFQDN ( void );
extern char * DAVDefaultEmail ( void );
extern char * DAVBreakString ( char *original );
extern time_t DAVTimeoutValue ( char *timeout );
extern char * DAVCopyFile ( char * filename,
                            int size );
extern ThotBool DAVAllowResource ( char *url );
extern char * DAVFindLockToken ( char *hostname,
                                 char *relative );
extern LockLine * DAVGetLockFromTree ( AwTree * tree,
                                       char *owner );
extern ThotBool DAVAddIfHeader ( AHTReqContext *context,
                                 char *url );
extern void DAVRemoveIfHeader ( AHTReqContext *context );
extern AHTDAVContext * AHTDAVContext_new ( const char *url );
extern void AHTDAVContext_delete ( AHTDAVContext * me );
extern AHTReqContext * DAVCreateDefaultContext ( int doc,
                                                 char *url,
                                                 AHTDAVContext *dav,
                                                 HTNetAfter * after,
                                                 TTcbf * terminate,
                                                 TIcbf * incremental,
                                                 BOOL preemptive,
                                                 int mode );
extern AHTReqContext * DAVCopyContext ( AHTReqContext *context );

#else /* __STDC__ */

extern const char * DAVFQDN ( void );
extern char * DAVDefaultEmail ( void );
extern char * DAVBreakString ( char *original );
extern time_t DAVTimeoutValue ( char *timeout );
extern char * DAVCopyFile ( char * filename,
                              int size );
extern ThotBool DAVAllowResource ( char *url );
extern char * DAVFindLockToken ( char *hostname,
                                   char *relative );
extern LockLine * DAVGetLockFromTree ( AwTree * tree,
                                         char *owner );
extern ThotBool DAVAddIfHeader ( AHTReqContext *context,
                                   char *url );
extern void DAVRemoveIfHeader ( AHTReqContext *context );
extern AHTDAVContext * AHTDAVContext_new ( const char *url );
extern void AHTDAVContext_delete ( AHTDAVContext * me );
extern AHTReqContext * DAVCreateDefaultContext ( int doc,
                                                   char *url,
                                                   AHTDAVContext *dav,
                                                   HTNetAfter * after,
                                                   TTcbf * terminate,
                                                   TIcbf * incremental,
                                                   BOOL preemptive,
                                                   int mode );
extern AHTReqContext * DAVCopyContext ( AHTReqContext *context );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
