#define INTERMEDIATE_SYMBOL	              0
#define UNMATCHING_STRUCT_SCHEME              1
#define MAX_LINE_SIZE_EXCEEDED	              2
#define UNKNOWN_TYPE_APP	              3
#define APP_STRUCT_SCHEM_NOT_FOUND	      4
#define FILE_NOT_FOUND	                      5
#define UNKNOWN_MESSAGE	                      6
#define FORBIDDEN_OUTSIDE_EDITOR_I	      7
#define UNKNOWN_ATTR_APP	              8
#define APP_ITEM_ALREADY_EXISTS	              9
#define NOT_IN_DEFAULT	                     10
#define MISSING_FIRST_SECOND	             11
#define NOT_A_PAIR		             12
#define FORBIDDEN_FOR_AN_ELEM	             13
#define FORBIDDEN_FOR_AN_ATTR	             14
#define ONLY_IF_PRE_ALLOWED	             15
#define MULTIPLE_CASCADE_LEVELS	             16
#define INVALID_FILE			     17
#define MSG_MAX_APP		             18
