#define ID_Tout			 0
#define ID_Indexer		 1
#define ID_Construire		 2
#define ID_Titre		 3
#define ID_Fusion		 4
#define ID_Descripteur		 5
#define ID_Marque		 6
#define INDEX_DEBORDEMENT	 7
#define INDEX_OPTIONS		 8
#define INDEX_CROISES		 9
#define INDEX_DEBUT_OK		10
#define INDEX_BAD_KEY		11
#define INDEX_NO_MARK		12
#define INDEX_VIDE		13
#define INDEX_BOUCLE_REF	14
#define INDEX_DON_T_COPY_MARK	15
#define INDEX_EXTENSION		16
#define INDEX_NO_EXTENSION	17
#define INDEX_STOP_SEMANTICS	18
#define INDEX_NO_INDEXPAR	19
#define INDEX_NO_FILE		20
#define INDEX_BAD_GROUP		21
#define INDEX_FIN_OK		22
#define INDEX_NO_TRI		23
#define INDEX_NO_DOC		24
#define INDEX_NOINDEX		25
#define INDEX_NOTABLE		26
#define INDEX_SUP_DESC  	27
#define INDEX_SUP_MARQUE	28
#define ID_Repaginate		29

#define INDEX_MSG_MAX		30
