#define PRS_INTERMEDIATE_SYMBOL	                       0  
#define PRS_THE_STRUCT_SCHEM_DOES_NOT_MATCH	       1 
#define PRS_WORD_TOO_LONG	                       2
#define PRS_TOO_MANY_VIEWS	                       3
#define PRS_TOO_MANY_COUNTERS	                       4
#define PRS_IDENTIFIER_NOT_DECLARED	               5
#define PRS_TOO_MANY_CONSTANTS	                       6
#define PRS_CHARACTER_STRING_TOO_LONG	               7
#define PRS_TOO_MANY_VARIABLES	                       8
#define PRS_TOO_MANY_BOXES	                       9
#define PRS_TOO_MANY_FUNCTIONS_IN_THIS_VARIABLE	      10
#define PRS_IT_S_NOT_AN_ASSOC_ELEM	              11
#define PRS_ONLY_FOR_REFS	                      12
#define PRS_LINE_TOO_LONG	                      13
#define PRS_UNKNOWN_ATTR	                      14
#define PRS_INCOR_ATTR_VALUE	                      15
#define PRS_UNKNOWN_TYPE	                      16
#define PRS_TOO_MANY_POSITIONS	                      17
#define PRS_TOO_MANY_DIGITS_AFTER	              18
#define PRS_INVALID_RULE_FOR_A_TYPE	              19
#define PRS_UNDEF_BOX	                              20
#define PRS_INHERIT_FROM_PREVIOUS_NOT_ALLOWED	      21
#define PRS_ONLY_ONE_PAGE_RULE	                      22
#define PRS_INHERIT_FROM_ENCLOSED_NOT_ALLOWED	      23
#define PRS_NOT_IMPLEMENTED_IN_THIS_VERSION	      24
#define PRS_NOT_ALLOWED_IN_DEFAULT_RULES	      25
#define PRS_ONE_DEFAULT_RULE_MISSING	              26
#define PRS_RULE_DEFINED_TWICE	                      27
#define PRS_ONLY_ENCLOSED_AND_ARE_ALLOWED	      28
#define PRS_INVALID_DIM_RULE	                      29
#define PRS_TOO_MANY_COLUMNS	                      30
#define PRS_NAME_ALREADY_DECLARED	              31
#define PRS_RULE_NOT_ALLOWED_IN_A_VIEW	              32
#define PRS_TOO_MANY_OPS_ON_THAT_COUNTER	      33
#define PRS_CONDITION_NOT_ALLOWED	              34
#define PRS_CREA_RULE_NOT_ALLOWED	              35
#define PRS_HAS_NO_VERTIC_POS_IN_THE_PAGE	      36
#define PRS_INCOR_VERTIC_POS_IN_PAGE	              37
#define PRS_INVALID_HEIGHT_RULE	                      38
#define PRS_INVALID_WIDTH_RULE	                      39
#define PRS_NO_REF_TO_THAT_ELEM	                      40
#define PRS_VERTIC_DIST_MUST_BE_CONSTANT	      41
#define PRS_STRUCT_SCHEM_NOT_FOUND	              42
#define PRS_INVALID_RULE_FOR_ROOT_ELEM	              43
#define PRS_INVALID_RULE_FOR_A_TERMINAL_ELEM	      44
#define PRS_DONT_USE_IN_FOR_THE_MAIN_VIEW	      45
#define PRS_INVALID_VERTPOS_RULE	              46
#define PRS_INVALID_HORIZPOS_RULE	              47
#define PRS_TWO_DIFFERENT_PAGE_NUMBERS	              48
#define PRS_INVALID_CHARACTER	                      49
#define PRS_FORBIDDEN_IN_HEIGHT_OR_WIDTH	      50
#define PRS_INCOMPAT_IN_THAT_RULE	              51
#define PRS_TOO_MANY_CASES_FOR_THAT_ATTR	      52
#define PRS_ONLY_ONE_EXPORT_VIEW_ALLOWED	      53
#define PRS_ALLOWED_ONLY_FOR_A_REF_ATTR	              54
#define PRS_ALREADY_DEFINED	                      55
#define PRS_INCOR_ATTR_TYPE	                      56
#define PRS_INVALID_UNIT_FOR_AN_ATTR	              57
#define PRS_NO_DECIMAL_PART_AFTER_AN_ATTR	      58
#define PRS_LOWER_BOUND_IS_GREATER	              59
#define PRS_USES_DIFFERENT_PAGE_COUNTERS	      60
#define PRS_ASSOC_ELEMS_ONLY	                      61
#define PRS_TOO_MANY_VIEWS_TO_BE_PRINTED	      62
#define PRS_NOT_AN_ATTR_FOR_THE_ROOT_ELEM	      63
#define PRS_UNUSED_BOX	                              64
#define PRS_NOT_ALLOWED_FOR_THIS_TYPE_OF_ATTR	      65
#define PRS_THIS_IS_NOT_A_NUMERICAL_ATTR	      66
#define PRS_NOT_ENOUGH_MEM	                      67
#define PRS_INCOR_COUNTER_VALUE	                      68
#define PRS_ONLY_ONE_CONTENT_RULE_ALLOWED	      69
#define PRS_INCOR_CONTENT_RULE	                      70
#define PRS_CONTENT_ALLOWED_ONLY_IN_MAIN_VIEW 	      71
#define PRS_INCOR_USE_OF_KEYWORD_FORWARD	      72
#define PRS_TOO_MANY_TRANSMIT_RULES_FOR_ELEMS	      73 
#define PRS_THIS_ELEM_HAS_A_TRANSMIT_RULE	      74
#define PRS_FORBIDDEN_IN_A_PRES_BOX	              75
#define PRS_TOO_MANY_TRANSMIT_RULES_FOR_THAT_COUNTER  76
#define PRS_THIS_IS_NOT_AN_INCLUDED_DOC	              77
#define PRS_NO_SUCH_FILE	                      78
#define PRS_FORBIDDEN_IN_A_REF                        79
#define PRS_ONLY_FOR_BOXES_AND_REFS                   80
#define PRS_ONLY_ONE_COPY_CONTENT_RULE                81
#define PRS_CANNOT_LOAD_SCHEMA                        82
#define PRS_NOT_FOR_PRES_BOX                          83
#define PRS_ONLY_FOR_EXT_REFS                         84
#define PRS_CONTENT_ALREADY_DEFINED                   85
#define PRS_MISSING_FIRST_SECOND                      86
#define PRS_NOT_A_PAIR                                87
#define PRS_PATTERN_NOT_FOUND                         88
#define PRS_ONLY_CONDITION_WITHIN	              89
#define PRS_COLOR_NOT_FOUND                           90
#define PRS_INVALID_RULE_FOR_A_CHOICE                 91
#define PRS_ONLY_FOR_PRES_BOX                         92
#define PRS_NAME_OF_THE_SCHEM_TO_COMPILE_WITHOUT_SCH  93
#define PRS_VUE_UNIQUE	                              94
#define PRS_NAME_OF_THE_SCHEM_TO_LIST	              95
#define PRS_USE_CREATEFIRST	                      96
#define PRS_USE_PAGEBREAK	                      97
#define PRS_TYPE_NAME_INVALID_FOR_A_BOX	              98
#define PRS_NOT_ALLOWED_IN_A_POSITION	              99
#define PRS_UNKNOWN_MESSAGE	                     100
#define PRS_CANNOT_WRITE	                     101
#define PRS_ONLY_FOR_ATTRIBUTES	                     102

#define PRS_MSG_MAX		                     103
