/*
 *
 *  (c) COPYRIGHT INRIA, 1996.
 *  Please first read the full copyright statement in file COPYRIGHT.
 *
 */
 
#define INTERMEDIATE_SYMBOL	               0  
#define STRUCT_SCHEM_DOES_NOT_MATCH	       1 
#define WORD_SIZE_OVERFLOW	               2
#define MAX_VIEWS_OVERFLOW	               3
#define MAX_COUNTERS_OVERFLOW	               4
#define UNDECLARED_IDENTIFIER	               5
#define MAX_CONSTANTS_OVERFLOW	               6
#define MAX_CHAR_STRING_SIZE_OVERFLOW	       7
#define MAX_VARIABLES_OVERFLOW	               8
#define MAX_BOXES_OVERFLOW	               9
#define MAX_FUNCTIONS_IN_A_VARIABLE_OVERFLOW  10
#define NOT_AN_ASSOC_ELEM	              11
#define VALID_ONLY_FOR_REFS	              12
#define MAX_LINE_SIZE_OVERFLOW	              13
#define NO_SUCH__ATTR	                      14
#define INVALID_ATTR_VALUE	              15
#define UNKNOWN_TYPE	                      16
#define MAX_POSITIONS_OVERFLOW	              17
#define MAX_AFTER_DIGITS_OVERFLOW	      18
#define INAPPROPRIATE_RULE_FOR_A_TYPE	      19
#define UNDEFINED_BOX	                      20
#define CANT_INHERIT_FROM_PREVIOUS	      21
#define ONLY_ONE_PAGE_RULE	              22
#define CANT_INHERIT_FROM_ENCLOSED	      23
#define UNSUPPORTED_IN_THIS_VERSION	      24
#define FORBIDDEN_IN_DEFAULT_RULES	      25
#define DEFAULT_RULE_MISSING	              26
#define RULE_ALREADY_DEFINED	              27
#define ONLY_ENCLOSED_AND_ARE_ALLOWED	      28
#define BAD_DIM_RULE	                      29
#define MAX_COLUMNS_OVERFLOW	              30
#define CANT_REDECLARE_NAME	              31
#define RULE_FORBIDDEN_IN_A_VIEW	      32
#define MAX_OPS_ON_A_COUNTER_OVERFLOW	      33
#define FORBIDDEN_CONDITION	              34
#define FORBIDDEN_CREA_RULE	              35
#define MISSING_VERTIC_POS_IN_THE_PAGE	      36
#define INVALID_VERTIC_POS_IN_PAGE	      37
#define BAD_HEIGHT_RULE	                      38
#define BAD_WIDTH_RULE	                      39
#define MISSING_REF_TO_ELEM	              40
#define VERTIC_DIST_ISNT_CONSTANT	      41
#define MISSING_STRUCT_SCHEM	              42
#define PRS_INVALID_RULE_FOR_ROOT_ELEM	      43
#define BAD_RULE_FOR_A_TERMINAL_ELEM	      44
#define FORBIDDEN_IN_THE_MAIN_VIEW	      45
#define BAD_VERTPOS_RULE	              46
#define BAD_HORIZPOS_RULE	              47
#define TWO_DIFFERENT_PAGE_NUMBERS	      48
#define BAD_CHARACTER	                      49
#define FORDBIDDEN_IN_HEIGHT_AND_WIDTH	      50
#define BROKEN_RULE	              51
#define MAX_CASES_IN_ATTR_OVERFLOW	      52
#define ONLY_ONE_EXPORT_VIEW_ALLOWED	      53
#define CANT_USE_IF_NOT_A_REF_ATTR	      54
#define CANT_REDEFINE	                      55
#define BAD_ATTR_TYPE	                      56
#define BAD_UNIT_FOR_AN_ATTR	              57
#define NO_DECIMAL_PART_AFTER_AN_ATTR	      58
#define INVALID_LOWER_BOUND	              59
#define USES_DIFFERENT_PAGE_COUNTERS	      60
#define ASSOC_ELEMS_ONLY	              61
#define MAX_VIEWS_TO_BE_PRINTED_OVERFLOW      62
#define NOT_AN_ATTR_FOR_THE_ROOT_ELEM	      63
#define UNUSED_BOX	                      64
#define FORBIDDEN_FOR_THIS_TYPE_OF_ATTR	      65
#define NOT_A_NUMERICAL_ATTR	              66
#define NO_MORE_MEM_LEFT	              67
#define BAD_COUNTER_VALUE	              68
#define ONLY_ONE_CONTENT_RULE_ALLOWED	      69
#define BAD_CONTENT_RULE	              70
#define FORBIDDEN_OUTSIDE_OF_MAIN_VIEW 	      71
#define BAD_USE_OF_KEYWORD_FORWARD	      72
#define MAX_MANY_TRANSMIT_RULES_FOR_ELEMS_OVERFLOW   73 
#define ELEM_HAS_A_TRANSMIT_RULE	      74
#define FORBIDDEN_IN_A_PRES_BOX	              75
#define MAX_TRANSMIT_RULES_FOR_COUNTER_OVERFLOW      76
#define NOT_AN_INCLUDED_DOC	              77
#define UNKNOWN_FILE	                      78
#define FORBIDDEN_IN_A_REF                    79
#define AUTHORIZED_ONLY_FOR_BOXES_AND_REFS    80
#define ONLY_ONE_COPY_CONTENT_RULE            81
#define CANT_LOAD_SCHEMA                      82
#define NOT_FOR_PRES_BOX                      83
#define AUTHORIZED_ONLY_FOR_EXT_REFS          84
#define REDEFINITION_OF_CONTENT               85
#define MISSING_FIRST_SECOND                  86
#define NOT_A_PAIR                            87
#define MISSING_PATTERN                       88
#define ONLY_CONDITION_WITHIN	              89
#define MISSING_COLOR                         90
#define CANT_USE_RULE_FOR_A_CHOICE            91
#define VALID_ONLY_FOR_PRES_BOX               92
#define SINGLE_VIEW	                      93
#define INVALID_FILE			      94
#define CPP_NOT_FOUND                         95
#define USE_CREATEFIRST	                      96
#define USE_PAGEBREAK	                      97
#define CANT_USE_TYPE_NAME_FOR_A_BOX	      98
#define FORBIDDEN_IN_A_POSITION	              99

#define WRITE_ERROR	                     101
#define VALID_ONLY_FOR_ATTRIBUTES	     102
#define PRS_MSG_MAX		             103

