/*
 *
 *  (c) COPYRIGHT INRIA, 1996.
 *  Please first read the full copyright statement in file COPYRIGHT.
 *
 */
 
#define INTERMEDIATE_SYMBOL	            	 0
#define CANT_READ_STRUCT_SCHEM	    	         1
#define STRUCT_SCHEM_DOES_NOT_MATCH	    	 2
#define MAX_LINE_SIZE_OVERFLOW	            	 3
#define MAX_NAME_SIZE_OVERFLOW	            	 4
#define NO_SPACE_LEFT_IN_TRANSLATION_TABLE	 5
#define MAX_STRING_SIZE_OVERFLOW	         6
#define CANT_RESPECIFY_TRANSLATION   	         7
#define INVALID_NAME_REDECLARATION	    	 8
#define MAX_POSSIBLE_BUFFERS_OVERFLOW	         9
#define CANT_USE_MORE_THAN_ONE_PICTURE_BUFFER 	10
#define MAX_POSSIBLE_CONSTANTS_OVERFLOW	        11
#define MAX_CONSTANT_BUFFER_OVERFLOW	   	12
#define MAX_POSSIBLE_COUNTERS_OVERFLOW	 	13
#define BAD_TYPE			        14
#define MAX_POSSIBLE_VARIABLES_OVERFLOW		15
#define UNDECLARED_COUNTER		        16
#define UNDECLARED_CONSTANT		        17
#define UNDECLARED_BUFFER			18
#define MAX_POSSIBLE_ELEMS_IN_VARIABLE_OVERFLOW	19
#define BAD_ATTR			        20
#define BAD_ATTR_VALUE			        21
#define VALID_ONLY_FOR_A_DIFFERENT_STRUCT_SCHEM	22
#define VALID_ONLY_FOR_THE_ROOT_ELEM		23
#define FOR_PART_MISSING			24
#define ONLY_ONE_CHARACTER			25
#define VALID_ONLY_FOR_PARAMETERS		26
#define VALID_ONLY_FOR_REFS			27
#define MUST_BE_UNCONDITIONAL		        28
#define MAX_POSSIBLE_TEXTTRANSLATE_OVERFLOW	29
#define CANT_REDEFINE_ALPHABET		        30
#define MAX_POSSIBLE_CASES_FOR_ATTR_OVERFLOW	31
#define RULES_ALREADY_EXIST_FOR_THAT_ATTR	32
#define RULES_ALREADY_EXIST_FOR_THAT_VALUE	33
#define EXPECTING_A_NUMERICAL_ATTR		34
#define BAD_LIMITS			        35
#define NOT_A_TEXTUAL_ATTR			36
#define REF_ATTR_NOT_ALLOWED		        37
#define VALID_ONLY_FOR_TEXT_UNITS		38
#define UNKNOWN_VARIABLE		        39
#define NOT_AN_ATTR_FOR_THE_ROOT_ELEM	        40
#define TOO_MANY_CONDITIONS			41
#define ONLY_IN_PRES_PART			42
#define MAX_POSSIBLE_CASES_FOR_PRES_OVERFLOW	43
#define FORBIDDEN_IN_PRES_PART		        44
#define OUT_OF_MEMORY			        45
#define VALID_ONLY_FOR_PAGES			46
#define CANT_LOAD_STRUCT_SCHEM	                47
#define MISSING_FILE 			        48
#define INVALID_FILE 			        49
#define NO_SPACE_LEFT_IN_RULES_TABLE		50
#define BAD_COUNTER			        51
#define CANT_REDEFINE			        52
#define MISSING_FIRST_SECOND		        53
#define NOT_A_PAIR				54
#define PATTERN_NOT_FOUND			55
#define CANT_WRITE			        56
#define MISSING_COLOR			        57
#define ONLY_FOR_ELEMS 			        58
#define CPP_NOT_FOUND			        59
#define ONLY_FOR_ATTRS 			        60
#define TRA_MSG_MAX				60
