
#font script 1-17 iso, then unicode,symbol,stix...;
#1 = serif;normale face;bold face;italic face  
#2 = sans-serif;normale face;bold face;italic face  
#3 = monospace;normale face;bold face;italic face  
#4 = cursive;normale face;bold face;italic face  
#5 = fantasy;normale face;bold face;italic face  


1;#Latin1 (West European)
1;1=/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman.ttf;2=/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Bold.ttf;3=/usr/share/fonts/truetype/msttcorefonts/Times_New_Roman_Italic.ttf;
2;1=/usr/share/fonts/truetype/msttcorefonts/Arial.ttf;2=/usr/share/fonts/truetype/msttcorefonts/Arial_Bold.ttf;3=/usr/share/fonts/truetype/msttcorefonts/Arial_Italic.ttf;
3;1=/usr/share/fonts/truetype/msttcorefonts/Courier_New.ttf;2=/usr/share/fonts/truetype/msttcorefonts/Courier_New_Bold.ttf;3=/usr/share/fonts/truetype/msttcorefonts/Courier_New_Italic.ttf;


2;#Latin2 (East European)


3;#Latin3 (South European)


4;#Latin4 (North European)


5;#Cyrillic


6;#Arabic


7;#Greek


8;#Hebrew


9;#Latin5 (Turkish)


10;#Latin6 (Nordic)


20;#Symbols (...)


21;#esstix (...)


0;#Unicode (.or ... JAPANESe)
