/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void TtaShowWindow ( int window_id,
                            bool show );
extern int TtaMakeWindow ( void );
extern int TtaMakeFrame ( Document doc,
                          int view,
                          const char * doc_name,
                          int width,
                          int height,
                          int * volume );
extern ThotBool TtaAttachFrame ( int frame_id,
                                 int window_id,
                                 int page_id );
extern ThotBool TtaDetachFrame ( int frame_id,
                                 int window_id );
extern int TtaGetFreePageId ( int window_id );
extern int TtaMakePanel ( const char * panel_title );
extern int TtaAttachPanel ( int window_id );
extern ThotBool TtaDetachPanel ( int panel_id,
                                 int window_id );
extern ThotBool TtaFrameIsActive ( int frame_id );

#else /* __STDC__ */

extern void TtaShowWindow ( int window_id,
                              bool show );
extern int TtaMakeWindow ( void );
extern int TtaMakeFrame ( Document doc,
                            int view,
                            const char * doc_name,
                            int width,
                            int height,
                            int * volume );
extern ThotBool TtaAttachFrame ( int frame_id,
                                   int window_id,
                                   int page_id );
extern ThotBool TtaDetachFrame ( int frame_id,
                                   int window_id );
extern int TtaGetFreePageId ( int window_id );
extern int TtaMakePanel ( const char * panel_title );
extern int TtaAttachPanel ( int window_id );
extern ThotBool TtaDetachPanel ( int panel_id,
                                   int window_id );
extern ThotBool TtaFrameIsActive ( int frame_id );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
