/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void TtaShowWindow ( int window_id,
                            ThotBool show );
extern int TtaMakeWindow ( int x,
                           int y,
                           int w,
                           int h,
                           int kind,
                           int parent_window_id );
extern void TtaMakeWindowMenuBar ( int window_id );
extern void TtaInitMenuItemStats ( int doc_id );
extern void TtaInitTopMenuStats ( int doc_id );
extern void TtaRefreshTopMenuStats ( int doc_id,
                                     int menu_id );
extern void TtaRefreshMenuItemStats ( int doc_id,
                                      void * context,
                                      int menu_item_id );
extern void TtaToggleLogError ( Document doc_id,
                                ThotBool enable );
extern void TtaSetLockButton ( Document doc_id,
                               int status );
extern int TtaMakeFrame ( const char * schema_name,
                          int schView,
                          Document doc_id,
                          const char * doc_name,
                          int width,
                          int height,
                          int * volume,
                          const char * viewName,
                          int window_id,
                          int page_id,
                          int page_position );
extern ThotBool TtaMakePage ( int window_id,
                              int page_id,
                              Document doc );
extern int TtaGetIconIndex ( const char * filename );
extern void TtaSetPageIcon ( Document doc,
                             View view,
                             char *iconpath );
extern ThotBool TtaAttachFrame ( int frame_id,
                                 int window_id,
                                 int page_id,
                                 int position,
                                 int split );
extern void TtaRefreshActiveFrame ( void );
extern ThotBool TtaDetachFrame ( int frame_id );
extern ThotBool TtaDestroyFrame ( int frame_id );
extern void TtaCleanUpWindow ( int window_id );
extern ThotBool TtaClosePage ( int window_id,
                               int page_id );
extern ThotBool TtaCloseAllPageButThis ( int window_id,
                                         int page_id );
extern int TtaGetActiveWindowId ( void );
extern int TtaGetFreePageId ( int window_id );
extern int TtaGetHelpWindowId ( void );
extern int TtaGetAnnotWindowId ( void );
extern int TtaGetFreeWindowId ( void );
extern int TtaGetDocumentWindowId ( Document doc_id,
                                    int schView );
extern ThotBool TtaUniqueTabInWindow ( Document doc_id );
extern void TtaGetDocumentPageId ( Document doc_id,
                                   int schView,
                                   int * page_id,
                                   int * page_position );
extern int TtaGetFrameDocumentId ( int frame_id );
extern int TtaGetFrameWindowParentId ( int frame_id );
extern int TtaGetFrameId ( int window_id,
                           int page_id,
                           int position );
extern void TtaCloseWindow ( int window_id );
extern void TtaEmptyURLBar ( int window_id );
extern int TtaGetWindowNumber ( void );
extern ThotBool TtaFrameIsClosed ( int frame_id );
extern void TtaSetURLBar ( int frame_id,
                           const char * listUrl,
                           void (* procedure)() );
extern void TtaSwitchPanelButton ( Document doc,
                                   View view,
                                   int panel_type,
                                   int button_id,
                                   ThotBool value );
extern ThotBool TtaRegisterWidgetWX ( int ref,
                                      void * p_widget );
extern void TtaToggleOnOffSidePanel ( int frame_id );
extern void TtaToggleToolbar ( int frame_id,
                               int toolbar_id );
extern void TtaSplitViewHorizontally ( int frame_id );
extern void TtaSplitViewVertically ( int frame_id );
extern void TtaDoPostFrameCreation ( int frame_id );
extern void TtaToggleOnOffFullScreen ( int frame_id );
extern ThotBool TtaGetFullScreenState ( int frame_id );
extern void TtaRegisterOpenURLCallback ( void (*callback) (void *) );
extern void TtaCheckLostFocus ( void );
extern void TtaRedirectFocus ( void );
extern ThotBool TtaFrameIsShown ( int frame );
extern void TtaSendStatsInfo ( void );
extern void TtaResetEnumContextMenu ( void );
extern void TtaSetEnumContextMenu ( int res );
extern int TtaGetEnumContextMenu ( void );

#else /* __STDC__ */

extern void TtaShowWindow ( int window_id,
                              ThotBool show );
extern int TtaMakeWindow ( int x,
                             int y,
                             int w,
                             int h,
                             int kind,
                             int parent_window_id );
extern void TtaMakeWindowMenuBar ( int window_id );
extern void TtaInitMenuItemStats ( int doc_id );
extern void TtaInitTopMenuStats ( int doc_id );
extern void TtaRefreshTopMenuStats ( int doc_id,
                                       int menu_id );
extern void TtaRefreshMenuItemStats ( int doc_id,
                                        void * context,
                                        int menu_item_id );
extern void TtaToggleLogError ( Document doc_id,
                                  ThotBool enable );
extern void TtaSetLockButton ( Document doc_id,
                                 int status );
extern int TtaMakeFrame ( const char * schema_name,
                            int schView,
                            Document doc_id,
                            const char * doc_name,
                            int width,
                            int height,
                            int * volume,
                            const char * viewName,
                            int window_id,
                            int page_id,
                            int page_position );
extern ThotBool TtaMakePage ( int window_id,
                                int page_id,
                                Document doc );
extern int TtaGetIconIndex ( const char * filename );
extern void TtaSetPageIcon ( Document doc,
                               View view,
                               char *iconpath );
extern ThotBool TtaAttachFrame ( int frame_id,
                                   int window_id,
                                   int page_id,
                                   int position,
                                   int split );
extern void TtaRefreshActiveFrame ( void );
extern ThotBool TtaDetachFrame ( int frame_id );
extern ThotBool TtaDestroyFrame ( int frame_id );
extern void TtaCleanUpWindow ( int window_id );
extern ThotBool TtaClosePage ( int window_id,
                                 int page_id );
extern ThotBool TtaCloseAllPageButThis ( int window_id,
                                           int page_id );
extern int TtaGetActiveWindowId ( void );
extern int TtaGetFreePageId ( int window_id );
extern int TtaGetHelpWindowId ( void );
extern int TtaGetAnnotWindowId ( void );
extern int TtaGetFreeWindowId ( void );
extern int TtaGetDocumentWindowId ( Document doc_id,
                                      int schView );
extern ThotBool TtaUniqueTabInWindow ( Document doc_id );
extern void TtaGetDocumentPageId ( Document doc_id,
                                     int schView,
                                     int * page_id,
                                     int * page_position );
extern int TtaGetFrameDocumentId ( int frame_id );
extern int TtaGetFrameWindowParentId ( int frame_id );
extern int TtaGetFrameId ( int window_id,
                             int page_id,
                             int position );
extern void TtaCloseWindow ( int window_id );
extern void TtaEmptyURLBar ( int window_id );
extern int TtaGetWindowNumber ( void );
extern ThotBool TtaFrameIsClosed ( int frame_id );
extern void TtaSetURLBar ( int frame_id,
                             const char * listUrl,
                             void (* procedure)() );
extern void TtaSwitchPanelButton ( Document doc,
                                     View view,
                                     int panel_type,
                                     int button_id,
                                     ThotBool value );
extern ThotBool TtaRegisterWidgetWX ( int ref,
                                        void * p_widget );
extern void TtaToggleOnOffSidePanel ( int frame_id );
extern void TtaToggleToolbar ( int frame_id,
                                 int toolbar_id );
extern void TtaSplitViewHorizontally ( int frame_id );
extern void TtaSplitViewVertically ( int frame_id );
extern void TtaDoPostFrameCreation ( int frame_id );
extern void TtaToggleOnOffFullScreen ( int frame_id );
extern ThotBool TtaGetFullScreenState ( int frame_id );
extern void TtaRegisterOpenURLCallback ( void (*callback) (void *) );
extern void TtaCheckLostFocus ( void );
extern void TtaRedirectFocus ( void );
extern ThotBool TtaFrameIsShown ( int frame );
extern void TtaSendStatsInfo ( void );
extern void TtaResetEnumContextMenu ( void );
extern void TtaSetEnumContextMenu ( int res );
extern int TtaGetEnumContextMenu ( void );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
