/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void TtaShowWindow ( int window_id,
                            ThotBool show );
extern int TtaMakeWindow ( int x,
                           int y,
                           int w,
                           int h,
                           int kind,
                           int parent_window_id );
extern int TtaMakeFrame ( const char * schema_name,
                          int schView,
                          Document doc_id,
                          const char * doc_name,
                          int width,
                          int height,
                          int * volume );
extern ThotBool TtaAttachFrame ( int frame_id,
                                 int window_id,
                                 int page_id,
                                 int position );
extern ThotBool TtaDetachFrame ( int frame_id );
extern ThotBool TtaDestroyFrame ( int frame_id );
extern void TtaCleanUpWindow ( int window_id );
extern ThotBool TtaClosePage ( int window_id,
                               int page_id );
extern int TtaGetActiveWindowId ( void );
extern int TtaGetFreePageId ( int window_id );
extern int TtaGetFreeWindowId ( void );
extern int TtaGetDocumentWindowId ( Document doc_id,
                                    int schView );
extern void TtaGetDocumentPageId ( Document doc_id,
                                   int schView,
                                   int * page_id,
                                   int * page_position );
extern int TtaGetFrameDocumentId ( int frame_id );
extern int TtaGetFrameWindowParentId ( int frame_id );
extern int TtaGetFrameId ( int window_id,
                           int page_id,
                           int position );
extern void TtaCloseWindow ( int window_id );
extern int TtaGetWindowNumber ( void );
extern int TtaMakePanel ( const char * panel_title );
extern int TtaAttachPanel ( int window_id );
extern ThotBool TtaDetachPanel ( int panel_id,
                                 int window_id );
extern ThotBool TtaFrameIsActive ( int frame_id );
extern ThotBool TtaFrameIsClosed ( int frame_id );
extern void TtaInitializeURLBar ( int frame_id,
                                  const char * label,
                                  ThotBool editable,
                                  void (* procedure)() );
extern void TtaSetURLBar ( int frame_id,
                           const char * listUrl );
extern void APP_Callback_URLActivate ( int frame_id,
                                       const char *text );
extern void APP_Callback_ToolBarButtonActivate ( int frame_id,
                                                 int button_id );
extern int TtaAddToolBarButton ( int window_id,
                                 ThotIcon picture,
                                 char * tooltip,
                                 char * functionName,
                                 void (*procedure) (),
                                 ThotBool status );
extern ThotBool TtaRegisterWidgetWX ( int ref,
                                      void * p_widget );

#else /* __STDC__ */

extern void TtaShowWindow ( int window_id,
                              ThotBool show );
extern int TtaMakeWindow ( int x,
                             int y,
                             int w,
                             int h,
                             int kind,
                             int parent_window_id );
extern int TtaMakeFrame ( const char * schema_name,
                            int schView,
                            Document doc_id,
                            const char * doc_name,
                            int width,
                            int height,
                            int * volume );
extern ThotBool TtaAttachFrame ( int frame_id,
                                   int window_id,
                                   int page_id,
                                   int position );
extern ThotBool TtaDetachFrame ( int frame_id );
extern ThotBool TtaDestroyFrame ( int frame_id );
extern void TtaCleanUpWindow ( int window_id );
extern ThotBool TtaClosePage ( int window_id,
                                 int page_id );
extern int TtaGetActiveWindowId ( void );
extern int TtaGetFreePageId ( int window_id );
extern int TtaGetFreeWindowId ( void );
extern int TtaGetDocumentWindowId ( Document doc_id,
                                      int schView );
extern void TtaGetDocumentPageId ( Document doc_id,
                                     int schView,
                                     int * page_id,
                                     int * page_position );
extern int TtaGetFrameDocumentId ( int frame_id );
extern int TtaGetFrameWindowParentId ( int frame_id );
extern int TtaGetFrameId ( int window_id,
                             int page_id,
                             int position );
extern void TtaCloseWindow ( int window_id );
extern int TtaGetWindowNumber ( void );
extern int TtaMakePanel ( const char * panel_title );
extern int TtaAttachPanel ( int window_id );
extern ThotBool TtaDetachPanel ( int panel_id,
                                   int window_id );
extern ThotBool TtaFrameIsActive ( int frame_id );
extern ThotBool TtaFrameIsClosed ( int frame_id );
extern void TtaInitializeURLBar ( int frame_id,
                                    const char * label,
                                    ThotBool editable,
                                    void (* procedure)() );
extern void TtaSetURLBar ( int frame_id,
                             const char * listUrl );
extern void APP_Callback_URLActivate ( int frame_id,
                                         const char *text );
extern void APP_Callback_ToolBarButtonActivate ( int frame_id,
                                                   int button_id );
extern int TtaAddToolBarButton ( int window_id,
                                   ThotIcon picture,
                                   char * tooltip,
                                   char * functionName,
                                   void (*procedure) (),
                                   ThotBool status );
extern ThotBool TtaRegisterWidgetWX ( int ref,
                                        void * p_widget );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
