/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void ThotUpdatePalette ( void );
extern void ThotSelectPalette ( int bground,
                                int fground );
extern void ThotGetSelectedElementColor ( void );
extern void TtcGetPaletteColors ( int *fg,
                                  int *bg,
                                  ThotBool palType );

#else /* __STDC__ */

extern void ThotUpdatePalette ( void );
extern void ThotSelectPalette ( int bground,
                                  int fground );
extern void ThotGetSelectedElementColor ( void );
extern void TtcGetPaletteColors ( int *fg,
                                    int *bg,
                                    ThotBool palType );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
