/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void DisplayConfirmMessage ( const char *text );
extern void DisplayMessage ( char *text,
                             int msgType );
extern void TtaError ( int errorCode );
extern void CompilerMessage ( int index,
                              int origin,
                              int level,
                              int msgCode,
                              unsigned char *inputline,
                              int lineNum );
extern void CompilerMessageString ( int index,
                                    int origin,
                                    int level,
                                    int msgCode,
                                    char *inputline,
                                    int lineNum,
                                    char *string );

#else /* __STDC__ */

extern void DisplayConfirmMessage ( const char *text );
extern void DisplayMessage ( char *text,
                               int msgType );
extern void TtaError ( int errorCode );
extern void CompilerMessage ( int index,
                                int origin,
                                int level,
                                int msgCode,
                                unsigned char *inputline,
                                int lineNum );
extern void CompilerMessageString ( int index,
                                      int origin,
                                      int level,
                                      int msgCode,
                                      char *inputline,
                                      int lineNum,
                                      char *string );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
