/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void ConfigInit ( void );
extern void TtaConfigReadConfigFiles ( STRING aSchemaPath );
extern int ConfigMakeDocTypeMenu ( STRING BufMenu,
                                   int *lgmenu,
                                   boolean doc );
extern void TtaConfigSSchemaExternalName ( STRING nameUser,
                                           STRING nameSchema,
                                           int Typ );
extern void ConfigSSchemaInternalName ( STRING nameUser,
                                        STRING nameSchema,
                                        boolean Doc );
extern int ConfigMakeMenuPres ( STRING schema,
                                STRING BufMenu );
extern void ConfigGetPSchemaName ( int choix,
                                   STRING schpres );
extern int ConfigMakeImportMenu ( STRING BufMenu );
extern int ConfigMakeMenuExport ( STRING schema,
                                  STRING BufMenu );
extern void ConfigGetExportSchemaName ( int choix,
                                        STRING schtrad );
extern void ConfigTranslateSSchema ( PtrSSchema pSS );
extern boolean ConfigDefaultPSchema ( STRING schstr,
                                      STRING schpres );
extern void ConfigKeyboard ( int *x,
                             int *y );
extern void ConfigOpenFirstViews ( PtrDocument pDoc );
extern void ConfigGetViewGeometry ( PtrDocument pDoc,
                                    STRING view,
                                    int *x,
                                    int *y,
                                    int *width,
                                    int *height );
extern void TtaGetViewWH ( Document doc,
                           int view,
                           int *width,
                           int *height );
extern void TtaGetViewGeometryRegistry ( Document document,
                                         STRING name,
                                         int *x,
                                         int *y,
                                         int *width,
                                         int *height );
extern void TtaGetViewGeometry ( Document document,
                                 STRING name,
                                 int *x,
                                 int *y,
                                 int *width,
                                 int *height );
extern void TtaGetViewGeometryMM ( Document document,
                                   STRING name,
                                   int *x,
                                   int *y,
                                   int *width,
                                   int *height );
extern boolean ConfigGetPSchemaNature ( PtrSSchema pSS,
                                        STRING nameNature,
                                        STRING presNature );
extern void ConfigGetPresentationOption ( PtrSSchema pSS,
                                          STRING optionName,
                                          STRING optionValue );
extern void ConfigGetPSchemaForPageSize ( PtrSSchema pSS,
                                          STRING pageSize,
                                          STRING schemaName );
extern int MakeMenuPattern ( STRING BufMenu,
                             int LgMax );
extern int MakeMenuColor ( STRING BufMenu,
                           int LgMax );
extern boolean ConfigDefaultTypoSchema ( PtrSSchema pSS,
                                         STRING nameNature,
                                         STRING schtypo );

#else /* __STDC__ */

extern void ConfigInit (/* void */);
extern void TtaConfigReadConfigFiles (/* STRING aSchemaPath */);
extern int ConfigMakeDocTypeMenu (/* STRING BufMenu,
                                     int *lgmenu,
                                     boolean doc */);
extern void TtaConfigSSchemaExternalName (/* STRING nameUser,
                                             STRING nameSchema,
                                             int Typ */);
extern void ConfigSSchemaInternalName (/* STRING nameUser,
                                          STRING nameSchema,
                                          boolean Doc */);
extern int ConfigMakeMenuPres (/* STRING schema,
                                  STRING BufMenu */);
extern void ConfigGetPSchemaName (/* int choix,
                                     STRING schpres */);
extern int ConfigMakeImportMenu (/* STRING BufMenu */);
extern int ConfigMakeMenuExport (/* STRING schema,
                                    STRING BufMenu */);
extern void ConfigGetExportSchemaName (/* int choix,
                                          STRING schtrad */);
extern void ConfigTranslateSSchema (/* PtrSSchema pSS */);
extern boolean ConfigDefaultPSchema (/* STRING schstr,
                                        STRING schpres */);
extern void ConfigKeyboard (/* int *x,
                               int *y */);
extern void ConfigOpenFirstViews (/* PtrDocument pDoc */);
extern void ConfigGetViewGeometry (/* PtrDocument pDoc,
                                      STRING view,
                                      int *x,
                                      int *y,
                                      int *width,
                                      int *height */);
extern void TtaGetViewWH (/* Document doc,
                             int view,
                             int *width,
                             int *height */);
extern void TtaGetViewGeometryRegistry (/* Document document,
                                           STRING name,
                                           int *x,
                                           int *y,
                                           int *width,
                                           int *height */);
extern void TtaGetViewGeometry (/* Document document,
                                   STRING name,
                                   int *x,
                                   int *y,
                                   int *width,
                                   int *height */);
extern void TtaGetViewGeometryMM (/* Document document,
                                     STRING name,
                                     int *x,
                                     int *y,
                                     int *width,
                                     int *height */);
extern boolean ConfigGetPSchemaNature (/* PtrSSchema pSS,
                                          STRING nameNature,
                                          STRING presNature */);
extern void ConfigGetPresentationOption (/* PtrSSchema pSS,
                                            STRING optionName,
                                            STRING optionValue */);
extern void ConfigGetPSchemaForPageSize (/* PtrSSchema pSS,
                                            STRING pageSize,
                                            STRING schemaName */);
extern int MakeMenuPattern (/* STRING BufMenu,
                               int LgMax */);
extern int MakeMenuColor (/* STRING BufMenu,
                             int LgMax */);
extern boolean ConfigDefaultTypoSchema (/* PtrSSchema pSS,
                                           STRING nameNature,
                                           STRING schtypo */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
