/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern PtrTextBuffer NewTextBuffer ( PtrTextBuffer pBuf );
extern void CreateTextBuffer ( PtrElement pEl );
extern void DeleteTextBuffer ( PtrTextBuffer * pBuf );
extern void SplitTextElement ( PtrElement pEl,
                               int rank,
                               PtrDocument pDoc,
                               boolean withAppEvent,
                               PtrElement *pSecondPart );
extern boolean MergeTextElements ( PtrElement pEl,
                                   PtrElement * pFreeEl,
                                   PtrDocument pDoc,
                                   boolean withAppEvent,
                                   boolean removeAbsBox );
extern PtrTextBuffer CopyText ( PtrTextBuffer pBuf,
                                PtrElement pEl );
extern boolean StringAndTextEqual ( char *String,
                                    PtrTextBuffer pBuf );
extern boolean TextsEqual ( PtrTextBuffer pBuf1,
                            PtrTextBuffer pBuf2 );
extern void CopyTextToText ( PtrTextBuffer pSrceBuf,
                             PtrTextBuffer pCopyBuf,
                             int *len );
extern void CopyStringToText ( char *srceStrn,
                               PtrTextBuffer pCopyBuf,
                               int *LgCopiee );
extern void CopyTextToString ( PtrTextBuffer pSrceBuf,
                               char *pStrCpy,
                               int *len );
extern void ClearText ( PtrTextBuffer pBuf );
extern void AddPointInPolyline ( PtrTextBuffer firstBuffer,
                                 int rank,
                                 int x,
                                 int y );
extern void DeletePointInPolyline ( PtrTextBuffer * firstBuffer,
                                    int rank );
extern void ModifyPointInPolyline ( PtrTextBuffer firstBuffer,
                                    int rank,
                                    int x,
                                    int y );

#else /* __STDC__ */

extern PtrTextBuffer NewTextBuffer (/* PtrTextBuffer pBuf */);
extern void CreateTextBuffer (/* PtrElement pEl */);
extern void DeleteTextBuffer (/* PtrTextBuffer * pBuf */);
extern void SplitTextElement (/* PtrElement pEl,
                                 int rank,
                                 PtrDocument pDoc,
                                 boolean withAppEvent,
                                 PtrElement *pSecondPart */);
extern boolean MergeTextElements (/* PtrElement pEl,
                                     PtrElement * pFreeEl,
                                     PtrDocument pDoc,
                                     boolean withAppEvent,
                                     boolean removeAbsBox */);
extern PtrTextBuffer CopyText (/* PtrTextBuffer pBuf,
                                  PtrElement pEl */);
extern boolean StringAndTextEqual (/* char *String,
                                      PtrTextBuffer pBuf */);
extern boolean TextsEqual (/* PtrTextBuffer pBuf1,
                              PtrTextBuffer pBuf2 */);
extern void CopyTextToText (/* PtrTextBuffer pSrceBuf,
                               PtrTextBuffer pCopyBuf,
                               int *len */);
extern void CopyStringToText (/* char *srceStrn,
                                 PtrTextBuffer pCopyBuf,
                                 int *LgCopiee */);
extern void CopyTextToString (/* PtrTextBuffer pSrceBuf,
                                 char *pStrCpy,
                                 int *len */);
extern void ClearText (/* PtrTextBuffer pBuf */);
extern void AddPointInPolyline (/* PtrTextBuffer firstBuffer,
                                   int rank,
                                   int x,
                                   int y */);
extern void DeletePointInPolyline (/* PtrTextBuffer * firstBuffer,
                                      int rank */);
extern void ModifyPointInPolyline (/* PtrTextBuffer firstBuffer,
                                      int rank,
                                      int x,
                                      int y */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
