/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void CallbackConfirmMenu ( int ref,
                                  int typeData,
                                  STRING data );
extern void CallbackNewDocMenu ( int ref,
                                 int typeData,
                                 char* data );
extern void TtcCreateDocument ( Document document,
                                View view );

#else /* __STDC__ */

extern void CallbackConfirmMenu (/* int ref,
                                    int typeData,
                                    STRING data */);
extern void CallbackNewDocMenu (/* int ref,
                                   int typeData,
                                   char* data */);
extern void TtcCreateDocument (/* Document document,
                                  View view */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
