/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern boolean AskForNew_RemplRefer ( boolean * Creer,
                                      Name NomType );
extern void RetMenuAskForNew ( int Val );
extern void CreeEtActiveMenuChoix ( char *BufMenu,
                                    Name TitreMenu,
                                    int nbentree,
                                    boolean NatureChoice );
extern void SeparMenuCreeColle ( int *prevmenuind,
                                 int *nbentree,
                                 int *menuind,
                                 char *BufMenu );
extern void CreeEtActiveMenuCreeColle ( int RefMenu,
                                        char *BufMenu,
                                        Name titre,
                                        int nbentree,
                                        char bouton );

#else /* __STDC__ */

extern boolean AskForNew_RemplRefer (/* boolean * Creer,
                                        Name NomType */);
extern void RetMenuAskForNew (/* int Val */);
extern void CreeEtActiveMenuChoix (/* char *BufMenu,
                                      Name TitreMenu,
                                      int nbentree,
                                      boolean NatureChoice */);
extern void SeparMenuCreeColle (/* int *prevmenuind,
                                   int *nbentree,
                                   int *menuind,
                                   char *BufMenu */);
extern void CreeEtActiveMenuCreeColle (/* int RefMenu,
                                          char *BufMenu,
                                          Name titre,
                                          int nbentree,
                                          char bouton */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
