/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void TreateDictionary ( PtrDict dict );
extern int LoadTreatedDict ( PtrDict * pDictionary,
                             Language lang,
                             PtrDocument document,
                             char *dictName,
                             char *dictDirectory,
                             boolean readonly,
                             boolean toCreate );
extern boolean ReloadDictionary ( PtrDict * pDictionary );
extern void Dict_Init ( void );
extern boolean TtaLoadLanguageDictionaries ( Language languageId );
extern boolean TtaLoadTypoDictionaries ( Language languageId );
extern void TtaUnLoadLanguageDictionaries ( Language languageId );
extern void TtaUnLoadTypoDictionaries ( Language languageId );
extern Dictionary TtaGetPrincipalDictionary ( Language languageId );
extern Dictionary TtaGetPrincipalTypoDictionary ( Language languageId );
extern Dictionary TtaGetSecondaryDictionary ( Language languageId );
extern Dictionary TtaGetSecondaryTypoDictionary ( Language languageId );

#else /* __STDC__ */

extern void TreateDictionary (/* PtrDict dict */);
extern int LoadTreatedDict (/* PtrDict * pDictionary,
                               Language lang,
                               PtrDocument document,
                               char *dictName,
                               char *dictDirectory,
                               boolean readonly,
                               boolean toCreate */);
extern boolean ReloadDictionary (/* PtrDict * pDictionary */);
extern void Dict_Init (/* void */);
extern boolean TtaLoadLanguageDictionaries (/* Language languageId */);
extern boolean TtaLoadTypoDictionaries (/* Language languageId */);
extern void TtaUnLoadLanguageDictionaries (/* Language languageId */);
extern void TtaUnLoadTypoDictionaries (/* Language languageId */);
extern Dictionary TtaGetPrincipalDictionary (/* Language languageId */);
extern Dictionary TtaGetPrincipalTypoDictionary (/* Language languageId */);
extern Dictionary TtaGetSecondaryDictionary (/* Language languageId */);
extern Dictionary TtaGetSecondaryTypoDictionary (/* Language languageId */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
