/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern void AfTrame ( PtrBox pBox,
                      int frame,
                      char modele );
extern void PolyTransform ( PtrBox pBox );
extern void AfBoite ( PtrBox pBox,
                      int frame );

#else /* __STDC__ */

extern void AfTrame (/* PtrBox pBox,
                        int frame,
                        char modele */);
extern void PolyTransform (/* PtrBox pBox */);
extern void AfBoite (/* PtrBox pBox,
                        int frame */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
