/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern boolean DrawSelectPre ( NotifyElement * event );
extern void CreateAttributes ( NotifyElement * event );
extern boolean DeleteAnElement ( NotifyElement * event );
extern boolean CreerUneForme ( NotifyElement * event );
extern boolean GraphModify ( NotifyOnValue * event );
extern void ModifyPRule ( NotifyPresentation * event );
extern void CreerUnLien ( NotifyElement * event );
extern boolean DeleteALien ( NotifyElement * event );
extern boolean ModifyAttribute ( NotifyAttribute * event );
extern void ModifyAttributeDim ( NotifyAttribute * event );
extern void ModifyAttributePos ( NotifyAttribute * event );
extern void ModifAttributsRectangle ( NotifyElement * event );
extern void NewDraw ( NotifyElement * event );
extern void DeleteDraw ( NotifyElement * event );

#else /* __STDC__ */

extern boolean DrawSelectPre (/* NotifyElement * event */);
extern void CreateAttributes (/* NotifyElement * event */);
extern boolean DeleteAnElement (/* NotifyElement * event */);
extern boolean CreerUneForme (/* NotifyElement * event */);
extern boolean GraphModify (/* NotifyOnValue * event */);
extern void ModifyPRule (/* NotifyPresentation * event */);
extern void CreerUnLien (/* NotifyElement * event */);
extern boolean DeleteALien (/* NotifyElement * event */);
extern boolean ModifyAttribute (/* NotifyAttribute * event */);
extern void ModifyAttributeDim (/* NotifyAttribute * event */);
extern void ModifyAttributePos (/* NotifyAttribute * event */);
extern void ModifAttributsRectangle (/* NotifyElement * event */);
extern void NewDraw (/* NotifyElement * event */);
extern void DeleteDraw (/* NotifyElement * event */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
