/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern void ObjetsAligner ( char Plan,
                            char Axe,
                            Document Doc );
extern void ObjetsGrouper ( Document Doc );
extern void ObjetsDegrouper ( Document Doc );
extern void ObjetsHorsGroupe ( Document Doc );
extern void ObjetsMemeGroupe ( Document Doc );
extern void ObjetsMemeTaille ( Document Doc );
extern void ObjetsDupliquer ( Document Doc );
extern void ObjetsEquidistants ( Document Doc );
extern void ObjetsModifierPlan ( char Plan,
                                 Document Doc );
extern void CopieVersPalette ( Document Doc );
extern void ResizeGroup ( Document doc,
                          View view );

#else /* __STDC__ */

extern void ObjetsAligner (/* char Plan,
                              char Axe,
                              Document Doc */);
extern void ObjetsGrouper (/* Document Doc */);
extern void ObjetsDegrouper (/* Document Doc */);
extern void ObjetsHorsGroupe (/* Document Doc */);
extern void ObjetsMemeGroupe (/* Document Doc */);
extern void ObjetsMemeTaille (/* Document Doc */);
extern void ObjetsDupliquer (/* Document Doc */);
extern void ObjetsEquidistants (/* Document Doc */);
extern void ObjetsModifierPlan (/* char Plan,
                                   Document Doc */);
extern void CopieVersPalette (/* Document Doc */);
extern void ResizeGroup (/* Document doc,
                            View view */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
