/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotBool TtaReadByte ( BinFile file,
                              char* bval );
extern ThotBool TtaReadWideChar ( BinFile file,
                                  CHAR_T* bval,
                                  CHARSET encoding );
extern ThotBool TtaReadBool ( BinFile file,
                              ThotBool * bval );
extern ThotBool TtaReadShort ( BinFile file,
                               int *sval );
extern ThotBool TtaReadSignedShort ( BinFile file,
                                     int *sval );
extern ThotBool TtaReadInteger ( BinFile file,
                                 int *sval );
extern ThotBool TtaReadName ( BinFile file,
                              CHAR_T* name );
extern BinFile TtaReadOpen ( CONST CHAR_T* filename );
extern void TtaReadClose ( BinFile file );
extern BinFile TtaWriteOpen ( CONST STRING filename );
extern void TtaWriteClose ( BinFile file );
extern ThotBool TtaWriteByte ( BinFile file,
                               char bval );
extern ThotBool TtaWriteWideChar ( BinFile file,
                                   CHAR_T val,
                                   CHARSET encoding );
extern ThotBool TtaWriteShort ( BinFile file,
                                int sval );
extern ThotBool TtaWriteInteger ( BinFile file,
                                  int lval );
extern void TtaWriteDocIdent ( BinFile file,
                               DocumentIdentifier Ident );
extern void TtaReadDocIdent ( BinFile file,
                              DocumentIdentifier * Ident );
extern void CopyDocIdent ( DocumentIdentifier * Dest,
                           DocumentIdentifier Source );
extern ThotBool SameDocIdent ( DocumentIdentifier Ident1,
                               DocumentIdentifier Ident2 );
extern void ClearDocIdent ( DocumentIdentifier * Ident );
extern ThotBool DocIdentIsNull ( DocumentIdentifier Ident );
extern void TtaExtractName ( CHAR_T* text,
                             CHAR_T* aDirectory,
                             CHAR_T* aName );
extern void MakeCompleteName ( CHAR_T* fname,
                               CHAR_T* fext,
                               CHAR_T* directory_list,
                               CHAR_T* completeName,
                               int *length );
extern void GetPictureFileName ( STRING name,
                                 STRING fileName );
extern void FindCompleteName ( CHAR_T* fileName,
                               CHAR_T* extension,
                               PathBuffer directory,
                               PathBuffer completeName,
                               int *length );
extern void GetDocIdent ( DocumentIdentifier* Ident,
                          CHAR_T* docName );
extern void GetDocName ( DocumentIdentifier Ident,
                         CHAR_T* docName );
extern int FileWriteAccess ( STRING fileName );
extern void GetCounterValue ( int number,
                              CounterStyle style,
                              STRING string,
                              int *len );
extern ThotBool TtaMakeDirectory ( CHAR_T* directory );
extern ThotBool TtaCheckDirectory ( CHAR_T* directory );

#else /* __STDC__ */

extern ThotBool TtaReadByte (/* BinFile file,
                                char* bval */);
extern ThotBool TtaReadWideChar (/* BinFile file,
                                    CHAR_T* bval,
                                    CHARSET encoding */);
extern ThotBool TtaReadBool (/* BinFile file,
                                ThotBool * bval */);
extern ThotBool TtaReadShort (/* BinFile file,
                                 int *sval */);
extern ThotBool TtaReadSignedShort (/* BinFile file,
                                       int *sval */);
extern ThotBool TtaReadInteger (/* BinFile file,
                                   int *sval */);
extern ThotBool TtaReadName (/* BinFile file,
                                CHAR_T* name */);
extern BinFile TtaReadOpen (/* CONST CHAR_T* filename */);
extern void TtaReadClose (/* BinFile file */);
extern BinFile TtaWriteOpen (/* CONST STRING filename */);
extern void TtaWriteClose (/* BinFile file */);
extern ThotBool TtaWriteByte (/* BinFile file,
                                 char bval */);
extern ThotBool TtaWriteWideChar (/* BinFile file,
                                     CHAR_T val,
                                     CHARSET encoding */);
extern ThotBool TtaWriteShort (/* BinFile file,
                                  int sval */);
extern ThotBool TtaWriteInteger (/* BinFile file,
                                    int lval */);
extern void TtaWriteDocIdent (/* BinFile file,
                                 DocumentIdentifier Ident */);
extern void TtaReadDocIdent (/* BinFile file,
                                DocumentIdentifier * Ident */);
extern void CopyDocIdent (/* DocumentIdentifier * Dest,
                             DocumentIdentifier Source */);
extern ThotBool SameDocIdent (/* DocumentIdentifier Ident1,
                                 DocumentIdentifier Ident2 */);
extern void ClearDocIdent (/* DocumentIdentifier * Ident */);
extern ThotBool DocIdentIsNull (/* DocumentIdentifier Ident */);
extern void TtaExtractName (/* CHAR_T* text,
                               CHAR_T* aDirectory,
                               CHAR_T* aName */);
extern void MakeCompleteName (/* CHAR_T* fname,
                                 CHAR_T* fext,
                                 CHAR_T* directory_list,
                                 CHAR_T* completeName,
                                 int *length */);
extern void GetPictureFileName (/* STRING name,
                                   STRING fileName */);
extern void FindCompleteName (/* CHAR_T* fileName,
                                 CHAR_T* extension,
                                 PathBuffer directory,
                                 PathBuffer completeName,
                                 int *length */);
extern void GetDocIdent (/* DocumentIdentifier* Ident,
                            CHAR_T* docName */);
extern void GetDocName (/* DocumentIdentifier Ident,
                           CHAR_T* docName */);
extern int FileWriteAccess (/* STRING fileName */);
extern void GetCounterValue (/* int number,
                                CounterStyle style,
                                STRING string,
                                int *len */);
extern ThotBool TtaMakeDirectory (/* CHAR_T* directory */);
extern ThotBool TtaCheckDirectory (/* CHAR_T* directory */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
