/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int NumberOfFonts ( void );
extern int GetCharsCapacity ( int volpixel );
extern int CharacterWidth ( unsigned char c,
                            ptrfont font );
extern int CharacterHeight ( unsigned char c,
                             ptrfont font );
extern int CharacterAscent ( unsigned char c,
                             ptrfont font );
extern int FontAscent ( ptrfont font );
extern int FontHeight ( ptrfont font );
extern int PixelValue ( int val,
                        TypeUnit unit,
                        PtrAbstractBox pAb );
extern int LogicalValue ( int val,
                          TypeUnit unit,
                          PtrAbstractBox pAb );
extern int FontBase ( ptrfont font );
extern int FontRelSize ( int size );
extern int FontPointSize ( int size );
extern ptrfont LoadFont ( char name[100],
                          int toPatch );
extern void FontIdentifier ( char alphabet,
                             char family,
                             int highlight,
                             int size,
                             TypeUnit unit,
                             char r_name[10],
                             char r_nameX[100] );
extern ptrfont ReadFont ( char alphabet,
                          char family,
                          int highlight,
                          int size,
                          TypeUnit unit );
extern ptrfont ThotLoadFont ( char alphabet,
                              char family,
                              int highlight,
                              int size,
                              TypeUnit unit,
                              int frame );
extern void InitDialogueFonts ( char *name );
extern void ThotFreeFont ( int frame );

#else /* __STDC__ */

extern int NumberOfFonts (/* void */);
extern int GetCharsCapacity (/* int volpixel */);
extern int CharacterWidth (/* unsigned char c,
                              ptrfont font */);
extern int CharacterHeight (/* unsigned char c,
                               ptrfont font */);
extern int CharacterAscent (/* unsigned char c,
                               ptrfont font */);
extern int FontAscent (/* ptrfont font */);
extern int FontHeight (/* ptrfont font */);
extern int PixelValue (/* int val,
                          TypeUnit unit,
                          PtrAbstractBox pAb */);
extern int LogicalValue (/* int val,
                            TypeUnit unit,
                            PtrAbstractBox pAb */);
extern int FontBase (/* ptrfont font */);
extern int FontRelSize (/* int size */);
extern int FontPointSize (/* int size */);
extern ptrfont LoadFont (/* char name[100],
                            int toPatch */);
extern void FontIdentifier (/* char alphabet,
                               char family,
                               int highlight,
                               int size,
                               TypeUnit unit,
                               char r_name[10],
                               char r_nameX[100] */);
extern ptrfont ReadFont (/* char alphabet,
                            char family,
                            int highlight,
                            int size,
                            TypeUnit unit */);
extern ptrfont ThotLoadFont (/* char alphabet,
                                char family,
                                int highlight,
                                int size,
                                TypeUnit unit,
                                int frame */);
extern void InitDialogueFonts (/* char *name */);
extern void ThotFreeFont (/* int frame */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
