/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern PtrElement Ind_table ( int num );
extern PtrElement Ind_marquesuivante ( PtrElement pDesc,
                                       PtrElement pMarque );
extern int Ind_creertable ( int numtable,
                            boolean avec_raz );
extern void Ind_remplirtable ( boolean avec_fusion );
extern void Ind_remplirCR ( void );
extern char *Ind_textecle ( int numcle,
                            PtrElement pEl );
extern char *Ind_semantique ( PtrElement pEl );
extern void Ind_inittable ( int num );
extern int Ind_tousdesc ( void );
extern int Ind_touscroise ( void );

#else /* __STDC__ */

extern PtrElement Ind_table (/* int num */);
extern PtrElement Ind_marquesuivante (/* PtrElement pDesc,
                                         PtrElement pMarque */);
extern int Ind_creertable (/* int numtable,
                              boolean avec_raz */);
extern void Ind_remplirtable (/* boolean avec_fusion */);
extern void Ind_remplirCR (/* void */);
extern char *Ind_textecle (/* int numcle,
                              PtrElement pEl */);
extern char *Ind_semantique (/* PtrElement pEl */);
extern void Ind_inittable (/* int num */);
extern int Ind_tousdesc (/* void */);
extern int Ind_touscroise (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
