/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void XCharTranslation ( ThotEvent * event );
extern void ThotInput ( int frame,
                        USTRING string,
                        unsigned int nb,
                        int PicMask,
                        int key );
extern void FreeTranslations ( void );
extern ThotTranslations InitTranslations ( CHAR_T* appliname );

#else /* __STDC__ */

extern void XCharTranslation (/* ThotEvent * event */);
extern void ThotInput (/* int frame,
                          USTRING string,
                          unsigned int nb,
                          int PicMask,
                          int key */);
extern void FreeTranslations (/* void */);
extern ThotTranslations InitTranslations (/* CHAR_T* appliname */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
