/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern unsigned char *ReadJPEG ( FILE* infile,
                                 int* width,
                                 int* height,
                                 ThotColorStruct colrs[256] );
extern unsigned char *ReadJpegToData ( CHAR_T* datafile,
                                       int* w,
                                       int* h,
                                       ThotColorStruct colrs[256] );
extern void JpegPrintErrorMsg ( int ErrorNumber );
extern ThotBitmap JpegCreate ( CHAR_T *fn,
                               PictInfo *imageDesc,
                               int *xif,
                               int *yif,
                               int *wif,
                               int *hif,
                               unsigned long BackGroundPixel,
                               ThotBitmap *mask1,
                               int *width,
                               int *height,
                               int zoom );
extern void JpegPrint ( CHAR_T *fn,
                        PictureScaling pres,
                        int xif,
                        int yif,
                        int wif,
                        int hif,
                        int PicXArea,
                        int PicYArea,
                        int PicWArea,
                        int PicHArea,
                        FILE *fd,
                        unsigned long BackGroundPixel );
extern ThotBool IsJpegFormat ( CHAR_T* fn );

#else /* __STDC__ */

extern unsigned char *ReadJPEG (/* FILE* infile,
                                   int* width,
                                   int* height,
                                   ThotColorStruct colrs[256] */);
extern unsigned char *ReadJpegToData (/* CHAR_T* datafile,
                                         int* w,
                                         int* h,
                                         ThotColorStruct colrs[256] */);
extern void JpegPrintErrorMsg (/* int ErrorNumber */);
extern ThotBitmap JpegCreate (/* CHAR_T *fn,
                                 PictInfo *imageDesc,
                                 int *xif,
                                 int *yif,
                                 int *wif,
                                 int *hif,
                                 unsigned long BackGroundPixel,
                                 ThotBitmap *mask1,
                                 int *width,
                                 int *height,
                                 int zoom */);
extern void JpegPrint (/* CHAR_T *fn,
                          PictureScaling pres,
                          int xif,
                          int yif,
                          int wif,
                          int hif,
                          int PicXArea,
                          int PicYArea,
                          int PicWArea,
                          int PicHArea,
                          FILE *fd,
                          unsigned long BackGroundPixel */);
extern ThotBool IsJpegFormat (/* CHAR_T* fn */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
