/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void KbdCallbackHandler ( ThotWidget w,
                                 int param,
                                 caddr_t call_d );
extern void KeyboardMap ( int kb );
extern void GraphicsLoadResources ( void );
extern void KeyboardsLoadResources ( void );
extern void TtcDisplayMathKeyboard ( Document document,
                                     View view );
extern void TtcDisplayGraphicsKeyboard ( Document document,
                                         View view );
extern void TtcDisplayLatinKeyboard ( Document document,
                                      View view );
extern void TtcDisplayGreekKeyboard ( Document document,
                                      View view );

#else /* __STDC__ */

extern void KbdCallbackHandler (/* ThotWidget w,
                                   int param,
                                   caddr_t call_d */);
extern void KeyboardMap (/* int kb */);
extern void GraphicsLoadResources (/* void */);
extern void KeyboardsLoadResources (/* void */);
extern void TtcDisplayMathKeyboard (/* Document document,
                                       View view */);
extern void TtcDisplayGraphicsKeyboard (/* Document document,
                                           View view */);
extern void TtcDisplayLatinKeyboard (/* Document document,
                                        View view */);
extern void TtcDisplayGreekKeyboard (/* Document document,
                                        View view */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
