/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern char *TtaGetLanguageNameFromCode ( const char *code );
extern const char *TtaGetISO639Code ( int val );
extern char *GetListOfLanguages ( char *buffer,
                                  int length,
                                  char *languageCode,
                                  int *nbItem,
                                  int *defItem );
extern char *TtaGetLanguageCodeFromName ( const char *name );
extern void InitLanguage ( void );
extern Language TtaNewLanguage ( char *languageName,
                                 char languageScript,
                                 char *principalDictionary,
                                 char *secondDictionary );
extern void TtaRemoveLanguage ( Language language );
extern Language TtaGetLanguageIdFromName ( const char *name );
extern char *TtaGetVarLANG ( void );
extern Language TtaGetDefaultLanguage ( void );
extern Language TtaGetLanguageIdFromScript ( char languageScript );
extern char TtaGetCharacterScript ( wchar_t c );
extern char TtaGetScript ( Language languageId );
extern char *TtaGetLanguageName ( Language languageId );
extern char *TtaGetLanguageCode ( Language languageId );
extern int TtaGetNumberOfLanguages ( void );
extern int TtaGetFirstUserLanguage ( void );
extern ThotBool GetPatternList ( Language langId );
extern int *TtaGetPatternHyphenList ( char *word,
                                      Language languageId );
extern ThotBool TtaExistPatternList ( Language languageId );

#else /* __STDC__ */

extern char *TtaGetLanguageNameFromCode ( const char *code );
extern const char *TtaGetISO639Code ( int val );
extern char *GetListOfLanguages ( char *buffer,
                                    int length,
                                    char *languageCode,
                                    int *nbItem,
                                    int *defItem );
extern char *TtaGetLanguageCodeFromName ( const char *name );
extern void InitLanguage ( void );
extern Language TtaNewLanguage ( char *languageName,
                                   char languageScript,
                                   char *principalDictionary,
                                   char *secondDictionary );
extern void TtaRemoveLanguage ( Language language );
extern Language TtaGetLanguageIdFromName ( const char *name );
extern char *TtaGetVarLANG ( void );
extern Language TtaGetDefaultLanguage ( void );
extern Language TtaGetLanguageIdFromScript ( char languageScript );
extern char TtaGetCharacterScript ( wchar_t c );
extern char TtaGetScript ( Language languageId );
extern char *TtaGetLanguageName ( Language languageId );
extern char *TtaGetLanguageCode ( Language languageId );
extern int TtaGetNumberOfLanguages ( void );
extern int TtaGetFirstUserLanguage ( void );
extern ThotBool GetPatternList ( Language langId );
extern int *TtaGetPatternHyphenList ( char *word,
                                        Language languageId );
extern ThotBool TtaExistPatternList ( Language languageId );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
