/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void XcgLiteClueAddWidget ( ThotWidget w,
                                   ThotWidget watch,
                                   char * text,
                                   int size,
                                   int option );
extern void XcgLiteClueDeleteWidget ( ThotWidget w,
                                      ThotWidget watch );
extern void XcgLiteClueSetSensitive ( ThotWidget w,
                                      ThotWidget watch,
                                      Boolean sensitive );
extern Boolean XcgLiteClueGetSensitive ( ThotWidget w,
                                         ThotWidget watch );

#else /* __STDC__ */

extern void XcgLiteClueAddWidget (/* ThotWidget w,
                                     ThotWidget watch,
                                     char * text,
                                     int size,
                                     int option */);
extern void XcgLiteClueDeleteWidget (/* ThotWidget w,
                                        ThotWidget watch */);
extern void XcgLiteClueSetSensitive (/* ThotWidget w,
                                        ThotWidget watch,
                                        Boolean sensitive */);
extern Boolean XcgLiteClueGetSensitive (/* ThotWidget w,
                                           ThotWidget watch */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
