/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern void returnopenview ( int ref,
                             int typedata,
                             char *data );
extern void TtcOpenView ( Document document,
                          View vue );
extern void TtcCloseView ( Document document,
                           View view );
extern void changesynchronize ( Document document,
                                View view );

#else /* __STDC__ */

extern void returnopenview (/* int ref,
                               int typedata,
                               char *data */);
extern void TtcOpenView (/* Document document,
                            View vue */);
extern void TtcCloseView (/* Document document,
                             View view */);
extern void changesynchronize (/* Document document,
                                  View view */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
