/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern PtrDocument pDocument ( DocumentIdentifier docIdent );
extern boolean OuvreDoc ( Name docName,
                          PtrDocument pDoc,
                          boolean loadIncludedDoc,
                          boolean skeleton,
                          PtrSSchema pSS,
                          boolean withAppEvent );
extern void SupprDoc ( PtrDocument pDoc );

#else /* __STDC__ */

extern PtrDocument pDocument (/* DocumentIdentifier docIdent */);
extern boolean OuvreDoc (/* Name docName,
                            PtrDocument pDoc,
                            boolean loadIncludedDoc,
                            boolean skeleton,
                            PtrSSchema pSS,
                            boolean withAppEvent */);
extern void SupprDoc (/* PtrDocument pDoc */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
