/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void TtaRegisterPixmap ( char *name,
                                Pixmap pix );
extern Pixmap TtaLoadImage ( char *name,
                             char *path );
extern Pixmap TtaGetImage ( char *name );

#else /* __STDC__ */

extern void TtaRegisterPixmap (/* char *name,
                                  Pixmap pix */);
extern Pixmap TtaLoadImage (/* char *name,
                               char *path */);
extern Pixmap TtaGetImage (/* char *name */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
