/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotPixmap TtaCreateBitmapLogo ( int width,
                                        int height,
                                        char *bits );
extern ThotIcon TtaCreatePixmapLogo ( char **d );

#else /* __STDC__ */

extern ThotPixmap TtaCreateBitmapLogo ( int width,
                                          int height,
                                          char *bits );
extern ThotIcon TtaCreatePixmapLogo ( char **d );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
