/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void InitPictureHandlers ( boolean printing );
extern void GetPictHandlersList ( int *count,
                                  char *buffer );
extern void DrawPicture ( PtrBox box,
                          PictInfo * imageDesc,
                          int frame );
extern void UnmapImage ( PictInfo* imageDesc );
extern char *ZoomPicture ( char *cpic,
                           int cWIDE,
                           int cHIGH,
                           int eWIDE,
                           int eHIGH,
                           int bperpix );
extern void LoadPicture ( int frame,
                          PtrBox box,
                          PictInfo * imageDesc );
extern void FreePicture ( PictInfo * imageDesc );
extern int GetPictureType ( int GUIIndex );
extern int GetPictTypeIndex ( int PicType );
extern int GetPictPresIndex ( PictureScaling PicPresent );
extern void GetPictureHandlersList ( int *count,
                                     char *buffer );
extern void LittleXBigEndian ( unsigned char *b,
                               long n );
extern int TtaSetMainThotWindowBackgroundImage ( ThotWindow w,
                                                 char *imageFile );

#else /* __STDC__ */

extern void InitPictureHandlers (/* boolean printing */);
extern void GetPictHandlersList (/* int *count,
                                    char *buffer */);
extern void DrawPicture (/* PtrBox box,
                            PictInfo * imageDesc,
                            int frame */);
extern void UnmapImage (/* PictInfo* imageDesc */);
extern char *ZoomPicture (/* char *cpic,
                             int cWIDE,
                             int cHIGH,
                             int eWIDE,
                             int eHIGH,
                             int bperpix */);
extern void LoadPicture (/* int frame,
                            PtrBox box,
                            PictInfo * imageDesc */);
extern void FreePicture (/* PictInfo * imageDesc */);
extern int GetPictureType (/* int GUIIndex */);
extern int GetPictTypeIndex (/* int PicType */);
extern int GetPictPresIndex (/* PictureScaling PicPresent */);
extern void GetPictureHandlersList (/* int *count,
                                       char *buffer */);
extern void LittleXBigEndian (/* unsigned char *b,
                                 long n */);
extern int TtaSetMainThotWindowBackgroundImage (/* ThotWindow w,
                                                   char *imageFile */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
