/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int TtaFileExist ( CONST char* filename );
extern int TtaFileUnlink ( CONST STRING filename );
extern int ThotDirBrowse_first ( ThotDirBrowse * me,
                                 char* dir,
                                 char* name,
                                 char* ext );
extern int ThotDirBrowse_next ( ThotDirBrowse * me );
extern int ThotDirBrowse_close ( ThotDirBrowse * me );
extern ThotFileHandle TtaFileOpen ( CONST STRING name,
                                    ThotFileMode mode );
extern int TtaFileClose ( ThotFileHandle handle );
extern int TtaFileRead ( ThotFileHandle handle,
                         void *buffer,
                         unsigned int count );
extern int TtaFileWrite ( ThotFileHandle handle,
                          void *buffer,
                          unsigned int count );
extern ThotFileOffset TtaFileSeek ( ThotFileHandle handle,
                                    ThotFileOffset offset,
                                    ThotFileOrigin origin );
extern int TtaFileStat ( ThotFileHandle handle,
                         ThotFileInfo * pInfo );
extern void TtaFileCopy ( CONST STRING sourceFileName,
                          CONST STRING targetFileName );
extern ThotBool TtaCompareFiles ( CONST STRING file1,
                                  CONST STRING file2 );

#else /* __STDC__ */

extern int TtaFileExist (/* CONST char* filename */);
extern int TtaFileUnlink (/* CONST STRING filename */);
extern int ThotDirBrowse_first (/* ThotDirBrowse * me,
                                   char* dir,
                                   char* name,
                                   char* ext */);
extern int ThotDirBrowse_next (/* ThotDirBrowse * me */);
extern int ThotDirBrowse_close (/* ThotDirBrowse * me */);
extern ThotFileHandle TtaFileOpen (/* CONST STRING name,
                                      ThotFileMode mode */);
extern int TtaFileClose (/* ThotFileHandle handle */);
extern int TtaFileRead (/* ThotFileHandle handle,
                           void *buffer,
                           unsigned int count */);
extern int TtaFileWrite (/* ThotFileHandle handle,
                            void *buffer,
                            unsigned int count */);
extern ThotFileOffset TtaFileSeek (/* ThotFileHandle handle,
                                      ThotFileOffset offset,
                                      ThotFileOrigin origin */);
extern int TtaFileStat (/* ThotFileHandle handle,
                           ThotFileInfo * pInfo */);
extern void TtaFileCopy (/* CONST STRING sourceFileName,
                            CONST STRING targetFileName */);
extern ThotBool TtaCompareFiles (/* CONST STRING file1,
                                    CONST STRING file2 */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
