/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void InitPrintParameters ( Document document );
extern void TtaGetPrintNames ( char **printDocName,
                               char **printDirName );
extern void TtaPrint ( Document document,
                       char *viewNames,
                       char *cssNames );
extern void TtaSetPrintExportFunc ( Func exportFunc );
extern void TtaSetPrintParameter ( PrintParameter parameter,
                                   int value );
extern int TtaGetPrintParameter ( PrintParameter parameter );
extern void TtaSetPrintCommand ( const char *command );
extern void TtaSetPrintSchema ( const char *name );
extern void TtaSetPsFile ( const char *path );

#else /* __STDC__ */

extern void InitPrintParameters ( Document document );
extern void TtaGetPrintNames ( char **printDocName,
                                 char **printDirName );
extern void TtaPrint ( Document document,
                         char *viewNames,
                         char *cssNames );
extern void TtaSetPrintExportFunc ( Func exportFunc );
extern void TtaSetPrintParameter ( PrintParameter parameter,
                                     int value );
extern int TtaGetPrintParameter ( PrintParameter parameter );
extern void TtaSetPrintCommand ( const char *command );
extern void TtaSetPrintSchema ( const char *name );
extern void TtaSetPsFile ( const char *path );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
