/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern boolean OpenDocument ( Name docName,
                              PtrDocument pDoc,
                              boolean loadIncludedDoc,
                              boolean skeleton,
                              PtrSSchema pSS,
                              boolean withAppEvent );
extern void DeleteAllTrees ( PtrDocument pDoc );
extern PtrTextBuffer ReadComment ( BinFile file,
                                   boolean store,
                                   boolean oldformat );
extern void LabelStringToInt ( LabelString string,
                               int *number );
extern void ReadAttr ( BinFile pivFile,
                       PtrElement pEl,
                       PtrDocument pDoc,
                       boolean create,
                       PtrAttribute * pReadAttr,
                       PtrAttribute * pAttr );
extern void ReadPRulePiv ( PtrDocument pDoc,
                           BinFile pivFile,
                           PtrElement pEl,
                           boolean create,
                           PtrPRule * pRuleRead,
                           boolean link );
extern PtrElement ReadTreePiv ( BinFile pivFile,
                                PtrSSchema pSSchema,
                                PtrDocument pDoc,
                                char *tag,
                                int assocNum,
                                boolean createParam,
                                boolean createAll,
                                int * contentType,
                                PtrSSchema * pContSS,
                                int * typeRead,
                                PtrSSchema * pSSRead,
                                boolean createPage,
                                PtrElement pParent,
                                boolean createDesc );
extern boolean AbstractTreeOK ( PtrElement pEl,
                                PtrDocument pDoc );
extern void AssociatePairs ( PtrElement pRoot );
extern void ReadSchemaNamesPiv ( BinFile file,
                                 PtrDocument pDoc,
                                 char *tag,
                                 PtrSSchema pLoadedSS );
extern void ReadLanguageTablePiv ( BinFile file,
                                   PtrDocument pDoc,
                                   char *tag );
extern int ReadVersionNumberPiv ( BinFile file,
                                  PtrDocument pDoc );
extern void ReadPivotHeader ( BinFile file,
                              PtrDocument pDoc,
                              char *tag );
extern void LoadDocumentPiv ( BinFile file,
                              PtrDocument pDoc,
                              boolean loadExternalDoc,
                              boolean skeleton,
                              PtrSSchema pLoadedSS,
                              boolean withEvent );

#else /* __STDC__ */

extern boolean OpenDocument (/* Name docName,
                                PtrDocument pDoc,
                                boolean loadIncludedDoc,
                                boolean skeleton,
                                PtrSSchema pSS,
                                boolean withAppEvent */);
extern void DeleteAllTrees (/* PtrDocument pDoc */);
extern PtrTextBuffer ReadComment (/* BinFile file,
                                     boolean store,
                                     boolean oldformat */);
extern void LabelStringToInt (/* LabelString string,
                                 int *number */);
extern void ReadAttr (/* BinFile pivFile,
                         PtrElement pEl,
                         PtrDocument pDoc,
                         boolean create,
                         PtrAttribute * pReadAttr,
                         PtrAttribute * pAttr */);
extern void ReadPRulePiv (/* PtrDocument pDoc,
                             BinFile pivFile,
                             PtrElement pEl,
                             boolean create,
                             PtrPRule * pRuleRead,
                             boolean link */);
extern PtrElement ReadTreePiv (/* BinFile pivFile,
                                  PtrSSchema pSSchema,
                                  PtrDocument pDoc,
                                  char *tag,
                                  int assocNum,
                                  boolean createParam,
                                  boolean createAll,
                                  int * contentType,
                                  PtrSSchema * pContSS,
                                  int * typeRead,
                                  PtrSSchema * pSSRead,
                                  boolean createPage,
                                  PtrElement pParent,
                                  boolean createDesc */);
extern boolean AbstractTreeOK (/* PtrElement pEl,
                                  PtrDocument pDoc */);
extern void AssociatePairs (/* PtrElement pRoot */);
extern void ReadSchemaNamesPiv (/* BinFile file,
                                   PtrDocument pDoc,
                                   char *tag,
                                   PtrSSchema pLoadedSS */);
extern void ReadLanguageTablePiv (/* BinFile file,
                                     PtrDocument pDoc,
                                     char *tag */);
extern int ReadVersionNumberPiv (/* BinFile file,
                                    PtrDocument pDoc */);
extern void ReadPivotHeader (/* BinFile file,
                                PtrDocument pDoc,
                                char *tag */);
extern void LoadDocumentPiv (/* BinFile file,
                                PtrDocument pDoc,
                                boolean loadExternalDoc,
                                boolean skeleton,
                                PtrSSchema pLoadedSS,
                                boolean withEvent */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
