/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern boolean ReadStructureSchema ( Name fname,
                             PtrSSchema scheme );

#else /* __STDC__ */

extern boolean ReadStructureSchema (/* Name fname,
                               PtrSSchema scheme */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
