/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotBool ReadStructureSchema ( const char * fileName,
                                      PtrSSchema pSS );

#else /* __STDC__ */

extern ThotBool ReadStructureSchema ( const char * fileName,
                                        PtrSSchema pSS );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
