/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern boolean SearchRegularExpression ( PtrElement * firstEl,
                                         int *firstChar,
                                         PtrElement * lastEl,
                                         int *lastChar,
                                         boolean forward,
                                         boolean caseEquiv,
                                         char *expression );

#else /* __STDC__ */

extern boolean SearchRegularExpression (/* PtrElement * firstEl,
                                           int *firstChar,
                                           PtrElement * lastEl,
                                           int *lastChar,
                                           boolean forward,
                                           boolean caseEquiv,
                                           char *expression */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
