/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern boolean ChRegExp ( PtrElement * pElDebut,
                          int *NumCarDebut,
                          PtrElement * pElFin,
                          int *NumCarFin,
                          boolean EnAvant,
                          boolean MajEgalMin,
                          char *expression );

#else /* __STDC__ */

extern boolean ChRegExp (/* PtrElement * pElDebut,
                            int *NumCarDebut,
                            PtrElement * pElFin,
                            int *NumCarFin,
                            boolean EnAvant,
                            boolean MajEgalMin,
                            char *expression */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
