/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern char *TtaGetEnvString ( char *name );
extern void TtaSetEnvString ( char *name,
                              char *value,
                              int overwrite );
extern void TtaSaveAppRegistry ( void );
extern void TtaInitializeAppRegistry ( char *appArgv0 );
extern int SearchFile ( char *fileName,
                        int dir,
                        char *fullName );

#else /* __STDC__ */

extern char *TtaGetEnvString (/* char *name */);
extern void TtaSetEnvString (/* char *name,
                                char *value,
                                int overwrite */);
extern void TtaSaveAppRegistry (/* void */);
extern void TtaInitializeAppRegistry (/* char *appArgv0 */);
extern int SearchFile (/* char *fileName,
                          int dir,
                          char *fullName */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
