/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern STRING TtaSkipBlanks ( STRING ptr );
extern ThotBool TtaIsBlank ( STRING ptr );
extern ThotBool TtaGetEnvInt ( char* name,
                               int *value );
extern ThotBool TtaGetEnvBoolean ( char* name,
                                   ThotBool *value );
extern char* TtaGetEnvString ( char* name );
extern void TtaClearEnvString ( STRING name );
extern void TtaSetEnvInt ( STRING name,
                           int value,
                           int overwrite );
extern void TtaSetEnvBoolean ( STRING name,
                               ThotBool value,
                               int overwrite );
extern void TtaSetEnvString ( STRING name,
                              STRING value,
                              int overwrite );
extern void TtaSetDefEnvString ( STRING name,
                                 STRING value,
                                 int overwrite );
extern ThotBool TtaGetDefEnvInt ( STRING name,
                                  int *value );
extern ThotBool TtaGetDefEnvBoolean ( STRING name,
                                      ThotBool *value );
extern STRING TtaGetDefEnvString ( STRING name );
extern void TtaSaveAppRegistry ( void );
extern void TtaInitializeAppRegistry ( STRING appArgv0 );
extern void TtaFreeAppRegistry ( void );
extern int SearchFile ( STRING fileName,
                        int dir,
                        STRING fullName );

#else /* __STDC__ */

extern STRING TtaSkipBlanks (/* STRING ptr */);
extern ThotBool TtaIsBlank (/* STRING ptr */);
extern ThotBool TtaGetEnvInt (/* char* name,
                                 int *value */);
extern ThotBool TtaGetEnvBoolean (/* char* name,
                                     ThotBool *value */);
extern char* TtaGetEnvString (/* char* name */);
extern void TtaClearEnvString (/* STRING name */);
extern void TtaSetEnvInt (/* STRING name,
                             int value,
                             int overwrite */);
extern void TtaSetEnvBoolean (/* STRING name,
                                 ThotBool value,
                                 int overwrite */);
extern void TtaSetEnvString (/* STRING name,
                                STRING value,
                                int overwrite */);
extern void TtaSetDefEnvString (/* STRING name,
                                   STRING value,
                                   int overwrite */);
extern ThotBool TtaGetDefEnvInt (/* STRING name,
                                    int *value */);
extern ThotBool TtaGetDefEnvBoolean (/* STRING name,
                                        ThotBool *value */);
extern STRING TtaGetDefEnvString (/* STRING name */);
extern void TtaSaveAppRegistry (/* void */);
extern void TtaInitializeAppRegistry (/* STRING appArgv0 */);
extern void TtaFreeAppRegistry (/* void */);
extern int SearchFile (/* STRING fileName,
                          int dir,
                          STRING fullName */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
