/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void InitNatures ( void );
extern PtrSSchema GetSSchemaForDoc ( const char *name,
                                     PtrDocument pDoc );
extern PtrSSchema GetSSchemaByUriForDoc ( const char *uriName,
                                          PtrDocument pDoc );
extern void RegisterSSchemaForSavedElements ( PtrSSchema pSSchema );
extern void ReleaseSSchemasForSavedElements ( void );
extern ThotBool LoadPresentationSchema ( const char *schemaName,
                                         PtrSSchema pSS,
                                         PtrDocument pDoc );
extern void FreePresentationSchema ( PtrPSchema pPSchema,
                                     PtrSSchema pSS,
                                     PtrDocument pDoc );
extern PtrHandlePSchema FirstPSchemaExtension ( PtrSSchema pSS,
                                                PtrDocument pDoc,
                                                PtrElement pEl );
extern void UnlinkPSchemaExtension ( PtrDocument pDoc,
                                     PtrSSchema pSS,
                                     PtrPSchema pPS );
extern void SetElSchemasExtens ( PtrElement pEl,
                                 PtrDocSchemasDescr pPfS );
extern ThotBool InsertPSchemaExtension ( PtrDocument pDoc,
                                         PtrSSchema pSS,
                                         PtrPSchema pPS,
                                         PtrPSchema pOldPS,
                                         ThotBool before );
extern void UnlinkAllSchemasExtens ( PtrElement pEl );
extern PtrPSchema PresentationSchema ( PtrSSchema pSS,
                                       PtrDocument pDoc );
extern PtrSSchema LoadStructureSchema ( const char *schemaURI,
                                        const char * schemaName,
                                        PtrDocument pDoc );
extern void ReleaseStructureSchema ( PtrSSchema pSS,
                                     PtrDocument pDoc );
extern void LoadNatureSchema ( PtrSSchema pSS,
                               const char *PSchName,
                               int rule,
                               const char *schURI,
                               PtrDocument pDoc );
extern int CreateNature ( const char *SSchURI,
                          const char *SSchName,
                          const char *PSchName,
                          PtrSSchema pSS,
                          PtrDocument pDoc );
extern void LoadSchemas ( char *SSchName,
                          char *PSchName,
                          PtrSSchema *pSS,
                          PtrDocument pDoc,
                          PtrSSchema pLoadedSS,
                          ThotBool extension );
extern PtrSSchema LoadExtension ( char *SSchName,
                                  char *PSchName,
                                  PtrDocument pDoc );
extern ThotBool FreeNature ( PtrSSchema pSS,
                             PtrSSchema pNatureSS,
                             PtrDocument pDoc );
extern void FreeDocumentSchemas ( PtrDocument pDoc );
extern void AddSchemaGuestViews ( PtrDocument pDoc,
                                  PtrSSchema pSS );
extern void CreateGuestViewList ( PtrDocument pDoc,
                                  int view );
extern void BuildDocNatureTable ( PtrDocument pDoc );
extern void SearchNatures ( PtrDocument pDoc,
                            PtrSSchema natureTable[10],
                            int *natureTableLen );
extern void AppendXmlAttribute ( char *xmlName,
                                 AttributeType *attrType,
                                 PtrDocument pDoc );
extern void AddEmptyBox ( PtrElement element );
extern PtrPRule GetXmlPRule ( PtrPSchema pPSch,
                              int nSRule,
                              PRuleType PrType,
                              FunctionType FcType,
                              int view );
extern ThotBool HasXmlInLineRule ( ElementType elType,
                                   PtrDocument pDoc );
extern void SetXmlInLineRule ( ElementType elType,
                               PtrDocument pDoc );
extern void AppendXmlElement ( const char *xmlName,
                               int *typeNum,
                               PtrSSchema pSS,
                               char **mappedName,
                               PtrDocument pDoc );
extern void GetXmlAttributeType ( char* xmlName,
                                  AttributeType *attrType,
                                  PtrDocument pDoc );
extern void GetXmlElementType ( const char *xmlName,
                                ElementType *elType,
                                char **mappedName,
                                PtrDocument pDoc );
extern void SetUriSSchema ( PtrSSchema pSSchema,
                            const char *sSchemaUri );
extern void ChangeGenericSchemaNames ( const char *sSchemaUri,
                                       const char *sSchemaName,
                                       PtrDocument pDoc );
extern void SetNamespaceDeclaration ( PtrDocument pDoc,
                                      PtrElement element,
                                      const char *nsPrefix,
                                      const char *nsUri );
extern void RemoveANamespaceDeclaration ( PtrDocument pDoc,
                                          PtrElement element,
                                          const char *nsPrefix,
                                          const char *nsUri );
extern void RemoveNamespaceDeclaration ( PtrDocument pDoc,
                                         PtrElement element );
extern void ReplaceNamespaceDeclaration ( PtrDocument pDoc,
                                          PtrElement oldEl,
                                          PtrElement newEl );
extern void CopyNamespaceDeclarations ( PtrDocument docSource,
                                        PtrElement elSource,
                                        PtrDocument docTarget,
                                        PtrElement elTarget );
extern char *GiveCurrentNsUri ( PtrDocument pDoc,
                                PtrElement pEl );
extern void GiveElemNamespaceDeclarations ( PtrDocument pDoc,
                                            PtrElement pEl,
                                            char **declarations,
                                            char **prefixes,
                                            int max );
extern ThotBool DocumentUsesNsPrefixes ( PtrDocument pDoc );

#else /* __STDC__ */

extern void InitNatures ( void );
extern PtrSSchema GetSSchemaForDoc ( const char *name,
                                       PtrDocument pDoc );
extern PtrSSchema GetSSchemaByUriForDoc ( const char *uriName,
                                            PtrDocument pDoc );
extern void RegisterSSchemaForSavedElements ( PtrSSchema pSSchema );
extern void ReleaseSSchemasForSavedElements ( void );
extern ThotBool LoadPresentationSchema ( const char *schemaName,
                                           PtrSSchema pSS,
                                           PtrDocument pDoc );
extern void FreePresentationSchema ( PtrPSchema pPSchema,
                                       PtrSSchema pSS,
                                       PtrDocument pDoc );
extern PtrHandlePSchema FirstPSchemaExtension ( PtrSSchema pSS,
                                                  PtrDocument pDoc,
                                                  PtrElement pEl );
extern void UnlinkPSchemaExtension ( PtrDocument pDoc,
                                       PtrSSchema pSS,
                                       PtrPSchema pPS );
extern void SetElSchemasExtens ( PtrElement pEl,
                                   PtrDocSchemasDescr pPfS );
extern ThotBool InsertPSchemaExtension ( PtrDocument pDoc,
                                           PtrSSchema pSS,
                                           PtrPSchema pPS,
                                           PtrPSchema pOldPS,
                                           ThotBool before );
extern void UnlinkAllSchemasExtens ( PtrElement pEl );
extern PtrPSchema PresentationSchema ( PtrSSchema pSS,
                                         PtrDocument pDoc );
extern PtrSSchema LoadStructureSchema ( const char *schemaURI,
                                          const char * schemaName,
                                          PtrDocument pDoc );
extern void ReleaseStructureSchema ( PtrSSchema pSS,
                                       PtrDocument pDoc );
extern void LoadNatureSchema ( PtrSSchema pSS,
                                 const char *PSchName,
                                 int rule,
                                 const char *schURI,
                                 PtrDocument pDoc );
extern int CreateNature ( const char *SSchURI,
                            const char *SSchName,
                            const char *PSchName,
                            PtrSSchema pSS,
                            PtrDocument pDoc );
extern void LoadSchemas ( char *SSchName,
                            char *PSchName,
                            PtrSSchema *pSS,
                            PtrDocument pDoc,
                            PtrSSchema pLoadedSS,
                            ThotBool extension );
extern PtrSSchema LoadExtension ( char *SSchName,
                                    char *PSchName,
                                    PtrDocument pDoc );
extern ThotBool FreeNature ( PtrSSchema pSS,
                               PtrSSchema pNatureSS,
                               PtrDocument pDoc );
extern void FreeDocumentSchemas ( PtrDocument pDoc );
extern void AddSchemaGuestViews ( PtrDocument pDoc,
                                    PtrSSchema pSS );
extern void CreateGuestViewList ( PtrDocument pDoc,
                                    int view );
extern void BuildDocNatureTable ( PtrDocument pDoc );
extern void SearchNatures ( PtrDocument pDoc,
                              PtrSSchema natureTable[10],
                              int *natureTableLen );
extern void AppendXmlAttribute ( char *xmlName,
                                   AttributeType *attrType,
                                   PtrDocument pDoc );
extern void AddEmptyBox ( PtrElement element );
extern PtrPRule GetXmlPRule ( PtrPSchema pPSch,
                                int nSRule,
                                PRuleType PrType,
                                FunctionType FcType,
                                int view );
extern ThotBool HasXmlInLineRule ( ElementType elType,
                                     PtrDocument pDoc );
extern void SetXmlInLineRule ( ElementType elType,
                                 PtrDocument pDoc );
extern void AppendXmlElement ( const char *xmlName,
                                 int *typeNum,
                                 PtrSSchema pSS,
                                 char **mappedName,
                                 PtrDocument pDoc );
extern void GetXmlAttributeType ( char* xmlName,
                                    AttributeType *attrType,
                                    PtrDocument pDoc );
extern void GetXmlElementType ( const char *xmlName,
                                  ElementType *elType,
                                  char **mappedName,
                                  PtrDocument pDoc );
extern void SetUriSSchema ( PtrSSchema pSSchema,
                              const char *sSchemaUri );
extern void ChangeGenericSchemaNames ( const char *sSchemaUri,
                                         const char *sSchemaName,
                                         PtrDocument pDoc );
extern void SetNamespaceDeclaration ( PtrDocument pDoc,
                                        PtrElement element,
                                        const char *nsPrefix,
                                        const char *nsUri );
extern void RemoveANamespaceDeclaration ( PtrDocument pDoc,
                                            PtrElement element,
                                            const char *nsPrefix,
                                            const char *nsUri );
extern void RemoveNamespaceDeclaration ( PtrDocument pDoc,
                                           PtrElement element );
extern void ReplaceNamespaceDeclaration ( PtrDocument pDoc,
                                            PtrElement oldEl,
                                            PtrElement newEl );
extern void CopyNamespaceDeclarations ( PtrDocument docSource,
                                          PtrElement elSource,
                                          PtrDocument docTarget,
                                          PtrElement elTarget );
extern char *GiveCurrentNsUri ( PtrDocument pDoc,
                                  PtrElement pEl );
extern void GiveElemNamespaceDeclarations ( PtrDocument pDoc,
                                              PtrElement pEl,
                                              char **declarations,
                                              char **prefixes,
                                              int max );
extern ThotBool DocumentUsesNsPrefixes ( PtrDocument pDoc );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
