/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void InitNatures ( void );
extern PtrPSchema LoadPresentationSchema ( Name schemaName,
                                           PtrSSchema pSS );
extern void FreePresentationSchema ( PtrPSchema pPSchema,
                                     PtrSSchema pSS );
extern void LoadNatureSchema ( PtrSSchema pSS,
                               char *PSchName,
                               int rule );
extern int CreateNature ( char *SSchName,
                          char *PSchName,
                          PtrSSchema pSS );
extern void LoadSchemas ( char *SSchName,
                          char *PSchName,
                          PtrSSchema *pSS,
                          PtrSSchema pLoadedSS,
                          ThotBool extension );
extern PtrSSchema LoadExtension ( char *SSchName,
                                  char *PSchName,
                                  PtrDocument pDoc );
extern ThotBool FreeNature ( PtrSSchema pSS,
                             PtrSSchema pNatureSS );
extern void FreeDocumentSchemas ( PtrDocument pDoc );
extern void AddSchemaGuestViews ( PtrDocument pDoc,
                                  PtrSSchema pSS );
extern void CreateGuestViewList ( PtrDocument pDoc,
                                  int view );
extern void BuildDocNatureTable ( PtrDocument pDoc );

#else /* __STDC__ */

extern void InitNatures (/* void */);
extern PtrPSchema LoadPresentationSchema (/* Name schemaName,
                                             PtrSSchema pSS */);
extern void FreePresentationSchema (/* PtrPSchema pPSchema,
                                       PtrSSchema pSS */);
extern void LoadNatureSchema (/* PtrSSchema pSS,
                                 char *PSchName,
                                 int rule */);
extern int CreateNature (/* char *SSchName,
                            char *PSchName,
                            PtrSSchema pSS */);
extern void LoadSchemas (/* char *SSchName,
                            char *PSchName,
                            PtrSSchema *pSS,
                            PtrSSchema pLoadedSS,
                            ThotBool extension */);
extern PtrSSchema LoadExtension (/* char *SSchName,
                                    char *PSchName,
                                    PtrDocument pDoc */);
extern ThotBool FreeNature (/* PtrSSchema pSS,
                               PtrSSchema pNatureSS */);
extern void FreeDocumentSchemas (/* PtrDocument pDoc */);
extern void AddSchemaGuestViews (/* PtrDocument pDoc,
                                    PtrSSchema pSS */);
extern void CreateGuestViewList (/* PtrDocument pDoc,
                                    int view */);
extern void BuildDocNatureTable (/* PtrDocument pDoc */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
