/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern PtrReference NextReferenceToEl ( PtrElement pEl,
                                    PtrDocument pDocEl,
                                    boolean TraiteNonCharge,
                                    PtrReference pRefPrec,
                                    PtrDocument * pDocRef,
                                    PtrExternalDoc * pDE,
                                    boolean DocExtSuivant );
extern void FindReference ( PtrReference * ReferCour,
                       PtrDocument * DocDeReferCour,
                       PtrElement * ElemRefCour,
                       PtrDocument * DocDeElemRefCour,
                       PtrExternalDoc * pDocExtCour,
                       boolean DocExtSuivant );
extern void FindReferredEl ( void );
extern void CheckReferences ( PtrElement pRac,
                       PtrDocument pDoc );

#else /* __STDC__ */

extern PtrReference NextReferenceToEl (/* PtrElement pEl,
                                      PtrDocument pDocEl,
                                      boolean TraiteNonCharge,
                                      PtrReference pRefPrec,
                                      PtrDocument * pDocRef,
                                      PtrExternalDoc * pDE,
                                      boolean DocExtSuivant */);
extern void FindReference (/* PtrReference * ReferCour,
                         PtrDocument * DocDeReferCour,
                         PtrElement * ElemRefCour,
                         PtrDocument * DocDeElemRefCour,
                         PtrExternalDoc * pDocExtCour,
                         boolean DocExtSuivant */);
extern void FindReferredEl (/* void */);
extern void CheckReferences (/* PtrElement pRac,
                         PtrDocument pDoc */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
