/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern int ComposeMenuSelection ( char BufMenu[MAX_TXT_LEN] );
extern void MajMenuSelect ( PtrDocument pDoc );
extern void RetMenuSelect ( int refmenu,
                            int val,
                            int frame );
extern void SelectionMenuLoadResources ( void );

#else /* __STDC__ */

extern int ComposeMenuSelection (/* char BufMenu[MAX_TXT_LEN] */);
extern void MajMenuSelect (/* PtrDocument pDoc */);
extern void RetMenuSelect (/* int refmenu,
                              int val,
                              int frame */);
extern void SelectionMenuLoadResources (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
