/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#if __STDC__

extern boolean minMAJ ( char *chaine );
extern void majuscule ( char *chaine );
extern void capital ( char *chaine );
extern char tomin ( char caract );
extern boolean ismajuscule ( char *chaine );
extern boolean iscapital ( char *chaine );
extern boolean isiso ( char *chaine );
extern int existmot ( char mot[MAX_WORD_LEN],
                      PtrDico dico );
extern int Corr_verifiermot ( char mot[MAX_WORD_LEN],
                              Language langue,
                              PtrDico dico );
extern void Corr_ajoutermot ( char mot[MAX_WORD_LEN],
                              PtrDico * pDico );
extern void Corr_init_correction ( void );
extern void Corr_proposer ( Language langue,
                            PtrDico dicodocu );
extern void param_defauts ( int lettres );
extern int Corr_Param ( void );
extern void Corr_remplacermot ( char motorigine[MAX_WORD_LEN],
                                char motnouveau[MAX_WORD_LEN] );
extern boolean CorrChangeSelection ( void );
extern boolean TestListCar ( char car,
                             char *listcar );
extern boolean AUnNombre ( char mot[MAX_CHAR] );
extern boolean EstUnNombre ( char mot[MAX_CHAR] );
extern boolean EnRomain ( char mot[MAX_CHAR] );
extern void Corr_errsuivant ( char mot[MAX_CHAR],
                              PtrDico dicodocu );
extern void sauverdicofichier ( PtrDico dicodocu );

#else /* __STDC__ */

extern boolean minMAJ (/* char *chaine */);
extern void majuscule (/* char *chaine */);
extern void capital (/* char *chaine */);
extern char tomin (/* char caract */);
extern boolean ismajuscule (/* char *chaine */);
extern boolean iscapital (/* char *chaine */);
extern boolean isiso (/* char *chaine */);
extern int existmot (/* char mot[MAX_WORD_LEN],
                        PtrDico dico */);
extern int Corr_verifiermot (/* char mot[MAX_WORD_LEN],
                                Language langue,
                                PtrDico dico */);
extern void Corr_ajoutermot (/* char mot[MAX_WORD_LEN],
                                PtrDico * pDico */);
extern void Corr_init_correction (/* void */);
extern void Corr_proposer (/* Language langue,
                              PtrDico dicodocu */);
extern void param_defauts (/* int lettres */);
extern int Corr_Param (/* void */);
extern void Corr_remplacermot (/* char motorigine[MAX_WORD_LEN],
                                  char motnouveau[MAX_WORD_LEN] */);
extern boolean CorrChangeSelection (/* void */);
extern boolean TestListCar (/* char car,
                               char *listcar */);
extern boolean AUnNombre (/* char mot[MAX_CHAR] */);
extern boolean EstUnNombre (/* char mot[MAX_CHAR] */);
extern boolean EnRomain (/* char mot[MAX_CHAR] */);
extern void Corr_errsuivant (/* char mot[MAX_CHAR],
                                PtrDico dicodocu */);
extern void sauverdicofichier (/* PtrDico dicodocu */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
