/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void IsolateSelection ( PtrDocument pDoc,
                               PtrElement * pFirstSel,
                               PtrElement * pLastSel,
                               int *firstChar,
                               int *lastChar,
                               ThotBool createEmpty );
extern ThotBool SendEventSubTree ( APPevent AppEvent,
                                   PtrDocument pDoc,
                                   PtrElement pEl,
                                   int end );
extern void FreeSavedElements ( void );
extern void CopyCommand ( void );
extern PtrElement NextNotPage ( PtrElement pEl );
extern PtrElement PreviousNotPage ( PtrElement pEl );
extern void ProcessFirstLast ( PtrElement pPrev,
                               PtrElement pNext,
                               PtrDocument pDoc );
extern void CutCommand ( ThotBool save );
extern ThotBool EmptyElement ( PtrElement pEl );
extern void CreateNewElement ( int typeNum,
                               PtrSSchema pSS,
                               PtrDocument pDoc,
                               ThotBool Before );
extern void TtaCreateElement ( ElementType elementType,
                               Document document );
extern void TtaSetTransformCallback ( Func callbackFunc );
extern void SurroundMenuInput ( int item );
extern void TtcSurround ( Document document,
                          View view );
extern void ChangeTypeMenuInput ( int entree );
extern void TtcChangeType ( Document document,
                            View view );

#else /* __STDC__ */

extern void IsolateSelection (/* PtrDocument pDoc,
                                 PtrElement * pFirstSel,
                                 PtrElement * pLastSel,
                                 int *firstChar,
                                 int *lastChar,
                                 ThotBool createEmpty */);
extern ThotBool SendEventSubTree (/* APPevent AppEvent,
                                     PtrDocument pDoc,
                                     PtrElement pEl,
                                     int end */);
extern void FreeSavedElements (/* void */);
extern void CopyCommand (/* void */);
extern PtrElement NextNotPage (/* PtrElement pEl */);
extern PtrElement PreviousNotPage (/* PtrElement pEl */);
extern void ProcessFirstLast (/* PtrElement pPrev,
                                 PtrElement pNext,
                                 PtrDocument pDoc */);
extern void CutCommand (/* ThotBool save */);
extern ThotBool EmptyElement (/* PtrElement pEl */);
extern void CreateNewElement (/* int typeNum,
                                 PtrSSchema pSS,
                                 PtrDocument pDoc,
                                 ThotBool Before */);
extern void TtaCreateElement (/* ElementType elementType,
                                 Document document */);
extern void TtaSetTransformCallback (/* Func callbackFunc */);
extern void SurroundMenuInput (/* int item */);
extern void TtcSurround (/* Document document,
                            View view */);
extern void ChangeTypeMenuInput (/* int entree */);
extern void TtcChangeType (/* Document document,
                              View view */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
