/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void TtaLaunchTestCase ( const char * filename );
extern int TtaStartBenchmarkTimer ( const char * name );
extern void TtaStopBenchmarkTimer ( int bench_id );
extern void TtaSetBenchmarkMark ( int bench_id,
                                  const char * mark_name );

#else /* __STDC__ */

extern void TtaLaunchTestCase ( const char * filename );
extern int TtaStartBenchmarkTimer ( const char * name );
extern void TtaStopBenchmarkTimer ( int bench_id );
extern void TtaSetBenchmarkMark ( int bench_id,
                                    const char * mark_name );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
