/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void XmlSetPageBreakProperties ( Element el );
extern void XmlFreePresentationList ( void );
extern void XmlSetPresentation ( Document doc );
extern ThotBool ParseThotAttribute ( Document doc,
                                     Element el,
                                     STRING attrName,
                                     STRING value );
extern void StoreTableActions ( void );
extern void RestoreTableActions ( void );

#else /* __STDC__ */

extern void XmlSetPageBreakProperties (/* Element el */);
extern void XmlFreePresentationList (/* void */);
extern void XmlSetPresentation (/* Document doc */);
extern ThotBool ParseThotAttribute (/* Document doc,
                                       Element el,
                                       STRING attrName,
                                       STRING value */);
extern void StoreTableActions (/* void */);
extern void RestoreTableActions (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
