/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotBool ExportDocument ( PtrDocument pDoc,
                                 STRING fName,
                                 STRING TSchemaName,
                                 ThotBool recordLineNb );
extern void ExportTree ( PtrElement pEl,
                         PtrDocument pDoc,
                         STRING fName,
                         STRING TSchemaName );

#else /* __STDC__ */

extern ThotBool ExportDocument (/* PtrDocument pDoc,
                                   STRING fName,
                                   STRING TSchemaName,
                                   ThotBool recordLineNb */);
extern void ExportTree (/* PtrElement pEl,
                           PtrDocument pDoc,
                           STRING fName,
                           STRING TSchemaName */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
