/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void TtaSetEntityFunction ( Proc4 procedure );
extern void TtaSetDoctypeFunction ( Proc2 procedure );
extern void TtaGetTime ( char *s,
                         CHARSET charset );
extern ThotBool ExportDocument ( Document doc,
                                 char *fName,
                                 char *tschema,
                                 ThotBool recordLineNb );
extern void ExportXmlDocument ( Document doc,
                                PtrElement pNode,
                                ThotBool recordLineNb );
extern void ExportTree ( PtrElement pEl,
                         Document doc,
                         char *fName,
                         char *tschema );
extern ThotBool TtaExportDocument ( Document document,
                                    char *fileName,
                                    char *tschema );
extern ThotBool TtaExportDocumentWithNewLineNumbers ( Document document,
                                                      char *fileName,
                                                      char *tschema );

#else /* __STDC__ */

extern void TtaSetEntityFunction ( Proc4 procedure );
extern void TtaSetDoctypeFunction ( Proc2 procedure );
extern void TtaGetTime ( char *s,
                           CHARSET charset );
extern ThotBool ExportDocument ( Document doc,
                                   char *fName,
                                   char *tschema,
                                   ThotBool recordLineNb );
extern void ExportXmlDocument ( Document doc,
                                  PtrElement pNode,
                                  ThotBool recordLineNb );
extern void ExportTree ( PtrElement pEl,
                           Document doc,
                           char *fName,
                           char *tschema );
extern ThotBool TtaExportDocument ( Document document,
                                      char *fileName,
                                      char *tschema );
extern ThotBool TtaExportDocumentWithNewLineNumbers ( Document document,
                                                        char *fileName,
                                                        char *tschema );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
