/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__
extern unsigned char TtaGetCharFromWC ( wchar_t wc,
                                        CHARSET encoding );
extern wchar_t TtaConvertJisToWC ( unsigned char b1,
                                   unsigned char b2,
                                   CHARSET charset );
extern wchar_t TtaConvertSjisToWC ( unsigned char b1,
                                    unsigned char b2 );
extern int TtaJisEscMatch ( unsigned char *buf,
                            unsigned char *match,
                            int *more );
extern wchar_t TtaGetWCFromJisChar ( unsigned char c,
                                     CHARSET encoding );
extern wchar_t TtaGetWCFromChar ( unsigned char c,
                                  CHARSET encoding );
extern int TtaWCToMBstring ( wchar_t src,
                             unsigned char **dest );
extern int TtaMBstringToWC ( unsigned char **src,
                             wchar_t *dest );
extern int TtaGetNextWCFromString ( wchar_t *car,
                                    unsigned char **txt,
                                    CHARSET encoding );
extern int TtaGetNumberOfBytesToRead ( unsigned char **txt,
                                       CHARSET encoding );
extern unsigned char *TtaConvertWCToByte ( wchar_t *src,
                                           CHARSET encoding );
extern wchar_t *TtaConvertByteToWC ( unsigned char *src,
                                     CHARSET encoding );
extern unsigned char *TtaConvertByteToMbs ( unsigned char *src,
                                            CHARSET encoding );
extern unsigned char *TtaConvertMbsToByte ( unsigned char *src,
                                            CHARSET encoding );
extern CHAR_T *TtaConvertMbsToCHAR ( unsigned char *src );
extern unsigned char *TtaConvertCHARToByte ( CHAR_T *src,
                                             CHARSET encoding );
extern CHAR_T *TtaConvertByteToCHAR ( unsigned char *src,
                                      CHARSET encoding );

#else /* __STDC__ */
extern unsigned char TtaGetCharFromWC ( wchar_t wc,
                                          CHARSET encoding );
extern wchar_t TtaConvertJisToWC ( unsigned char b1,
                                     unsigned char b2,
                                     CHARSET charset );
extern wchar_t TtaConvertSjisToWC ( unsigned char b1,
                                      unsigned char b2 );
extern int TtaJisEscMatch ( unsigned char *buf,
                              unsigned char *match,
                              int *more );
extern wchar_t TtaGetWCFromJisChar ( unsigned char c,
                                       CHARSET encoding );
extern wchar_t TtaGetWCFromChar ( unsigned char c,
                                    CHARSET encoding );
extern int TtaWCToMBstring ( wchar_t src,
                               unsigned char **dest );
extern int TtaMBstringToWC ( unsigned char **src,
                               wchar_t *dest );
extern int TtaGetNextWCFromString ( wchar_t *car,
                                      unsigned char **txt,
                                      CHARSET encoding );
extern int TtaGetNumberOfBytesToRead ( unsigned char **txt,
                                         CHARSET encoding );
extern unsigned char *TtaConvertWCToByte ( wchar_t *src,
                                             CHARSET encoding );
extern wchar_t *TtaConvertByteToWC ( unsigned char *src,
                                       CHARSET encoding );
extern unsigned char *TtaConvertByteToMbs ( unsigned char *src,
                                              CHARSET encoding );
extern unsigned char *TtaConvertMbsToByte ( unsigned char *src,
                                              CHARSET encoding );
extern CHAR_T *TtaConvertMbsToCHAR ( unsigned char *src );
extern unsigned char *TtaConvertCHARToByte ( CHAR_T *src,
                                               CHARSET encoding );
extern CHAR_T *TtaConvertByteToCHAR ( unsigned char *src,
                                        CHARSET encoding );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
