/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern CHAR_T* ufgets ( CHAR_T* string,
                        int n,
                        FILE *stream );
extern FILE* ufopen ( const CHAR_T* name,
                      const CHAR_T* mode );

#else /* __STDC__ */

extern CHAR_T* ufgets (/* CHAR_T* string,
                          int n,
                          FILE *stream */);
extern FILE* ufopen (/* const CHAR_T* name,
                        const CHAR_T* mode */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
