/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int ustrcasecmp ( STRING str1,
                         const STRING str2 );
extern int cus2iso_strcasecmp (CharUnit*, const char*);
extern int iso2cus_strcasecmp (char*, const CharUnit*);
extern STRING ustrcat ( STRING dest,
                        const STRING src );
extern STRING ustrchr ( const STRING src,
                        CHAR_T c );
extern int ustrcmp ( const STRING str1,
                     const STRING str2 );
extern int ustrcoll ( const STRING str1,
                      const STRING str2 );
extern STRING ustrcpy ( STRING dest,
                        const STRING src );
extern STRING iso2wc_strcpy ( STRING dest,
                              const char* src );
extern char* wc2iso_strcpy ( char* dest,
                             const CHAR_T* src );
extern STRING ustrdup ( const STRING str );
extern STRING iso2wc_strdup ( const char* str );
extern char* wc2iso_strdup ( const STRING str );
extern size_t ustrlen ( const STRING str );
extern int ustrncasecmp ( STRING str1,
                          const STRING str2,
                          unsigned int count );
extern STRING ustrncat ( STRING dest,
                         const STRING src,
                         unsigned int count );
extern STRING ustrncmp ( const STRING str1,
                         const STRING str2,
                         unsigned int count );
extern STRING ustrncpy ( STRING dest,
                         const STRING src,
                         unsigned int count );
extern STRING iso2wc_strncpy ( STRING dest,
                               const STRING src,
                               unsigned int count );
extern STRING ustrrchr ( const STRING str,
                         CHAR_T c );
extern STRING ustrtok ( STRING str,
                        const STRING delemiter );
extern STRING ustrstr ( const STRING str,
                        const STRING strCharSet );
extern int StringCaseCompare ( CharUnit* str1,
                               const CharUnit* str2 );
extern CharUnit* StringConcat ( CharUnit* dest,
                                const CharUnit* src );
extern CharUnit* StrChr ( const CharUnit* src,
                          CharUnit c );
extern int StringCompare ( const CharUnit* str1,
                           const CharUnit* str2 );
extern int StrColl ( const CharUnit* str1,
                     const CharUnit* str2 );
extern CharUnit* StringCopy ( CharUnit* dest,
                              const CharUnit* src );
extern CharUnit* StringDuplicate ( const CharUnit* str );
extern size_t StringLength ( const CharUnit* str );
extern int StringNCaseCompare ( CharUnit* str1,
                                const CharUnit* str2,
                                unsigned int count );
extern CharUnit* StringNConcat ( CharUnit* dest,
                                 const CharUnit* src,
                                 unsigned int count );
extern CharUnit* StringNCompare ( const CharUnit* str1,
                                  const CharUnit* str2,
                                  unsigned int count );
extern CharUnit* StringNCopy ( CharUnit* dest,
                               const CharUnit* src,
                               unsigned int count );
extern CharUnit* StrRChr ( const CharUnit* str,
                           CharUnit c );
extern CharUnit* StringToken ( CharUnit* str,
                               const CharUnit* delemiter );
extern CharUnit* StringSubstring ( const CharUnit* str,
                                   const CharUnit* strCharSet );

#else /* __STDC__ */

extern int ustrcasecmp (/* STRING str1,
                           const STRING str2 */);
extern int cus2iso_strcasecmp (/* CharUnit*, const char* */);
extern int iso2cus_strcasecmp (/* char*, const CharUnit* */);
extern STRING ustrcat (/* STRING dest,
                          const STRING src */);
extern STRING ustrchr (/* const STRING src,
                          CHAR_T c */);
extern int ustrcmp (/* const STRING str1,
                       const STRING str2 */);
extern int ustrcoll (/* const STRING str1,
                        const STRING str2 */);
extern STRING ustrcpy (/* STRING dest,
                          const STRING src */);
extern STRING iso2wc_strcpy (/* STRING dest,
                                const char* src */);
extern char* wc2iso_strcpy (/* char* dest,
                               const CHAR_T* src */);
extern STRING ustrdup (/* const STRING str */);
extern STRING iso2wc_strdup (/* const char* str */);
extern char* wc2iso_strdup (/* const STRING str */);
extern size_t ustrlen (/* const STRING str */);
extern int ustrncasecmp (/* STRING str1,
                            const STRING str2,
                            unsigned int count */);
extern STRING ustrncat (/* STRING dest,
                           const STRING src,
                           unsigned int count */);
extern STRING ustrncmp (/* const STRING str1,
                           const STRING str2,
                           unsigned int count */);
extern STRING ustrncpy (/* STRING dest,
                           const STRING src,
                           unsigned int count */);
extern STRING iso2wc_strncpy (/* STRING dest,
                                 const STRING src,
                                 unsigned int count */);
extern STRING ustrrchr (/* const STRING str,
                           CHAR_T c */);
extern STRING ustrtok (/* STRING str,
                          const STRING delemiter */);
extern STRING ustrstr (/* const STRING str,
                          const STRING strCharSet */);
extern int StringCaseCompare (/* CharUnit* str1,
                                 const CharUnit* str2 */);
extern CharUnit* StringConcat (/* CharUnit* dest,
                                  const CharUnit* src */);
extern CharUnit* StrChr (/* const CharUnit* src,
                            CharUnit c */);
extern int StringCompare (/* const CharUnit* str1,
                             const CharUnit* str2 */);
extern int StrColl (/* const CharUnit* str1,
                       const CharUnit* str2 */);
extern CharUnit* StringCopy (/* CharUnit* dest,
                                const CharUnit* src */);
extern CharUnit* StringDuplicate (/* const CharUnit* str */);
extern size_t StringLength (/* const CharUnit* str */);
extern int StringNCaseCompare (/* CharUnit* str1,
                                  const CharUnit* str2,
                                  unsigned int count */);
extern CharUnit* StringNConcat (/* CharUnit* dest,
                                   const CharUnit* src,
                                   unsigned int count */);
extern CharUnit* StringNCompare (/* const CharUnit* str1,
                                    const CharUnit* str2,
                                    unsigned int count */);
extern CharUnit* StringNCopy (/* CharUnit* dest,
                                 const CharUnit* src,
                                 unsigned int count */);
extern CharUnit* StrRChr (/* const CharUnit* str,
                             CharUnit c */);
extern CharUnit* StringToken (/* CharUnit* str,
                                 const CharUnit* delemiter */);
extern CharUnit* StringSubstring (/* const CharUnit* str,
                                     const CharUnit* strCharSet */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
