/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotBool PaginatedView ( PtrDocument pDoc,
                                int view,
                                ThotBool assoc );
extern void GetViewFromFrame ( int nframe,
                               PtrDocument pDoc,
                               int *viewNum,
                               ThotBool * assoc );
extern void GetDocAndView ( int frame,
                            PtrDocument * pDoc,
                            int *viewNum,
                            ThotBool * assoc );
extern int BuildDocumentViewList ( PtrDocument pDoc,
                                   AvailableView viewList );
extern void ChangeDocumentName ( PtrDocument pDoc,
                                 STRING newName );
extern void TtaSetDocumentName ( Document document,
                                 STRING documentName );
extern void ViewClosed ( int nFrame );
extern void OpenDefaultViews ( PtrDocument pDoc );
extern int CreateAbstractImage ( PtrDocument pDoc,
                                 int v,
                                 int r,
                                 PtrSSchema pSS,
                                 int chosenView,
                                 ThotBool begin,
                                 PtrElement viewRoot );
extern void OpenCreatedView ( PtrDocument pDoc,
                              int view,
                              ThotBool assoc,
                              int X,
                              int Y,
                              int width,
                              int height );
extern int OpenViewByName ( PtrDocument pDoc,
                            Name viewName,
                            int X,
                            int Y,
                            int width,
                            int height );
extern void OpenViewByMenu ( PtrDocument pDoc,
                             int menuItem,
                             PtrElement subTree,
                             DocViewNumber selectedView );
extern void BuildViewList ( PtrDocument pDoc,
                            STRING buffer,
                            int *nItems );
extern void CloseView ( PtrDocument pDoc,
                        int viewNb,
                        ThotBool assoc );

#else /* __STDC__ */

extern ThotBool PaginatedView (/* PtrDocument pDoc,
                                  int view,
                                  ThotBool assoc */);
extern void GetViewFromFrame (/* int nframe,
                                 PtrDocument pDoc,
                                 int *viewNum,
                                 ThotBool * assoc */);
extern void GetDocAndView (/* int frame,
                              PtrDocument * pDoc,
                              int *viewNum,
                              ThotBool * assoc */);
extern int BuildDocumentViewList (/* PtrDocument pDoc,
                                     AvailableView viewList */);
extern void ChangeDocumentName (/* PtrDocument pDoc,
                                   STRING newName */);
extern void TtaSetDocumentName (/* Document document,
                                   STRING documentName */);
extern void ViewClosed (/* int nFrame */);
extern void OpenDefaultViews (/* PtrDocument pDoc */);
extern int CreateAbstractImage (/* PtrDocument pDoc,
                                   int v,
                                   int r,
                                   PtrSSchema pSS,
                                   int chosenView,
                                   ThotBool begin,
                                   PtrElement viewRoot */);
extern void OpenCreatedView (/* PtrDocument pDoc,
                                int view,
                                ThotBool assoc,
                                int X,
                                int Y,
                                int width,
                                int height */);
extern int OpenViewByName (/* PtrDocument pDoc,
                              Name viewName,
                              int X,
                              int Y,
                              int width,
                              int height */);
extern void OpenViewByMenu (/* PtrDocument pDoc,
                               int menuItem,
                               PtrElement subTree,
                               DocViewNumber selectedView */);
extern void BuildViewList (/* PtrDocument pDoc,
                              STRING buffer,
                              int *nItems */);
extern void CloseView (/* PtrDocument pDoc,
                          int viewNb,
                          ThotBool assoc */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
