/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern ThotDrawable XbmCreate ( char *fn,
                                PictInfo *imageDesc,
                                int *xif,
                                int *yif,
                                int *wif,
                                int *hif,
                                unsigned long bgPixel,
                                int *width,
                                int *height,
                                int zoom );
extern void XbmPrint ( char *fn,
                       PictureScaling pres,
                       int xif,
                       int yif,
                       int wif,
                       int hif,
                       FILE *fd,
                       unsigned int bgPixel );
extern ThotBool IsXbmFormat ( char *fn );

#else /* __STDC__ */

extern ThotDrawable XbmCreate (/* char *fn,
                                  PictInfo *imageDesc,
                                  int *xif,
                                  int *yif,
                                  int *wif,
                                  int *hif,
                                  unsigned long bgPixel,
                                  int *width,
                                  int *height,
                                  int zoom */);
extern void XbmPrint (/* char *fn,
                         PictureScaling pres,
                         int xif,
                         int yif,
                         int wif,
                         int hif,
                         FILE *fd,
                         unsigned int bgPixel */);
extern ThotBool IsXbmFormat (/* char *fn */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
