/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int XpmCreatePixmapFromBuffer ( Display * display,
                                       Drawable d,
                                       char *buffer,
                                       Pixmap * pixmap_return,
                                       Pixmap * shapemask_return,
                                       XpmAttributes * attributes );

#else /* __STDC__ */

extern int XpmCreatePixmapFromBuffer (/* Display * display,
                                         Drawable d,
                                         char *buffer,
                                         Pixmap * pixmap_return,
                                         Pixmap * shapemask_return,
                                         XpmAttributes * attributes */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
