/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern xpmHashAtom * xpmHashSlot ( xpmHashTable *table,
                                   char *s );
extern int xpmHashIntern ( xpmHashTable *table,
                           char *tag,
                           void *data );
extern int xpmHashTableInit ( xpmHashTable *table );
extern void xpmHashTableFree ( xpmHashTable *table );

#else /* __STDC__ */

extern xpmHashAtom * xpmHashSlot (/* xpmHashTable *table,
                                     char *s */);
extern int xpmHashIntern (/* xpmHashTable *table,
                             char *tag,
                             void *data */);
extern int xpmHashTableInit (/* xpmHashTable *table */);
extern void xpmHashTableFree (/* xpmHashTable *table */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
