/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int xpmParseData ( xpmData * data,
                          XpmImage * image,
                          XpmInfo * info );

#else /* __STDC__ */

extern int xpmParseData (/* xpmData * data,
                            XpmImage * image,
                            XpmInfo * info */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
