/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern BookmarkP Bookmark_new ( void );
extern void Bookmark_free ( BookmarkP me );
extern ThotBool BMList_delItem ( void *me );
extern char * BM_GetMDate ( void *object );

#else /* __STDC__ */

extern BookmarkP Bookmark_new (/* void */);
extern void Bookmark_free (/* BookmarkP me */);
extern ThotBool BMList_delItem (/* void *me */);
extern char * BM_GetMDate (/* void *object */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
