/*
 *
 *  (c) COPYRIGHT MIT and INRIA, 1996.
 *  Please first read the full copyright statement in file COPYRIGHT.
 *
 */

int                 AMAYA;

/* Index of amaya message table */

#define AM_FILES                        0
#define AM_OPEN_URL	                1
#define AM_CLEAR	                2
#define AM_SAVED			3
#define AM_ATTRIBUTE	                4
#define AM_HREF_VALUE                   5
#define AM_TEXT		                6
#define AM_NAME		                7
#define AM_PASSWORD	                8
#define AM_DEF_CLASS	                9
#define AM_APPLY_CLASS	               10
#define AM_SEL_CLASS	               11
#define AM_FETCHING	               12
#define AM_CANNOT_LOAD	               13
#define AM_DOCUMENT_LOADED             14
#define AM_SEL_TARGET	               15
#define AM_INVALID_TARGET	       16
#define AM_LOCATION	               17
#define AM_TITLE	               18
#define AM_DOC_MODIFIED	               19
#define AM_RED_FETCHING	               20
#define AM_REDIRECTIONS_LIMIT	       21
#define AM_CANNOT_CREATE_FILE	       22
#define AM_WAITING_FOR_SOCKET	       23
#define AM_PROG_READ	               24
#define AM_PROG_WRITE	               25
#define AM_WAITING_FOR_CONNECTION      26
#define AM_CONTACTING_HOST	       27
#define AM_LOOKING_HOST	               28
#define AM_UNKNOWN_STATUS              29
#define AM_GET_AUTHENTICATION 	       30
#define AM_AUTHENTICATION_FAILURE      31
#define AM_LOADED_NO_DATA	       32
#define AM_LOAD_ABORT	               33
#define AM_NOT_AVAILABLE_RETRY	       34
#define AM_ELEMENT_LOADED	       35
#define AM_REMOTE_SAVING	       36
#define AM_CANNOT_SAVE		       37
#define AM_SYSTEM_ERROR		       38
#define AM_INVALID_ANCHOR1	       39
#define AM_INVALID_ANCHOR2	       40
#define AM_GET_UNSUPPORTED_PROTOCOL    41
#define AM_PUT_UNSUPPORTED_PROTOCOL    42
#define AM_UNSUPPORTED_FEATURE	       43
#define AM_WROTE_OBJECT		       44
#define AM_BAD_URL		       45
#define AM_CACHE_ERROR		       46
#define AM_NO_TRANS		       47
#define AM_TRANS_FAILED		       48
#define AM_TRANS_PARSE_ERROR	       49
#define AM_ADD                         50
#define AM_SHOW                        51
#define AM_BROWSE                      52
#define AM_EXTERNAL_CSS                53
#define AM_DELETE_CSS                  54
#define AM_DELETE                      55
#define AM_SAVE                        56
#define AM_SAVE_AS                     57
#define AM_RELOAD                      58
#define AM_NEW                         59
#define AM_CSS                         60
#define AM_WARNING_SAVE_OVERWRITE      61
#define AM_URL_SAVE_FAILED             62
#define AM_SAVE_DISK                   63
#define AM_BCOPY_IMAGES                64
#define AM_BTRANSFORM_URL              65
#define AM_DOC_LOCATION                66
#define AM_IMAGES_LOCATION             67
#define AM_OBJECT_LOCATION             68
#define AM_DOC_STYLE                   69
#define AM_USER_PREFERENCES            70
#define AM_CSS_FILE_1                  71
#define AM_RULE_LIST_FILE_1            72
#define AM_CSS_FILE_2                  73
#define AM_RULE_LIST_FILE_2            74
#define AM_SELECT_EXTERNAL_STYLE_SHEET 75
#define AM_DELETE_STYLE_SHEET          76
#define AM_SYS_ERROR_TMPL              77
#define AM_GET_USER_NAME               78
#define AM_WAITING_REQUESTS            79
#define AM_CACHE_GC                    80
#define AM_BUTTON_INTERRUPT            81
#define AM_BUTTON_PREVIOUS             82
#define AM_BUTTON_NEXT                 83
#define AM_BUTTON_RELOAD               84
#define AM_BUTTON_SAVE                 85
#define AM_BUTTON_PRINT                86
#define AM_BUTTON_SEARCH               87
#define AM_BUTTON_ITALICS              88
#define AM_BUTTON_BOLD                 89
#define AM_BUTTON_CODE                 90
#define AM_BUTTON_CSS                  91
#define AM_BUTTON_IMG                  92
#define AM_BUTTON_H1                   93
#define AM_BUTTON_H2                   94
#define AM_BUTTON_H3                   95
#define AM_BUTTON_UL                   96
#define AM_BUTTON_OL                   97
#define AM_BUTTON_DL                   98
#define AM_BUTTON_LINK		       99
#define AM_BUTTON_TABLE               100
#define AM_NO_NAME                    101
#define AM_BUTTON_PLUGIN              102
#define AM_UNKNOWN_SAVE_ERROR         103
#define AM_CANT_CONNECT_TO_HOST       104
#define AM_FORBIDDEN_ACCESS           105
#define AM_REQUEST_SUCCEEDED          106
#define AM_CREATED_NEW_REMOTE_RESSOURCE 107
#define AM_UPDATED_REMOTE_RESSOURCE   108
#define AM_UNKNOWN_XXX_STATUS         109
#define AM_SERVER_DID_NOT_UNDERSTAND_REQ_SYNTAX 110
#define AM_NO_DATA                    111
#define AM_METHOD_NOT_ALLOWED         112
#define AM_PLEASE_AUTHENTICATE        113
#define AM_VERIFYING                  114
#define AM_SAVING_FAILED              115
#define AM_SAVE_COMPARE_FAILED        116
#define AM_SAVE_REDIRECTED            117
#define AM_SAVE_RELOAD_FAILED         118
#define AM_SERVER_INTERNAL_ERROR_500_CAUSE 119
#define AM_SERVER_INTERNAL_ERROR_500_NO_CAUSE 120
#define AM_SERVER_NOT_IMPLEMENTED_501_ERROR 121
#define AM_PARSE		      122
#define AM_ACTIVE_TRANSFERS	      123
#define AM_WAITING_TRANSFERS	      124
#define AM_PRINT_TOC		      125
#define AM_NUMBERED_LINKS	      126
#define AM_BUTTON_JAVA                127
#define AM_REPEAT_MODE                128
#define AM_REPEAT                     129
#define AM_REPEAT_X                   130
#define AM_REPEAT_Y                   131
#define AM_NO_REPEAT                  132
#define AM_ABOUT1                     133
#define AM_ABOUT2                     134
#define AM_BUTTON_MATH                135
#define AM_TOO_LONG_URL               136
#define AM_CSS_ERROR		      137
#define AM_INVALID_TYPE		      138
#define AM_UPDATED_LINK		      139
#define AM_NOTHING_TO_SAVE	      140
#define AMAYA_MSG_MAX                 141
