/* Types and attributes for the document type HTML */

/* Global attributes */
#define HTML_ATTR_Langue 1
#define HTML_ATTR_Class 2
#define HTML_ATTR_PseudoClass 3
#define HTML_ATTR_Style_ 4
#define HTML_ATTR_Invalid_attribute 5
#define HTML_ATTR_Ghost_restruct 6

/* Local attributes */
#define HTML_ATTR_background_ 7
#define HTML_ATTR_BackgroundColor 8
#define HTML_ATTR_TextColor 9
#define HTML_ATTR_LinkColor 10
#define HTML_ATTR_VisitedLinkColor 11
#define HTML_ATTR_ActiveLinkColor 12
#define HTML_ATTR_Prompt 13
#define HTML_ATTR_Notation 14
#define HTML_ATTR_http_equiv 15
#define HTML_ATTR_meta_name 16
#define HTML_ATTR_meta_content 17
#define HTML_ATTR_HREF_ 18
#define HTML_ATTR_REL 19
#define HTML_ATTR_REV 20
#define HTML_ATTR_Title 21
#define HTML_ATTR_METHODS 22
#define HTML_ATTR_Selector 23
#define HTML_ATTR_Align 24
#define HTML_ATTR_Align_VAL_left_ 1
#define HTML_ATTR_Align_VAL_center_ 2
#define HTML_ATTR_Align_VAL_right_ 3
#define HTML_ATTR_NoShade 25
#define HTML_ATTR_NoShade_VAL_NoShade_ 1
#define HTML_ATTR_Size_ 26
#define HTML_ATTR_Width__ 27
#define HTML_ATTR_IntWidthPercent 28
#define HTML_ATTR_IntWidthPxl 29
#define HTML_ATTR_WidthElement 30
#define HTML_ATTR_NAME 31
#define HTML_ATTR_Alignment 32
#define HTML_ATTR_Alignment_VAL_Top_ 1
#define HTML_ATTR_Alignment_VAL_Middle_ 2
#define HTML_ATTR_Alignment_VAL_Bottom_ 3
#define HTML_ATTR_Alignment_VAL_Left_ 4
#define HTML_ATTR_Alignment_VAL_Right_ 5
#define HTML_ATTR_Height_ 33
#define HTML_ATTR_Width_ 34
#define HTML_ATTR_hspace 35
#define HTML_ATTR_vspace 36
#define HTML_ATTR_Img_border 37
#define HTML_ATTR_ISMAP 38
#define HTML_ATTR_ISMAP_VAL_Yes_ 1
#define HTML_ATTR_USEMAP 39
#define HTML_ATTR_SRC 40
#define HTML_ATTR_ALT 41
#define HTML_ATTR_BaseFontSize 42
#define HTML_ATTR_Font_size 43
#define HTML_ATTR_IntSizeIncr 44
#define HTML_ATTR_IntSizeDecr 45
#define HTML_ATTR_IntSizeRel 46
#define HTML_ATTR_color 47
#define HTML_ATTR_codebase 48
#define HTML_ATTR_code 49
#define HTML_ATTR_applet_name 50
#define HTML_ATTR_alt 51
#define HTML_ATTR_Param_name 52
#define HTML_ATTR_Param_value 53
#define HTML_ATTR_BulletStyle 54
#define HTML_ATTR_BulletStyle_VAL_disc 1
#define HTML_ATTR_BulletStyle_VAL_circle 2
#define HTML_ATTR_BulletStyle_VAL_square 3
#define HTML_ATTR_COMPACT 55
#define HTML_ATTR_COMPACT_VAL_Yes_ 1
#define HTML_ATTR_NumberStyle 56
#define HTML_ATTR_NumberStyle_VAL_Arabic_ 1
#define HTML_ATTR_NumberStyle_VAL_LowerAlpha 2
#define HTML_ATTR_NumberStyle_VAL_UpperAlpha 3
#define HTML_ATTR_NumberStyle_VAL_LowerRoman 4
#define HTML_ATTR_NumberStyle_VAL_UpperRoman 5
#define HTML_ATTR_Start 57
#define HTML_ATTR_ItemStyle 58
#define HTML_ATTR_ItemStyle_VAL_disc 1
#define HTML_ATTR_ItemStyle_VAL_circle 2
#define HTML_ATTR_ItemStyle_VAL_square 3
#define HTML_ATTR_ItemStyle_VAL_Arabic_ 4
#define HTML_ATTR_ItemStyle_VAL_LowerAlpha 5
#define HTML_ATTR_ItemStyle_VAL_UpperAlpha 6
#define HTML_ATTR_ItemStyle_VAL_LowerRoman 7
#define HTML_ATTR_ItemStyle_VAL_UpperRoman 8
#define HTML_ATTR_IntItemStyle 59
#define HTML_ATTR_IntItemStyle_VAL_disc 1
#define HTML_ATTR_IntItemStyle_VAL_circle 2
#define HTML_ATTR_IntItemStyle_VAL_square 3
#define HTML_ATTR_IntItemStyle_VAL_Arabic_ 4
#define HTML_ATTR_IntItemStyle_VAL_LowerAlpha 5
#define HTML_ATTR_IntItemStyle_VAL_UpperAlpha 6
#define HTML_ATTR_IntItemStyle_VAL_LowerRoman 7
#define HTML_ATTR_IntItemStyle_VAL_UpperRoman 8
#define HTML_ATTR_ItemValue 60
#define HTML_ATTR_Script_URL 61
#define HTML_ATTR_METHOD 62
#define HTML_ATTR_METHOD_VAL_Get_ 1
#define HTML_ATTR_METHOD_VAL_Post_ 2
#define HTML_ATTR_ENCTYPE 63
#define HTML_ATTR_Rows 64
#define HTML_ATTR_Columns 65
#define HTML_ATTR_Default_Value 66
#define HTML_ATTR_Multiple 67
#define HTML_ATTR_Multiple_VAL_Yes_ 1
#define HTML_ATTR_Selected 68
#define HTML_ATTR_Selected_VAL_Yes_ 1
#define HTML_ATTR_DefaultSelected 69
#define HTML_ATTR_DefaultSelected_VAL_Yes_ 1
#define HTML_ATTR_Checked 70
#define HTML_ATTR_Checked_VAL_Yes_ 1
#define HTML_ATTR_Checked_VAL_No_ 2
#define HTML_ATTR_DefaultChecked 71
#define HTML_ATTR_DefaultChecked_VAL_Yes_ 1
#define HTML_ATTR_DefaultChecked_VAL_No_ 2
#define HTML_ATTR_Area_Size 72
#define HTML_ATTR_MaxLength 73
#define HTML_ATTR_Border 74
#define HTML_ATTR_Table_align 75
#define HTML_ATTR_Table_align_VAL_Align_left 1
#define HTML_ATTR_Table_align_VAL_Center_ 2
#define HTML_ATTR_Table_align_VAL_Align_right 3
#define HTML_ATTR_cellspacing 76
#define HTML_ATTR_cellpadding 77
#define HTML_ATTR_Position 78
#define HTML_ATTR_Position_VAL_Position_top 1
#define HTML_ATTR_Position_VAL_Position_bottom 2
#define HTML_ATTR_Col_width_percent 79
#define HTML_ATTR_Col_width_pxl 80
#define HTML_ATTR_IntMaxVol 81
#define HTML_ATTR_Row_align 82
#define HTML_ATTR_Row_align_VAL_Row_left 1
#define HTML_ATTR_Row_align_VAL_Row_center 2
#define HTML_ATTR_Row_align_VAL_Row_right 3
#define HTML_ATTR_Row_valign 83
#define HTML_ATTR_Row_valign_VAL_Row_top 1
#define HTML_ATTR_Row_valign_VAL_Row_middle 2
#define HTML_ATTR_Row_valign_VAL_Row_bottom 3
#define HTML_ATTR_Row_valign_VAL_Row_baseline 4
#define HTML_ATTR_Ref_column 84
#define HTML_ATTR_ColExt 85
#define HTML_ATTR_RowExt 86
#define HTML_ATTR_colspan 87
#define HTML_ATTR_rowspan 88
#define HTML_ATTR_Cell_align 89
#define HTML_ATTR_Cell_align_VAL_Cell_left 1
#define HTML_ATTR_Cell_align_VAL_Cell_center 2
#define HTML_ATTR_Cell_align_VAL_Cell_right 3
#define HTML_ATTR_Cell_valign 90
#define HTML_ATTR_Cell_valign_VAL_Cell_top 1
#define HTML_ATTR_Cell_valign_VAL_Cell_middle 2
#define HTML_ATTR_Cell_valign_VAL_Cell_bottom 3
#define HTML_ATTR_Cell_valign_VAL_Cell_baseline 4
#define HTML_ATTR_Cell_width 91
#define HTML_ATTR_Cell_height 92
#define HTML_ATTR_Word_wrap 93
#define HTML_ATTR_Word_wrap_VAL_Wrap 1
#define HTML_ATTR_Word_wrap_VAL_No_wrap 2
#define HTML_ATTR_Ref_IMG 94
#define HTML_ATTR_shape 95
#define HTML_ATTR_shape_VAL_rectangle 1
#define HTML_ATTR_shape_VAL_circle 2
#define HTML_ATTR_shape_VAL_polygon 3
#define HTML_ATTR_shape_VAL_default_ 4
#define HTML_ATTR_coords 96
#define HTML_ATTR_nohref 97
#define HTML_ATTR_nohref_VAL_Yes_ 1
#define HTML_ATTR_x_coord 98
#define HTML_ATTR_y_coord 99
#define HTML_ATTR_width_ 100
#define HTML_ATTR_height_ 101
#define HTML_ATTR_AreaRef_IMG 102

/* Basic elements */
#define HTML_EL_TEXT_UNIT 1
#define HTML_EL_GRAPHICS_UNIT 2
#define HTML_EL_SYMBOL_UNIT 3
#define HTML_EL_PICTURE_UNIT 4
#define HTML_EL_PAGE_BREAK 6

/* Constants */
#define HTML_EL_C_Empty 8
#define HTML_EL_C_Foot 9
#define HTML_EL_C_Head 10

/* Elements */
#define HTML_EL_HTML 11
#define HTML_EL_BODY 12
#define HTML_EL_Invalid_element 13
#define HTML_EL_Comment_ 14
#define HTML_EL_Comment_line 15
#define HTML_EL_HEAD 16
#define HTML_EL_Document_URL 17
#define HTML_EL_TITLE 18
#define HTML_EL_ISINDEX 19
#define HTML_EL_Styles 20
#define HTML_EL_Scripts 21
#define HTML_EL_SCRIPT 22
#define HTML_EL_Metas 23
#define HTML_EL_Links 24
#define HTML_EL_META 25
#define HTML_EL_LINK 26
#define HTML_EL_StyleRule 27
#define HTML_EL_BASE 28
#define HTML_EL_Element 29
#define HTML_EL_Block_Quote 30
#define HTML_EL_Address 31
#define HTML_EL_Horizontal_Rule 32
#define HTML_EL_AddressContent 33
#define HTML_EL_Basic_Set 34
#define HTML_EL_Heading 35
#define HTML_EL_H1 36
#define HTML_EL_H2 37
#define HTML_EL_H3 38
#define HTML_EL_H4 39
#define HTML_EL_H5 40
#define HTML_EL_H6 41
#define HTML_EL_Paragraph 42
#define HTML_EL_Preformatted 43
#define HTML_EL_Pre_Line 44
#define HTML_EL_Anchor 45
#define HTML_EL_Basic_Elem 46
#define HTML_EL_BaseFont 47
#define HTML_EL_Font 48
#define HTML_EL_Italic_text 49
#define HTML_EL_Bold_text 50
#define HTML_EL_Teletype_text 51
#define HTML_EL_Struck_text 52
#define HTML_EL_Big_text 53
#define HTML_EL_Small_text 54
#define HTML_EL_Subscript 55
#define HTML_EL_Superscript 56
#define HTML_EL_Phrase 57
#define HTML_EL_Emphasis 58
#define HTML_EL_Strong 59
#define HTML_EL_Def 60
#define HTML_EL_Code 61
#define HTML_EL_Sample 62
#define HTML_EL_Keyboard 63
#define HTML_EL_Variable 64
#define HTML_EL_Cite 65
#define HTML_EL_Font_ 66
#define HTML_EL_Applet 67
#define HTML_EL_Applet_Content 68
#define HTML_EL_Parameter 69
#define HTML_EL_Block 70
#define HTML_EL_Center 71
#define HTML_EL_Division 72
#define HTML_EL_List_ 73
#define HTML_EL_Unnumbered_List 74
#define HTML_EL_Numbered_List 75
#define HTML_EL_Directory 76
#define HTML_EL_Menu 77
#define HTML_EL_Definition_List 78
#define HTML_EL_List_Item 79
#define HTML_EL_Definition_Item 80
#define HTML_EL_Term_List 81
#define HTML_EL_Term 82
#define HTML_EL_Definition 83
#define HTML_EL_Form 84
#define HTML_EL_Form_Element 85
#define HTML_EL_Text_Area 86
#define HTML_EL_Option_Menu 87
#define HTML_EL_Option 88
#define HTML_EL_Toggle_Menu 89
#define HTML_EL_Toggle_Item 90
#define HTML_EL_Checkbox_Input 91
#define HTML_EL_Radio_Menu 92
#define HTML_EL_Radio_Item 93
#define HTML_EL_Radio_Input 94
#define HTML_EL_Text_Input_Line 95
#define HTML_EL_Text_Input 96
#define HTML_EL_Command_Line 97
#define HTML_EL_Reset_Input 98
#define HTML_EL_Space 99
#define HTML_EL_Submit_Input 100
#define HTML_EL_Input 101
#define HTML_EL_Hidden_Input 102
#define HTML_EL_Password_Input 103
#define HTML_EL_File_Input 104
#define HTML_EL_Text_With_Frame 105
#define HTML_EL_Inserted_Text 106
#define HTML_EL_Frame 107
#define HTML_EL_Table 108
#define HTML_EL_CAPTION 109
#define HTML_EL_Table_head 110
#define HTML_EL_thead 111
#define HTML_EL_Table_body 112
#define HTML_EL_tbody 113
#define HTML_EL_tfoot 114
#define HTML_EL_Table_foot 115
#define HTML_EL_Column_head 116
#define HTML_EL_Table_row 117
#define HTML_EL_Table_cell 118
#define HTML_EL_Data_cell 119
#define HTML_EL_Heading_cell 120
#define HTML_EL_Table_cell_ghost 121
#define HTML_EL_MAP 122
#define HTML_EL_AREA 123
