#
# Makefile.svg
# Autoconf Fragment when using SVG
# Irene Vatton 1998-2003
#

AMAYA_SVG_OPTIONS=-D_SVG

AMAYA_SVG_OBJ= \
	anim.o \
	animbuilder.o \
	SVGAPP.o \
	SVGbuilder.o \
	SVGedit.o \
	TimelineAPP.o

AMAYA_SVG_SRC= \
	anim.c \
	animbuilder.c \
        SVG.h \
	SVGAPP.c \
	SVGbuilder.c \
	SVGedit.c \
	Timeline.h \
	TimelineAPP.c 


AMAYA_SVG_INCLUDES= 

SVG_SCHEMAS= $(AMAYA)/SVG.S $(AMAYA)/SVGP.P $(AMAYA)/SVGT.T \
	$(AMAYA)/Timeline.S $(AMAYA)/TimelineP.P $(AMAYA)/TimelineT.T

svg_schema= compSVG compSVGP compSVGT \
	compTimeline compTimelineP compTimelineT SVG.h


#
# Structure schema compilation.
#
compSVG : $(AMAYA)/SVG.STR
$(AMAYA)/SVG.STR : $(AMAYA)/SVG.S ../bin/str ../bin/prs ../bin/tra
	STR=`pwd`/../bin/str;PRS=`pwd`/../bin/prs;TRA=`pwd`/../bin/tra;\
	cd $(AMAYA); THOTDIR=`pwd`/.. ;export THOTDIR; \
	$$STR $(ALL_AMAYA_OPTIONS) SVG ; \
	$$PRS $(ALL_AMAYA_OPTIONS) SVGP ; \
	$$TRA $(ALL_AMAYA_OPTIONS) -DXML SVGT SVGTX ; \
	$$TRA $(ALL_AMAYA_OPTIONS) SVGT

#
# Presentation schemas compilation
#
compSVGP : $(AMAYA)/SVGP.PRS
$(AMAYA)/SVGP.PRS : $(AMAYA)/SVGP.P ../bin/prs
	PRS=`pwd`/../bin/prs;\
	cd $(AMAYA); THOTDIR=`pwd`/.. ;export THOTDIR; \
	$$PRS $(ALL_AMAYA_OPTIONS) SVGP

#
# Traduction schemas compilation
#
compSVGT : $(AMAYA)/SVGT.TRA
$(AMAYA)/SVGT.TRA : $(AMAYA)/SVGT.T ../bin/tra
	TRA=`pwd`/../bin/tra;\
	cd $(AMAYA); THOTDIR=`pwd`/.. ;export THOTDIR; \
	$$TRA $(ALL_AMAYA_OPTIONS) -DXML SVGT SVGTX ; \
	$$TRA $(ALL_AMAYA_OPTIONS) SVGT

#
# Interface schemas compilation
#
SVG.h SVGAPP.c : $(AMAYA)/SVG.STR $(AMAYA)/SVG.A ../bin/app
	(if test "$(AMAYA)" != "" -a "$(AMAYA)" != "." ; then \
	    $(CP) $(AMAYA)/SVG.A .  ; \
	    $(CP) $(AMAYA)/SVG.STR .  ; \
	fi)
	THOTDIR=$(THOTDIR) ; export THOTDIR ; \
	../bin/app $(ALL_AMAYA_OPTIONS) SVG.A





#
# Structure schema compilation.
#
compTimeline : $(AMAYA)/Timeline.STR
$(AMAYA)/Timeline.STR : $(AMAYA)/Timeline.S ../bin/str ../bin/prs ../bin/tra
	STR=`pwd`/../bin/str;PRS=`pwd`/../bin/prs;TRA=`pwd`/../bin/tra;\
	cd $(AMAYA); THOTDIR=`pwd`/.. ;export THOTDIR; \
	$$STR $(ALL_AMAYA_OPTIONS) Timeline ; \
	$$PRS $(ALL_AMAYA_OPTIONS) TimelineP ; \
	$$TRA $(ALL_AMAYA_OPTIONS) -DXML TimelineT TimelineTX ; \
	$$TRA $(ALL_AMAYA_OPTIONS) TimelineT

#
# Presentation schemas compilation
#
compTimelineP : $(AMAYA)/TimelineP.PRS
$(AMAYA)/TimelineP.PRS : $(AMAYA)/TimelineP.P ../bin/prs
	PRS=`pwd`/../bin/prs;\
	cd $(AMAYA); THOTDIR=`pwd`/.. ;export THOTDIR; \
	$$PRS $(ALL_AMAYA_OPTIONS) TimelineP

#
# Traduction schemas compilation
#
compTimelineT : $(AMAYA)/TimelineT.TRA
$(AMAYA)/TimelineT.TRA : $(AMAYA)/TimelineT.T ../bin/tra
	TRA=`pwd`/../bin/tra;\
	cd $(AMAYA); THOTDIR=`pwd`/.. ;export THOTDIR; \
	$$TRA $(ALL_AMAYA_OPTIONS) -DXML TimelineT TimelineTX ; \
	$$TRA $(ALL_AMAYA_OPTIONS) TimelineT

#
# Interface schemas compilation
#
Timeline.h TimelineAPP.c : $(AMAYA)/Timeline.STR $(AMAYA)/Timeline.A ../bin/app
	(if test "$(AMAYA)" != "" -a "$(AMAYA)" != "." ; then \
	    $(CP) $(AMAYA)/Timeline.A .  ; \
	    $(CP) $(AMAYA)/Timeline.STR .  ; \
	fi)
	THOTDIR=$(THOTDIR) ; export THOTDIR ; \
	../bin/app $(ALL_AMAYA_OPTIONS) Timeline.A
