#
# Makefile.libwww
# Autoconf Fragment when using libWWW
# Daniel Veillard, 1997
#

AMAYA_LIBWWW_OPTIONS=

AMAYA_LIBWWW_OBJ= \
	AHTBridge.o \
	AHTFWrite.o \
	answer.o \
	query.o \
	AHTMemConv.o 

AMAYA_LIBWWW_LIBS= ../libwww.a
LIBWWW_LIBS= -L.. -lwww
AMAYA_LIBWWW_EXTRA_LIBS=

AMAYA_LIBWWW_INCLUDES= -I$(THOTDIR)/../libwww/Library/src

../libwww.a :
	@(cd .. ; $(MAKE) libwww.a)

