#
# Makefile.libwww
# Autoconf Fragment when using annotations
# Jose Kahan, Sep 1999
#

AMAYA_ANNOT_OPTIONS=-DANNOTATIONS

AMAYA_ANNOT_INCLUDES=

AMAYA_ANNOT_OBJ= \
	ANNOTevent.o \
	ANNOTfiles.o \
	ANNOTlink.o \
	ANNOTtools.o

AMAYA_ANNOT_SRC= \
	annot.h \
	ANNOTevent.c \
	ANNOTfiles.c \
	ANNOTlink.c \
	ANNOTtools.c

AMAYA_ANNOT_LIBS=

AMAYA_ANNOT_EXTRA_LIBS=

AMAYA_ANNOT_SCHEMAS=

amaya_comp_annot :  

