/* mapping table of MathML elements */
#include "MathML.h"
static ElemMapping    MathMLElemMappingTable[] =
{
   /* This table MUST be in alphabetical order */
   {TEXT("XMLPI"), SPACE, MathML_EL_XMLPI, L_Other, FALSE},
   {TEXT("XMLPI_line"), SPACE, MathML_EL_XMLPI_line, L_Other, FALSE},
   {TEXT("XMLcomment"), SPACE, MathML_EL_XMLcomment, L_Other, FALSE},
   {TEXT("XMLcomment_line"), SPACE, MathML_EL_XMLcomment_line, L_Other, FALSE},
   {TEXT("c"), SPACE, MathML_EL_TEXT_UNIT, L_Other, TRUE},
   {TEXT("maligngroup"), 'E', MathML_EL_MALIGNGROUP, L_Other, FALSE},
   {TEXT("malignmark"), 'E', MathML_EL_MALIGNMARK, L_Other, FALSE},
   {TEXT("math"), SPACE, MathML_EL_MathML, L_Other, FALSE},
   {TEXT("menclose"), SPACE, MathML_EL_MENCLOSE, L_Other, FALSE},
   {TEXT("merror"), SPACE, MathML_EL_MERROR, L_Other, FALSE},
   {TEXT("mf"), SPACE, MathML_EL_MF, L_Other, FALSE},  /* for compatibility with an old version of MathML: WD-math-970704 */
   {TEXT("mfenced"), SPACE, MathML_EL_MFENCED, L_Other, FALSE},
   {TEXT("mfrac"), SPACE, MathML_EL_MFRAC, L_Other, FALSE},
   {TEXT("mglyph"), 'E', MathML_EL_MGLYPH, L_Other, FALSE},
   {TEXT("mi"), SPACE, MathML_EL_MI, L_Other, FALSE},
   {TEXT("mlabeledtr"), SPACE, MathML_EL_MLABELEDTR, L_Other, FALSE},
   {TEXT("mmultiscripts"), SPACE, MathML_EL_MMULTISCRIPTS, L_Other, FALSE},
   {TEXT("mn"), SPACE, MathML_EL_MN, L_Other, FALSE},
   {TEXT("mo"), SPACE, MathML_EL_MO, L_Other, FALSE},
   {TEXT("mover"), SPACE, MathML_EL_MOVER, L_Other, FALSE},
   {TEXT("mpadded"), SPACE, MathML_EL_MPADDED, L_Other, FALSE},
   {TEXT("mphantom"), SPACE, MathML_EL_MPHANTOM, L_Other, FALSE},
   {TEXT("mprescripts"), SPACE, MathML_EL_PrescriptPairs, L_Other, FALSE},
   {TEXT("mroot"), SPACE, MathML_EL_MROOT, L_Other, FALSE},
   {TEXT("mrow"), SPACE, MathML_EL_MROW, L_Other, FALSE},
   {TEXT("ms"), SPACE, MathML_EL_MS, L_Other, FALSE},
   {TEXT("mspace"), 'E', MathML_EL_MSPACE, L_Other, FALSE},
   {TEXT("msqrt"), SPACE, MathML_EL_MSQRT, L_Other, FALSE},
   {TEXT("mstyle"), SPACE, MathML_EL_MSTYLE, L_Other, FALSE},
   {TEXT("msub"), SPACE, MathML_EL_MSUB, L_Other, FALSE},
   {TEXT("msubsup"), SPACE, MathML_EL_MSUBSUP, L_Other, FALSE},
   {TEXT("msup"), SPACE, MathML_EL_MSUP, L_Other, FALSE},
   {TEXT("mtable"), SPACE, MathML_EL_MTABLE, L_Other, FALSE},
   {TEXT("mtd"), SPACE, MathML_EL_MTD, L_Other, FALSE},
   {TEXT("mtext"), SPACE, MathML_EL_MTEXT, L_Other, FALSE},
   {TEXT("mtr"), SPACE, MathML_EL_MTR, L_Other, FALSE},
   {TEXT("munder"), SPACE, MathML_EL_MUNDER, L_Other, FALSE},
   {TEXT("munderover"), SPACE, MathML_EL_MUNDEROVER, L_Other, FALSE},
   {TEXT("none"), SPACE, MathML_EL_Construct, L_Other, FALSE},
   {TEXT(""), SPACE, 0, L_Other, FALSE}	 /* Last entry. Mandatory */
};

static AttributeMapping MathMLAttributeMappingTable[] =
{
   /* The first entry MUST be unknown_attr */
   /* The rest of this table MUST be in alphabetical order */
   {TEXT("unknown_attr"), TEXT(""), 'A', MathML_ATTR_Invalid_attribute, L_Other},

   {TEXT("accent"), TEXT(""), 'A', MathML_ATTR_accent, L_Other},
   {TEXT("accentunder"), TEXT(""), 'A', MathML_ATTR_accentunder, L_Other},
   {TEXT("actiontype"), TEXT(""), 'A', MathML_ATTR_actiontype, L_Other},
   {TEXT("align"), TEXT(""), 'A', MathML_ATTR_align, L_Other},
   {TEXT("alignmentscope"), TEXT(""), 'A', MathML_ATTR_alignmentscope, L_Other},
   {TEXT("alt"), TEXT(""), 'A', MathML_ATTR_alt, L_Other},
   {TEXT("altimg"), TEXT(""), 'A', MathML_ATTR_altimg, L_Other},
   {TEXT("alttext"), TEXT(""), 'A', MathML_ATTR_alttext, L_Other},
   {TEXT("background"), TEXT(""), 'A', MathML_ATTR_background_, L_Other},
   {TEXT("bevelled"), TEXT(""), 'A', MathML_ATTR_bevelled, L_Other},
   {TEXT("class"), TEXT(""), 'A', MathML_ATTR_class, L_Other},
   {TEXT("close"), TEXT(""), 'A', MathML_ATTR_close, L_Other},
   {TEXT("columnalign"), TEXT("mtd"), 'A', MathML_ATTR_columnalign_mtd, L_Other},
   {TEXT("columnalign"), TEXT(""), 'A', MathML_ATTR_columnalign, L_Other},
   {TEXT("columnlines"), TEXT(""), 'A', MathML_ATTR_columnlines, L_Other},
   {TEXT("columnspacing"), TEXT(""), 'A', MathML_ATTR_columnspacing, L_Other},
   {TEXT("columnspan"), TEXT(""), 'A', MathML_ATTR_columnspan, L_Other},
   {TEXT("columnwidth"), TEXT(""), 'A', MathML_ATTR_columnwidth, L_Other},
   {TEXT("color"), TEXT(""), 'A', MathML_ATTR_color, L_Other},
   {TEXT("denomalign"), TEXT(""), 'A', MathML_ATTR_denomalign, L_Other},
   {TEXT("depth"), TEXT(""), 'A', MathML_ATTR_depth_, L_Other},
   {TEXT("display"), TEXT(""), 'A', MathML_ATTR_display, L_Other},
   {TEXT("displaystyle"), TEXT(""), 'A', MathML_ATTR_displaystyle, L_Other},
   {TEXT("edge"), TEXT(""), 'A', MathML_ATTR_edge, L_Other},
   {TEXT("equalcolumns"), TEXT(""), 'A', MathML_ATTR_equalcolumns, L_Other},
   {TEXT("equalrows"), TEXT(""), 'A', MathML_ATTR_equalrows, L_Other},
   {TEXT("fence"), TEXT(""), 'A', MathML_ATTR_fence, L_Other},
   {TEXT("fontfamily"), TEXT(""), 'A', MathML_ATTR_fontfamily, L_Other},
   {TEXT("fontstyle"), TEXT(""), 'A', MathML_ATTR_fontstyle, L_Other},
   {TEXT("fontsize"), TEXT(""), 'A', MathML_ATTR_fontsize, L_Other},
   {TEXT("fontweight"), TEXT(""), 'A', MathML_ATTR_fontweight, L_Other},
   {TEXT("form"), TEXT(""), 'A', MathML_ATTR_form, L_Other},
   {TEXT("frame"), TEXT(""), 'A', MathML_ATTR_frame, L_Other},
   {TEXT("framespacing"), TEXT(""), 'A', MathML_ATTR_framespacing, L_Other},
   {TEXT("groupalign"), TEXT("maligngroup"), 'A', MathML_ATTR_groupalign_malgr, L_Other},
   {TEXT("groupalign"), TEXT(""), 'A', MathML_ATTR_groupalign, L_Other},
   {TEXT("height"), TEXT(""), 'A', MathML_ATTR_height_, L_Other},
   {TEXT("id"), TEXT(""), 'A', MathML_ATTR_id, L_Other},
   {TEXT("index"), TEXT(""), 'A', MathML_ATTR_index, L_Other},
   {TEXT("largeop"), TEXT(""), 'A', MathML_ATTR_largeop, L_Other},
   {TEXT("linebreak"), TEXT(""), 'A', MathML_ATTR_linebreak_, L_Other},
   {TEXT("linethickness"), TEXT(""), 'A', MathML_ATTR_linethickness, L_Other},
   {TEXT("lquote"), TEXT(""), 'A', MathML_ATTR_lquote, L_Other},
   {TEXT("lspace"), TEXT(""), 'A', MathML_ATTR_lspace, L_Other},
   {TEXT("mathbackground"), TEXT(""), 'A', MathML_ATTR_mathbackground, L_Other},
   {TEXT("mathcolor"), TEXT(""), 'A', MathML_ATTR_mathcolor, L_Other},
   {TEXT("mathsize"), TEXT(""), 'A', MathML_ATTR_mathsize, L_Other},
   {TEXT("mathvariant"), TEXT(""), 'A', MathML_ATTR_mathvariant, L_Other},
   {TEXT("maxsize"), TEXT(""), 'A', MathML_ATTR_maxsize, L_Other},
   {TEXT("minlabelspacing"), TEXT(""), 'A', MathML_ATTR_minlabelspacing, L_Other},
   {TEXT("minsize"), TEXT(""), 'A', MathML_ATTR_minsize, L_Other},
   {TEXT("mode"), TEXT(""), 'A', MathML_ATTR_display, L_Other},
   {TEXT("movablelimits"), TEXT(""), 'A', MathML_ATTR_movablelimits, L_Other},
   {TEXT("notation"), TEXT(""), 'A', MathML_ATTR_notation, L_Other},
   {TEXT("numalign"), TEXT(""), 'A', MathML_ATTR_numalign, L_Other},
   {TEXT("open"), TEXT(""), 'A', MathML_ATTR_open, L_Other},
   {TEXT("other"), TEXT(""), 'A', MathML_ATTR_other, L_Other},
   {TEXT("overflow"), TEXT(""), 'A', MathML_ATTR_overflow, L_Other},
   {TEXT("rowalign"), TEXT("mtr"), 'A', MathML_ATTR_rowalign_mtr, L_Other},
   {TEXT("rowalign"), TEXT("mlabeledtr"), 'A', MathML_ATTR_rowalign_mtr, L_Other},
   {TEXT("rowalign"), TEXT("mtd"), 'A', MathML_ATTR_rowalign_mtr, L_Other},
   {TEXT("rowalign"), TEXT(""), 'A', MathML_ATTR_rowalign, L_Other},
   {TEXT("rowlines"), TEXT(""), 'A', MathML_ATTR_rowlines, L_Other},
   {TEXT("rowspacing"), TEXT(""), 'A', MathML_ATTR_rowspacing, L_Other},
   {TEXT("rowspan"), TEXT(""), 'A', MathML_ATTR_rowspan_, L_Other},
   {TEXT("rquote"), TEXT(""), 'A', MathML_ATTR_rquote, L_Other},
   {TEXT("rspace"), TEXT(""), 'A', MathML_ATTR_rspace, L_Other},
   {TEXT("scriptlevel"), TEXT(""), 'A', MathML_ATTR_scriptlevel, L_Other},
   {TEXT("scriptminsize"), TEXT(""), 'A', MathML_ATTR_scriptminsize, L_Other},
   {TEXT("scriptsizemultiplier"), TEXT(""), 'A', MathML_ATTR_scriptsizemultiplier, L_Other},
   {TEXT("selection"), TEXT(""), 'A', MathML_ATTR_selection, L_Other},
   {TEXT("separator"), TEXT(""), 'A', MathML_ATTR_separator, L_Other},
   {TEXT("separators"), TEXT(""), 'A', MathML_ATTR_separators, L_Other},
   {TEXT("side"), TEXT(""), 'A', MathML_ATTR_side, L_Other},
   {TEXT("stretchy"), TEXT(""), 'A', MathML_ATTR_stretchy, L_Other},
   {TEXT("style"), TEXT(""), 'A', MathML_ATTR_style_, L_Other},
   {TEXT("subscriptshift"), TEXT(""), 'A', MathML_ATTR_subscriptshift, L_Other},
   {TEXT("superscriptshift"), TEXT(""), 'A', MathML_ATTR_superscriptshift, L_Other},
   {TEXT("symmetric"), TEXT(""), 'A', MathML_ATTR_symmetric, L_Other},
   {TEXT("width"), TEXT(""), 'A', MathML_ATTR_width_, L_Other},
   {TEXT("xml:space"), TEXT(""), 'A', MathML_ATTR_xml_space, L_Other},
   {TEXT("xref"), TEXT(""), 'A', MathML_ATTR_xref, L_Other},
   {TEXT("zzghost"), TEXT(""), 'A', MathML_ATTR_Ghost_restruct, L_Other},

   {TEXT(""), TEXT(""), EOS, 0, L_Other}		/* Last entry. Mandatory */
};


XmlEntity  MathEntityTable[] =
{
   /* This table MUST be in alphabetical order */
   /* This table contains characters from the Symbol font plus some
      specific MathML entities */
   {TEXT("Aacute"), 192, 'L'},
   {TEXT("Acirc"), 194, 'L'},
   {TEXT("Agr"), 65, 'G'},
   {TEXT("And"), 217, 'G'},
   {TEXT("ApplyFunction"), 129, 'L'},   /* rendered as a thin space */
   {TEXT("Backslash"), 92, 'L'},
   {TEXT("Bgr"), 66, 'G'},
   {TEXT("Cap"), 199, 'G'},
   {TEXT("CenterDot"), 215, 'G'},
   {TEXT("CirclePlus"), 197, 'G'},
   {TEXT("CircleTimes"), 196, 'G'},
   {TEXT("Colon"), 58, 'G'},
   {TEXT("Congruent"), 64, 'G'},
   {TEXT("Cup"), 200, 'G'},
   {TEXT("Del"), 209, 'G'},
   {TEXT("Delta"), 68, 'G'},
   {TEXT("Diamond"), 168, 'G'},
   {TEXT("DifferentialD"), 100, 'L'},
   {TEXT("DoubleDownArrow"), 223, 'G'},
   {TEXT("DoubleLeftArrow"), 220, 'G'},
   {TEXT("DoubleLeftRightArrow"), 219, 'G'},
   {TEXT("DoubleRightArrow"), 222, 'G'},
   {TEXT("DoubleUpArrow"), 221, 'G'},
   {TEXT("DownArrow"), 175, 'G'},
   {TEXT("DownTee"), 94, 'G'},
   {TEXT("EEgr"), 72, 'G'},
   {TEXT("Egr"), 69, 'G'},
   {TEXT("Element"), 206, 'G'},
   {TEXT("Equal"), 61, 'L'},
   {TEXT("EqualTilde"), 64, 'G'},
   {TEXT("Exists"), 36, 'G'},
   {TEXT("ExponentialE"), 101, 'L'},
   {TEXT("ForAll"), 34, 'G'},
   {TEXT("Gamma"), 71, 'G'},
   {TEXT("GreaterEqual"), 179, 'G'},
   {TEXT("Hat"), 94, 'L'},
   {TEXT("Igr"), 73, 'G'},
   {TEXT("ImaginaryI"), 105, 'L'},
   {TEXT("Integral"), 242, 'G'},
   {TEXT("Intersection"), 199, 'G'},
   {TEXT("InvisibleComma"), 129, 'L'},   /* thin space */
   {TEXT("InvisibleTimes"), 129, 'L'},   /* thin space */
   {TEXT("Kgr"), 75, 'G'},
   {TEXT("KHgr"), 67, 'G'},
   {TEXT("Lambda"), 76, 'G'},
   {TEXT("LeftAngleBracket"), 225, 'G'},
   {TEXT("LeftArrow"), 172, 'G'},
   {TEXT("LeftCeiling"), 233, 'G'},
   {TEXT("LeftFloor"), 235, 'G'},
   {TEXT("LeftRightArrow"), 171, 'G'},
   {TEXT("Mgr"), 77, 'G'},
   {TEXT("Ngr"), 78, 'G'},
   {TEXT("NonBreakingSpace"), 160, 'L'},
   {TEXT("Not"), 216, 'G'},
   {TEXT("NotElement"), 207, 'G'},
   {TEXT("NotEqual"), 185, 'G'},
   {TEXT("NotSubset"), 203, 'G'},
   {TEXT("Ogr"), 79, 'G'},
   {TEXT("Omega"), 87, 'G'},
   {TEXT("Or"), 218, 'G'},
   {TEXT("OverBar"), 45, 'G'},
   {TEXT("OverBrace"), 132, 'G'},    /* 132?? */
   {TEXT("PI"), 213, 'G'},
   {TEXT("PartialD"), 182, 'G'},
   {TEXT("Phi"), 70, 'G'},
   {TEXT("Pi"), 80, 'G'},
   {TEXT("PlusMinus"), 177, 'G'},
   {TEXT("Prime"), 178, 'G'},
   {TEXT("Product"), 213, 'G'},
   {TEXT("Proportional"), 181, 'G'},
   {TEXT("Psi"), 89, 'G'},
   {TEXT("RightAngleBracket"), 241, 'G'},
   {TEXT("RightCeiling"), 249, 'G'},
   {TEXT("RightFloor"), 251, 'G'},
   {TEXT("Rgr"), 82, 'G'},
   {TEXT("RightArrow"), 174, 'G'},
   {TEXT("Sigma"), 83, 'G'},
   {TEXT("Sol"), 164, 'G'},
   {TEXT("Star"), 42, 'L'},
   {TEXT("Subset"), 204, 'G'},
   {TEXT("SubsetEqual"), 205, 'G'},
   {TEXT("SuchThat"), 39, 'G'},
   {TEXT("Sum"), 229, 'G'},
   {TEXT("Superset"), 201, 'G'},
   {TEXT("SupersetEqual"), 202, 'G'},
   {TEXT("Tgr"), 84, 'G'},
   {TEXT("Therefore"), 92, 'G'},
   {TEXT("Theta"), 81, 'G'},
   {TEXT("ThickSpace"), 130, 'L'},
   {TEXT("ThinSpace"), 129, 'L'},
   {TEXT("Tilde"), 126, 'L'},
   {TEXT("TripleDot"), 188, 'G'},
   {TEXT("UnderBar"), 45, 'G'},
   {TEXT("UnderBrace"), 133, 'G'},    /* 133?? */
   {TEXT("Union"), 200, 'G'},
   {TEXT("UpArrow"), 173, 'G'},
   {TEXT("Upsi"), 85, 'G'},
   {TEXT("Upsi1"), 161, 'G'},
   {TEXT("Vee"), 218, 'G'},
   {TEXT("Verbar"), 189, 'G'},
   {TEXT("VerticalBar"), 124, 'L'},
   {TEXT("Xi"), 88, 'G'},
   {TEXT("Zgr"), 90, 'G'},
   {TEXT("aacute"), 224, 'L'},
   {TEXT("acirc"), 226, 'L'},
   {TEXT("acute"), 180, 'L'},
   {TEXT("af"), 129, 'L'},             /* rendered as thin space */
   {TEXT("aleph"), 192, 'G'},
   {TEXT("alpha"), 97, 'G'},
   {TEXT("and"), 217, 'G'},
   {TEXT("angle"), 208, 'G'},
   {TEXT("ap"), 187, 'G'},
   {TEXT("beta"), 98, 'G'},
   {TEXT("bot"), 94, 'G'},
   {TEXT("bottom"), 94, 'G'},
   {TEXT("bull"), 183, 'G'},
   {TEXT("cap"), 199, 'G'},
   {TEXT("chi"), 99, 'G'},
   {TEXT("circ"), 94, 'L'},
   {TEXT("clubs"), 167, 'G'},
   {TEXT("cong"), 64, 'G'},
   {TEXT("copysf"), 211, 'G'},
   {TEXT("copyssf"), 227, 'G'},
   {TEXT("cr"), 191, 'G'},
   {TEXT("cup"), 200, 'G'},
   {TEXT("dArr"), 223, 'G'},
   {TEXT("darr"), 175, 'G'},
   {TEXT("dd"), 100, 'L'},
   {TEXT("deg"), 176, 'G'},
   {TEXT("delta"), 100, 'G'},
   {TEXT("diams"), 168, 'G'},
   {TEXT("divide"), 184, 'G'},
   {TEXT("dtri"), 209, 'G'},
   {TEXT("ee"), 101, 'L'},
   {TEXT("empty"), 198, 'G'},
   {TEXT("emptyset"), 198, 'G'},
   {TEXT("emsp"), 32, 'G'},
   {TEXT("epsiv"), 101, 'G'},
   {TEXT("equiv"), 186, 'G'},
   {TEXT("eta"), 104, 'G'},
   {TEXT("exist"), 36, 'G'},
   {TEXT("florin"), 166, 'G'},
   {TEXT("forall"), 34, 'G'},
   {TEXT("gamma"), 103, 'G'},
   {TEXT("ge"), 179, 'G'},
   {TEXT("geq"), 179, 'G'},
   {TEXT("gt"), 62, 'L'},
   {TEXT("hearts"), 169, 'G'},
   {TEXT("horbar"), 190, 'G'},
   {TEXT("iff"), 219, 'G'},
   {TEXT("ifraktur"), 193, 'G'},
   {TEXT("in"), 206, 'G'},
   {TEXT("infin"), 165, 'G'},
   {TEXT("int"), 242, 'G'},
   {TEXT("iota"), 105, 'G'},
   {TEXT("isin"), 206, 'G'},
   {TEXT("it"), 129, 'L'},          /* rendered as a thin space */
   {TEXT("kappa"), 107, 'G'},
   {TEXT("lArr"), 220, 'G'},
   {TEXT("lambda"), 108, 'G'},
   {TEXT("lang"), 225, 'G'},
   {TEXT("langle"), 225, 'G'},
   {TEXT("larr"), 172, 'G'},
   {TEXT("lbrace"), 123, 'L'},
   {TEXT("lceil"), 233, 'G'},
   {TEXT("lcub"), 123, 'L'},
   {TEXT("le"), 163, 'G'},
   {TEXT("leq"), 163, 'G'},
   {TEXT("lfloor"), 235, 'G'},
   {TEXT("lowbar"), 95, 'G'},
   {TEXT("loz"), 224, 'G'},
   {TEXT("lrArr"), 219, 'G'},
   {TEXT("lrarr"), 171, 'G'},
   {TEXT("lsqb"), 91, 'G'},
   {TEXT("lt"), 60, 'L'},
   {TEXT("middot"), 215, 'G'},
   {TEXT("mldr"), 188, 'G'},
   {TEXT("mu"), 109, 'G'},
   {TEXT("nabla"), 209, 'G'},
   {TEXT("nbsp"), 160, 'L'},
   {TEXT("ne"), 185, 'G'},
   {TEXT("neq"), 185, 'G'},
   {TEXT("not"), 216, 'G'},
   {TEXT("notin"), 207, 'G'},
   {TEXT("nu"), 110, 'G'},
   {TEXT("ogr"), 111, 'G'},
   {TEXT("omega"), 119, 'G'},
   {TEXT("oplus"), 197, 'G'},
   {TEXT("or"), 218, 'G'},
   {TEXT("otimes"), 196, 'G'},
   {TEXT("part"), 182, 'G'},
   {TEXT("perp"), 94, 'G'},
   {TEXT("phi"), 102, 'G'},
   {TEXT("phiv"), 106, 'G'},
   {TEXT("pi"), 112, 'G'},
   {TEXT("piv"), 118, 'G'},
   {TEXT("prime"), 162, 'G'},
   {TEXT("prop"), 181, 'G'},
   {TEXT("psi"), 121, 'G'},
   {TEXT("rArr"), 222, 'G'},
   {TEXT("radic"), 214, 'G'},
   {TEXT("rang"), 241, 'G'},
   {TEXT("rangle"), 241, 'G'},
   {TEXT("rarr"), 174, 'G'},
   {TEXT("rbrace"), 125, 'L'},
   {TEXT("rceil"), 249, 'G'},
   {TEXT("rcub"), 125, 'L'},
   {TEXT("rdquo"), 178, 'G'},
   {TEXT("regsf"), 210, 'G'},
   {TEXT("regssf"), 226, 'G'},
   {TEXT("rfloor"), 251, 'G'},
   {TEXT("rfraktur"), 194, 'G'},
   {TEXT("rho"), 114, 'G'},
   {TEXT("rsqb"), 93, 'G'},
   {TEXT("sigma"), 115, 'G'},
   {TEXT("sigmav"), 86, 'G'},
   {TEXT("spades"), 170, 'G'},
   {TEXT("sub"), 204, 'G'},
   {TEXT("sube"), 205, 'G'},
   {TEXT("subne"), 203, 'G'},
   {TEXT("subset"), 204, 'G'},
   {TEXT("sum"), 229, 'G'},
   {TEXT("sup"), 201, 'G'},
   {TEXT("supe"), 202, 'G'},
   {TEXT("supset"), 201, 'G'},
   {TEXT("supseteq"), 202, 'G'},
   {TEXT("supseteqq"), 202, 'G'},
   {TEXT("tau"), 116, 'G'},
   {TEXT("there4"), 92, 'G'},
   {TEXT("therefore"), 92, 'G'},
   {TEXT("theta"), 113, 'G'},
   {TEXT("thetav"), 74, 'G'},
   {TEXT("thickspace"), 130, 'L'},
   {TEXT("times"), 180, 'G'},
   {TEXT("trade"), 212, 'G'},
   {TEXT("tradesf"), 212, 'G'},
   {TEXT("tradessf"), 228, 'G'},
   {TEXT("uArr"), 221, 'G'},
   {TEXT("uarr"), 173, 'G'},
   {TEXT("upsi"), 117, 'G'},
   {TEXT("vee"), 218, 'G'},
   {TEXT("weierp"), 195, 'G'},
   {TEXT("xi"), 120, 'G'},
   {TEXT("zeta"), 122, 'G'},
   {TEXT("zzzz"), -1, SPACE}		/* this last entry is required */
};

