        { Translation of ISO-Latin 1 characters into HTML 4.0 entities }
 
TextTRANSLATE Latin
  BEGIN
{ '\42' -> '&quot;'; }	{ quotation mark = APL quote, U+0022 ISOnum }
  '\46' -> '&amp;';	{ ampersand, U+0026 ISOnum }
  '\74' -> '&lt;';	{ less-than sign, U+003C ISOnum }
{ '\76' -> '&gt;'; }	{ greater-than sign, U+003E ISOnum }
  '\201' -> '&thinsp;';	{ thin space, U+2009 ISOpub }
  '\202' -> '&ensp;';	{ en space, U+2002 ISOpub }
  '\240' -> '&nbsp;';	{ no-break space = non-breaking space, U+00A0 ISOnum }
  '\241' -> '&iexcl;';	{ inverted exclamation mark, U+00A1 ISOnum }
  '\242' -> '&cent;';	{ cent sign, U+00A2 ISOnum }
  '\243' -> '&pound;';	{ pound sign, U+00A3 ISOnum }
  '\244' -> '&curren;';	{ currency sign, U+00A4 ISOnum }
  '\245' -> '&yen;';	{ yen sign = yuan sign, U+00A5 ISOnum }
  '\246' -> '&brvbar;';	{ broken bar = broken vertical bar, U+00A6 ISOnum }
  '\247' -> '&sect;';	{ section sign, U+00A7 ISOnum }
  '\250' -> '&uml;';	{ diaeresis = spacing diaeresis, U+00A8 ISOdia }
  '\251' -> '&copy;';	{ copyright sign, U+00A9 ISOnum }
  '\252' -> '&ordf;';	{ feminine ordinal indicator, U+00AA ISOnum }
  '\253' -> '&laquo;';	{ left-pointing double angle quotation mark = left pointing guillemet, U+00AB ISOnum }
  '\254' -> '&not;';	{ not sign, U+00AC ISOnum }
  '\255' -> '&hyphen;';	{ hyphen = discretionary hyphen, U+00AD ISOnum }
  '\256' -> '&reg;';	{ registered sign = registered trade mark sign, U+00AE ISOnum }
  '\257' -> '&macr;';	{ macron = spacing macron = overline = APL overbar, U+00AF ISOdia }
  '\260' -> '&deg;';	{ degree sign, U+00B0 ISOnum }
  '\261' -> '&plusmn;';	{ plus-minus sign = plus-or-minus sign, U+00B1 ISOnum }
  '\262' -> '&sup2;';	{ superscript two = superscript digit two = squared, U+00B2 ISOnum }
  '\263' -> '&sup3;';	{ superscript three = superscript digit three = cubed, U+00B3 ISOnum }
  '\264' -> '&acute;';	{ acute accent = spacing acute, U+00B4 ISOdia }
  '\265' -> '&micro;';	{ micro sign, U+00B5 ISOnum }
  '\266' -> '&para;';	{ pilcrow sign = paragraph sign, U+00B6 ISOnum }
  '\267' -> '&middot;';	{ middle dot = Georgian comma = Greek middle dot, U+00B7 ISOnum }
  '\270' -> '&cedil;';	{ cedilla = spacing cedilla, U+00B8 ISOdia }
  '\271' -> '&sup1;';	{ superscript one = superscript digit one, U+00B9 ISOnum }
  '\272' -> '&ordm;';	{ masculine ordinal indicator, U+00BA ISOnum }
  '\273' -> '&raquo;';	{ right-pointing double angle quotation mark = right pointing guillemet, U+00BB ISOnum }
  '\274' -> '&frac14;';	{ vulgar fraction one quarter = fraction one quarter, U+00BC ISOnum }
  '\275' -> '&frac12;';	{ vulgar fraction one half = fraction one half, U+00BD ISOnum }
  '\276' -> '&frac34;';	{ vulgar fraction three quarters = fraction three quarters, U+00BE ISOnum }
  '\277' -> '&iquest;';	{ inverted question mark = turned question mark, U+00BF ISOnum }
  '\300' -> '&Agrave;';	{ latin capital letter A with grave = latin capital letter A grave, U+00C0 ISOlat1 }
  '\301' -> '&Aacute;';	{ latin capital letter A with acute, U+00C1 ISOlat1 }
  '\302' -> '&Acirc;';	{ latin capital letter A with circumflex, U+00C2 ISOlat1 }
  '\303' -> '&Atilde;';	{ latin capital letter A with tilde, U+00C3 ISOlat1 }
  '\304' -> '&Auml;';	{ latin capital letter A with diaeresis, U+00C4 ISOlat1 }
  '\305' -> '&Aring;';	{ latin capital letter A with ring above = latin capital letter A ring, U+00C5 ISOlat1 }
  '\306' -> '&AElig;';	{ latin capital letter AE = latin capital ligature AE, U+00C6 ISOlat1 }
  '\307' -> '&Ccedil;';	{ latin capital letter C with cedilla, U+00C7 ISOlat1 }
  '\310' -> '&Egrave;';	{ latin capital letter E with grave, U+00C8 ISOlat1 }
  '\311' -> '&Eacute;';	{ latin capital letter E with acute, U+00C9 ISOlat1 }
  '\312' -> '&Ecirc;';	{ latin capital letter E with circumflex, U+00CA ISOlat1 }
  '\313' -> '&Euml;';	{ latin capital letter E with diaeresis, U+00CB ISOlat1 }
  '\314' -> '&Igrave;';	{ latin capital letter I with grave, U+00CC ISOlat1 }
  '\315' -> '&Iacute;';	{ latin capital letter I with acute, U+00CD ISOlat1 }
  '\316' -> '&Icirc;';	{ latin capital letter I with circumflex, U+00CE ISOlat1 }
  '\317' -> '&Iuml;';	{ latin capital letter I with diaeresis, U+00CF ISOlat1 }
  '\320' -> '&ETH;';	{ latin capital letter ETH, U+00D0 ISOlat1 }
  '\321' -> '&Ntilde;';	{ latin capital letter N with tilde, U+00D1 ISOlat1 }
  '\322' -> '&Ograve;';	{ latin capital letter O with grave, U+00D2 ISOlat1 }
  '\323' -> '&Oacute;';	{ latin capital letter O with acute, U+00D3 ISOlat1 }
  '\324' -> '&Ocirc;';	{ latin capital letter O with circumflex, U+00D4 ISOlat1 }
  '\325' -> '&Otilde;';	{ latin capital letter O with tilde, U+00D5 ISOlat1 }
  '\326' -> '&Ouml;';	{ latin capital letter O with diaeresis, U+00D6 ISOlat1 }
  '\327' -> '&times;';	{ multiplication sign, U+00D7 ISOnum }
  '\330' -> '&Oslash;';	{ latin capital letter O with stroke = latin capital letter O slash, U+00D8 ISOlat1 }
  '\331' -> '&Ugrave;';	{ latin capital letter U with grave, U+00D9 ISOlat1 }
  '\332' -> '&Uacute;';	{ latin capital letter U with acute, U+00DA ISOlat1 }
  '\333' -> '&Ucirc;';	{ latin capital letter U with circumflex, U+00DB ISOlat1 }
  '\334' -> '&Uuml;';	{ latin capital letter U with diaeresis, U+00DC ISOlat1 }
  '\335' -> '&Yacute;';	{ latin capital letter Y with acute, U+00DD ISOlat1 }
  '\336' -> '&THORN;';	{ latin capital letter THORN, U+00DE ISOlat1 }
  '\337' -> '&szlig;';	{ latin small letter sharp s = ess-zed, U+00DF ISOlat1 }
  '\340' -> '&agrave;';	{ latin small letter a with grave = latin small letter a grave, U+00E0 ISOlat1 }
  '\341' -> '&aacute;';	{ latin small letter a with acute, U+00E1 ISOlat1 }
  '\342' -> '&acirc;';	{ latin small letter a with circumflex, U+00E2 ISOlat1 }
  '\343' -> '&atilde;';	{ latin small letter a with tilde, U+00E3 ISOlat1 }
  '\344' -> '&auml;';	{ latin small letter a with diaeresis, U+00E4 ISOlat1 }
  '\345' -> '&aring;';	{ latin small letter a with ring above = latin small letter a ring, U+00E5 ISOlat1 }
  '\346' -> '&aelig;';	{ latin small letter ae = latin small ligature ae, U+00E6 ISOlat1 }
  '\347' -> '&ccedil;';	{ latin small letter c with cedilla, U+00E7 ISOlat1 }
  '\350' -> '&egrave;';	{ latin small letter e with grave, U+00E8 ISOlat1 }
  '\351' -> '&eacute;';	{ latin small letter e with acute, U+00E9 ISOlat1 }
  '\352' -> '&ecirc;';	{ latin small letter e with circumflex, U+00EA ISOlat1 }
  '\353' -> '&euml;';	{ latin small letter e with diaeresis, U+00EB ISOlat1 }
  '\354' -> '&igrave;';	{ latin small letter i with grave, U+00EC ISOlat1 }
  '\355' -> '&iacute;';	{ latin small letter i with acute, U+00ED ISOlat1 }
  '\356' -> '&icirc;';	{ latin small letter i with circumflex, U+00EE ISOlat1 }
  '\357' -> '&iuml;';	{ latin small letter i with diaeresis, U+00EF ISOlat1 }
  '\360' -> '&eth;';	{ latin small letter eth, U+00F0 ISOlat1 }
  '\361' -> '&ntilde;';	{ latin small letter n with tilde, U+00F1 ISOlat1 }
  '\362' -> '&ograve;';	{ latin small letter o with grave, U+00F2 ISOlat1 }
  '\363' -> '&oacute;';	{ latin small letter o with acute, U+00F3 ISOlat1 }
  '\364' -> '&ocirc;';	{ latin small letter o with circumflex, U+00F4 ISOlat1 }
  '\365' -> '&otilde;';	{ latin small letter o with tilde, U+00F5 ISOlat1 }
  '\366' -> '&ouml;';	{ latin small letter o with diaeresis, U+00F6 ISOlat1 }
  '\367' -> '&divide;';	{ division sign, U+00F7 ISOnum }
  '\370' -> '&oslash;';	{ latin small letter o with stroke, = latin small letter o slash, U+00F8 ISOlat1 }
  '\371' -> '&ugrave;';	{ latin small letter u with grave, U+00F9 ISOlat1 }
  '\372' -> '&uacute;';	{ latin small letter u with acute, U+00FA ISOlat1 }
  '\373' -> '&ucirc;';	{ latin small letter u with circumflex, U+00FB ISOlat1 }
  '\374' -> '&uuml;';	{ latin small letter u with diaeresis, U+00FC ISOlat1 }
  '\375' -> '&yacute;';	{ latin small letter y with acute, U+00FD ISOlat1 }
  '\376' -> '&thorn;';	{ latin small letter thorn with, U+00FE ISOlat1 }
  '\377' -> '&yuml;';	{ latin small letter y with diaeresis, U+00FF ISOlat1 }
  END;
