	{ Translation of ISO-Latin 1 characters into SGML entities

	  I. Vatton	July 1995 }

TextTRANSLATE Latin
	BEGIN
	'<'    -> '&lt;';
	'&'    -> '&amp;';
	'\212' -> '\12'; { '&CTLrc;' }
	'\230' -> 'oe'; { '&oelig;'}
	'\231' -> 'OE'; {'&OElig;'}
	'\240' -> '&nbsp;';
	'\241' -> '&iexcl;';
	'\242' -> '&cent;';
	'\243' -> '&pound;';
	'\244' -> '&curren;';
	'\245' -> '&yen;';
	'\246' -> '&brvbar;';
	'\247' -> '&sect;';
	'\250' -> '&die;';
	'\251' -> '&copy;';
	'\252' -> '&ordf;';
	'\253' -> '&laquo;';
	'\254' -> '&not;';
	'\255' -> '&hyphen;';
	'\256' -> '&reg;';
	'\257' -> '&macr;';
	'\260' -> '&deg;';
	'\261' -> '&plusmn;';
	'\262' -> '&sup2;';
	'\263' -> '&sup3;';
	'\264' -> '&acute;';
	'\265' -> '&micro;';
	'\266' -> '&para;';
	'\267' -> '&middot;';
	'\270' -> '&cedil;';
	'\271' -> '&sup1;';
	'\272' -> '&ordm;';
	'\273' -> '&raquo;';
	'\274' -> '&frac14;';
	'\275' -> '&frac12;';
	'\276' -> '&frac34;';
	'\277' -> '&iquest;';
	'\300' -> '&Agrave;';
	'\301' -> '&Aacute;';
	'\302' -> '&Acirc;';
	'\303' -> '&Atilde;';
	'\304' -> '&Auml;';
	'\305' -> '&Aring;';
	'\306' -> '&AElig;';
	'\307' -> '&Ccedil;';
	'\310' -> '&Egrave;';
	'\311' -> '&Eacute;';
	'\312' -> '&Ecirc;';
	'\313' -> '&Euml;';
	'\314' -> '&Igrave;';
	'\315' -> '&Iacute;';
	'\316' -> '&Icirc;';
	'\317' -> '&Iuml;';
	'\320' -> '&ETH;';
	'\321' -> '&Ntilde;';
	'\322' -> '&Ograve;';
	'\323' -> '&Oacute;';
	'\324' -> '&Ocirc;';
	'\325' -> '&Otilde;';
	'\326' -> '&Ouml;';
	'\327' -> 'OE';  {'&times;';}
	'\330' -> '&Oslash;';
	'\331' -> '&Ugrave;';
	'\332' -> '&Uacute;';
	'\333' -> '&Ucirc;';
	'\334' -> '&Uuml;';
	'\335' -> '&Yacute;';
	'\336' -> '&THORN;';
	'\337' -> '&szlig;';
	'\340' -> '&agrave;';
	'\341' -> '&aacute;';
	'\342' -> '&acirc;';
	'\343' -> '&atilde;';
	'\344' -> '&auml;';
	'\345' -> '&aring;';
	'\346' -> '&aelig;';
	'\347' -> '&ccedil;';
	'\350' -> '&egrave;';
	'\351' -> '&eacute;';
	'\352' -> '&ecirc;';
	'\353' -> '&euml;';
	'\354' -> '&igrave;';
	'\355' -> '&iacute;';
	'\356' -> '&icirc;';
	'\357' -> '&iuml;';
	'\360' -> '&eth;';
	'\361' -> '&ntilde;';
	'\362' -> '&ograve;';
	'\363' -> '&oacute;';
	'\364' -> '&ocirc;';
	'\365' -> '&otilde;';
	'\366' -> '&ouml;';
	'\367' -> 'oe'; { '&divide;' }
	'\370' -> '&oslash;';
	'\371' -> '&ugrave;';
	'\372' -> '&uacute;';
	'\373' -> '&ucirc;';
	'\374' -> '&uuml;';
	'\375' -> '&yacute;';
	'\376' -> '&thorn;';
	'\377' -> '&yuml;';
	END;
