#ifndef LIB_MSG_H
#define LIB_MSG_H

/* Beginning of labels */
#define TMSG_LIB_X11_ERR		0
#define TMSG_LIB_CONFIRM		1
#define TMSG_MISSING_ALPHABET		2
#define TMSG_OLD_VIEW_NOT_REPLACED		3
#define TMSG_OLD_SCH_TO_RECOMP		4
#define TMSG_MISSING_FONT		5
#define TMSG_NO_MEMORY		6
#define TMSG_UNABLE_TO_CONNECT_TO_X		7
#define TMSG_VIEW_MODIFIED_BEFORE_CREATION		8
#define TMSG_LIB_RULES_TABLE_FULL		9
#define TMSG_INCORRECT_STR_FILE		10
#define TMSG_INCORRECT_PRS_FILE		11
#define TMSG_DOC_PRINTED		12
#define TMSG_REDUCTION		13
#define TMSG_1_PAGE_SHEET		14
#define TMSG_2_PAGE_SHEET		15
#define TMSG_4_PAGE_SHEET		16
#define TMSG_LIB_STRING		17
#define TMSG_NOT_ENOUGH_MEMORY		18
#define TMSG_DEBUG_ERROR		19
#define TMSG_DEBUG_SAV_FILES		20
#define TMSG_TRA_FILE_INCORRECT		21
#define TMSG_INVALID_SIBLING		22
#define TMSG_INVALID_CHILD		23
#define TMSG_PAGE		24
#define TMSG_LANGUAGE		25
#define TMSG_ATTR		26
#define TMSG_STD_PRES		27
#define TMSG_APPLY		28
#define TMSG_CHAR		29
#define TMSG_LINE		30
#define TMSG_GRAPHICS_PRES		31
#define TMSG_FORMAT		32
#define TMSG_UNCHANGED		33
#define TMSG_ALIGN		34
#define TMSG_INDENT		35
#define TMSG_LIB_PRINTING_IN_PROGRESS		36
#define TMSG_LIB_PRINT		37
#define TMSG_MANUAL_FEED		38
#define TMSG_OPTIONS		39
#define TMSG_A4		40
#define TMSG_US		41
#define TMSG_PAPER_SIZE		42
#define TMSG_DONE		43
#define TMSG_DOC_DIR		44
#define TMSG_FILE_EXIST		45
#define TMSG_BUTTON_1		46
#define TMSG_BUTTON_2		47
#define TMSG_FONT_FAMILY		48
#define TMSG_ROMAN		49
#define TMSG_BOLD		50
#define TMSG_ITALIC		51
#define TMSG_OBLIQUE		52
#define TMSG_NOT_BOLD		53
#define TMSG_BOLDNESS		54
#define TMSG_NORMAL		55
#define TMSG_UNDERLINE		56
#define TMSG_CROSS_OUT		57
#define TMSG_BODY_SIZE_PTS		58
#define TMSG_NOINDENT		59
#define TMSG_LINE_SPACING		60
#define TMSG_HLINE_SPACING		61
#define TMSG_DLINE_SPACING		62
#define TMSG_SAVE_DOC		63
#define TMSG_CLOSE_DON_T_SAVE		64
#define TMSG_STYLE		65
#define TMSG_COLORS		66
#define TMSG_ELEMENTS		67
#define TMSG_DEL		68
#define TMSG_OUTPUT		69
#define TMSG_PS_FILE		70
#define TMSG_PRINTER		71
#define TMSG_SEARCH_FOR		72
#define TMSG_UPPERCASE_EQ_LOWERCASE		73
#define TMSG_REPLACE_BY		74
#define TMSG_REPLACE		75
#define TMSG_NO_REPLACE		76
#define TMSG_REPLACE_ON_REQU		77
#define TMSG_AUTO_REPLACE		78
#define TMSG_SEARCH_WHERE		79
#define TMSG_BEFORE_SEL		80
#define TMSG_WITHIN_SEL		81
#define TMSG_AFTER_SEL		82
#define TMSG_IN_WHOLE_DOC		83
#define TMSG_DO_NOT_REPLACE		84
#define TMSG_BEFORE_CLOSING		85
#define TMSG_CLOSE_DOC		86
#define TMSG_MATH_SYMBOLS		87
#define TMSG_GRAPHICS		88
#define TMSG_LATIN_ALPHABET		89
#define TMSG_GREEK_ALPHABET		90
#define TMSG_SAVE		91
#define TMSG_TEXT		92
#define TMSG_GRAPHIC		93
#define TMSG_SYMBOL		94
#define TMSG_PICTURE		95
#define TMSG_EL_TYPE		96
#define TMSG_AFTER		97
#define TMSG_BEFORE		98
#define TMSG_AROUND		99
#define TMSG_INCLUDE		100
#define TMSG_PASTE		101
#define TMSG_TO_CREATE		102
#define TMSG_INSERT		103
#define TMSG_PAGE_BRK		104
#define TMSG_LANG_OF_EL		105
#define TMSG_INHERITED_LANG		106
#define TMSG_NOT_FOUND		107
#define TMSG_SEARCH_IN		108
#define TMSG_SEARCH		109
#define TMSG_EL_RO		110
#define TMSG_NOTHING_TO_REPLACE		111
#define TMSG_STD_CHAR		112
#define TMSG_STD_GRAPHICS		113
#define TMSG_STD_FORMAT		114
#define TMSG_STD_GEOMETRY		115
#define TMSG_TYPOGRAPHIC_POINTS		116
#define TMSG_LINE_STYLE		117
#define TMSG_LINE_WEIGHT		118
#define TMSG_FILL_PATTERN		119
#define TMSG_SPLIT		120
#define TMSG_OBJECT_TYPE		121
#define TMSG_GOTO_PAGE		122
#define TMSG_ANY		123
#define TMSG_ATTR_TO_SEARCH		124
#define TMSG_TYPE_TO_SEARCH		125
#define TMSG_NATURES		126
#define TMSG_ATTRIBUTE_NAME		127
#define TMSG_ATTRIBUTE_VALUE		128
#define TMSG_VALUE_OF_ATTR		129
#define TMSG_UNKNOWN_ATTR		130
#define TMSG_CANCEL		131
#define TMSG_ERROR_PS_TRANSLATION		132
#define TMSG_UNKNOWN_PRINTER		133
#define TMSG_CANNOT_CREATE_PS		134
#define TMSG_OVERLINE		135
#define TMSG_DOCUMENT_FORMAT		136
#define TMSG_DEL_ATTR		137
#define TMSG_CPCOLORBG		138
#define TMSG_CPCOLORFG		139
#define TMSG_NO_ELEMENT		140
#define TMSG_What		141
#define TMSG_Pass_Without		142
#define TMSG_Replace_With		143
#define TMSG_Replace_Without		144
#define TMSG_Keep_Unknown		145
#define TMSG_Pass_With		146
#define TMSG_Specials		147
#define TMSG_Correct		148
#define TMSG_Romans		149
#define TMSG_Ignore		150
#define TMSG_Capitals		151
#define TMSG_Arabics		152
#define TMSG_NO_PARAM		153
#define TMSG_NO_KEYBOARD		154
#define TMSG_NO_SAVE		155
#define TMSG_REFUSE_WORD		156
#define TMSG_ADD_WORD		157
#define TMSG_END_CHECK		158
#define TMSG_STOP_CHECK		159
#define TMSG_NO_SELECT		160
#define TMSG_OK_SAVE		161
#define TMSG_NOT_AVAILABLE		162
#define TMSG_ATTACHDETACH		163
#define TMSG_TOOLS		164
#define TMSG_ATTR_MANDATORY		165
#define TMSG_REFRESH		166
#define TMSG_FORMATLEFT		167
#define TMSG_FORMATRIGHT		168
#define TMSG_FORMATCENTER		169
#define TMSG_FORMATJUSTIFY		170
#define TMSG_APPLY_CLASS		171
#define TMSG_SEL_CLASS		172
#define TMSG_SEL		173
#define TMSG_DISCARD		174
#define TMSG_MATHML		175
#define TMSG_MISC		176
#define TMSG_BINARY_REL		177
#define TMSG_BINARY_REL_NEG		178
#define TMSG_OPERATOR		179
#define TMSG_GREEK_CAP		180
#define TMSG_ARROW		181
#define TMSG_SPECHAR		182
#define TMSG_BUTTON_INTERRUPT		183
#define TMSG_BUTTON_PREVIOUS		184
#define TMSG_BUTTON_NEXT		185
#define TMSG_BUTTON_RELOAD		186
#define TMSG_BUTTON_SAVE		187
#define TMSG_BUTTON_SAVE_ALL		188
#define TMSG_BUTTON_NEW		189
#define TMSG_BUTTON_OPEN		190
#define TMSG_BUTTON_PRINT		191
#define TMSG_BUTTON_SEARCH		192
#define TMSG_BUTTON_HOME		193
#define TMSG_BUTTON_ITALICS		194
#define TMSG_BUTTON_BOLD		195
#define TMSG_BUTTON_CODE		196
#define TMSG_BUTTON_IMG		197
#define TMSG_BUTTON_H1		198
#define TMSG_BUTTON_H2		199
#define TMSG_BUTTON_H3		200
#define TMSG_BUTTON_H4		201
#define TMSG_BUTTON_P		202
#define TMSG_BUTTON_UL		203
#define TMSG_BUTTON_OL		204
#define TMSG_BUTTON_DL		205
#define TMSG_BUTTON_LINK		206
#define TMSG_BUTTON_TABLE		207
#define TMSG_LIB_WARNCTAB_INFO		208
#define TMSG_LIB_WARNCTAB_CHECK		209
#define TMSG_LIB_CLOSETABS		210
#define TMSG_LIB_NOERROR_DOC		211
#define TMSG_LIB_ERROR_DOC		212
#define TMSG_LIB_BOXES		213
#define TMSG_BUTTON_DIV		214
#define TMSG_BUTTON_TARGET		215
#define TMSG_INSERTION		216
#define TMSG_DELETION		217
#define TMSG_SUB		218
#define TMSG_SUP		219
#define TMSG_BUTTON_DT		220
#define TMSG_BUTTON_DD		221
#define TMSG_OBJECT		222
#define TMSG_CSSStyle		223
#define TMSG_EXPLORE		224
#define TMSG_SplitHorizontally		225
#define TMSG_SplitVertically		226
#define TMSG_ShowPanel		227
#define TMSG_Undo		228
#define TMSG_Redo		229
#define TMSG_Cut		230
#define TMSG_Copy		231
#define TMSG_Paste		232
#define TMSG_Spell		233
#define TMSG_MATH_PANEL_1		234
#define TMSG_MATH_PANEL_2		235
#define TMSG_MATH_PANEL_3		236
#define TMSG_MATH_PANEL_4		237
#define TMSG_MATH_PANEL_5		238
#define TMSG_MATH_PANEL_6		239
#define TMSG_ZoomIn		240
#define TMSG_ZoomOut		241
#define TMSG_THEME		242
#define TMSG_INSERT_MODE_XML		243
#define TMSG_INSERT_MODE_TEXT		244
#define TMSG_NO_RECENT_DOC		245
#define TMSG_CLIC_ELEM_TO_SELECT_IT		246
#define TMSG_INSERT_MODE		247
#define CellMerge		248
#define CellHShrink		249
#define CellVShrink		250
#define CreateRowB		251
#define CreateRowA		252
#define CreateColumnB		253
#define CreateColumnA		254
#define TIP_DIALOG_TITLE		255
#define TIP_DIALOG_STARTUP		256
#define TIP_DIALOG_PREVIOUS_TIP		257
#define TIP_DIALOG_NEXT_TIP		258
#define TIP_DIALOG_DID_YOU_KNOW		259
#define TIP_DIALOG_TIP_CLOSE		260
#define TIP_AMAYA_PROFILES		261
#define TIP_PANEL_MODES		262
#define TIP_PARENT_SELECTION		263
#define TIP_SPLIT_NOTEBOOK		264
#define TIP_MOVE_PANELS		265
#define TIP_MANY_COLUMNS		266
#define TIP_EDITING_MODE		267
#define TIP_ERROR_BUTTON		268
#define TIP_PATH_CONTROL		269
#define TIP_DOCUMENT_LIST_MENU		270
#define TIP_LINK_TARGET		271
#define TIP_SVG_ROTATE		272
#define TIP_SVG_SHAPE_EDIT		273
#define TIP_SVG_LINES		274
#define TIP_SVG_ASPECT_RATIO		275
#define TIP_LANGUAGES		276
#define Classic		277
#define Modern		278
#define NoTheme		279
#define TMSG_SVG_Information		280
#define TMSG_SVG_GenerateDescription		281
#define TMSG_SVG_Square		282
#define TMSG_SVG_RoundedSquare		283
#define TMSG_SVG_Rectangle		284
#define TMSG_SVG_RoundedRectangle		285
#define TMSG_SVG_Diamond		286
#define TMSG_SVG_Parallelogram		287
#define TMSG_SVG_Trapezium		288
#define TMSG_SVG_EquilateralTriangle		289
#define TMSG_SVG_IsoscelesTriangle		290
#define TMSG_SVG_RightTriangle		291
#define TMSG_SVG_Circle		292
#define TMSG_SVG_Ellipse		293
#define TMSG_SVG_Line		294
#define TMSG_SVG_SimpleArrow		295
#define TMSG_SVG_DoubleArrow		296
#define TMSG_SVG_Zigzag		297
#define TMSG_SVG_Group		298
#define TMSG_SVG_Ungroup		299
#define TMSG_SVG_BringToFront		300
#define TMSG_SVG_SendToBack		301
#define TMSG_SVG_BringForward		302
#define TMSG_SVG_SendBackward		303
#define TMSG_SVG_RotateAntiClockwise		304
#define TMSG_SVG_RotateClockwise		305
#define TMSG_SVG_Rotate		306
#define TMSG_SVG_FlipVertically		307
#define TMSG_SVG_FlipHorizontally		308
#define TMSG_SVG_Scale		309
#define TMSG_SVG_Skew		310
#define TMSG_SVG_Translate		311
#define TMSG_SVG_AlignBottom		312
#define TMSG_SVG_AlignCenter		313
#define TMSG_SVG_AlignLeft		314
#define TMSG_SVG_AlignMiddle		315
#define TMSG_SVG_AlignRight		316
#define TMSG_SVG_AlignTop		317
#define TMSG_SVG_DistributeBottom		318
#define TMSG_SVG_DistributeCenter		319
#define TMSG_SVG_DistributeLeft		320
#define TMSG_SVG_DistributeMiddle		321
#define TMSG_SVG_DistributeRight		322
#define TMSG_SVG_DistributeTop		323
#define TMSG_SVG_DistributeVSpacing		324
#define TMSG_SVG_DistributeHSpacing		325
#define TMSG_SVG_ClosedBezier		326
#define TMSG_SVG_Bezier		327
#define TMSG_SVG_Polyline		328
#define TMSG_SVG_Polygon		329
#define TMSG_SVG_ForeigObject		330
#define TMSG_SVG_Image		331
#define TMSG_SVG_SvgCanvas		332
#define TMSG_SVG_Text		333
#define TMSG_SVG_Cone		334
#define TMSG_SVG_Cube		335
#define TMSG_SVG_Cylinder		336
#define TMSG_SVG_Octahedron		337
#define TMSG_SVG_Parallelepiped		338
#define TMSG_SVG_Pyramid		339
#define TMSG_SVG_Beaker		340
#define TMSG_SVG_Funnel		341
#define TMSG_SVG_Bunsen_burner		342
#define TMSG_SVG_Buchner_flask		343
#define TMSG_SVG_Boiling_flask		344
#define TMSG_SVG_Burette		345
#define TMSG_SVG_Erlenmeyer_flask		346
#define TMSG_SVG_Test_tube		347
#define TMSG_SVG_Pipette		348
#define TMSG_SVG_Rectangular		349
#define TMSG_SVG_Rounded_rectangular		350
#define TMSG_SVG_Round		351
#define TMSG_SVG_Scream		352
#define TMSG_SVG_Thought		353
#define TMSG_SVG_Capacitor		354
#define TMSG_SVG_Current_source		355
#define TMSG_SVG_Diode		356
#define TMSG_SVG_Ground_point		357
#define TMSG_SVG_Inductor		358
#define TMSG_SVG_Led		359
#define TMSG_SVG_Op_amp		360
#define TMSG_SVG_Resistor		361
#define TMSG_SVG_Switch		362
#define TMSG_SVG_Transistor		363
#define TMSG_SVG_Voltage_source		364
#define TMSG_SVG_Zener_diode		365
#define TMSG_SVG_Pentagon		366
#define TMSG_SVG_Hexagon		367
#define TMSG_SVG_Heptagon		368
#define TMSG_SVG_Octogon		369
#define TMSG_SVG_Star4		370
#define TMSG_SVG_Star5		371
#define TMSG_SVG_Star6		372
#define TMSG_SVG_AND		373
#define TMSG_SVG_NAND		374
#define TMSG_SVG_OR		375
#define TMSG_SVG_NOR		376
#define TMSG_SVG_XOR		377
#define TMSG_SVG_XNOR		378
#define TMSG_SVG_NOT		379
#define TMSG_SVG_Cross		380
#define TMSG_SVG_Frame		381
#define TMSG_SVG_Ring		382
#define TMSG_SVG_Cloud		383
#define TMSG_SVG_Scroll		384
#define TMSG_SVG_Sun		385
#define TMSG_SVG_Lightning_Bolt		386
#define TMSG_SVG_Moon		387
#define TMSG_SVG_Smiley		388
#define TMSG_SVG_Heart		389
#define TMSG_SVG_Flower		390
#define TMSG_SVG_Prohibited		391
#define TMSG_SVG_Pentagon_Arrow		392
#define TMSG_SVG_2_Way_Rounded_Arrow		393
#define TMSG_SVG_3_Way_Arrow_Callout		394
#define TMSG_SVG_3_Way_Arrow		395
#define TMSG_SVG_4_Way_Arrow_Callout		396
#define TMSG_SVG_4_Way_Arrow		397
#define TMSG_SVG_Chevron		398
#define TMSG_SVG_Circular_Arrow		399
#define TMSG_SVG_Corner_Arrow		400
#define TMSG_SVG_Corner_Double_Arrow_Callout		401
#define TMSG_SVG_Corner_Double_Arrow		402
#define TMSG_SVG_Double_Arrow_Callout		403
#define TMSG_SVG_Double_Arrow		404
#define TMSG_SVG_Notched_Arrow		405
#define TMSG_SVG_Rounded_Arrow		406
#define TMSG_SVG_Simple_Arrow_Callout		407
#define TMSG_SVG_Simple_Arrow		408
#define TMSG_SVG_Split_Arrow		409
#define TMSG_SVG_S_Shape_Arrow		410
#define TMSG_SVG_Striped_Arrow		411
#define TemplateFromDocument		412
#define TemplateTextBox		413
#define TemplateUseBox		414
#define TemplateUseCompBox		415
#define TemplateRepeat		416
#define TemplateRepeatComp		417
#define TemplateFreeBox		418
#define TemplateUnion		419
#define TemplateLibrary		420
#define TemplateImport		421
#define BUTTON_UP		422
#define TMSG_DOUBLECLICK		423
#define TMSG_SIMPLECLICK		424
#define LOCK		425
#define UNLOCK		426
#define NO_WEBDAV		427
#define TMSG_LIB_MSG_MAX		428

#endif
