#ifndef LIB_MSG_H
#define LIB_MSG_H

/* ---  --- --- --- MESSAGES FOR THE LIBRARY --- --- --- ---  */

/*=====   Simple messages                                     */

#define REG_EXP_TOO_BIG		               0
#define MISSING_VIEW			               1
#define ERR_LOADING_DICO			               2
#define LIB_MISSING_FILE			               3
#define WRITING_IMP			               4
#define SCHEMA_NOT_FIND			               5
#define LIB_CONFIRM				               6
#define MISSING_ALPHABET			                       7
#define OPEN_DOC_IMP			               8
#define ERR_PIV			               9
#define OLD_VIEW_NOT_REPLACED	              10
#define OLD_SCH_TO_RECOMP		              11
#define BAD_FRAME_NB		                      12
#define MISSING_FONT			              13
#define COLUMNS_PAGINATE_AGAIN	              14
#define NO_MEMORY			              15
#define UNABLE_TO_CONNECT_TO_X		              16
#define VIEW_MODIFIED_BEFORE_CREATION	              17
#define SEL_BEFORE			              18
#define NO_PLACE_FOR_FONT		              19
#define INCORRECT_DOC_STRUCTURE	              20
#define LOCKED_DOC			              21
#define INCORRECT_REG_EXP		              22
#define UNMATCHED_LEFT			              23
#define UNMATCHED_RIGHT			              24
#define PREMATURE_END_REG_EXP	              25
#define LIB_NESTING_TOO_DEEP			              26
#define INCORRECT_HORIZ_POS			              27
#define INCORRECT_VERT_POS			              28
#define LIB_RULES_TABLE_FULL			              29
#define STR_SCH_CHANGED		              30
#define INCORRECT_STR_FILE			              31
#define INCORRECT_PRS_FILE			              32
#define MISSING_DIR		                      33
#define PRINT_IMP			              34
#define CHANGE_PRES_IMP			              35
#define SAVE_IN_PS_IMP		              36
#define IMPORT_FILE_IMP			              37
#define EMPTY_VIEW			              38
#define RO_EL_FORBIDDEN		              39
#define DON_T_COPY_PAIRED_EL		              40
#define INCORRECT_HORIZ_SIZING		              41
#define INCORRECT_VERT_SIZING		              42
#define NEW_DICO				              43
#define HORIZ_BOX_OVERFLOW			              44
#define VERT_BOX_OVERFLOW		                      45
#define BAD_HORIZ_POS_SEE_PRS_SCH	              46
#define BAD_VERT_POS_SEE_PRS_SCH	              47
#define BAD_HORIZ_SIZING_SEE_PRS_SCH	              48
#define BAD_VERT_SIZING_SEE_PRS_SCH	      49
#define A_COPY			              50
#define LIB_NO_LOAD				              51
#define MISSING_DICOPAR				              52
#define SELF_REF_IMP	              53
#define LIB_ATTR_REQUIRED_NOT_DELETED		              54
#define NATURE_FORBIDDEN		              55
#define LIB_MANDATORY_COMPONENT		                      56
#define SEL_ONE_COMPONENT		              57
#define PASTING_EL_IMP	              58
#define MODIFYING_BOX_IMP	              59
#define LIB_STRING				              60
#define NO_VIEW_SEL_FOR_PRINTING	      61
#define ENTER_PRS_SCH			              62
#define READING_DOC			              63
#define SEL_EL			              64
#define NO_KBD			              65
#define X_BUF_UNMODIFIED			              66
#define COPYING_DIFFERENT_COMPONENTS_IMP	      67
#define RO_DOC_FORBIDDEN		              68
#define SELF_DOC_INCLUSION_IMP	                      69
#define MODIFYING_BOX			              70
#define MOVING_BOX			              71
#define LIB_DOC_WRITTEN			                      72
#define WRITING				              73
#define EMPTY_REF				              74
#define COPYING_PAGE_BRK_IMP		              75
#define SEL_EL_MANDATORY		              76
#define MODIFYING_DIR_LIST		              77
#define PRINTING		                	      78
#define EXPORTING				              79
#define DICO				              80
#define SAVE_IN_PS		              81
#define IMPORTING_FILE			              82
#define CHOOSE_DOC_FORM_FOR_LOADING	      83
#define TWO_POINTS_IN_POLYLINE_NEEDED	              84
#define VAL_FOR_ATTR_REQUESTED		              85
#define OLD_PIV_FORMAT_SAVE_DOC_WITH_THOT	      86
#define CREATING_BOX			              87
#define NOT_ENOUGH_MEMORY			              88
#define SEL_EL_TYPE		                      89
#define HOLOPHRAST_IMP			              90
#define SEL_REFERRED_EL		              91
#define TOO_MANY_DOCS			              92
#define EMPTY_DOC_NOT_WRITTEN		              93
#define INSERTING_IMP			              94
#define NOTHING_TO_DEL			              95
#define MANDATORY_ATTR			              96
#define ALL_VIEWS_ALREADY_CREATED		              97
#define EMPTY_DOC				              98
#define CHANGING_DOC_IMP			              99
#define LIB_TOO_MANY_VIEWS			             100
#define NOTHING_TO_PASTE		             101
#define OPENING_NEW_FRAME_IMP	             102
#define DEBUG_ERROR		             103
#define DEBUG_SAV_FILES   104
#define LIB_X11_ERR				             105
#define DEBUG_NO_SEL			             106
#define DEBUG_LINK_NEW_EL	             107
#define DEBUG_SUPPREF		             108
#define DEBUG_DUP_LABEL		             109
#define PREMAT_EOF				             110
#define NO_BOUNDING_BOX_IN_PS		             111
#define HYPHEN_FILE_NOT_OPEN                             112
#define HYPHEN_FILE_OPEN                                 113
#define HYPHEN_WORD_TOO_LONG                             114
#define COLOR_INCORRECT				             115
#define XPM_OPEN_ERR			                     116
#define XPM_FILE_INCORRECT                                     117
#define XPM_NO_MEM                                        118
#define XPM_COLOR_ERR                                     119
#define INCLUDE_FILE_IMP	                             120
#define CREATE_FILE_IMP		                     121
#define EL_NOT_TRANSLATED	                     122
#define TRA_FILE_INCORRECT		                     123
#define TOO_MANY_OUTPUT_FILES	                     124
#define CREATE_FRAME_FOR_VIEW		             125
#define INVALID_SIBLING		             126
#define INVALID_CHILD		             127
#define ATTR_REQUIRED_FOR_EL		             128
#define PAGE				             129
#define LIB_UNKNOWN_TYPE			             130
#define LANGUAGE			                     131
#define ATTR			                     132
#define SEARCH_REF		                     133
#define STD_PRES	                     134
#define APPLY			                     135
#define CHAR			                     136
#define LINE			                     137
#define GRAPHICS_PRES	                     138
#define FORMAT			                     139
#define UNCHANGED			                     140
#define ALIGN			                     141
#define INDENT			                     142
#define LIB_PRINT			                     143
#define MANUAL_FEED		                             144
#define OPTIONS			                     145
#define A4				                     146
#define US		       		                     147
#define PAPER_SIZE		                     148
#define DONE                                             149
#define DOC_DIR	                     150
#define DOCUMENT_NAME		                     151
#define FILE_EXIST			                     152
#define BUTTON_1                                         153
#define BUTTON_2                                         154
#define FONT_FAMILY	       	                             155
#define ROMAN			                     156
#define BOLD		          	             157
#define ITALIC			                     158
#define OBLIQUE			                     159
#define BOLD_ITALIC		                             160
#define BOLD_OBLIQUE	       	                     161
#define NORMAL			                     162
#define UNDERLINE			                     163
#define CROSS_OUT			                     164
#define BODY_SIZE_PTS	       	                     165
#define INDENT_PTS 		                             166
#define LINE_SPACING_PTS		                     167
#define LINE_SPACING	       	                     168
#define JUSTIFY		                     169
#define LIB_YES			                             170
#define LIB_NO				                     171
#define SAVE_DOC		                     172
#define CLOSE_DON_T_SAVE		                     173
#define STYLE			                     174
#define COLORS			                     175
#define DEL			                     176
#define OUTPUT			                     177
#define PS_FILE		                     178
#define PRINTER     		                     179
#define SEARCH_FOR		       	                     180
#define REG_EXP		                     181
#define UPPERCASE_EQ_LOWERCASE    	                     182
#define REPLACE_BY		       	                     183
#define REPLACE			                     184
#define NO_REPLACE  		                     185
#define REPLACE_ON_REQU 	                             186
#define AUTO_REPLACE  	                             187
#define SEARCH_WHERE		                     188
#define BEFORE_SEL		                     189
#define WITHIN_SEL		                     190
#define AFTER_SEL		                     191
#define IN_WHOLE_DOC  	                             192
#define DO_NOT_REPLACE		                     193
#define STD_COLORS		                     194
#define BEFORE_CLOSING		                     195
#define CLOSE_DOC		                     196
#define NO_NAME			                     197
#define CREATE_DOC		                     198
#define DOC_TYPE	       	                     199
#define RENAME			                     200
#define MATH_SYMBOLS       	                             201
#define GRAPHICS			                     202
#define LATIN_ALPHABET		                     203
#define GREEK_ALPHABET		                     204
#define PRES		                     205
#define FILES			                     206
#define OPEN_DOC		                     207
#define IMPORT_DOC_TYPE		                     208
#define VIEWS	       		                     209
#define CHANGE_FILTER		                     210
#define VALUE_NOT_CHANGED		                     211
#define INCREASE			                     212
#define DECREASE			                     213
#define VISIB			                     214
#define CHANGE_ZOOM	       	                             215
#define LIB_ZOOM		       	                     216
#define SAVE_AS					     217
#define SAVE					     218
#define THOT_APP					     219
#define DOC_FORMAT					     220
#define COPY					     221
#define TEXT					     222
#define GRAPHIC					     223
#define SYMBOL					     224
#define PICTURE					     225
#define EL_TYPE				     226
#define AFTER					     227
#define BEFORE					     228
#define AROUND					     229
#define INCLUDE					     230
#define PASTE					     231
#define TO_CREATE					     232
#define INSERT					     233
#define PAGE_BRK					     234
#define READ_ONLY					     235
#define SURROUND					     236
#define CHANGE_TYPE				             237
#define LANG_OF_EL			             238
#define INHERITED_LANG				     239
#define DO_NOT_CHANGE_DOC			     240
#define	NOT_FOUND					     241
#define	SEARCH_IN					     242
#define	SEARCH_EMPTY_EL			     243
#define	SEARCH_EMPTY_REF			     244
#define EARCH_REF_TO_EL			     245
#define	LINK					     246
#define REF_IN_DOC			     247
#define SEARCH					     248
#define EL_RO				     249
#define NOTHING_TO_REPLACE				     250
#define OPEN					     251
#define STD_CHAR			             252
#define STD_GRAPHICS			             253
#define STD_FORMAT				     254
#define STD_GEOMETRY				     255
#define TYPOGRAPHIC_POINTS				     256
#define LINE_STYLE					     257
#define LINE_WEIGHT				             258
#define FILL_PATTERN				     259
#define SPLIT					     260
#define OBJECT_TYPE					     261
#define GOTO_PAGE					     262
#define ANY						     263
#define ATTR_TO_SEARCH				     264
#define TYPE_TO_SEARCH				     265
#define NATURES					     266
#define VALUE_OF_ATTR				     267
#define UNKNOWN_ATTR				     268
#define CREATE_EL_REF				     269
#define SHOW_EL_REF				     270
#define MODE_INSERT					     271
#define CANCEL                                           272
#define ERROR_PS_TRANSLATION                     273
#define UNKNOWN_PRINTER                                  274
#define CANNOT_CREATE_PS                         275
#define DOC_PRINTED                                      276
#define LIB_MSG_MAX					     277

#endif
