#ifdef _WX

#ifndef __PANELTYPES_H__
#define __PANELTYPES_H__

/* use to differenciate panel types */
typedef enum
  {
    WXAMAYA_PANEL_XHTML
  } wxAMAYA_PANEL_TYPE;

typedef enum
  {
    WXAMAYA_PANEL_XHTML_STRONG,
    WXAMAYA_PANEL_XHTML_EMPH,
    WXAMAYA_PANEL_XHTML_CODE,
    WXAMAYA_PANEL_XHTML_H1,
    WXAMAYA_PANEL_XHTML_H2,
    WXAMAYA_PANEL_XHTML_H3,
    WXAMAYA_PANEL_XHTML_BULLET,
    WXAMAYA_PANEL_XHTML_NL,
    WXAMAYA_PANEL_XHTML_DL,
    WXAMAYA_PANEL_XHTML_IMG,
    WXAMAYA_PANEL_XHTML_LINK,
    WXAMAYA_PANEL_XHTML_TABLE
  } wxAMAYA_PANEL_XHTML_B;

#endif /* __PANELTYPES_H__ */

#endif /* _WX */
