#ifdef _WX

#ifndef __PANELTYPES_H__
#define __PANELTYPES_H__

/* use to differenciate panel types */
typedef enum
  {
    WXAMAYA_PANEL_UNKNOWN,
    WXAMAYA_PANEL_ELEMENTS,
    WXAMAYA_PANEL_XHTML,
    WXAMAYA_PANEL_EXPLORER,
    WXAMAYA_PANEL_ATTRIBUTE,
    WXAMAYA_PANEL_APPLYCLASS,
    WXAMAYA_PANEL_STYLE,
    WXAMAYA_PANEL_MATHML,
    WXAMAYA_PANEL_XML,
    WXAMAYA_PANEL_SPECHAR,
    WXAMAYA_PANEL_SVG,
    WXAMAYA_PANEL_TYPE_NB,
    
    WXAMAYA_PANEL_STYLE_LIST
    
  } wxAMAYA_PANEL_TYPE;


/* Use to identify requested doctypes. */
typedef enum
{
  WXAMAYA_DOCTYPE_UNKNOWN = -1,
  WXAMAYA_DOCTYPE_XHTML   = 0,
  WXAMAYA_DOCTYPE_MATHML,
  WXAMAYA_DOCTYPE_SVG,
  WXAMAYA_DOCTYPE_XTIGER,
  WXAMAYA_DOCTYPE_XML,

  WXAMAYA_DOCTYPE_NUMBER
} wxAMAYA_DOCTYPE;
  
typedef enum
  {
    WXAMAYA_PANEL_XHTML_DIV,
    WXAMAYA_PANEL_XHTML_H1,
    WXAMAYA_PANEL_XHTML_H2,
    WXAMAYA_PANEL_XHTML_H3,
    WXAMAYA_PANEL_XHTML_TABLE,
    WXAMAYA_PANEL_XHTML_TARGET,
    WXAMAYA_PANEL_XHTML_LINK,
    WXAMAYA_PANEL_XHTML_BULLET,
    WXAMAYA_PANEL_XHTML_NL,
    WXAMAYA_PANEL_XHTML_DL,
    WXAMAYA_PANEL_XHTML_DT,
    WXAMAYA_PANEL_XHTML_DD,
    WXAMAYA_PANEL_XHTML_IMG,
    WXAMAYA_PANEL_XHTML_OBJ,
    WXAMAYA_PANEL_XHTML_STRONG,
    WXAMAYA_PANEL_XHTML_EMPH,
    WXAMAYA_PANEL_XHTML_CODE,
    WXAMAYA_PANEL_XHTML_INS,
    WXAMAYA_PANEL_XHTML_DEL,
    WXAMAYA_PANEL_XHTML_SUP,
    WXAMAYA_PANEL_XHTML_SUB
  } wxAMAYA_PANEL_XHTML_B;

#endif /* __PANELTYPES_H__ */

#endif /* _WX */
