#ifndef _UCS2_CONST
#define _UCS2_CONST

#if defined(_I18N_) || defined(__JIS__)
#   define _ZERO_             L"0"
#   define _ONE_              L"1"
#   define _TWO_              L"2"
#   define _THREE_            L"3"
#   define _FOUR_             L"4"
#   define _FIVE_             L"5"
#   define _SIX_              L"6"
#   define _SEVEN_            L"7"
#   define _EIGHT_            L"8"
#   define _NINE_             L"9" 
#   define _A_                L"A"
#   define _B_                L"B"
#   define _C_                L"C"
#   define _D_                L"D"
#   define _E_		      L"E"
#   define _F_                L"F"
#   define _G_                L"G"
#   define _H_                L"H"
#   define _I_                L"I"
#   define _J_                L"J"
#   define _K_                L"K"
#   define _L_                L"L"
#   define _M_                L"M"
#   define _N_                L"N"
#   define _O_                L"O"
#   define _P_                L"P"
#   define _Q_                L"Q"
#   define _R_                L"R"
#   define _S_                L"S"
#   define _T_                L"T"
#   define _U_                L"U"
#   define _V_                L"V"
#   define _W_                L"W"
#   define _X_                L"X"
#   define _Y_                L"Y"
#   define _Z_                L"Z"
#   define _a_                L"a"
#   define _b_                L"b"
#   define _c_                L"c"
#   define _d_                L"d"
#   define _e_                L"e"
#   define _f_                L"f"
#   define _g_                L"g"
#   define _h_                L"h"
#   define _i_                L"i"
#   define _j_                L"j"
#   define _k_                L"k"
#   define _l_                L"l"
#   define _m_                L"m"
#   define _n_                L"n"
#   define _o_                L"o"
#   define _p_                L"p"
#   define _q_                L"q"
#   define _r_                L"r"
#   define _s_                L"s"
#   define _t_                L"t"
#   define _u_                L"u"
#   define _v_                L"v"
#   define _w_                L"w"
#   define _x_                L"x"
#   define _y_                L"y"
#   define _z_                L"z"

#   define LT_OP              L"<"
#   define GT_OP              L">"
#   define EQ_OP              L"="
#   define AND_OP             L"&"

/*           Special characters */
#   define _NEWLINE_          L"\n"
#   define _TABULATION_       L"\t"

#   define _ActiveBoxColorCST_    L"ActiveBoxColor"
#   define _AlphabetCST_          L"alphabet"
#   define _AmayaMainCST_         L"AmayaMain"
#   define _BackgroundColorCST_   L"BackgroundColor"
#   define _BUTTONCST_            L"BUTTON"
#   define _ClientWndProcCST_     L"ClientWndProc"
#   define _CorrdialogueCST_      L"corrdialogue"
#   define _DicCST_               L"dic"
#   define _DCTCST_               L"DCT"
#   define _DocSelectColorCST_    L"DocSelectColor"
#   define _DocumentCST_          L"document"
#   define _DocumentNatureCST_    L"document-nature"
#   define _EDITCST_              L"EDIT"
#   define _EDITORCST_            L"EDITOR"
#   define _ExportCST_            L"export"
#   define _ExtensionCST_         L"extension"
#   define _ForegroundColorCST_   L"ForegroundColor"
#   define _FormattedViewCST_     L"Formatted_view"
#   define _FormClassCST_         L"FormClass" 
#   define _GeometryCST_          L"geometry"
#   define _IDI_APPICONCST_       L"IDI_APPICON"
#   define _ImportCST_            L"import"
#   define _InactiveItemColorCST_ L"InactiveItemColor"
#   define _KeyboardCST_          L"keyboard"
#   define _LEXCST_               L"LEX"
#   define _LibdialogueCST_       L"libdialogue"
#   define _MenuAttributeCST_     L"MenuAttribute"
#   define _MenuBgColorCST_       L"MenuBgColor"
#   define _MenuFgColorCST_       L"MenuFgColor"
#   define _MenuHelpCST_          L"MenuHelp"
#   define _MenuSelectionCST_     L"MenuSelection"
#   define _NatureCST_            L"nature"
#   define _NumAttrClassCST_      L"NumAttrClass"
#   define _PagesizeCST_          L"pagesize"
#   define _PresentationCST_      L"presentation"
#   define _OpenCST_              L"open"
#   define _OptionsCST_           L"options"
#   define _ReadOnlyColorCST_     L"ReadOnlyColor"
#   define _SaveFileAsCST_        L"Save File as"
#   define _ScrollbarCST_         L"scrollbar"
#   define _SheetClassCST_        L"SheetClass" 
#   define _SpecialCharsCST_      L"@#$&+~" 
#   define _STATICCST_            L"STATIC"
#   define _StyleCST_             L"style"
#   define _ThotColorPaletteCST_  L"ThotColorPalette"
#   define _TranslationCST_       L"translation"
#   define _TtcPasteCST_          L"TtcPaste"
#   define _TtcRedoCST_           L"TtcRedo"
#   define _TtcUndoCST_           L"TtcUndo"
#   define _TypographyCST_        L"typography"
#   define _VISIBILITYCST_        L"VISIBILITY"
#   define _WNDIALOGBOXCST_       L"WNDIALOGBOX"
#   define _ZOOMCST_              L"ZOOM"

#   define _THOTElement_          L"thot"
#   define _XMLElement_           L"xml"
#   define _XMLNameSpace_         L"xmlns"

#   define _AmayaFatalErrorMSG_            L"Amaya: fatal error"
#   define _AttributeElementMismatchMSG_   L"attribute element mismatch"
#   define _BufferTooSmallMSG_             L"buffer too small"
#   define _CannotHolophrastARootMSG_      L"cannot holophrast a root"
#   define _CannotHolophrastThatTypeMSG_   L"cannot holophrast that type"
#   define _CannotLoadPschemaMSG_          L"cannot load pschema"
#   define _CannotReadStructureSchemaMSG_  L"cannot read structure schema"
#   define _CannotOpenViewMSG_             L"cannot open view"
#   define _CannotOpenPivotFileMSG_        L"cannot open pivot file"
#   define _CannotSetLinkMSG_              L"cannot set link"
#   define _DuplicateAttributeMSG_         L"duplicate attribute"
#   define _DuplicatePresentationRuleMSG_  L"duplicate presentation rule"
#   define _EmptyDocumentMSG_              L"empty document"
#   define _ElementAlreadyInsertedMSG_     L"element already inserted"
#   define _ElementDoesNotMatchDTDMSG_     L"element does not match DTD"
#   define _ElementHasNoBoxMSG_            L"element has no box"
#   define _FeatureNotImplementedMSG_      L"feature not implemented"
#   define _IncorrectTreeMSG_              L"incorrect tree"
#   define _InvalidAssociatedRootMSG_      L"invalid associated root"
#   define _InvalidAttributeTypeMSG_       L"invalid attribute type"
#   define _InvalidAttributeValueMSG_      L"invalid attribute value"
#   define _InvalidButtonNdxMSG_           L"Invalid Button Index"
#   define _InvalidDocumentNameMSG_        L"invalid document name" 
#   define _InvalidDocumentParameterMSG_   L"invalid document parameter"
#   define _InvalidElementTypeMSG_         L"invalid element type"
#   define _InvalidParameterMSG_           L"invalid parameter"
#   define _LanguageNotFoundMSG_           L"language not found"
#   define _LanguageTableIsFullMSG_        L"language table is full"
#   define _MainWindowNotOpenMSG_          L"main window not open"
#   define _MandatoryAttributeMSG_         L"mandatory attribute"
#   define _NoPresentationSchemaMSG_       L"no presentation schema"
#   define _NoSelectionInDocumentMSG_      L"no selection in document"
#   define _ReadOnlyDocumentMSG_           L"read only document"
#   define _SpellCheckingMSG_              L"Spell checking"
#   define _StringTooLongMSG_              L"string too long"
#   define _ThereAreOpenViewsMSG_          L"there are open views"
#   define _TooManyDocumentsMSG_           L"too many documents" 

#   define _ANYFILE_                       L"*."
#   define BAK_EXT2                        L"BAK"
#   define EXE_EXT                         L".exe"
#   define EXE_EXT2                        L"EXE"
#   define EXT_EXT2                        L"EXT"
#   define KB_EXT                          L".kb"
#   define html_EXT                        L".html"
#   define html_EXT2                       L"html"
#   define Keyboard_EXT                    L".keyboard"
#   define OLD_EXT2                        L"OLD"
#   define PIV_EXT                         L".PIV"
#   define PIV_EXT2                        L"PIV"
#   define PRS_EXT                         L".PRS"
#   define PRS_EXT2                        L"PRS"
#   define Ps_EXT2                         L"ps"
#   define REF_EXT2                        L"REF"
#   define SAV_EXT2                        L"SAV"
#   define STR_EXT                         L".STR"
#   define STR_EXT2                        L"STR"
#   define Tmp_EXT2                        L"Tmp"
#   define TRA_EXT                         L".TRA"
#   define TRA_EXT2                        L"TRA"
#   define X_EXT                           L".X"
#   define XML_EXT                         L".xml"
#   define XML_EXT2                        L"XML"

#   define _CONFSUFFIX_                    L"conf"

#   define _CsLANG_                        L"cs"
#   define _FiLANG_                        L"fi"
#   define _FrLANG_                        L"fr"
#   define _ElLANG_                        L"el"
#   define _EnLANG_                        L"en"
#   define _EsLANG_                        L"es"
#   define _DeLANG_                        L"de"
#   define _ItLANG_                        L"it"
#   define _NlLANG_                        L"nl"
#   define _PlLANG_                        L"pl"
#   define _PtLANG_                        L"pt"
#   define _SvLANG_                        L"sv"
#   define _TrLANG_                        L"tr"
#   define _EnUSLANG_                      L"en-US"


#   define _APPHOME_EVAR_                  L"APP_HOME"
#   define _Appname_EVAR_                  L"appname"
#   define _AUTOSAVE_EVAR_                 L"AUTOSAVE"
#   define _BackgroundColor_EVAR_          L"BackgroundColor"
#   define _CACHEDIR_EVAR_                 L"CACHE_DIR"
#   define _CACHEDISCONNECTEDMODE_EVAR_    L"CACHE_DISCONNECTED_MODE"
#   define _CACHEEXPIREIGNORE_EVAR_        L"CACHE_EXPIRE_IGNORE"
#   define _CACHEPROTECTEDDOCS_EVAR_       L"CACHE_PROTECTED_DOCS"
#   define _CACHESIZE_EVAR_                L"CACHE_SIZE"
#   define _DEFAULTNAME_EVAR_              L"DEFAULTNAME"
#   define _DICOPAR_EVAR_                  L"DICOPAR"
#   define _DNSTIMEOUT_EVAR_               L"DNS_TIMEOUT"
#   define _DOUBLECLICKDELAY_EVAR_         L"DOUBLECLICKDELAY"
#   define _ENABLEBGIMAGES_EVAR_           L"ENABLE_BG_IMAGES"
#   define _ENABLECACHE_EVAR_              L"ENABLE_CACHE"
#   define _ENABLEDOUBLECLICK_EVAR_        L"ENABLE_DOUBLECLICK"
#   define _ENABLELOSTUPDATECHECK_EVAR_    L"ENABLE_LOST_UPDATE_CHECK"
#   define _ENABLEMDA_EVAR_                L"ENABLE_MDA"
#   define _ENABLEMULTIKEY_EVAR_           L"ENABLE_MULTIKEY"
#   define _ENABLEPIPELINING_EVAR_         L"ENABLE_PIPELINING"
#   define _EXTENDDICT_EVAR_               L"EXTENDDICT"
#   define _FontFamily_EVAR_               L"FontFamily"
#   define _FontMenuSize_EVAR_             L"FontMenuSize"
#   define _ForegroundColor_EVAR_          L"ForegroundColor"
#   define _HOME_EVAR_                     L"HOME"
#   define _HOMEPAGE_EVAR_                 L"HOME_PAGE"
#   define _HTTPPROXY_EVAR_                L"HTTP_PROXY"
#   define _LANG_EVAR_                     L"LANG"
#   define _MAXCACHEENTRYSIZE_EVAR_        L"MAX_CACHE_ENTRY_SIZE"
#   define _MAXSOCKET_EVAR_                L"MAX_SOCKET"
#   define _NETEVENTTIMEOUT_EVAR_          L"NET_EVENT_TIMEOUT"
#   define _NOPROXY_EVAR_                  L"NO_PROXY"
#   define _PAPERSIZE_EVAR_                L"PAPERSIZE"
#   define _PATH_EVAR_                     L"PATH"
#   define _PERSISTCXTIMEOUT_EVAR_         L"PERSIST_CX_TIMEOUT"
#   define _PWD_EVAR_                      L"PWD"
#   define _ReduceColor_EVAR_              L"ReduceColor"
#   define _THOTDOC_EVAR_                  L"THOTDOC"
#   define _THOTDIR_EVAR_                  L"THOTDIR"
#   define _THOTPRINT_EVAR_                L"THOTPRINT"
#   define _THOTSCH_EVAR_                  L"THOTSCH"
#   define _THOTSYSSCH_EVAR_               L"THOTSYSSCH"
#   define _TMPDIR_EVAR_                   L"TMPDIR"
#   define _TOOLTIPDELAY_EVAR_             L"TOOLTIPDELAY"
#   define _VERIFYPUBLISH_EVAR_            L"VERIFY_PUBLISH"
#   define _ZOOM_EVAR_                     L"ZOOM"


#   define _AltKEY_                        L"Alt"
#   define _BackspaceKEY_                  L"backspace"
#   define _CtrlKEY_                       L"Ctrl"
#   define _DeleteKEY_                     L"delete"
#   define _DownKEY_                       L"down"
#   define _EndKEY_                        L"end"
#   define _EscapeKEY_                     L"escape"
#   define _F1KEY_                         L"F1"
#   define _F2KEY_                         L"F2"
#   define _F3KEY_                         L"F3"
#   define _F4KEY_                         L"F4"
#   define _F5KEY_                         L"F5"
#   define _F6KEY_                         L"F6"
#   define _F7KEY_                         L"F7"
#   define _F8KEY_                         L"F8"
#   define _F9KEY_                         L"F9"
#   define _F10KEY_                        L"F10"
#   define _F11KEY_                        L"F11"
#   define _F12KEY_                        L"F12"
#   define _F13KEY_                        L"F13"
#   define _F14KEY_                        L"F14"
#   define _F15KEY_                        L"F15"
#   define _F16KEY_                        L"F16"
#   define _F17KEY_                        L"F17"
#   define _F18KEY_                        L"F18"
#   define _F19KEY_                        L"F19"
#   define _F20KEY_                        L"F20"
#   define _F21KEY_                        L"F21"
#   define _F22KEY_                        L"F22"
#   define _F23KEY_                        L"F23"
#   define _F24KEY_                        L"F24"
#   define _F25KEY_                        L"F25"
#   define _F26KEY_                        L"F26"
#   define _F27KEY_                        L"F27"
#   define _F28KEY_                        L"F28"
#   define _F29KEY_                        L"F29"
#   define _F30KEY_                        L"F30"
#   define _F31KEY_                        L"F31"
#   define _F32KEY_                        L"F32"
#   define _F33KEY_                        L"F33"
#   define _F34KEY_                        L"F34"
#   define _F35KEY_                        L"F35"
#   define _HomeKEY_                       L"home"
#   define _LeftKEY_                       L"left"
#   define _MetaKEY_                       L"meta"
#   define _RightKEY_                      L"right"
#   define _ReturnKEY_                     L"Return"
#   define _ShiftKEY_                      L"Shift"
#   define _SpaceKEY_                      L"space"
#   define _UpKEY_                         L"up"

#   define _KBKeyRC_                       L"<Key>"

#   define _AmericanID_                    L"American"
#   define _CzechID_                       L"Czech"
#   define _DutchID_                       L"Dutch"
#   define _DutchPatternID_                L"nederl.ptn"
#   define _DutchPrincDictID_              L"Nprinc"
#   define _DeID_                          L"German"
#   define _DePatternID_                   L"deutsch.ptn"
#   define _DePrincDictID_                 L"Gprinc"
#   define _EnID_                          L"English"
#   define _EnPatternID_                   L"english.ptn"
#   define _EnPersoDictID_                 L"Eperso"
#   define _EnPrincDictID_                 L"Eprinc"
#   define _EsID_                          L"Spanish"
#   define _EsPatternID_                   L"espanol.ptn"
#   define _EsPrincDictID_                 L"Sprinc"
#   define _FinnishID_                     L"Finnish"
#   define _FiPatternID_                   L"finish.ptn"
#   define _FrID_                          L"French"
#   define _FrPatternID_                   L"francais.ptn"
#   define _FrPersoDictID_                 L"Fperso"
#   define _FrPrincDictID_                 L"Fprinc"
#   define _GreekID_                       L"Greek"
#   define _ItalianID_                     L"Italian"
#   define _ItPrincDictID_                 L"Iprinc"
#   define _ItPatternID_                   L"italiano.ptn"
#   define _PolishID_                      L"Polish"
#   define _PortugueseID_                  L"Portuguese"
#   define _PtPatternID_                   L"portug.ptn"
#   define _SwedishID_                     L"Swedish"
#   define _SwPatternID_                   L"swedish.ptn"
#   define _TurkishID_                     L"Turkish" 
#   define _USPatternID_                   L"american.ptn"
#   define _WPrincDictID_                  L"Wprinc"


#   define _ISO_ID1_                       L"iso_8859_1"

#   define _ReadMODE_                      L"r" 
#   define _RBinaryMODE_                   L"rb"
#   define _WriteMODE_                     L"w" 
#   define _WBinaryMODE_                   L"wb" 
#   define _AppendBinaryMODE_              L"wb+"
#   define _RW_MODE_                       L"rw"
#   define _AppendMODE_                    L"w+"       

#   define _USPaperFormat_                 L"US"
#   define _A4PaperFormat_                 L"A4"
#   define _A3PaperFormat_                 L"A3"

#   define  WIN_DEF_TMPDIR                 L"c:\\temp"

#else  /* !_I18N_ */
#      define _ZERO_              "0"
#      define _ONE_               "1"
#      define _TWO_               "2"
#      define _THREE_             "3"
#      define _FOUR_              "4"
#      define _FIVE_              "5"
#      define _SIX_               "6"
#      define _SEVEN_             "7"
#      define _EIGHT_             "8"
#      define _NINE_              "9" 
#      define _A_                 "A"
#      define _B_                 "B"
#      define _C_                 "C"
#      define _D_                 "D"
#      define _E_                 "E"
#      define _F_                 "F"
#      define _G_                 "G"
#      define _H_                 "H"
#      define _I_                 "I"
#      define _J_                 "J"
#      define _K_                 "K"
#      define _L_                 "L"
#      define _M_                 "M"
#      define _N_                 "N"
#      define _O_                 "O"
#      define _P_                 "P"
#      define _Q_                 "Q"
#      define _R_                 "R"
#      define _S_                 "S"
#      define _T_                 "T"
#      define _U_                 "U"
#      define _V_                 "V"
#      define _W_                 "W"
#      define _X_                 "X"
#      define _Y_                 "Y"
#      define _Z_                 "Z"
#      define _a_                 "a"
#      define _b_                 "b"
#      define _c_                 "c"
#      define _d_                 "d"
#      define _e_                 "e"
#      define _f_                 "f"
#      define _g_                 "g"
#      define _h_                 "h"
#      define _i_                 "i"
#      define _j_                 "j"
#      define _k_                 "k"
#      define _l_                 "l"
#      define _m_                 "m"
#      define _n_                 "n"
#      define _o_                 "o"
#      define _p_                 "p"
#      define _q_                 "q"
#      define _r_                 "r"
#      define _s_                 "s"
#      define _t_                 "t"
#      define _u_                 "u"
#      define _v_                 "v"
#      define _w_                 "w"
#      define _x_                 "x"
#      define _y_                 "y"
#      define _z_                 "z"

#      define LT_OP               "<"
#      define GT_OP               ">"
#      define EQ_OP               "="
#      define AND_OP              "&"

/*     Special characters */
#      define _NEWLINE_           "\n"
#      define _TABULATION_        "\t"

#      define _ActiveBoxColorCST_    "ActiveBoxColor"
#      define _AlphabetCST_          "alphabet"
#      define _AmayaMainCST_         "AmayaMain"
#      define _BackgroundColorCST_   "BackgroundColor"
#      define _BUTTONCST_            "BUTTON"
#      define _ClientWndProcCST_     "ClientWndProc"
#      define _CorrdialogueCST_      "corrdialogue"
#      define _DicCST_               "dic"
#      define _DCTCST_               "DCT"
#      define _DocSelectColorCST_    "DocSelectColor"
#      define _DocumentCST_          "document"
#      define _DocumentNatureCST_    "document-nature"
#      define _EDITCST_              "EDIT"
#      define _EDITORCST_            "EDITOR"
#      define _ExportCST_            "export"
#      define _ExtensionCST_         "extension"
#      define _ForegroundColorCST_   "ForegroundColor"
#      define _FormattedViewCST_     "Formatted_view"
#      define _FormClassCST_         "FormClass" 
#      define _GeometryCST_          "geometry"
#      define _IDI_APPICONCST_       "IDI_APPICON"
#      define _ImportCST_            "import"
#      define _InactiveItemColorCST_ "InactiveItemColor"
#      define _KeyboardCST_          "keyboard"
#      define _LEXCST_               "LEX"
#      define _LibdialogueCST_       "libdialogue"
#      define _MenuAttributeCST_     "MenuAttribute"
#      define _MenuBgColorCST_       "MenuBgColor"
#      define _MenuFgColorCST_       "MenuFgColor"
#      define _MenuHelpCST_          "MenuHelp"
#      define _MenuSelectionCST_     "MenuSelection"
#      define _NatureCST_            "nature"
#      define _NumAttrClassCST_      "NumAttrClass"
#      define _PagesizeCST_          "pagesize"
#      define _PresentationCST_      "presentation"
#      define _OpenCST_              "open"
#      define _OptionsCST_           "options"
#      define _ReadOnlyColorCST_     "ReadOnlyColor"
#      define _SaveFileAsCST_        "Save File as"
#      define _ScrollbarCST_          "scrollbar"
#      define _SheetClassCST_        "SheetClass" 
#      define _SpecialCharsCST_      "@#$&+~" 
#      define _STATICCST_            "STATIC"
#      define _StyleCST_             "style"
#      define _ThotColorPaletteCST_  "ThotColorPalette"
#      define _TranslationCST_       "translation"
#      define _TtcPasteCST_          "TtcPaste"
#      define _TtcRedoCST_           "TtcRedo"
#      define _TtcUndoCST_           "TtcUndo"
#      define _TypographyCST_        "typography"
#      define _VISIBILITYCST_        "VISIBILITY"
#      define _WNDIALOGBOXCST_       "WNDIALOGBOX"
#      define _ZOOMCST_              "ZOOM"

#      define _THOTElement_          "thot"
#      define _XMLElement_           "xml"
#      define _XMLNameSpace_         "xmlns"

#      define _AmayaFatalErrorMSG_            "Amaya: fatal error"
#      define _AttributeElementMismatchMSG_   "attribute element mismatch"
#      define _BufferTooSmallMSG_             "buffer too small"
#      define _CannotHolophrastARootMSG_      "cannot holophrast a root"
#      define _CannotHolophrastThatTypeMSG_   "cannot holophrast that type"
#      define _CannotLoadPschemaMSG_          "cannot load pschema"
#      define _CannotReadStructureSchemaMSG_  "cannot read structure schema"
#      define _CannotOpenPivotFileMSG_        "cannot open pivot file"
#      define _CannotOpenViewMSG_             "cannot open view"
#      define _CannotSetLinkMSG_              "cannot set link"
#      define _DuplicateAttributeMSG_         "duplicate attribute"
#      define _DuplicatePresentationRuleMSG_  "duplicate presentation rule"
#      define _EmptyDocumentMSG_              "empty document"
#      define _ElementAlreadyInsertedMSG_     "element already inserted"
#      define _ElementDoesNotMatchDTDMSG_     "element does not match DTD"
#      define _ElementHasNoBoxMSG_            "element has no box"
#      define _FeatureNotImplementedMSG_      "feature not implemented"
#      define _IncorrectTreeMSG_              "incorrect tree"
#      define _InvalidAssociatedRootMSG_      "invalid associated root"
#      define _InvalidAttributeTypeMSG_       "invalid attribute type"
#      define _InvalidAttributeValueMSG_      "invalid attribute value"
#      define _InvalidButtonNdxMSG_           "Invalid Button Index" 
#      define _InvalidDocumentNameMSG_        "invalid document name"
#      define _InvalidDocumentParameterMSG_   "invalid document parameter"
#      define _InvalidElementTypeMSG_         "invalid element type"
#      define _InvalidParameterMSG_           "invalid parameter"
#      define _LanguageNotFoundMSG_           "language not found"
#      define _LanguageTableIsFullMSG_        "language table is full"
#      define _MainWindowNotOpenMSG_          "main window not open"
#      define _MandatoryAttributeMSG_         "mandatory attribute"
#      define _NoPresentationSchemaMSG_       "no presentation schema"
#      define _NoSelectionInDocumentMSG_      "no selection in document"
#      define _ReadOnlyDocumentMSG_           "read only document"
#      define _SpellCheckingMSG_              "Spell checking"
#      define _StringTooLongMSG_              "string too long"
#      define _ThereAreOpenViewsMSG_          "there are open views"
#      define _TooManyDocumentsMSG_           "too many documents" 

#      define _ANYFILE_                       "*."
#      define BAK_EXT2                        "BAK"
#      define EXE_EXT                         ".exe"
#      define EXE_EXT2                        "EXE"
#      define EXT_EXT2                        "EXT"
#      define html_EXT                        ".html"
#      define html_EXT2                       "html"
#      define KB_EXT                          ".kb"
#      define Keyboard_EXT                    ".keyboard"
#      define OLD_EXT2                        "OLD"
#      define PIV_EXT                         ".PIV"
#      define PIV_EXT2                        "PIV"
#      define PRS_EXT                         ".PRS"
#      define PRS_EXT2                        "PRS"
#      define Ps_EXT2                         "ps"
#      define REF_EXT2                        "REF"
#      define SAV_EXT2                        "SAV"
#      define STR_EXT                         ".STR"
#      define STR_EXT2                        "STR"
#      define Tmp_EXT2                        "Tmp"
#      define TRA_EXT                         ".TRA"
#      define TRA_EXT2                        "TRA"
#      define X_EXT                           ".X"
#      define XML_EXT                         ".xml"
#      define XML_EXT2                        "XML"

#      define _CONFSUFFIX_                    "conf"

#      define _CsLANG_                        "cs"
#      define _FiLANG_                        "fi"
#      define _FrLANG_                        "fr"
#      define _ElLANG_                        "el"
#      define _EnLANG_                        "en"
#      define _EsLANG_                        "es"
#      define _DeLANG_                        "de"
#      define _ItLANG_                        "it"
#      define _PlLANG_                        "pl"
#      define _PtLANG_                        "pt"
#      define _NlLANG_                        "nl"
#      define _SvLANG_                        "sv"
#      define _TrLANG_                        "tr"
#      define _EnUSLANG_                      "en-US"

#      define _APPHOME_EVAR_                  "APP_HOME"
#      define _Appname_EVAR_                  "appname"
#      define _AUTOSAVE_EVAR_                 "AUTOSAVE"
#      define _BackgroundColor_EVAR_          "BackgroundColor"
#      define _CACHEDIR_EVAR_                 "CACHE_DIR"
#      define _CACHEDISCONNECTEDMODE_EVAR_    "CACHE_DISCONNECTED_MODE"
#      define _CACHEEXPIREIGNORE_EVAR_        "CACHE_EXPIRE_IGNORE"
#      define _CACHEPROTECTEDDOCS_EVAR_       "CACHE_PROTECTED_DOCS"
#      define _CACHESIZE_EVAR_                "CACHE_SIZE"
#      define _DEFAULTNAME_EVAR_              "DEFAULTNAME"
#      define _DICOPAR_EVAR_                  "DICOPAR"
#      define _DNSTIMEOUT_EVAR_               "DNS_TIMEOUT"
#      define _DOUBLECLICKDELAY_EVAR_         "DOUBLECLICKDELAY"
#      define _ENABLEBGIMAGES_EVAR_           "ENABLE_BG_IMAGES"
#      define _ENABLECACHE_EVAR_              "ENABLE_CACHE"
#      define _ENABLEDOUBLECLICK_EVAR_        "ENABLE_DOUBLECLICK"
#      define _ENABLELOSTUPDATECHECK_EVAR_    "ENABLE_LOST_UPDATE_CHECK"
#      define _ENABLEMDA_EVAR_                "ENABLE_MDA"
#      define _ENABLEMULTIKEY_EVAR_           "ENABLE_MULTIKEY"
#      define _ENABLEPIPELINING_EVAR_         "ENABLE_PIPELINING"
#      define _EXTENDDICT_EVAR_               "EXTENDDICT"
#      define _FontFamily_EVAR_               "FontFamily"
#      define _FontMenuSize_EVAR_             "FontMenuSize"
#      define _ForegroundColor_EVAR_          "ForegroundColor"
#      define _HOME_EVAR_                     "HOME"
#      define _HOMEPAGE_EVAR_                 "HOME_PAGE"
#      define _HTTPPROXY_EVAR_                "HTTP_PROXY"
#      define _LANG_EVAR_                     "LANG"
#      define _MAXCACHEENTRYSIZE_EVAR_        "MAX_CACHE_ENTRY_SIZE"
#      define _MAXSOCKET_EVAR_                "MAX_SOCKET"
#      define _NETEVENTTIMEOUT_EVAR_          "NET_EVENT_TIMEOUT"
#      define _NOPROXY_EVAR_                  "NO_PROXY"
#      define _PAPERSIZE_EVAR_                "PAPERSIZE"
#      define _PATH_EVAR_                     "PATH"
#      define _PERSISTCXTIMEOUT_EVAR_         "PERSIST_CX_TIMEOUT"
#      define _PWD_EVAR_                      "PWD"
#      define _ReduceColor_EVAR_              "ReduceColor"
#      define _THOTDOC_EVAR_                  "THOTDOC"
#      define _THOTDIR_EVAR_                  "THOTDIR"
#      define _THOTPRINT_EVAR_                "THOTPRINT"
#      define _THOTSCH_EVAR_                  "THOTSCH"
#      define _THOTSYSSCH_EVAR_               "THOTSYSSCH"
#      define _TMPDIR_EVAR_                   "TMPDIR"
#      define _TOOLTIPDELAY_EVAR_             "TOOLTIPDELAY"
#      define _VERIFYPUBLISH_EVAR_            "VERIFY_PUBLISH"
#      define _ZOOM_EVAR_                     "ZOOM"

#      define _AltKEY_                        "Alt"
#      define _BackspaceKEY_                  "backspace"
#      define _CtrlKEY_                       "Ctrl"
#      define _DeleteKEY_                     "delete"
#      define _DownKEY_                       "down"
#      define _EndKEY_                        "end"
#      define _EscapeKEY_                     "escape"
#      define _F1KEY_                         "F1"
#      define _F2KEY_                         "F2"
#      define _F3KEY_                         "F3"
#      define _F4KEY_                         "F4"
#      define _F5KEY_                         "F5"
#      define _F6KEY_                         "F6"
#      define _F7KEY_                         "F7"
#      define _F8KEY_                         "F8"
#      define _F9KEY_                         "F9"
#      define _F10KEY_                        "F10"
#      define _F11KEY_                        "F11"
#      define _F12KEY_                        "F12"
#      define _F13KEY_                        "F13"
#      define _F14KEY_                        "F14"
#      define _F15KEY_                        "F15"
#      define _F16KEY_                        "F16"
#      define _F17KEY_                        "F17"
#      define _F18KEY_                        "F18"
#      define _F19KEY_                        "F19"
#      define _F20KEY_                        "F20"
#      define _F21KEY_                        "F21"
#      define _F22KEY_                        "F22"
#      define _F23KEY_                        "F23"
#      define _F24KEY_                        "F24"
#      define _F25KEY_                        "F25"
#      define _F26KEY_                        "F26"
#      define _F27KEY_                        "F27"
#      define _F28KEY_                        "F28"
#      define _F29KEY_                        "F29"
#      define _F30KEY_                        "F30"
#      define _F31KEY_                        "F31"
#      define _F32KEY_                        "F32"
#      define _F33KEY_                        "F33"
#      define _F34KEY_                        "F34"
#      define _F35KEY_                        "F35"
#      define _HomeKEY_                       "home"
#      define _LeftKEY_                       "left"
#      define _MetaKEY_                       "meta"
#      define _RightKEY_                      "right"
#      define _ReturnKEY_                     "Return"
#      define _ShiftKEY_                      "Shift"
#      define _SpaceKEY_                      "space"
#      define _UpKEY_                         "up"

#      define _KBKeyRC_                       "<Key>"

#      define _AmericanID_                    "American"
#      define _CzechID_                       "Czech"
#      define _DutchID_                       "Dutch"
#      define _DutchPatternID_                "nederl.ptn"
#      define _DutchPrincDictID_              "Nprinc"
#      define _DeID_                          "German"
#      define _DePatternID_                   "deutsch.ptn"
#      define _DePrincDictID_                 "Gprinc"
#      define _EnID_                          "English"
#      define _EnPatternID_                   "english.ptn"
#      define _EnPersoDictID_                 "Eperso"
#      define _EnPrincDictID_                 "Eprinc"
#      define _EsID_                          "Spanish"
#      define _EsPatternID_                   "espanol.ptn"
#      define _EsPrincDictID_                 "Sprinc"
#      define _FinnishID_                     "Finnish"
#      define _FiPatternID_                   "finish.ptn"
#      define _FrID_                          "French"
#      define _FrPatternID_                   "francais.ptn"
#      define _FrPersoDictID_                 "Fperso"
#      define _FrPrincDictID_                 "Fprinc"
#      define _GreekID_                       "Greek"
#      define _ItalianID_                     "Italian"
#      define _ItPrincDictID_                 "Iprinc"
#      define _ItPatternID_                   "italiano.ptn"
#      define _PolishID_                      "Polish"
#      define _PortugueseID_                  "Portuguese"
#      define _PtPatternID_                   "portug.ptn"
#      define _SwedishID_                     "Swedish"
#      define _SwPatternID_                   "swedish.ptn"
#      define _TurkishID_                     "Turkish" 
#      define _USPatternID_                   "american.ptn"
#      define _WPrincDictID_                  "Wprinc"

#      define _ISO_ID1_                       "iso_8859_1"

#      define _ReadMODE_                      "r" 
#      define _RBinaryMODE_                   "rb"
#      define _RW_MODE_                       "rw"
#      define _WBinaryMODE_                   "wb" 
#      define _AppendBinaryMODE_              "wb+"
#      define _WriteMODE_                     "w" 
#      define _AppendMODE_                    "w+" 

#      define _USPaperFormat_                  "US"
#      define _A4PaperFormat_                  "A4"
#      define _A3PaperFormat_                  "A3"

#      ifdef _WINDOWS
#      define  WIN_DEF_TMPDIR           "c:\\temp"
#      else  /* !_WINDOWS */
#      endif /* ! _WINDOWS */


#endif /* !_I18N_ */

#endif /* _UCS2_CONST */
