#include <native.h>
#include "JavaTypes.h"
#include "biss_awt_APIstubs.h"

void register_biss_awt_API_stubs(void)
{
#ifndef _WINDOWS
      addNativeMethod("biss_awt_kernel_NativeLib_initStdColor",
		      biss_awt_kernel_NativeLib_initStdColor);
      addNativeMethod("biss_awt_kernel_NativeLib_getNextEvent",
		      biss_awt_kernel_NativeLib_getNextEvent);
      addNativeMethod("biss_awt_kernel_NativeLib_initialize",
		      biss_awt_kernel_NativeLib_initialize);
      addNativeMethod("biss_awt_kernel_NativeLib_setDebugLevel",
		      biss_awt_kernel_NativeLib_setDebugLevel);
      addNativeMethod("biss_awt_kernel_NativeLib_sync",
		      biss_awt_kernel_NativeLib_sync);
      addNativeMethod("biss_awt_kernel_NativeLib_initFontMetrics",
		      biss_awt_kernel_NativeLib_initFontMetrics);
      addNativeMethod("biss_awt_kernel_NativeLib_releaseFontMetrics",
		      biss_awt_kernel_NativeLib_releaseFontMetrics);
      addNativeMethod("biss_awt_kernel_NativeLib_setStdFontSpec",
		      biss_awt_kernel_NativeLib_setStdFontSpec);
      addNativeMethod("biss_awt_kernel_NativeLib_stringWidth",
		      biss_awt_kernel_NativeLib_stringWidth);
      addNativeMethod("biss_awt_kernel_NativeLib_clearRect",
		      biss_awt_kernel_NativeLib_clearRect);
      addNativeMethod("biss_awt_kernel_NativeLib_clipGraphics",
		      biss_awt_kernel_NativeLib_clipGraphics);
      addNativeMethod("biss_awt_kernel_NativeLib_copyArea",
		      biss_awt_kernel_NativeLib_copyArea);
      addNativeMethod("biss_awt_kernel_NativeLib_draw3DRect",
		      biss_awt_kernel_NativeLib_draw3DRect);
      addNativeMethod("biss_awt_kernel_NativeLib_drawArc",
		      biss_awt_kernel_NativeLib_drawArc);
      addNativeMethod("biss_awt_kernel_NativeLib_drawChars",
		      biss_awt_kernel_NativeLib_drawChars);
      addNativeMethod("biss_awt_kernel_NativeLib_drawImage",
		      biss_awt_kernel_NativeLib_drawImage);
      addNativeMethod("biss_awt_kernel_NativeLib_drawLine",
		      biss_awt_kernel_NativeLib_drawLine);
      addNativeMethod("biss_awt_kernel_NativeLib_drawOval",
		      biss_awt_kernel_NativeLib_drawOval);
      addNativeMethod("biss_awt_kernel_NativeLib_drawPolygon",
		      biss_awt_kernel_NativeLib_drawPolygon);
      addNativeMethod("biss_awt_kernel_NativeLib_drawRect",
		      biss_awt_kernel_NativeLib_drawRect);
      addNativeMethod("biss_awt_kernel_NativeLib_drawRoundRect",
		      biss_awt_kernel_NativeLib_drawRoundRect);
      addNativeMethod("biss_awt_kernel_NativeLib_drawString",
		      biss_awt_kernel_NativeLib_drawString);
      addNativeMethod("biss_awt_kernel_NativeLib_fillArc",
		      biss_awt_kernel_NativeLib_fillArc);
      addNativeMethod("biss_awt_kernel_NativeLib_fillOval",
		      biss_awt_kernel_NativeLib_fillOval);
      addNativeMethod("biss_awt_kernel_NativeLib_fillPolygon",
		      biss_awt_kernel_NativeLib_fillPolygon);
      addNativeMethod("biss_awt_kernel_NativeLib_fillRect",
		      biss_awt_kernel_NativeLib_fillRect);
      addNativeMethod("biss_awt_kernel_NativeLib_fillRoundRect",
		      biss_awt_kernel_NativeLib_fillRoundRect);
      addNativeMethod("biss_awt_kernel_NativeLib_initGraphics",
		      biss_awt_kernel_NativeLib_initGraphics);
      addNativeMethod("biss_awt_kernel_NativeLib_initPaintGraphics",
		      biss_awt_kernel_NativeLib_initPaintGraphics);
      addNativeMethod("biss_awt_kernel_NativeLib_releaseGraphics",
		      biss_awt_kernel_NativeLib_releaseGraphics);
      addNativeMethod("biss_awt_kernel_NativeLib_releasePaintGraphics",
		      biss_awt_kernel_NativeLib_releasePaintGraphics);
      addNativeMethod("biss_awt_kernel_NativeLib_setColor",
		      biss_awt_kernel_NativeLib_setColor);
      addNativeMethod("biss_awt_kernel_NativeLib_setFont",
		      biss_awt_kernel_NativeLib_setFont);
      addNativeMethod("biss_awt_kernel_NativeLib_setPaintMode",
		      biss_awt_kernel_NativeLib_setPaintMode);
      addNativeMethod("biss_awt_kernel_NativeLib_setXORMode",
		      biss_awt_kernel_NativeLib_setXORMode);
      addNativeMethod("biss_awt_kernel_NativeLib_initBlankImage",
		      biss_awt_kernel_NativeLib_initBlankImage);
      addNativeMethod("biss_awt_kernel_NativeLib_releaseImage",
		      biss_awt_kernel_NativeLib_releaseImage);
      addNativeMethod("biss_awt_kernel_NativeLib_createWindow",
		      biss_awt_kernel_NativeLib_createWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_destroyWindow",
		      biss_awt_kernel_NativeLib_destroyWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_getTargetBackground",
		      biss_awt_kernel_NativeLib_getTargetBackground);
      addNativeMethod("biss_awt_kernel_NativeLib_getTargetFont",
		      biss_awt_kernel_NativeLib_getTargetFont);
      addNativeMethod("biss_awt_kernel_NativeLib_getTargetForeground",
		      biss_awt_kernel_NativeLib_getTargetForeground);
      addNativeMethod("biss_awt_kernel_NativeLib_hideWindow",
		      biss_awt_kernel_NativeLib_hideWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_lowerWindow",
		      biss_awt_kernel_NativeLib_lowerWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_raiseWindow",
		      biss_awt_kernel_NativeLib_raiseWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_repaintWindow",
		      biss_awt_kernel_NativeLib_repaintWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_reshapeWindow",
		      biss_awt_kernel_NativeLib_reshapeWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_setFocusWindow",
		      biss_awt_kernel_NativeLib_setFocusWindow);
      addNativeMethod("biss_awt_kernel_NativeLib_setWindowBackground",
		      biss_awt_kernel_NativeLib_setWindowBackground);
      addNativeMethod("biss_awt_kernel_NativeLib_setWindowCursor",
		      biss_awt_kernel_NativeLib_setWindowCursor);
      addNativeMethod("biss_awt_kernel_NativeLib_setWindowTitle",
		      biss_awt_kernel_NativeLib_setWindowTitle);
      addNativeMethod("biss_awt_kernel_NativeLib_showWindow",
		      biss_awt_kernel_NativeLib_showWindow);
#endif
}
