Document TtaNewDocument(char *structureSchema, char *documentName);
Document TtaOpenDocument(char *documentName, int accessMode);
void TtaSaveDocument(Document document, char *documentName);
void TtaExportDocument(Document document, char *fileName, char *TSchemaName);
void TtaCloseDocument(Document document);
void TtaRemoveDocument(Document document);
void TtaSetDocumentPath(char *path);
boolean TtaCheckDirectory(char *aDirectory);
boolean TtaCheckPath(char *path);
boolean TtaIsInDocumentPath(char *aDirectory);
void TtaAppendDocumentPath(char *aDirectory);
void TtaSetSchemaPath(char *path);
SSchema TtaNewNature(SSchema schema, char *natureName, char *presentationName);
SSchema TtaNewSchemaExtension(Document document, char *extensionName, char *presentationName);
SSchema TtaGetSchemaExtension(Document document, char *NomExtension);
void TtaSetPSchema(Document document, char *presentationName);
void TtaSetDocumentDirectory(Document document, char *directory);
void TtaSetDocumentName(Document document, char *documentName);
void TtaSetDocumentAccessMode(Document document, int accessMode);
void TtaSetDocumentBackUpInterval(Document document, int interval);
void TtaSetNotificationMode(Document document, int notificationMode);
void TtaSetDocumentModified(Document document);
void TtaSetDocumentUnmodified(Document document);
char *TtaGetDocumentName(Document document);
Document TtaGetDocumentFromName(char *documentName);
void TtaGetDocumentDirectory(Document document, char *buffer, int bufferLength);
SSchema TtaGetDocumentSSchema(Document document);
char *TtaGetSSchemaName(SSchema schema);
char *TtaGetPSchemaName(SSchema schema);
SSchema TtaGetSSchema(char *name, Document document);
int TtaSameSSchemas(SSchema schema1, SSchema schema2);
void TtaGiveSchemasOfDocument(char *documentName, char *structureName, char *presentationName);
int TtaIsDocumentModified(Document document);
int TtaGetDocumentAccessMode(Document document);
int TtaGetDocumentBackUpInterval(Document document);
int TtaGetNotificationMode(Document document);
void TtaGetDocumentPath(char *buffer, int bufferLength);
void TtaGetSchemaPath(char *buffer, int bufferLength);
Document TtaGetDocumentOfSavedElements(void);
Document TtaGetDocumentOfSavedElements(void);
