/*
 * Java public native definitions for class thotlib_Language
 * This piece of code has to be copied in the Java code
 * for class thotlib_Language i.e thotlib_Language.java
 *
 * Generated by the following command from /users/veillard/opera/javalib directory
 * javastub -C thotlib_Language ../thotlib/include/language.h 
 */

	public native String TtaGetVarLANG();
	public native int TtaGetNumberOfLanguages();
