/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIInterface -J ../classes/thotlib/APIInterface.java ../thotlib/include/interface.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APIInterface from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 * As well as the Class LOCK/UNLOCK macros
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APIInterface.h"
#include "thotlib_APIInterface_stubs.h"

#ifndef thotlib_APIInterface_LOCK
#define thotlib_APIInterface_LOCK()
#endif /* thotlib_APIInterface_LOCK */
#ifndef thotlib_APIInterface_UNLOCK
#define thotlib_APIInterface_UNLOCK()
#endif /* thotlib_APIInterface_UNLOCK */

/*
 * Java to C function TtaSwitchButton stub.
 */
void
thotlib_APIInterface_TtaSwitchButton(struct Hthotlib_APIInterface* none, jint document, jint view, jint index)
{


	thotlib_APIInterface_LOCK();

	TtaSwitchButton((Document ) document, (View ) view, (int ) index);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaSetTextZone stub.
 */
void
thotlib_APIInterface_TtaSetTextZone(struct Hthotlib_APIInterface* none, jint document, jint view, jint index, struct Hjava_lang_String* jtext)
{
	char text[1024];

	javaString2CString(jtext, text, sizeof(text));

	thotlib_APIInterface_LOCK();

	TtaSetTextZone((Document ) document, (View ) view, (int ) index, (char *) text);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaSetMenuOff stub.
 */
void
thotlib_APIInterface_TtaSetMenuOff(struct Hthotlib_APIInterface* none, jint document, jint view, jint menuID)
{


	thotlib_APIInterface_LOCK();

	TtaSetMenuOff((Document ) document, (View ) view, (int ) menuID);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaSetMenuOn stub.
 */
void
thotlib_APIInterface_TtaSetMenuOn(struct Hthotlib_APIInterface* none, jint document, jint view, jint menuID)
{


	thotlib_APIInterface_LOCK();

	TtaSetMenuOn((Document ) document, (View ) view, (int ) menuID);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaSetToggleItem stub.
 */
void
thotlib_APIInterface_TtaSetToggleItem(struct Hthotlib_APIInterface* none, jint document, jint view, jint menuID, jint itemID, jint on)
{


	thotlib_APIInterface_LOCK();

	TtaSetToggleItem((Document ) document, (View ) view, (int ) menuID, (int ) itemID, (boolean ) on);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaSetActionOff stub.
 */
void
thotlib_APIInterface_TtaSetActionOff(struct Hthotlib_APIInterface* none, jint document, jint view, jint menuID, jint itemID)
{


	thotlib_APIInterface_LOCK();

	TtaSetActionOff((Document ) document, (View ) view, (int ) menuID, (int ) itemID);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaSetActionOn stub.
 */
void
thotlib_APIInterface_TtaSetActionOn(struct Hthotlib_APIInterface* none, jint document, jint view, jint menuID, jint itemID)
{


	thotlib_APIInterface_LOCK();

	TtaSetActionOn((Document ) document, (View ) view, (int ) menuID, (int ) itemID);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaSetStatus stub.
 */
void
thotlib_APIInterface_TtaSetStatus(struct Hthotlib_APIInterface* none, jint document, jint view, struct Hjava_lang_String* jtext, struct Hjava_lang_String* jname)
{
	char text[1024];
	char name[1024];

	javaString2CString(jtext, text, sizeof(text));
	javaString2CString(jname, name, sizeof(name));

	thotlib_APIInterface_LOCK();

	TtaSetStatus((Document ) document, (View ) view, (char *) text, (char *) name);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaGetViewFrame stub.
 */
jint
thotlib_APIInterface_TtaGetViewFrame(struct Hthotlib_APIInterface* none, jint document, jint view)
{
	ThotWidget res;


	thotlib_APIInterface_LOCK();

	res = TtaGetViewFrame((Document ) document, (View ) view);

	thotlib_APIInterface_UNLOCK();

	return((jint) res);
}

/*
 * Java to C function TtaMainLoop stub.
 */
void
thotlib_APIInterface_TtaMainLoop(struct Hthotlib_APIInterface* none)
{


	thotlib_APIInterface_LOCK();

	TtaMainLoop();

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaHandlePendingEvents stub.
 */
void
thotlib_APIInterface_TtaHandlePendingEvents(struct Hthotlib_APIInterface* none)
{


	thotlib_APIInterface_LOCK();

	TtaHandlePendingEvents();

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaClickElement stub.
 */
void
thotlib_APIInterface_TtaClickElement(struct Hthotlib_APIInterface* none, struct Hthotlib_Document* jdocument, struct Hthotlib_Element* jelement)
{
	Document *document;
	Element *element;

	/* convert arg struct Hthotlib_Document* jdocument to Document *document */
	JavaDocument2CDocumentPtr(jdocument,&document);
	/* convert arg struct Hthotlib_Element* jelement to Element *element */
	JavaElement2CElementPtr(jelement,&element);

	thotlib_APIInterface_LOCK();

	TtaClickElement((Document *) document, (Element *) element);

	thotlib_APIInterface_UNLOCK();
	/* convert Document *document to arg struct Hthotlib_Document* jdocument */
	CDocumentPtr2JavaDocument(document,&jdocument);
	/* convert Element *element to arg struct Hthotlib_Element* jelement */
	CElementPtr2JavaElement(element,&jelement);
}

/*
 * Java to C function TtaSetCursorWatch stub.
 */
void
thotlib_APIInterface_TtaSetCursorWatch(struct Hthotlib_APIInterface* none, jint document, jint view)
{


	thotlib_APIInterface_LOCK();

	TtaSetCursorWatch((Document ) document, (View ) view);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaResetCursor stub.
 */
void
thotlib_APIInterface_TtaResetCursor(struct Hthotlib_APIInterface* none, jint document, jint view)
{


	thotlib_APIInterface_LOCK();

	TtaResetCursor((Document ) document, (View ) view);

	thotlib_APIInterface_UNLOCK();
}

/*
 * Java to C function TtaGetMenuColor stub.
 */
jint
thotlib_APIInterface_TtaGetMenuColor(struct Hthotlib_APIInterface* none)
{
	Pixel res;


	thotlib_APIInterface_LOCK();

	res = TtaGetMenuColor();

	thotlib_APIInterface_UNLOCK();

	return((jint) res);
}

/*
 * Java to C function TtaGetButtonColor stub.
 */
jint
thotlib_APIInterface_TtaGetButtonColor(struct Hthotlib_APIInterface* none)
{
	Pixel res;


	thotlib_APIInterface_LOCK();

	res = TtaGetButtonColor();

	thotlib_APIInterface_UNLOCK();

	return((jint) res);
}

/*
 * Java to C function TtaGetScreenDepth stub.
 */
jint
thotlib_APIInterface_TtaGetScreenDepth(struct Hthotlib_APIInterface* none)
{
	int res;


	thotlib_APIInterface_LOCK();

	res = TtaGetScreenDepth();

	thotlib_APIInterface_UNLOCK();

	return((jint) res);
}

/*
 * Function to register all thotlib_APIInterface stubs.
 */
void register_thotlib_APIInterface_stubs(void)
{
	addNativeMethod("thotlib_APIInterface_TtaSwitchButton", thotlib_APIInterface_TtaSwitchButton);
	addNativeMethod("thotlib_APIInterface_TtaSetTextZone", thotlib_APIInterface_TtaSetTextZone);
	addNativeMethod("thotlib_APIInterface_TtaSetMenuOff", thotlib_APIInterface_TtaSetMenuOff);
	addNativeMethod("thotlib_APIInterface_TtaSetMenuOn", thotlib_APIInterface_TtaSetMenuOn);
	addNativeMethod("thotlib_APIInterface_TtaSetToggleItem", thotlib_APIInterface_TtaSetToggleItem);
	addNativeMethod("thotlib_APIInterface_TtaSetActionOff", thotlib_APIInterface_TtaSetActionOff);
	addNativeMethod("thotlib_APIInterface_TtaSetActionOn", thotlib_APIInterface_TtaSetActionOn);
	addNativeMethod("thotlib_APIInterface_TtaSetStatus", thotlib_APIInterface_TtaSetStatus);
	addNativeMethod("thotlib_APIInterface_TtaGetViewFrame", thotlib_APIInterface_TtaGetViewFrame);
	addNativeMethod("thotlib_APIInterface_TtaMainLoop", thotlib_APIInterface_TtaMainLoop);
	addNativeMethod("thotlib_APIInterface_TtaHandlePendingEvents", thotlib_APIInterface_TtaHandlePendingEvents);
	addNativeMethod("thotlib_APIInterface_TtaClickElement", thotlib_APIInterface_TtaClickElement);
	addNativeMethod("thotlib_APIInterface_TtaSetCursorWatch", thotlib_APIInterface_TtaSetCursorWatch);
	addNativeMethod("thotlib_APIInterface_TtaResetCursor", thotlib_APIInterface_TtaResetCursor);
	addNativeMethod("thotlib_APIInterface_TtaGetMenuColor", thotlib_APIInterface_TtaGetMenuColor);
	addNativeMethod("thotlib_APIInterface_TtaGetButtonColor", thotlib_APIInterface_TtaGetButtonColor);
	addNativeMethod("thotlib_APIInterface_TtaGetScreenDepth", thotlib_APIInterface_TtaGetScreenDepth);
}

