int TtaNewDocument(String structureSchema, String documentName);
int TtaOpenDocument(String documentName, int accessMode);
 TtaSaveDocument(int document, String documentName);
 TtaExportDocument(int document, String fileName, String TSchemaName);
 TtaCloseDocument(int document);
 TtaRemoveDocument(int document);
 TtaSetDocumentPath(String path);
boolean TtaCheckDirectory(String aDirectory);
boolean TtaCheckPath(String path);
boolean TtaIsInDocumentPath(String aDirectory);
 TtaAppendDocumentPath(String aDirectory);
 TtaSetSchemaPath(String path);
int TtaNewNature(int schema, String natureName, String presentationName);
int TtaNewSchemaExtension(int document, String extensionName, String presentationName);
int TtaGetSchemaExtension(int document, String NomExtension);
 TtaSetPSchema(int document, String presentationName);
 TtaSetDocumentDirectory(int document, String directory);
 TtaSetDocumentName(int document, String documentName);
 TtaSetDocumentAccessMode(int document, int accessMode);
 TtaSetDocumentBackUpInterval(int document, int interval);
 TtaSetNotificationMode(int document, int notificationMode);
 TtaSetDocumentModified(int document);
 TtaSetDocumentUnmodified(int document);
String TtaGetDocumentName(int document);
int TtaGetDocumentFromName(String documentName);
 TtaGetDocumentDirectory(int document, String buffer, int bufferLength);
int TtaGetDocumentSSchema(int document);
String TtaGetSSchemaName(int schema);
String TtaGetPSchemaName(int schema);
int TtaGetSSchema(String name, int document);
int TtaSameSSchemas(int schema1, int schema2);
 TtaGiveSchemasOfDocument(String documentName, String structureName, String presentationName);
int TtaIsDocumentModified(int document);
int TtaGetDocumentAccessMode(int document);
int TtaGetDocumentBackUpInterval(int document);
int TtaGetNotificationMode(int document);
 TtaGetDocumentPath(String buffer, int bufferLength);
 TtaGetSchemaPath(String buffer, int bufferLength);
int TtaGetDocumentOfSavedElements(void);
int TtaGetDocumentOfSavedElements(void);
