/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * /users/veillard/opera/LINUX-ELF/javalib/../bin/javastub -T JavaTypes.def -M thotlib_APITree -J ../classes/thotlib/APITree.java ../thotlib/include/tree.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APITree from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 * As well as the Class LOCK/UNLOCK macros
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APITree.h"
#include "thotlib_APITree_stubs.h"

#ifndef thotlib_APITree_LOCK
#define thotlib_APITree_LOCK() fprintf(stderr,"thotlib_APITree_LOCK undefined");
#endif /* thotlib_APITree_LOCK */
#ifndef thotlib_APITree_UNLOCK
#define thotlib_APITree_UNLOCK() fprintf(stderr,"thotlib_APITree_UNLOCK undefined");
#endif /* thotlib_APITree_UNLOCK */

/*
 * Java to C function ChangeElementType stub.
 */
void
thotlib_APITree_ChangeElementType(struct Hthotlib_APITree* none, jlong jelement, jint typeNum)
{
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	ChangeElementType((Element ) element, (int ) typeNum);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaCopyTree stub.
 */
jlong
thotlib_APITree_TtaCopyTree(struct Hthotlib_APITree* none, jlong jsourceElement, jint sourceDocument, jint destinationDocument, jlong jparent)
{
	jlong result;
	Element res;
	Element sourceElement;
	Element parent;

	/* convert arg jlong jsourceElement to Element sourceElement */
	Javalong2CElement(jsourceElement,&sourceElement);
	/* convert arg jlong jparent to Element parent */
	Javalong2CElement(jparent,&parent);

	thotlib_APITree_LOCK();

	res = TtaCopyTree((Element ) sourceElement, (Document ) sourceDocument, (Document ) destinationDocument, (Element ) parent);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaDeleteTree stub.
 */
void
thotlib_APITree_TtaDeleteTree(struct Hthotlib_APITree* none, jlong jelement, jint document)
{
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	TtaDeleteTree((Element ) element, (Document ) document);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaAttachNewTree stub.
 */
void
thotlib_APITree_TtaAttachNewTree(struct Hthotlib_APITree* none, jlong jtree, jint document)
{
	Element tree;

	/* convert arg jlong jtree to Element tree */
	Javalong2CElement(jtree,&tree);

	thotlib_APITree_LOCK();

	TtaAttachNewTree((Element ) tree, (Document ) document);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaInsertSibling stub.
 */
void
thotlib_APITree_TtaInsertSibling(struct Hthotlib_APITree* none, jlong jnewElement, jlong jsibling, jint before, jint document)
{
	Element newElement;
	Element sibling;

	/* convert arg jlong jnewElement to Element newElement */
	Javalong2CElement(jnewElement,&newElement);
	/* convert arg jlong jsibling to Element sibling */
	Javalong2CElement(jsibling,&sibling);

	thotlib_APITree_LOCK();

	TtaInsertSibling((Element ) newElement, (Element ) sibling, (boolean ) before, (Document ) document);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaInsertFirstChild stub.
 */
void
thotlib_APITree_TtaInsertFirstChild(struct Hthotlib_APITree* none, struct Hthotlib_Element* jnewElement, jlong jparent, jint document)
{
	Element *newElement;
	Element parent;

	/* convert arg struct Hthotlib_Element* jnewElement to Element *newElement */
	JavaElement2CElementPtr(jnewElement,&newElement);
	/* convert arg jlong jparent to Element parent */
	Javalong2CElement(jparent,&parent);

	thotlib_APITree_LOCK();

	TtaInsertFirstChild((Element *) newElement, (Element ) parent, (Document ) document);

	thotlib_APITree_UNLOCK();

	/* convert Element *newElement to arg struct Hthotlib_Element* jnewElement */
	CElementPtr2JavaElement(newElement,&jnewElement);
}

/*
 * Java to C function TtaRemoveTree stub.
 */
void
thotlib_APITree_TtaRemoveTree(struct Hthotlib_APITree* none, jlong jelement, jint document)
{
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	TtaRemoveTree((Element ) element, (Document ) document);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaSetAccessRight stub.
 */
void
thotlib_APITree_TtaSetAccessRight(struct Hthotlib_APITree* none, jlong jelement, jint right, jint document)
{
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	TtaSetAccessRight((Element ) element, (AccessRight ) right, (Document ) document);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaHolophrastElement stub.
 */
void
thotlib_APITree_TtaHolophrastElement(struct Hthotlib_APITree* none, jlong jelement, jint holophrast, jint document)
{
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	TtaHolophrastElement((Element ) element, (boolean ) holophrast, (Document ) document);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaSetStructureChecking stub.
 */
void
thotlib_APITree_TtaSetStructureChecking(struct Hthotlib_APITree* none, jint on, jint document)
{


	thotlib_APITree_LOCK();

	TtaSetStructureChecking((boolean ) on, (Document ) document);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaGetStructureChecking stub.
 */
jint
thotlib_APITree_TtaGetStructureChecking(struct Hthotlib_APITree* none, jint document)
{
	int res;


	thotlib_APITree_LOCK();

	res = TtaGetStructureChecking((Document ) document);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaSetCheckingMode stub.
 */
void
thotlib_APITree_TtaSetCheckingMode(struct Hthotlib_APITree* none, jint strict)
{


	thotlib_APITree_LOCK();

	TtaSetCheckingMode((boolean ) strict);

	thotlib_APITree_UNLOCK();

}

/*
 * Java to C function TtaGetMainRoot stub.
 */
jlong
thotlib_APITree_TtaGetMainRoot(struct Hthotlib_APITree* none, jint document)
{
	jlong result;
	Element res;


	thotlib_APITree_LOCK();

	res = TtaGetMainRoot((Document ) document);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaNextAssociatedRoot stub.
 */
void
thotlib_APITree_TtaNextAssociatedRoot(struct Hthotlib_APITree* none, jint document, struct Hthotlib_Element* jroot)
{
	Element *root;

	/* convert arg struct Hthotlib_Element* jroot to Element *root */
	JavaElement2CElementPtr(jroot,&root);

	thotlib_APITree_LOCK();

	TtaNextAssociatedRoot((Document ) document, (Element *) root);

	thotlib_APITree_UNLOCK();

	/* convert Element *root to arg struct Hthotlib_Element* jroot */
	CElementPtr2JavaElement(root,&jroot);
}

/*
 * Java to C function TtaGetFirstChild stub.
 */
jlong
thotlib_APITree_TtaGetFirstChild(struct Hthotlib_APITree* none, jlong jparent)
{
	jlong result;
	Element res;
	Element parent;

	/* convert arg jlong jparent to Element parent */
	Javalong2CElement(jparent,&parent);

	thotlib_APITree_LOCK();

	res = TtaGetFirstChild((Element ) parent);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaGetLastChild stub.
 */
jlong
thotlib_APITree_TtaGetLastChild(struct Hthotlib_APITree* none, jlong jparent)
{
	jlong result;
	Element res;
	Element parent;

	/* convert arg jlong jparent to Element parent */
	Javalong2CElement(jparent,&parent);

	thotlib_APITree_LOCK();

	res = TtaGetLastChild((Element ) parent);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaPreviousSibling stub.
 */
void
thotlib_APITree_TtaPreviousSibling(struct Hthotlib_APITree* none, struct Hthotlib_Element* jelement)
{
	Element *element;

	/* convert arg struct Hthotlib_Element* jelement to Element *element */
	JavaElement2CElementPtr(jelement,&element);

	thotlib_APITree_LOCK();

	TtaPreviousSibling((Element *) element);

	thotlib_APITree_UNLOCK();

	/* convert Element *element to arg struct Hthotlib_Element* jelement */
	CElementPtr2JavaElement(element,&jelement);
}

/*
 * Java to C function TtaNextSibling stub.
 */
void
thotlib_APITree_TtaNextSibling(struct Hthotlib_APITree* none, struct Hthotlib_Element* jelement)
{
	Element *element;

	/* convert arg struct Hthotlib_Element* jelement to Element *element */
	JavaElement2CElementPtr(jelement,&element);

	thotlib_APITree_LOCK();

	TtaNextSibling((Element *) element);

	thotlib_APITree_UNLOCK();

	/* convert Element *element to arg struct Hthotlib_Element* jelement */
	CElementPtr2JavaElement(element,&jelement);
}

/*
 * Java to C function TtaGetSuccessor stub.
 */
jlong
thotlib_APITree_TtaGetSuccessor(struct Hthotlib_APITree* none, jlong jelement)
{
	jlong result;
	Element res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaGetSuccessor((Element ) element);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaGetPredecessor stub.
 */
jlong
thotlib_APITree_TtaGetPredecessor(struct Hthotlib_APITree* none, jlong jelement)
{
	jlong result;
	Element res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaGetPredecessor((Element ) element);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaGetParent stub.
 */
jlong
thotlib_APITree_TtaGetParent(struct Hthotlib_APITree* none, jlong jelement)
{
	jlong result;
	Element res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaGetParent((Element ) element);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaGetCommonAncestor stub.
 */
jlong
thotlib_APITree_TtaGetCommonAncestor(struct Hthotlib_APITree* none, jlong jelement1, jlong jelement2)
{
	jlong result;
	Element res;
	Element element1;
	Element element2;

	/* convert arg jlong jelement1 to Element element1 */
	Javalong2CElement(jelement1,&element1);
	/* convert arg jlong jelement2 to Element element2 */
	Javalong2CElement(jelement2,&element2);

	thotlib_APITree_LOCK();

	res = TtaGetCommonAncestor((Element ) element1, (Element ) element2);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaIsExtensionElement stub.
 */
jint
thotlib_APITree_TtaIsExtensionElement(struct Hthotlib_APITree* none, jlong jelement)
{
	boolean res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaIsExtensionElement((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaGiveTypeFromName stub.
 */
void
thotlib_APITree_TtaGiveTypeFromName(struct Hthotlib_APITree* none, struct Hthotlib_ElementType* jelementType, struct Hjava_lang_String* jname)
{
	ElementType *elementType;
	char name[1024];
	char *name_ptr = &name[0];

	/* convert arg struct Hthotlib_ElementType* jelementType to ElementType *elementType */
	JavaElementType2CElementTypePtr(jelementType,&elementType);
	if (jname != NULL)
	  javaString2CString(jname, name_ptr, sizeof(name));
	else
	  name_ptr = NULL;

	thotlib_APITree_LOCK();

	TtaGiveTypeFromName((ElementType *) elementType, (char *) name_ptr);

	thotlib_APITree_UNLOCK();

	/* convert ElementType *elementType to arg struct Hthotlib_ElementType* jelementType */
	CElementTypePtr2JavaElementType(elementType,&jelementType);
}

/*
 * Java to C function TtaGetElementLabel stub.
 */
struct Hjava_lang_String*
thotlib_APITree_TtaGetElementLabel(struct Hthotlib_APITree* none, jlong jelement)
{
	char *res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaGetElementLabel((Element ) element);

	thotlib_APITree_UNLOCK();


	if (res == NULL)
		return(NULL);
	else;
		return(makeJavaString(res, strlen(res)));
}

/*
 * Java to C function TtaGetElementVolume stub.
 */
jint
thotlib_APITree_TtaGetElementVolume(struct Hthotlib_APITree* none, jlong jelement)
{
	int res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaGetElementVolume((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaGetAccessRight stub.
 */
jint
thotlib_APITree_TtaGetAccessRight(struct Hthotlib_APITree* none, jlong jelement)
{
	AccessRight res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaGetAccessRight((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaIsHolophrasted stub.
 */
jint
thotlib_APITree_TtaIsHolophrasted(struct Hthotlib_APITree* none, jlong jelement)
{
	int res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaIsHolophrasted((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaIsReadOnly stub.
 */
jint
thotlib_APITree_TtaIsReadOnly(struct Hthotlib_APITree* none, jlong jelement)
{
	int res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaIsReadOnly((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaIsHidden stub.
 */
jint
thotlib_APITree_TtaIsHidden(struct Hthotlib_APITree* none, jlong jelement)
{
	int res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaIsHidden((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaIsInAnInclusion stub.
 */
jint
thotlib_APITree_TtaIsInAnInclusion(struct Hthotlib_APITree* none, jlong jelement)
{
	int res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaIsInAnInclusion((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaIsAncestor stub.
 */
jint
thotlib_APITree_TtaIsAncestor(struct Hthotlib_APITree* none, jlong jelement, jlong jancestor)
{
	int res;
	Element element;
	Element ancestor;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);
	/* convert arg jlong jancestor to Element ancestor */
	Javalong2CElement(jancestor,&ancestor);

	thotlib_APITree_LOCK();

	res = TtaIsAncestor((Element ) element, (Element ) ancestor);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaIsBefore stub.
 */
jint
thotlib_APITree_TtaIsBefore(struct Hthotlib_APITree* none, jlong jelement1, jlong jelement2)
{
	int res;
	Element element1;
	Element element2;

	/* convert arg jlong jelement1 to Element element1 */
	Javalong2CElement(jelement1,&element1);
	/* convert arg jlong jelement2 to Element element2 */
	Javalong2CElement(jelement2,&element2);

	thotlib_APITree_LOCK();

	res = TtaIsBefore((Element ) element1, (Element ) element2);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaIsFirstPairedElement stub.
 */
jint
thotlib_APITree_TtaIsFirstPairedElement(struct Hthotlib_APITree* none, jlong jelement)
{
	int res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaIsFirstPairedElement((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaGetDocument stub.
 */
jint
thotlib_APITree_TtaGetDocument(struct Hthotlib_APITree* none, jlong jelement)
{
	Document res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaGetDocument((Element ) element);

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaNextCopiedElement stub.
 */
void
thotlib_APITree_TtaNextCopiedElement(struct Hthotlib_APITree* none, struct Hthotlib_Element* jelement)
{
	Element *element;

	/* convert arg struct Hthotlib_Element* jelement to Element *element */
	JavaElement2CElementPtr(jelement,&element);

	thotlib_APITree_LOCK();

	TtaNextCopiedElement((Element *) element);

	thotlib_APITree_UNLOCK();

	/* convert Element *element to arg struct Hthotlib_Element* jelement */
	CElementPtr2JavaElement(element,&jelement);
}

/*
 * Java to C function TtaGetCopiedDocument stub.
 */
jint
thotlib_APITree_TtaGetCopiedDocument(struct Hthotlib_APITree* none)
{
	Document res;


	thotlib_APITree_LOCK();

	res = TtaGetCopiedDocument();

	thotlib_APITree_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaSearchElementByLabel stub.
 */
jlong
thotlib_APITree_TtaSearchElementByLabel(struct Hthotlib_APITree* none, struct Hjava_lang_String* jsearchedLabel, jlong jelement)
{
	jlong result;
	Element res;
	char searchedLabel[1024];
	char *searchedLabel_ptr = &searchedLabel[0];
	Element element;

	if (jsearchedLabel != NULL)
	  javaString2CString(jsearchedLabel, searchedLabel_ptr, sizeof(searchedLabel));
	else
	  searchedLabel_ptr = NULL;
	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaSearchElementByLabel((char *) searchedLabel_ptr, (Element ) element);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaSearchEmptyElement stub.
 */
jlong
thotlib_APITree_TtaSearchEmptyElement(struct Hthotlib_APITree* none, jint scope, jlong jelement)
{
	jlong result;
	Element res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaSearchEmptyElement((SearchDomain ) scope, (Element ) element);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaSearchOtherPairedElement stub.
 */
jlong
thotlib_APITree_TtaSearchOtherPairedElement(struct Hthotlib_APITree* none, jlong jelement)
{
	jlong result;
	Element res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaSearchOtherPairedElement((Element ) element);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaSearchNoPageBreak stub.
 */
jlong
thotlib_APITree_TtaSearchNoPageBreak(struct Hthotlib_APITree* none, jlong jelement, jint forward)
{
	jlong result;
	Element res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APITree_LOCK();

	res = TtaSearchNoPageBreak((Element ) element, (boolean ) forward);

	thotlib_APITree_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaAskFirstCreation stub.
 */
void
thotlib_APITree_TtaAskFirstCreation(struct Hthotlib_APITree* none)
{


	thotlib_APITree_LOCK();

	TtaAskFirstCreation();

	thotlib_APITree_UNLOCK();

}

/*
 * Function to register all thotlib_APITree stubs.
 */
void register_thotlib_APITree_stubs(void)
{
	addNativeMethod("thotlib_APITree_ChangeElementType", thotlib_APITree_ChangeElementType);
	addNativeMethod("thotlib_APITree_TtaCopyTree", thotlib_APITree_TtaCopyTree);
	addNativeMethod("thotlib_APITree_TtaDeleteTree", thotlib_APITree_TtaDeleteTree);
	addNativeMethod("thotlib_APITree_TtaAttachNewTree", thotlib_APITree_TtaAttachNewTree);
	addNativeMethod("thotlib_APITree_TtaInsertSibling", thotlib_APITree_TtaInsertSibling);
	addNativeMethod("thotlib_APITree_TtaInsertFirstChild", thotlib_APITree_TtaInsertFirstChild);
	addNativeMethod("thotlib_APITree_TtaRemoveTree", thotlib_APITree_TtaRemoveTree);
	addNativeMethod("thotlib_APITree_TtaSetAccessRight", thotlib_APITree_TtaSetAccessRight);
	addNativeMethod("thotlib_APITree_TtaHolophrastElement", thotlib_APITree_TtaHolophrastElement);
	addNativeMethod("thotlib_APITree_TtaSetStructureChecking", thotlib_APITree_TtaSetStructureChecking);
	addNativeMethod("thotlib_APITree_TtaGetStructureChecking", thotlib_APITree_TtaGetStructureChecking);
	addNativeMethod("thotlib_APITree_TtaSetCheckingMode", thotlib_APITree_TtaSetCheckingMode);
	addNativeMethod("thotlib_APITree_TtaGetMainRoot", thotlib_APITree_TtaGetMainRoot);
	addNativeMethod("thotlib_APITree_TtaNextAssociatedRoot", thotlib_APITree_TtaNextAssociatedRoot);
	addNativeMethod("thotlib_APITree_TtaGetFirstChild", thotlib_APITree_TtaGetFirstChild);
	addNativeMethod("thotlib_APITree_TtaGetLastChild", thotlib_APITree_TtaGetLastChild);
	addNativeMethod("thotlib_APITree_TtaPreviousSibling", thotlib_APITree_TtaPreviousSibling);
	addNativeMethod("thotlib_APITree_TtaNextSibling", thotlib_APITree_TtaNextSibling);
	addNativeMethod("thotlib_APITree_TtaGetSuccessor", thotlib_APITree_TtaGetSuccessor);
	addNativeMethod("thotlib_APITree_TtaGetPredecessor", thotlib_APITree_TtaGetPredecessor);
	addNativeMethod("thotlib_APITree_TtaGetParent", thotlib_APITree_TtaGetParent);
	addNativeMethod("thotlib_APITree_TtaGetCommonAncestor", thotlib_APITree_TtaGetCommonAncestor);
	addNativeMethod("thotlib_APITree_TtaIsExtensionElement", thotlib_APITree_TtaIsExtensionElement);
	addNativeMethod("thotlib_APITree_TtaGiveTypeFromName", thotlib_APITree_TtaGiveTypeFromName);
	addNativeMethod("thotlib_APITree_TtaGetElementLabel", thotlib_APITree_TtaGetElementLabel);
	addNativeMethod("thotlib_APITree_TtaGetElementVolume", thotlib_APITree_TtaGetElementVolume);
	addNativeMethod("thotlib_APITree_TtaGetAccessRight", thotlib_APITree_TtaGetAccessRight);
	addNativeMethod("thotlib_APITree_TtaIsHolophrasted", thotlib_APITree_TtaIsHolophrasted);
	addNativeMethod("thotlib_APITree_TtaIsReadOnly", thotlib_APITree_TtaIsReadOnly);
	addNativeMethod("thotlib_APITree_TtaIsHidden", thotlib_APITree_TtaIsHidden);
	addNativeMethod("thotlib_APITree_TtaIsInAnInclusion", thotlib_APITree_TtaIsInAnInclusion);
	addNativeMethod("thotlib_APITree_TtaIsAncestor", thotlib_APITree_TtaIsAncestor);
	addNativeMethod("thotlib_APITree_TtaIsBefore", thotlib_APITree_TtaIsBefore);
	addNativeMethod("thotlib_APITree_TtaIsFirstPairedElement", thotlib_APITree_TtaIsFirstPairedElement);
	addNativeMethod("thotlib_APITree_TtaGetDocument", thotlib_APITree_TtaGetDocument);
	addNativeMethod("thotlib_APITree_TtaNextCopiedElement", thotlib_APITree_TtaNextCopiedElement);
	addNativeMethod("thotlib_APITree_TtaGetCopiedDocument", thotlib_APITree_TtaGetCopiedDocument);
	addNativeMethod("thotlib_APITree_TtaSearchElementByLabel", thotlib_APITree_TtaSearchElementByLabel);
	addNativeMethod("thotlib_APITree_TtaSearchEmptyElement", thotlib_APITree_TtaSearchEmptyElement);
	addNativeMethod("thotlib_APITree_TtaSearchOtherPairedElement", thotlib_APITree_TtaSearchOtherPairedElement);
	addNativeMethod("thotlib_APITree_TtaSearchNoPageBreak", thotlib_APITree_TtaSearchNoPageBreak);
	addNativeMethod("thotlib_APITree_TtaAskFirstCreation", thotlib_APITree_TtaAskFirstCreation);
}

