/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APILanguage -J ../classes/thotlib/APILanguage.java ../thotlib/include/language.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APILanguage from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 * As well as the Class LOCK/UNLOCK macros
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APILanguage.h"
#include "thotlib_APILanguage_stubs.h"

#ifndef thotlib_APILanguage_LOCK
#define thotlib_APILanguage_LOCK() fprintf(stderr,"thotlib_APILanguage_LOCK undefined");
#endif /* thotlib_APILanguage_LOCK */
#ifndef thotlib_APILanguage_UNLOCK
#define thotlib_APILanguage_UNLOCK() fprintf(stderr,"thotlib_APILanguage_UNLOCK undefined");
#endif /* thotlib_APILanguage_UNLOCK */

/*
 * Java to C function TtaNewLanguage stub.
 */
jint
thotlib_APILanguage_TtaNewLanguage(struct Hthotlib_APILanguage* none, struct Hjava_lang_String* jlanguageName, int languageAlphabet, struct Hjava_lang_String* jprincipalDictionary, struct Hjava_lang_String* jsecondDictionary)
{
	Language res;
	char languageName[1024];
	char *languageName_ptr = &languageName[0];
	char principalDictionary[1024];
	char *principalDictionary_ptr = &principalDictionary[0];
	char secondDictionary[1024];
	char *secondDictionary_ptr = &secondDictionary[0];

	if (jlanguageName != NULL)
	  javaString2CString(jlanguageName, languageName_ptr, sizeof(languageName));
	else
	  languageName_ptr = NULL;
	if (jprincipalDictionary != NULL)
	  javaString2CString(jprincipalDictionary, principalDictionary_ptr, sizeof(principalDictionary));
	else
	  principalDictionary_ptr = NULL;
	if (jsecondDictionary != NULL)
	  javaString2CString(jsecondDictionary, secondDictionary_ptr, sizeof(secondDictionary));
	else
	  secondDictionary_ptr = NULL;

	thotlib_APILanguage_LOCK();

	res = TtaNewLanguage((char *) languageName_ptr, (char ) languageAlphabet, (char *) principalDictionary_ptr, (char *) secondDictionary_ptr);

	thotlib_APILanguage_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaRemoveLanguage stub.
 */
void
thotlib_APILanguage_TtaRemoveLanguage(struct Hthotlib_APILanguage* none, jint language)
{


	thotlib_APILanguage_LOCK();

	TtaRemoveLanguage((Language ) language);

	thotlib_APILanguage_UNLOCK();

}

/*
 * Java to C function TtaGetLanguageIdFromName stub.
 */
jint
thotlib_APILanguage_TtaGetLanguageIdFromName(struct Hthotlib_APILanguage* none, struct Hjava_lang_String* jlanguageName)
{
	Language res;
	char languageName[1024];
	char *languageName_ptr = &languageName[0];

	if (jlanguageName != NULL)
	  javaString2CString(jlanguageName, languageName_ptr, sizeof(languageName));
	else
	  languageName_ptr = NULL;

	thotlib_APILanguage_LOCK();

	res = TtaGetLanguageIdFromName((char *) languageName_ptr);

	thotlib_APILanguage_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaGetVarLANG stub.
 */
struct Hjava_lang_String*
thotlib_APILanguage_TtaGetVarLANG(struct Hthotlib_APILanguage* none)
{
	char *res;


	thotlib_APILanguage_LOCK();

	res = TtaGetVarLANG();

	thotlib_APILanguage_UNLOCK();


	if (res == NULL)
		return(NULL);
	else;
		return(makeJavaString(res, strlen(res)));
}

/*
 * Java to C function TtaGetDefaultLanguage stub.
 */
jint
thotlib_APILanguage_TtaGetDefaultLanguage(struct Hthotlib_APILanguage* none)
{
	Language res;


	thotlib_APILanguage_LOCK();

	res = TtaGetDefaultLanguage();

	thotlib_APILanguage_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaGetLanguageIdFromAlphabet stub.
 */
jint
thotlib_APILanguage_TtaGetLanguageIdFromAlphabet(struct Hthotlib_APILanguage* none, int languageAlphabet)
{
	Language res;


	thotlib_APILanguage_LOCK();

	res = TtaGetLanguageIdFromAlphabet((char ) languageAlphabet);

	thotlib_APILanguage_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaGetAlphabet stub.
 */
int
thotlib_APILanguage_TtaGetAlphabet(struct Hthotlib_APILanguage* none, jint languageId)
{
	char res;


	thotlib_APILanguage_LOCK();

	res = TtaGetAlphabet((Language ) languageId);

	thotlib_APILanguage_UNLOCK();


	return((int) res);
}

/*
 * Java to C function TtaGetLanguageName stub.
 */
struct Hjava_lang_String*
thotlib_APILanguage_TtaGetLanguageName(struct Hthotlib_APILanguage* none, jint languageId)
{
	char *res;


	thotlib_APILanguage_LOCK();

	res = TtaGetLanguageName((Language ) languageId);

	thotlib_APILanguage_UNLOCK();


	if (res == NULL)
		return(NULL);
	else;
		return(makeJavaString(res, strlen(res)));
}

/*
 * Java to C function TtaGetLanguageCode stub.
 */
struct Hjava_lang_String*
thotlib_APILanguage_TtaGetLanguageCode(struct Hthotlib_APILanguage* none, jint languageId)
{
	char *res;


	thotlib_APILanguage_LOCK();

	res = TtaGetLanguageCode((Language ) languageId);

	thotlib_APILanguage_UNLOCK();


	if (res == NULL)
		return(NULL);
	else;
		return(makeJavaString(res, strlen(res)));
}

/*
 * Java to C function TtaGetNumberOfLanguages stub.
 */
jint
thotlib_APILanguage_TtaGetNumberOfLanguages(struct Hthotlib_APILanguage* none)
{
	int res;


	thotlib_APILanguage_LOCK();

	res = TtaGetNumberOfLanguages();

	thotlib_APILanguage_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaLoadLanguageDictionaries stub.
 */
jint
thotlib_APILanguage_TtaLoadLanguageDictionaries(struct Hthotlib_APILanguage* none, jint languageId)
{
	boolean res;


	thotlib_APILanguage_LOCK();

	res = TtaLoadLanguageDictionaries((Language ) languageId);

	thotlib_APILanguage_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaUnLoadLanguageDictionaries stub.
 */
void
thotlib_APILanguage_TtaUnLoadLanguageDictionaries(struct Hthotlib_APILanguage* none, jint languageId)
{


	thotlib_APILanguage_LOCK();

	TtaUnLoadLanguageDictionaries((Language ) languageId);

	thotlib_APILanguage_UNLOCK();

}

/*
 * Function to register all thotlib_APILanguage stubs.
 */
void register_thotlib_APILanguage_stubs(void)
{
	addNativeMethod("thotlib_APILanguage_TtaNewLanguage", thotlib_APILanguage_TtaNewLanguage);
	addNativeMethod("thotlib_APILanguage_TtaRemoveLanguage", thotlib_APILanguage_TtaRemoveLanguage);
	addNativeMethod("thotlib_APILanguage_TtaGetLanguageIdFromName", thotlib_APILanguage_TtaGetLanguageIdFromName);
	addNativeMethod("thotlib_APILanguage_TtaGetVarLANG", thotlib_APILanguage_TtaGetVarLANG);
	addNativeMethod("thotlib_APILanguage_TtaGetDefaultLanguage", thotlib_APILanguage_TtaGetDefaultLanguage);
	addNativeMethod("thotlib_APILanguage_TtaGetLanguageIdFromAlphabet", thotlib_APILanguage_TtaGetLanguageIdFromAlphabet);
	addNativeMethod("thotlib_APILanguage_TtaGetAlphabet", thotlib_APILanguage_TtaGetAlphabet);
	addNativeMethod("thotlib_APILanguage_TtaGetLanguageName", thotlib_APILanguage_TtaGetLanguageName);
	addNativeMethod("thotlib_APILanguage_TtaGetLanguageCode", thotlib_APILanguage_TtaGetLanguageCode);
	addNativeMethod("thotlib_APILanguage_TtaGetNumberOfLanguages", thotlib_APILanguage_TtaGetNumberOfLanguages);
	addNativeMethod("thotlib_APILanguage_TtaLoadLanguageDictionaries", thotlib_APILanguage_TtaLoadLanguageDictionaries);
	addNativeMethod("thotlib_APILanguage_TtaUnLoadLanguageDictionaries", thotlib_APILanguage_TtaUnLoadLanguageDictionaries);
}

