/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * javastub -T JavaTypes.def -M thotlib_APILanguage -J ../classes/thotlib/APILanguage.java ../thotlib/include/language.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APILanguage from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APILanguage.h"
#include "thotlib_APILanguage_stubs.h"
/*
 * Java to C function TtaNewLanguage stub.
 */
jint
thotlib_APILanguage_TtaNewLanguage(struct Hthotlib_APILanguage* none, struct Hjava_lang_String* jlanguageName, int languageAlphabet, struct Hjava_lang_String* jprincipalDictionary, struct Hjava_lang_String* jsecondDictionary)
{
	Language res;
	char languageName[1024];
	char principalDictionary[1024];
	char secondDictionary[1024];

	javaString2CString(jlanguageName, languageName, sizeof(languageName));
	javaString2CString(jprincipalDictionary, principalDictionary, sizeof(principalDictionary));
	javaString2CString(jsecondDictionary, secondDictionary, sizeof(secondDictionary));

	res = TtaNewLanguage((char *) languageName, (char ) languageAlphabet, (char *) principalDictionary, (char *) secondDictionary);

	return((jint) res);
}

/*
 * Java to C function TtaGetLanguageIdFromName stub.
 */
jint
thotlib_APILanguage_TtaGetLanguageIdFromName(struct Hthotlib_APILanguage* none, struct Hjava_lang_String* jlanguageName)
{
	Language res;
	char languageName[1024];

	javaString2CString(jlanguageName, languageName, sizeof(languageName));

	res = TtaGetLanguageIdFromName((char *) languageName);

	return((jint) res);
}

/*
 * Java to C function TtaGetVarLANG stub.
 */
struct Hjava_lang_String*
thotlib_APILanguage_TtaGetVarLANG(struct Hthotlib_APILanguage* none)
{
	char *res;


	res = TtaGetVarLANG();

	return(makeJavaString(res, sizeof(res)));
}

/*
 * Java to C function TtaGetDefaultLanguage stub.
 */
jint
thotlib_APILanguage_TtaGetDefaultLanguage(struct Hthotlib_APILanguage* none)
{
	Language res;


	res = TtaGetDefaultLanguage();

	return((jint) res);
}

/*
 * Java to C function TtaGetLanguageIdFromAlphabet stub.
 */
jint
thotlib_APILanguage_TtaGetLanguageIdFromAlphabet(struct Hthotlib_APILanguage* none, int languageAlphabet)
{
	Language res;


	res = TtaGetLanguageIdFromAlphabet((char ) languageAlphabet);

	return((jint) res);
}

/*
 * Java to C function TtaGetAlphabet stub.
 */
int
thotlib_APILanguage_TtaGetAlphabet(struct Hthotlib_APILanguage* none, jint languageId)
{
	char res;


	res = TtaGetAlphabet((Language ) languageId);

	return((int) res);
}

/*
 * Java to C function TtaGetLanguageName stub.
 */
struct Hjava_lang_String*
thotlib_APILanguage_TtaGetLanguageName(struct Hthotlib_APILanguage* none, jint languageId)
{
	char *res;


	res = TtaGetLanguageName((Language ) languageId);

	return(makeJavaString(res, sizeof(res)));
}

/*
 * Java to C function TtaGetNumberOfLanguages stub.
 */
jint
thotlib_APILanguage_TtaGetNumberOfLanguages(struct Hthotlib_APILanguage* none)
{
	int res;


	res = TtaGetNumberOfLanguages();

	return((jint) res);
}

/*
 * Java to C function TtaLoadLanguageDictionaries stub.
 */
jint
thotlib_APILanguage_TtaLoadLanguageDictionaries(struct Hthotlib_APILanguage* none, jint languageId)
{
	boolean res;


	res = TtaLoadLanguageDictionaries((Language ) languageId);

	return((jint) res);
}

/*
 * Java to C function TtaUnLoadLanguageDictionaries stub.
 */
void
thotlib_APILanguage_TtaUnLoadLanguageDictionaries(struct Hthotlib_APILanguage* none, jint languageId)
{


	TtaUnLoadLanguageDictionaries((Language ) languageId);
}

/*
 * Function to register all thotlib_APILanguage stubs.
 */
void register_thotlib_APILanguage_stubs(void)
{
	addNativeMethod("thotlib_APILanguage_TtaNewLanguage", thotlib_APILanguage_TtaNewLanguage);
	addNativeMethod("thotlib_APILanguage_TtaGetLanguageIdFromName", thotlib_APILanguage_TtaGetLanguageIdFromName);
	addNativeMethod("thotlib_APILanguage_TtaGetVarLANG", thotlib_APILanguage_TtaGetVarLANG);
	addNativeMethod("thotlib_APILanguage_TtaGetDefaultLanguage", thotlib_APILanguage_TtaGetDefaultLanguage);
	addNativeMethod("thotlib_APILanguage_TtaGetLanguageIdFromAlphabet", thotlib_APILanguage_TtaGetLanguageIdFromAlphabet);
	addNativeMethod("thotlib_APILanguage_TtaGetAlphabet", thotlib_APILanguage_TtaGetAlphabet);
	addNativeMethod("thotlib_APILanguage_TtaGetLanguageName", thotlib_APILanguage_TtaGetLanguageName);
	addNativeMethod("thotlib_APILanguage_TtaGetNumberOfLanguages", thotlib_APILanguage_TtaGetNumberOfLanguages);
	addNativeMethod("thotlib_APILanguage_TtaLoadLanguageDictionaries", thotlib_APILanguage_TtaLoadLanguageDictionaries);
	addNativeMethod("thotlib_APILanguage_TtaUnLoadLanguageDictionaries", thotlib_APILanguage_TtaUnLoadLanguageDictionaries);
}

