/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIView -J ../classes/thotlib/APIView.java ../thotlib/include/view.h 
 */
/*
 * External definitions needed for class thotlib_APIView stubs
 */

#ifndef _Included_thotlib_APIView_stub_h
#define _Included_thotlib_APIView_stub_h
#include "../thotlib/include/view.h"


extern View TtaOpenMainView(Document document, int x, int y, int w, int h);
extern void TtaGetViewGeometry(Document document, char *name, /*OUT*/ int *x, /*OUT*/ int *y, /*OUT*/ int *width, /*OUT*/ int *height);
extern View TtaOpenView(Document document, char *viewName, int x, int y, int w, int h);
extern View TtaOpenSubView(Document document, char *viewName, int x, int y, int w, int h, Element subtree);
extern void TtaChangeViewTitle(Document document, View view, char *title);
extern void TtaCloseView(Document document, View view);
extern void TtaFreeView(Document document, View view);
extern void TtaSetSensibility(Document document, View view, int value);
extern void TtaSetZoom(Document document, View view, int value);
extern void TtaShowElement(Document document, View view, Element element, int position);
extern int TtaGetSensibility(Document document, View view);
extern int TtaGetZoom(Document document, View view);
extern int TtaIsPSchemaValid(char *structureName, char *presentationName);
extern void TtaGiveViewsToOpen(Document document, /*OUT*/ char *buffer, /*OUT*/ int *nbViews);
extern char *TtaGetViewName(Document document, View view);
extern boolean TtaIsViewOpened(Document document, View view);
extern View TtaGetViewFromName(Document document, char *viewName);
extern void TtaRaiseView(Document document, View view);
extern void TtaSetDisplayMode(Document document, DisplayMode newDisplayMode);
extern DisplayMode TtaGetDisplayMode(Document document);
extern void TtaResetViewBackgroundColor(Document doc, View view);
extern void TtaSetViewBackgroundColor(Document doc, View view, int color);
extern int TtaGetViewBackgroundColor(Document doc, View view);
extern void TtaClearViewSelections(void);
extern void register_thotlib_APIView_stubs(void);

#endif /* _Included_thotlib_APIView_stub_h */
