/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>
/* Stubs for class thotlib_Tree */

/* SYMBOL: thotlib_Tree TtaSetStructureChecking(ZI)V */
EXPORT(void)
Kaffe_thotlib_Tree_TtaSetStructureChecking_stub(stack_item* _P_, stack_item* _R_)
{
	extern void thotlib_Tree_TtaSetStructureChecking(void*, jint /* bool */, jint);
	thotlib_Tree_TtaSetStructureChecking(_P_[2].p, _P_[1].i, _P_[0].i);
}

/* SYMBOL: thotlib_Tree TtaGetStructureChecking(I)I */
EXPORT(void)
Kaffe_thotlib_Tree_TtaGetStructureChecking_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint thotlib_Tree_TtaGetStructureChecking(void*, jint);
	jint ret = thotlib_Tree_TtaGetStructureChecking(_P_[1].p, _P_[0].i);
	return_int(ret);
}

/* SYMBOL: thotlib_Tree TtaSetCheckingMode(Z)V */
EXPORT(void)
Kaffe_thotlib_Tree_TtaSetCheckingMode_stub(stack_item* _P_, stack_item* _R_)
{
	extern void thotlib_Tree_TtaSetCheckingMode(void*, jint /* bool */);
	thotlib_Tree_TtaSetCheckingMode(_P_[1].p, _P_[0].i);
}

/* SYMBOL: thotlib_Tree TtaGetCopiedDocument()I */
EXPORT(void)
Kaffe_thotlib_Tree_TtaGetCopiedDocument_stub(stack_item* _P_, stack_item* _R_)
{
	extern jint thotlib_Tree_TtaGetCopiedDocument(void*);
	jint ret = thotlib_Tree_TtaGetCopiedDocument(_P_[0].p);
	return_int(ret);
}

/* SYMBOL: thotlib_Tree TtaAskFirstCreation()V */
EXPORT(void)
Kaffe_thotlib_Tree_TtaAskFirstCreation_stub(stack_item* _P_, stack_item* _R_)
{
	extern void thotlib_Tree_TtaAskFirstCreation(void*);
	thotlib_Tree_TtaAskFirstCreation(_P_[0].p);
}
