/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APILanguage -J ../classes/thotlib/APILanguage.java ../thotlib/include/language.h 
 */
/*
 * External definitions needed for class thotlib_APILanguage stubs
 */

#ifndef _Included_thotlib_APILanguage_stub_h
#define _Included_thotlib_APILanguage_stub_h
#include "../thotlib/include/language.h"


extern Language TtaNewLanguage(char *languageName, char languageAlphabet, char *principalDictionary, char *secondDictionary);
extern void TtaRemoveLanguage(Language language);
extern Language TtaGetLanguageIdFromName(char *languageName);
extern char *TtaGetVarLANG(void);
extern Language TtaGetDefaultLanguage(void);
extern Language TtaGetLanguageIdFromAlphabet(char languageAlphabet);
extern char TtaGetAlphabet(Language languageId);
extern char *TtaGetLanguageName(Language languageId);
extern char *TtaGetLanguageCode(Language languageId);
extern int TtaGetNumberOfLanguages(void);
extern boolean TtaLoadLanguageDictionaries(Language languageId);
extern void TtaUnLoadLanguageDictionaries(Language languageId);
extern void register_thotlib_APILanguage_stubs(void);

#endif /* _Included_thotlib_APILanguage_stub_h */
