/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * javastub -T JavaTypes.def -M thotlib_APIPresentation -J ../classes/thotlib/APIPresentation.java ../thotlib/include/presentation.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APIPresentation from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APIPresentation.h"
#include "thotlib_APIPresentation_stubs.h"
/*
 * Java to C function TtaNewPRule stub.
 */
jint
thotlib_APIPresentation_TtaNewPRule(struct Hthotlib_APIPresentation* none, jint presentationType, jint view, jint document)
{
	PRule res;


	res = TtaNewPRule((int ) presentationType, (View ) view, (Document ) document);

	return((jint) res);
}

/*
 * Java to C function TtaNewPRuleForNamedView stub.
 */
jint
thotlib_APIPresentation_TtaNewPRuleForNamedView(struct Hthotlib_APIPresentation* none, jint presentationType, struct Hjava_lang_String* jviewName, jint document)
{
	PRule res;
	char viewName[1024];

	javaString2CString(jviewName, viewName, sizeof(viewName));

	res = TtaNewPRuleForNamedView((int ) presentationType, (char *) viewName, (Document ) document);

	return((jint) res);
}

/*
 * Java to C function TtaCopyPRule stub.
 */
jint
thotlib_APIPresentation_TtaCopyPRule(struct Hthotlib_APIPresentation* none, jint pRule)
{
	PRule res;


	res = TtaCopyPRule((PRule ) pRule);

	return((jint) res);
}

/*
 * Java to C function TtaAttachPRule stub.
 */
void
thotlib_APIPresentation_TtaAttachPRule(struct Hthotlib_APIPresentation* none, jint element, jint pRule, jint document)
{


	TtaAttachPRule((Element ) element, (PRule ) pRule, (Document ) document);
}

/*
 * Java to C function TtaRemovePRule stub.
 */
void
thotlib_APIPresentation_TtaRemovePRule(struct Hthotlib_APIPresentation* none, jint element, jint pRule, jint document)
{


	TtaRemovePRule((Element ) element, (PRule ) pRule, (Document ) document);
}

/*
 * Java to C function TtaSetPRuleValue stub.
 */
void
thotlib_APIPresentation_TtaSetPRuleValue(struct Hthotlib_APIPresentation* none, jint element, jint pRule, jint value, jint document)
{


	TtaSetPRuleValue((Element ) element, (PRule ) pRule, (int ) value, (Document ) document);
}

/*
 * Java to C function TtaChangeBoxSize stub.
 */
void
thotlib_APIPresentation_TtaChangeBoxSize(struct Hthotlib_APIPresentation* none, jint element, jint document, jint view, jint deltaX, jint deltaY, jint unit)
{


	TtaChangeBoxSize((Element ) element, (Document ) document, (View ) view, (int ) deltaX, (int ) deltaY, (TypeUnit ) unit);
}

/*
 * Java to C function TtaChangeBoxPosition stub.
 */
void
thotlib_APIPresentation_TtaChangeBoxPosition(struct Hthotlib_APIPresentation* none, jint element, jint document, jint view, jint X, jint Y, jint unit)
{


	TtaChangeBoxPosition((Element ) element, (Document ) document, (View ) view, (int ) X, (int ) Y, (TypeUnit ) unit);
}

/*
 * Java to C function TtaGetPRule stub.
 */
jint
thotlib_APIPresentation_TtaGetPRule(struct Hthotlib_APIPresentation* none, jint element, jint presentationType)
{
	PRule res;


	res = TtaGetPRule((Element ) element, (int ) presentationType);

	return((jint) res);
}

/*
 * Java to C function TtaGetPRuleType stub.
 */
jint
thotlib_APIPresentation_TtaGetPRuleType(struct Hthotlib_APIPresentation* none, jint pRule)
{
	int res;


	res = TtaGetPRuleType((PRule ) pRule);

	return((jint) res);
}

/*
 * Java to C function TtaGetPRuleValue stub.
 */
jint
thotlib_APIPresentation_TtaGetPRuleValue(struct Hthotlib_APIPresentation* none, jint pRule)
{
	int res;


	res = TtaGetPRuleValue((PRule ) pRule);

	return((jint) res);
}

/*
 * Java to C function TtaSamePRules stub.
 */
jint
thotlib_APIPresentation_TtaSamePRules(struct Hthotlib_APIPresentation* none, jint pRule1, jint pRule2)
{
	int res;


	res = TtaSamePRules((PRule ) pRule1, (PRule ) pRule2);

	return((jint) res);
}

/*
 * Function to register all thotlib_APIPresentation stubs.
 */
void register_thotlib_APIPresentation_stubs(void)
{
	addExternalNativeFunc("thotlib_APIPresentation_TtaNewPRule", thotlib_APIPresentation_TtaNewPRule);
	addExternalNativeFunc("thotlib_APIPresentation_TtaNewPRuleForNamedView", thotlib_APIPresentation_TtaNewPRuleForNamedView);
	addExternalNativeFunc("thotlib_APIPresentation_TtaCopyPRule", thotlib_APIPresentation_TtaCopyPRule);
	addExternalNativeFunc("thotlib_APIPresentation_TtaAttachPRule", thotlib_APIPresentation_TtaAttachPRule);
	addExternalNativeFunc("thotlib_APIPresentation_TtaRemovePRule", thotlib_APIPresentation_TtaRemovePRule);
	addExternalNativeFunc("thotlib_APIPresentation_TtaSetPRuleValue", thotlib_APIPresentation_TtaSetPRuleValue);
	addExternalNativeFunc("thotlib_APIPresentation_TtaChangeBoxSize", thotlib_APIPresentation_TtaChangeBoxSize);
	addExternalNativeFunc("thotlib_APIPresentation_TtaChangeBoxPosition", thotlib_APIPresentation_TtaChangeBoxPosition);
	addExternalNativeFunc("thotlib_APIPresentation_TtaGetPRule", thotlib_APIPresentation_TtaGetPRule);
	addExternalNativeFunc("thotlib_APIPresentation_TtaGetPRuleType", thotlib_APIPresentation_TtaGetPRuleType);
	addExternalNativeFunc("thotlib_APIPresentation_TtaGetPRuleValue", thotlib_APIPresentation_TtaGetPRuleValue);
	addExternalNativeFunc("thotlib_APIPresentation_TtaSamePRules", thotlib_APIPresentation_TtaSamePRules);
}

