/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIApplication -J ../classes/thotlib/APIApplication.java ../thotlib/include/application.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APIApplication from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 * As well as the Class LOCK/UNLOCK macros
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APIApplication.h"
#include "thotlib_APIApplication_stubs.h"

#ifndef thotlib_APIApplication_LOCK
#define thotlib_APIApplication_LOCK()
#endif /* thotlib_APIApplication_LOCK */
#ifndef thotlib_APIApplication_UNLOCK
#define thotlib_APIApplication_UNLOCK()
#endif /* thotlib_APIApplication_UNLOCK */

/*
 * Java to C function TtaInitialize stub.
 */
void
thotlib_APIApplication_TtaInitialize(struct Hthotlib_APIApplication* none, struct Hjava_lang_String* japplicationName)
{
	char applicationName[1024];

	javaString2CString(japplicationName, applicationName, sizeof(applicationName));

	thotlib_APIApplication_LOCK();

	TtaInitialize((char *) applicationName);

	thotlib_APIApplication_UNLOCK();
}

/*
 * Java to C function TtaQuit stub.
 */
void
thotlib_APIApplication_TtaQuit(struct Hthotlib_APIApplication* none)
{


	thotlib_APIApplication_LOCK();

	TtaQuit();

	thotlib_APIApplication_UNLOCK();
}

/*
 * Java to C function TtaSetErrorMessages stub.
 */
void
thotlib_APIApplication_TtaSetErrorMessages(struct Hthotlib_APIApplication* none, jint on)
{


	thotlib_APIApplication_LOCK();

	TtaSetErrorMessages((int ) on);

	thotlib_APIApplication_UNLOCK();
}

/*
 * Java to C function TtaGetVersion stub.
 */
struct Hjava_lang_String*
thotlib_APIApplication_TtaGetVersion(struct Hthotlib_APIApplication* none)
{
	char *res;


	thotlib_APIApplication_LOCK();

	res = TtaGetVersion();

	thotlib_APIApplication_UNLOCK();

	if (res == NULL)
		return(NULL);
	else;
		return(makeJavaString(res, strlen(res)));
}

/*
 * Java to C function TtaGetErrorCode stub.
 */
jint
thotlib_APIApplication_TtaGetErrorCode(struct Hthotlib_APIApplication* none)
{
	int res;


	thotlib_APIApplication_LOCK();

	res = TtaGetErrorCode();

	thotlib_APIApplication_UNLOCK();

	return((jint) res);
}

/*
 * Java to C function TtaGetStrError stub.
 */
struct Hjava_lang_String*
thotlib_APIApplication_TtaGetStrError(struct Hthotlib_APIApplication* none, jint errorCode)
{
	char *res;


	thotlib_APIApplication_LOCK();

	res = TtaGetStrError((int ) errorCode);

	thotlib_APIApplication_UNLOCK();

	if (res == NULL)
		return(NULL);
	else;
		return(makeJavaString(res, strlen(res)));
}

/*
 * Java to C function TtaExtractName stub.
 */
void
thotlib_APIApplication_TtaExtractName(struct Hthotlib_APIApplication* none, struct Hjava_lang_String* jtext, struct Hjava_lang_String* jaDirectory, struct Hjava_lang_String* jaName)
{
	char text[1024];
	char aDirectory[1024];
	char aName[1024];

	javaString2CString(jtext, text, sizeof(text));
	javaString2CString(jaDirectory, aDirectory, sizeof(aDirectory));
	javaString2CString(jaName, aName, sizeof(aName));

	thotlib_APIApplication_LOCK();

	TtaExtractName((char *) text, (char *) aDirectory, (char *) aName);

	thotlib_APIApplication_UNLOCK();
}

/*
 * Java to C function TtaCheckDirectory stub.
 */
jint
thotlib_APIApplication_TtaCheckDirectory(struct Hthotlib_APIApplication* none, struct Hjava_lang_String* jaDirectory)
{
	boolean res;
	char aDirectory[1024];

	javaString2CString(jaDirectory, aDirectory, sizeof(aDirectory));

	thotlib_APIApplication_LOCK();

	res = TtaCheckDirectory((char *) aDirectory);

	thotlib_APIApplication_UNLOCK();

	return((jint) res);
}

/*
 * Java to C function TtaStrdup stub.
 */
struct Hjava_lang_String*
thotlib_APIApplication_TtaStrdup(struct Hthotlib_APIApplication* none, struct Hjava_lang_String* jstr)
{
	char *res;
	char str[1024];

	javaString2CString(jstr, str, sizeof(str));

	thotlib_APIApplication_LOCK();

	res = TtaStrdup((char *) str);

	thotlib_APIApplication_UNLOCK();

	if (res == NULL)
		return(NULL);
	else;
		return(makeJavaString(res, strlen(res)));
}

/*
 * Function to register all thotlib_APIApplication stubs.
 */
void register_thotlib_APIApplication_stubs(void)
{
	addNativeMethod("thotlib_APIApplication_TtaInitialize", thotlib_APIApplication_TtaInitialize);
	addNativeMethod("thotlib_APIApplication_TtaQuit", thotlib_APIApplication_TtaQuit);
	addNativeMethod("thotlib_APIApplication_TtaSetErrorMessages", thotlib_APIApplication_TtaSetErrorMessages);
	addNativeMethod("thotlib_APIApplication_TtaGetVersion", thotlib_APIApplication_TtaGetVersion);
	addNativeMethod("thotlib_APIApplication_TtaGetErrorCode", thotlib_APIApplication_TtaGetErrorCode);
	addNativeMethod("thotlib_APIApplication_TtaGetStrError", thotlib_APIApplication_TtaGetStrError);
	addNativeMethod("thotlib_APIApplication_TtaExtractName", thotlib_APIApplication_TtaExtractName);
	addNativeMethod("thotlib_APIApplication_TtaCheckDirectory", thotlib_APIApplication_TtaCheckDirectory);
	addNativeMethod("thotlib_APIApplication_TtaStrdup", thotlib_APIApplication_TtaStrdup);
}

