/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIReference -J ../classes/thotlib/APIReference.java ../thotlib/include/reference.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APIReference from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 * As well as the Class LOCK/UNLOCK macros
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APIReference.h"
#include "thotlib_APIReference_stubs.h"

#ifndef thotlib_APIReference_LOCK
#define thotlib_APIReference_LOCK() fprintf(stderr,"thotlib_APIReference_LOCK undefined");
#endif /* thotlib_APIReference_LOCK */
#ifndef thotlib_APIReference_UNLOCK
#define thotlib_APIReference_UNLOCK() fprintf(stderr,"thotlib_APIReference_UNLOCK undefined");
#endif /* thotlib_APIReference_UNLOCK */

/*
 * Java to C function TtaSetReference stub.
 */
void
thotlib_APIReference_TtaSetReference(struct Hthotlib_APIReference* none, jlong jelement, jint document, jlong jtarget, jint targetDocument)
{
	Element element;
	Element target;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);
	/* convert arg jlong jtarget to Element target */
	Javalong2CElement(jtarget,&target);

	thotlib_APIReference_LOCK();

	TtaSetReference((Element ) element, (Document ) document, (Element ) target, (Document ) targetDocument);

	thotlib_APIReference_UNLOCK();

}

/*
 * Java to C function TtaNewInclusion stub.
 */
jlong
thotlib_APIReference_TtaNewInclusion(struct Hthotlib_APIReference* none, jint document, jlong jtarget, jint targetDocument)
{
	jlong result;
	Element res;
	Element target;

	/* convert arg jlong jtarget to Element target */
	Javalong2CElement(jtarget,&target);

	thotlib_APIReference_LOCK();

	res = TtaNewInclusion((Document ) document, (Element ) target, (Document ) targetDocument);

	thotlib_APIReference_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Java to C function TtaCopyReference stub.
 */
void
thotlib_APIReference_TtaCopyReference(struct Hthotlib_APIReference* none, jlong jelement, jlong jsource)
{
	Element element;
	Element source;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);
	/* convert arg jlong jsource to Element source */
	Javalong2CElement(jsource,&source);

	thotlib_APIReference_LOCK();

	TtaCopyReference((Element ) element, (Element ) source);

	thotlib_APIReference_UNLOCK();

}

/*
 * Java to C function TtaSetAttributeReference stub.
 */
void
thotlib_APIReference_TtaSetAttributeReference(struct Hthotlib_APIReference* none, jlong jattribute, jlong jelement, jint document, jlong jtarget, jint targetDocument)
{
	Attribute attribute;
	Element element;
	Element target;

	/* convert arg jlong jattribute to Attribute attribute */
	Javalong2CAttribute(jattribute,&attribute);
	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);
	/* convert arg jlong jtarget to Element target */
	Javalong2CElement(jtarget,&target);

	thotlib_APIReference_LOCK();

	TtaSetAttributeReference((Attribute ) attribute, (Element ) element, (Document ) document, (Element ) target, (Document ) targetDocument);

	thotlib_APIReference_UNLOCK();

}

/*
 * Java to C function TtaCopyAttributeReference stub.
 */
void
thotlib_APIReference_TtaCopyAttributeReference(struct Hthotlib_APIReference* none, jlong jattribute, jlong jelement, jlong jsource)
{
	Attribute attribute;
	Element element;
	Attribute source;

	/* convert arg jlong jattribute to Attribute attribute */
	Javalong2CAttribute(jattribute,&attribute);
	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);
	/* convert arg jlong jsource to Attribute source */
	Javalong2CAttribute(jsource,&source);

	thotlib_APIReference_LOCK();

	TtaCopyAttributeReference((Attribute ) attribute, (Element ) element, (Attribute ) source);

	thotlib_APIReference_UNLOCK();

}

/*
 * Java to C function TtaGiveReferredElement stub.
 */
void
thotlib_APIReference_TtaGiveReferredElement(struct Hthotlib_APIReference* none, jlong jelement, struct Hthotlib_Element* jtarget, struct Hjava_lang_StringBuffer* jtargetDocumentName, struct Hthotlib_Document* jtargetDocument)
{
	Element element;
	Element *target;
	char *targetDocumentName;
	Document *targetDocument;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);
	/* convert arg struct Hthotlib_Element* jtarget to Element *target */
	JavaElement2CElementPtr(jtarget,&target);
	/* convert arg struct Hjava_lang_StringBuffer* jtargetDocumentName to char *targetDocumentName */
	JavaStringBuffer2CcharPtr(jtargetDocumentName,&targetDocumentName);
	/* convert arg struct Hthotlib_Document* jtargetDocument to Document *targetDocument */
	JavaDocument2CDocumentPtr(jtargetDocument,&targetDocument);

	thotlib_APIReference_LOCK();

	TtaGiveReferredElement((Element ) element, (Element *) target, (char *) targetDocumentName, (Document *) targetDocument);

	thotlib_APIReference_UNLOCK();

	/* convert Element *target to arg struct Hthotlib_Element* jtarget */
	CElementPtr2JavaElement(target,&jtarget);
	/* convert char *targetDocumentName to arg struct Hjava_lang_StringBuffer* jtargetDocumentName */
	CcharPtr2JavaStringBuffer(targetDocumentName,&jtargetDocumentName);
	/* convert Document *targetDocument to arg struct Hthotlib_Document* jtargetDocument */
	CDocumentPtr2JavaDocument(targetDocument,&jtargetDocument);
}

/*
 * Java to C function TtaIsElementTypeReference stub.
 */
jint
thotlib_APIReference_TtaIsElementTypeReference(struct Hthotlib_APIReference* none, jlong jelementType)
{
	int res;
	ElementType elementType;

	/* convert arg jlong jelementType to ElementType elementType */
	Javalong2CElementType(jelementType,&elementType);

	thotlib_APIReference_LOCK();

	res = TtaIsElementTypeReference((ElementType ) elementType);

	thotlib_APIReference_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaSameReferences stub.
 */
jint
thotlib_APIReference_TtaSameReferences(struct Hthotlib_APIReference* none, jlong jelement1, jlong jelement2)
{
	int res;
	Element element1;
	Element element2;

	/* convert arg jlong jelement1 to Element element1 */
	Javalong2CElement(jelement1,&element1);
	/* convert arg jlong jelement2 to Element element2 */
	Javalong2CElement(jelement2,&element2);

	thotlib_APIReference_LOCK();

	res = TtaSameReferences((Element ) element1, (Element ) element2);

	thotlib_APIReference_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaGiveReferenceAttributeValue stub.
 */
void
thotlib_APIReference_TtaGiveReferenceAttributeValue(struct Hthotlib_APIReference* none, jlong jattribute, struct Hthotlib_Element* jtarget, struct Hjava_lang_StringBuffer* jtargetDocumentName, struct Hthotlib_Document* jtargetDocument)
{
	Attribute attribute;
	Element *target;
	char *targetDocumentName;
	Document *targetDocument;

	/* convert arg jlong jattribute to Attribute attribute */
	Javalong2CAttribute(jattribute,&attribute);
	/* convert arg struct Hthotlib_Element* jtarget to Element *target */
	JavaElement2CElementPtr(jtarget,&target);
	/* convert arg struct Hjava_lang_StringBuffer* jtargetDocumentName to char *targetDocumentName */
	JavaStringBuffer2CcharPtr(jtargetDocumentName,&targetDocumentName);
	/* convert arg struct Hthotlib_Document* jtargetDocument to Document *targetDocument */
	JavaDocument2CDocumentPtr(jtargetDocument,&targetDocument);

	thotlib_APIReference_LOCK();

	TtaGiveReferenceAttributeValue((Attribute ) attribute, (Element *) target, (char *) targetDocumentName, (Document *) targetDocument);

	thotlib_APIReference_UNLOCK();

	/* convert Element *target to arg struct Hthotlib_Element* jtarget */
	CElementPtr2JavaElement(target,&jtarget);
	/* convert char *targetDocumentName to arg struct Hjava_lang_StringBuffer* jtargetDocumentName */
	CcharPtr2JavaStringBuffer(targetDocumentName,&jtargetDocumentName);
	/* convert Document *targetDocument to arg struct Hthotlib_Document* jtargetDocument */
	CDocumentPtr2JavaDocument(targetDocument,&jtargetDocument);
}

/*
 * Java to C function TtaIsElementReferred stub.
 */
jint
thotlib_APIReference_TtaIsElementReferred(struct Hthotlib_APIReference* none, jlong jelement)
{
	int res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APIReference_LOCK();

	res = TtaIsElementReferred((Element ) element);

	thotlib_APIReference_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaSameReferenceAttributes stub.
 */
jint
thotlib_APIReference_TtaSameReferenceAttributes(struct Hthotlib_APIReference* none, jlong jattribute1, jlong jattribute2)
{
	int res;
	Attribute attribute1;
	Attribute attribute2;

	/* convert arg jlong jattribute1 to Attribute attribute1 */
	Javalong2CAttribute(jattribute1,&attribute1);
	/* convert arg jlong jattribute2 to Attribute attribute2 */
	Javalong2CAttribute(jattribute2,&attribute2);

	thotlib_APIReference_LOCK();

	res = TtaSameReferenceAttributes((Attribute ) attribute1, (Attribute ) attribute2);

	thotlib_APIReference_UNLOCK();


	return((jint) res);
}

/*
 * Java to C function TtaNextLoadedReference stub.
 */
void
thotlib_APIReference_TtaNextLoadedReference(struct Hthotlib_APIReference* none, jlong jtarget, jint targetDocument, struct Hthotlib_Element* jreferenceElement, struct Hthotlib_Attribute* jreferenceAttribute, struct Hthotlib_Document* jreferenceDocument)
{
	Element target;
	Element *referenceElement;
	Attribute *referenceAttribute;
	Document *referenceDocument;

	/* convert arg jlong jtarget to Element target */
	Javalong2CElement(jtarget,&target);
	/* convert arg struct Hthotlib_Element* jreferenceElement to Element *referenceElement */
	JavaElement2CElementPtr(jreferenceElement,&referenceElement);
	/* convert arg struct Hthotlib_Attribute* jreferenceAttribute to Attribute *referenceAttribute */
	JavaAttribute2CAttributePtr(jreferenceAttribute,&referenceAttribute);
	/* convert arg struct Hthotlib_Document* jreferenceDocument to Document *referenceDocument */
	JavaDocument2CDocumentPtr(jreferenceDocument,&referenceDocument);

	thotlib_APIReference_LOCK();

	TtaNextLoadedReference((Element ) target, (Document ) targetDocument, (Element *) referenceElement, (Attribute *) referenceAttribute, (Document *) referenceDocument);

	thotlib_APIReference_UNLOCK();

	/* convert Element *referenceElement to arg struct Hthotlib_Element* jreferenceElement */
	CElementPtr2JavaElement(referenceElement,&jreferenceElement);
	/* convert Attribute *referenceAttribute to arg struct Hthotlib_Attribute* jreferenceAttribute */
	CAttributePtr2JavaAttribute(referenceAttribute,&jreferenceAttribute);
	/* convert Document *referenceDocument to arg struct Hthotlib_Document* jreferenceDocument */
	CDocumentPtr2JavaDocument(referenceDocument,&jreferenceDocument);
}

/*
 * Java to C function TtaNextUnloadedReferringDocument stub.
 */
void
thotlib_APIReference_TtaNextUnloadedReferringDocument(struct Hthotlib_APIReference* none, jlong jtarget, jint targetDocument, struct Hjava_lang_StringBuffer* jreferringDocumentName)
{
	Element target;
	char *referringDocumentName;

	/* convert arg jlong jtarget to Element target */
	Javalong2CElement(jtarget,&target);
	/* convert arg struct Hjava_lang_StringBuffer* jreferringDocumentName to char *referringDocumentName */
	JavaStringBuffer2CcharPtr(jreferringDocumentName,&referringDocumentName);

	thotlib_APIReference_LOCK();

	TtaNextUnloadedReferringDocument((Element ) target, (Document ) targetDocument, (char *) referringDocumentName);

	thotlib_APIReference_UNLOCK();

	/* convert char *referringDocumentName to arg struct Hjava_lang_StringBuffer* jreferringDocumentName */
	CcharPtr2JavaStringBuffer(referringDocumentName,&jreferringDocumentName);
}

/*
 * Java to C function TtaSearchReferenceElement stub.
 */
jlong
thotlib_APIReference_TtaSearchReferenceElement(struct Hthotlib_APIReference* none, jint scope, jlong jelement)
{
	jlong result;
	Element res;
	Element element;

	/* convert arg jlong jelement to Element element */
	Javalong2CElement(jelement,&element);

	thotlib_APIReference_LOCK();

	res = TtaSearchReferenceElement((SearchDomain ) scope, (Element ) element);

	thotlib_APIReference_UNLOCK();

	/* convert Element res to jlong result */
	CElement2Javalong(res, &result);

	return(result);
}

/*
 * Function to register all thotlib_APIReference stubs.
 */
void register_thotlib_APIReference_stubs(void)
{
	addNativeMethod("thotlib_APIReference_TtaSetReference", thotlib_APIReference_TtaSetReference);
	addNativeMethod("thotlib_APIReference_TtaNewInclusion", thotlib_APIReference_TtaNewInclusion);
	addNativeMethod("thotlib_APIReference_TtaCopyReference", thotlib_APIReference_TtaCopyReference);
	addNativeMethod("thotlib_APIReference_TtaSetAttributeReference", thotlib_APIReference_TtaSetAttributeReference);
	addNativeMethod("thotlib_APIReference_TtaCopyAttributeReference", thotlib_APIReference_TtaCopyAttributeReference);
	addNativeMethod("thotlib_APIReference_TtaGiveReferredElement", thotlib_APIReference_TtaGiveReferredElement);
	addNativeMethod("thotlib_APIReference_TtaIsElementTypeReference", thotlib_APIReference_TtaIsElementTypeReference);
	addNativeMethod("thotlib_APIReference_TtaSameReferences", thotlib_APIReference_TtaSameReferences);
	addNativeMethod("thotlib_APIReference_TtaGiveReferenceAttributeValue", thotlib_APIReference_TtaGiveReferenceAttributeValue);
	addNativeMethod("thotlib_APIReference_TtaIsElementReferred", thotlib_APIReference_TtaIsElementReferred);
	addNativeMethod("thotlib_APIReference_TtaSameReferenceAttributes", thotlib_APIReference_TtaSameReferenceAttributes);
	addNativeMethod("thotlib_APIReference_TtaNextLoadedReference", thotlib_APIReference_TtaNextLoadedReference);
	addNativeMethod("thotlib_APIReference_TtaNextUnloadedReferringDocument", thotlib_APIReference_TtaNextUnloadedReferringDocument);
	addNativeMethod("thotlib_APIReference_TtaSearchReferenceElement", thotlib_APIReference_TtaSearchReferenceElement);
}

