/*
 * DO NOT EDIT
 * Generated by the following command from /users/veillard/opera/javalib directory
 * ../LINUX-ELF/bin/javastub -T JavaTypes.def -M thotlib_APIAppAction -J ../classes/thotlib/APIAppAction.java ../thotlib/include/appaction.h 
 */
/*
 * Kaffe stubs generated for class thotlib_APIAppAction from includes
 * The user need to write JavaTypes.h which gives the
 * signatures of Java2C and C2Java conversion handlers
 * As well as the Class LOCK/UNLOCK macros
 */

#include <native.h>
#include "JavaTypes.h"
#include "thotlib_APIAppAction.h"
#include "thotlib_APIAppAction_stubs.h"

#ifndef thotlib_APIAppAction_LOCK
#define thotlib_APIAppAction_LOCK() fprintf(stderr,"thotlib_APIAppAction_LOCK undefined");
#endif /* thotlib_APIAppAction_LOCK */
#ifndef thotlib_APIAppAction_UNLOCK
#define thotlib_APIAppAction_UNLOCK() fprintf(stderr,"thotlib_APIAppAction_UNLOCK undefined");
#endif /* thotlib_APIAppAction_UNLOCK */

/*
 * Function to register all thotlib_APIAppAction stubs.
 */
void register_thotlib_APIAppAction_stubs(void)
{
}

